Repository Sylius/Sylius, pull requests merged in 2018-02, with the labels that each got.

#9155 [Documentation] Add CMS integration cookbook
  docs/cookbook/index.rst
  docs/cookbook/shop/cms.rst
Labels: Documentation

#9192 [Documentation] Add 1.1 branch to Contribution guides
  docs/contributing/code/patches.rst
  docs/contributing/documentation/overview.rst
Labels: Documentation

#9189 [Documentation] Add more rules to the contribution guide + Fix CMS cookbook
  docs/contributing/documentation/standards.rst
  docs/cookbook/shop/cms.rst
  docs/cookbook/shop/map.rst.inc
Labels: Documentation

#9204 Fix invalid use of count by checking for an array
  src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/SelectAttributeType.php
Labels: Bug

#9206 [Documentation] Translatable model - Fix titles and add template support
  docs/cookbook/entities/custom-translatable-model.rst
Labels: Documentation

#9145 Run Travis with readonly project directories
  .travis.yml
  composer.lock
  etc/travis/suites/application/before_script.sh
Labels: Maintenance

#9195 [Documentation][GridBundle]Wrong definition of sortable attribute
  docs/components_and_bundles/bundles/SyliusGridBundle/configuration.rst
Labels: Documentation

#9181 Remove surprising redundant x sign from docblock
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
Labels: Enhancement

#9211 Bring extra care for the documentation!
  .github/CODEOWNERS
Labels: Maintenance

#9194 [Documentation][Cookbook]Adding validation for image uploads
  docs/cookbook/images/images-on-entity.rst
Labels: Documentation
