Repository Sylius/Sylius, pull requests merged in 2018-06, with the labels that each got.

#9441 Remove vendorPath command-line argument from root gulpfile
  gulpfile.babel.js
Labels: Maintenance

#9422 Add ability to use a custom service as factory
  docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
  src/Sylius/Bundle/ResourceBundle/Controller/NewResourceFactory.php
  src/Sylius/Bundle/ResourceBundle/spec/Controller/NewResourceFactorySpec.php
  src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
  src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
  src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Factory/CustomBookFactory.php
  src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
Labels: Feature

#9444 [Documentation] Fixed typo in note about --force-with-lease flag
  docs/contributing/code/patches.rst
Labels: Documentation

#9442 Add an ability to use custom resource repositories
  composer.json
  src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
  src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php
  src/Sylius/Bundle/ResourceBundle/Controller/SingleResourceProvider.php
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesResolverSpec.php
  src/Sylius/Bundle/ResourceBundle/spec/Controller/SingleResourceProviderSpec.php
  src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
  src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
  src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Repository/CustomBookRepository.php
  src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
Labels: Feature

#9454 Symfony 4.1 support (together with dropping Symfony 4.0 support)
  .travis.yml
  app/TestAppKernel.php
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/FixturesBundle/composer.json
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/ThemeBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Grid/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Resource/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Bug, Maintenance

#9456 Add documentation for using custom repository service in ResourceBundle
  docs/components_and_bundles/bundles/SyliusResourceBundle/show_resource.rst
Labels: Documentation, Feature

#9458 [docs] fix server:start command
  docs/book/installation/installation.rst
Labels: Documentation

#9398 [Core] Default shipping method basing on category fix
  UPGRADE-1.2.md
  features/cart/shopping_cart/resolving_default_shipping_method_in_cart_summary_for_simple_products.feature
  src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
  src/Sylius/Component/Core/Resolver/DefaultShippingMethodResolver.php
  src/Sylius/Component/Core/Resolver/EligibleDefaultShippingMethodResolver.php
  src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
  src/Sylius/Component/Core/spec/Resolver/DefaultShippingMethodResolverSpecSpec.php
  src/Sylius/Component/Core/spec/Resolver/EligibleDefaultShippingMethodResolverSpec.php
Labels: Bug

#9463 Update platform-sh.rst
  docs/cookbook/deployment/platform-sh.rst
Labels: Documentation

#9462 Remove two redundant services from CoreBundle
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
Labels: Maintenance

#9465 [Documentation] Fix deprecated link to repository
  docs/contributing/code/patches.rst
Labels: Documentation

#9464 Fixed typo in PayumController
  src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
Labels: Bug

#9466 Document "event" option in resource routing
  docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/delete_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/update_resource.rst
Labels: Documentation

#9470 [Documentation] Updated link to Payum docs
  docs/book/orders/payments.rst
Labels: Documentation

#9461 Added note about LiipImagineBundle upgrade
  UPGRADE-1.2.md
Labels: Documentation

#9467 Update outdated method prototype('array') with arrayPrototype() @se…
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/FixturesBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
Labels: Enhancement

#9476 Enhance workarounds while waiting for Symfony 4.1.1
  app/TestAppKernel.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
Labels: Enhancement, Maintenance

#9477 Remove labels descriptions in docs
  docs/contributing/organization/vision-and-strategy.rst
Labels: Documentation, Enhancement

#9480 [docs] Use `app/config/routing/admin.yml` everywhere
  docs/cookbook/entities/custom-model.rst
Labels: Documentation

#9488 Describe upgrade process for 1.1.x -> 1.2.0
  UPGRADE-1.2.md
Labels: Maintenance

#9487 Improve use of Semantic's cards in frontend
  src/Sylius/Behat/Page/Shop/Product/IndexPage.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_horizontalList.html.twig
Labels: Shop

#9491 [Documentation] Document Forum in the support section
  docs/support/index.rst
Labels: Documentation

#9492 Update Sylius issue templates
  .github/ISSUE_TEMPLATE/bug-report---.md
  .github/ISSUE_TEMPLATE/documentation-issue---.md
  .github/ISSUE_TEMPLATE/feature-request--.md
  .github/ISSUE_TEMPLATE/support-question---.md
Labels: Maintenance

#9498 Require PHP ^7.2 in Sylius ^1.3
  .travis.yml
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/FixturesBundle/composer.json
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/ThemeBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Grid/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Mailer/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Registry/composer.json
  src/Sylius/Component/Resource/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, RFC

#9537 [Admin] Add missing form parameter to sonata form events
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
Labels: Admin, Bug

#9515 [Documentation] Fix typos
  docs/book/customers/addresses/address_book.rst
  docs/book/customers/customer_and_shopuser.rst
  docs/book/orders/adjustments.rst
  docs/book/orders/coupons.rst
  docs/book/orders/payments.rst
  docs/book/orders/promotions.rst
  docs/book/orders/shipments.rst
  docs/book/products/inventory.rst
  docs/book/products/pricing.rst
  docs/book/products/search.rst
  docs/book/products/taxons.rst
Labels: Documentation
