Repository Sylius/Sylius, pull requests merged in 2018-07, with the labels that each got.

#9475 Make Stalebot less annoying
  .github/stale.yml
Labels: Maintenance

#9539 [minor] SCA
  src/Sylius/Behat/Context/Api/Admin/ManagingProductVariantsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Order/UpdatePage.php
  src/Sylius/Behat/Page/SymfonyPage.php
  src/Sylius/Bundle/ShopBundle/Router/LocaleStrippingRouter.php
  src/Sylius/Bundle/ThemeBundle/Loader/CircularDependencyChecker.php
  src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
  src/Sylius/Component/Promotion/Model/Promotion.php
Labels: Enhancement, Maintenance

#9541 Require Symfony 4.1.1 and remove hotfixes for 4.1.0
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/FixturesBundle/composer.json
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/ThemeBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Grid/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Resource/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#9527 [ResourceBundle] Fix DoctrineTargetEntitiesResolverPass priority to avoid mapping issues.
  docs/components_and_bundles/bundles/SyliusAddressingBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusAttributeBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusCustomerBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusOrderBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusProductBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusPromotionBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusShippingBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusTaxationBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusTaxonomyBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusUserBundle/installation.rst
  src/Sylius/Bundle/AddressingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/AttributeBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ChannelBundle/test/app/AppKernel.php
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
  src/Sylius/Bundle/CurrencyBundle/test/app/AppKernel.php
  src/Sylius/Bundle/CustomerBundle/test/app/AppKernel.php
  src/Sylius/Bundle/FixturesBundle/test/app/AppKernel.php
  src/Sylius/Bundle/GridBundle/test/app/AppKernel.php
  src/Sylius/Bundle/InventoryBundle/test/app/AppKernel.php
  src/Sylius/Bundle/LocaleBundle/test/app/AppKernel.php
  src/Sylius/Bundle/MoneyBundle/test/app/AppKernel.php
  src/Sylius/Bundle/OrderBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PaymentBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ProductBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ResourceBundle/SyliusResourceBundle.php
  src/Sylius/Bundle/ResourceBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ShippingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/TaxationBundle/test/app/AppKernel.php
  src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/AppKernel.php
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php
Labels: Bug, Enhancement

#9546 Added title to product reviews, fixes #9425
  src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_single.html.twig
Labels: Bug, Enhancement

#9345 [HOTFIX] Missing configuration for channel in sonata
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
Labels: Bug

#9534 [ResourceBundle] fix routing templates for sf4
  src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
  src/Sylius/Bundle/ResourceBundle/spec/Routing/ResourceLoaderSpec.php
Labels: Bug, Enhancement, Maintenance

#9340 the name of file was wrong in docu
  docs/cookbook/shop/custom-redirect-after-cart-add-action.rst
Labels: Documentation

#9548 Unify catch block in ShopBasedCartContext
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
Labels: Enhancement, Maintenance

#9550 Mention roadmap in README
  README.md
Labels: Enhancement

#9551 Deprecate MongoDB and PHPCR drivers in ResourceBundle and GridBundle
  UPGRADE-2.0.md
  src/Sylius/Bundle/GridBundle/DependencyInjection/SyliusGridExtension.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/DataSource.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/Driver.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilder.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilderInterface.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionVisitor.php
  src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExtraComparison.php
  src/Sylius/Bundle/GridBundle/Resources/config/services/integrations/doctrine/phpcr-odm.xml
  src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/TranslatableRepository.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/DefaultParentListener.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/NameFilterListener.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/NameResolverListener.php
  src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/Form/Builder/DefaultFormBuilder.php
  src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
  src/Sylius/Bundle/ResourceBundle/EventListener/ODMRepositoryClassSubscriber.php
  src/Sylius/Bundle/ResourceBundle/EventListener/ODMTranslatableListener.php
  src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
Labels: Maintenance, RFC

#9493 Document officially supported plugins in the README
  README.md
Labels: Maintenance

#9555 Add Sylius/CustomerOrderCancellationPlugin to the list of official plugins
  README.md
Labels: Documentation, Enhancement

#7978 Remove groupby and add distinct
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
Labels: Bug

#9561 Fix a TypeError on admin login page.
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-notification.js
Labels: Admin, Bug

#9578 [Core] Nullable customer on order
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/spec/Model/OrderSpec.php
Labels: BC Break, Bug

#9557 Use generic names for data-* properties in sylius-lazy-choice-tree.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
Labels: Enhancement

#9553 Fix wrong type for "images" option in ProductFixture
  src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductFixtureTest.php
Labels: Bug

#9580 [User] Fix bc-break in UserLastLoginSubscriber
  src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
Labels: BC Break, Bug

#9563 [AdminApi] Fix command
  src/Sylius/Bundle/AdminApiBundle/Command/CreateClientCommand.php
  src/Sylius/Bundle/AdminApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminApiBundle/spec/Command/CreateClientCommandSpec.php
Labels: Bug

#9583 Remove Symfony Version from README.md
  src/Sylius/Bundle/ThemeBundle/README.md
Labels: Maintenance

#9587 Adding strict typing for PHP classes in images doc
  docs/cookbook/images/images-on-entity.rst
Labels: Documentation

#9193 [Documentation][GridBundle]Describes sorting, filtering by sub entity properties
  docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
Labels: Documentation

#9590 Ensure that DatabaseSetupCommandsProvider::getDatabaseName() returns a string.
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
Labels: Bug

#9352 Minor fixes to grammar
  docs/components_and_bundles/components/general/creating_resources.rst
Labels: Documentation

#9289 Check if customer is set before get/set email
  src/Sylius/Component/Core/Model/ShopUser.php
  src/Sylius/Component/Core/spec/Model/ShopUserSpec.php
Labels: Bug

#9600 Pull request template fix
  docs/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#9599 [Behat] Grammar fix
  features/account/resetting_password.feature
  features/user/managing_customers/resetting_customer_password.feature
  src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
Labels: Behat

#9596 Take unitTotal of order item to check if taxon rule can be applied
  features/checkout/order_promotion/order_promotion_integrity_validation.feature
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderPromotionIntegrityCheckerSpec.php
Labels: Bug

#9608 Remove instances of loop.index0
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_items.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_payment.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_form.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_shipment.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig
Labels: Bug

#9611 [Doc] Fix service name for custom taxation calculator
  docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
Labels: Documentation

#9613 Fix ShopBasedCartContext resetting
  src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
Labels: Bug

#9612 Handle null email in oauth login
  src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
  src/Sylius/Bundle/CoreBundle/spec/OAuth/UserProviderSpec.php
Labels: Bug

#9616 Added account verification option to fixture parser
  src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/ChannelFixtureTest.php
Labels: Feature

#9592 Plugin development guide v1.0
  docs/_images/product_variant_available_on_demand.png
  docs/plugins/index.rst
  docs/plugins/map.rst.inc
  docs/plugins/plugin-development-guide/idea.rst
  docs/plugins/plugin-development-guide/implementation.rst
  docs/plugins/plugin-development-guide/index.rst
  docs/plugins/plugin-development-guide/installation.rst
  docs/plugins/plugin-development-guide/naming.rst
  docs/plugins/plugin-development-guide/specification.rst
  docs/plugins/plugin-development-guide/summary.rst
Labels: Documentation

#9618 Reproduce CSRF token validation failure when deleting an user in admin panel
  features/user/managing_users/deleting_account.feature
  src/Sylius/Behat/Resources/config/suites/ui/user/managing_users.yml
  src/Sylius/Bundle/AdminBundle/Menu/CustomerShowMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/spec/Menu/CustomerShowMenuBuilderSpec.php
Labels: Bug

#9620 [docs] updating taxon models documentation
  docs/components_and_bundles/components/Taxonomy/models.rst
Labels: Bug, Documentation

#9617 Fix CS and add tests for ShopBasedCartContext
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
  src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
Labels: Enhancement

#9615 Simplify code of `sylius-product-images-preview` module
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-product-images-preview.js
Labels: Admin, DX, Enhancement

#9622 Quote row_number identifier for MySQL queries
  app/migrations/Version20161223091334.php
Labels: Bug
