Repository Sylius/Sylius, pull requests merged in 2018-12, with the labels that each got.

#9975 Ignore locale request restriction for profiler and it's toolbar
  src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
Labels: Bug

#9985 Add missing code and calculator mandatory field on tax rate documenation
  docs/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.rst
Labels: Documentation

#9837 Repaired shipping method fixture
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
Labels: Bug

#9995 Remove `AppBundle` from docs.
  docs/book/architecture/translations.rst
  docs/book/installation/installation.rst
  docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_fixture.rst
  docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_listener.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_action.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_field_type.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_filter.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
  docs/components_and_bundles/bundles/SyliusInventoryBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusMailerBundle/configuration.rst
  docs/components_and_bundles/bundles/SyliusMailerBundle/your_first_email.rst
  docs/components_and_bundles/bundles/SyliusPromotionBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/configuration.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/forms.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/reference.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/routing.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/update_resource.rst
  docs/components_and_bundles/bundles/SyliusShippingBundle/custom_calculators.rst
  docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
  docs/components_and_bundles/components/Promotion/basic_usage.rst
  docs/cookbook/emails/disabling-order-confirmation-email.rst
  docs/cookbook/entities/custom-translatable-model.rst
  docs/cookbook/frontend/admin-js-and-css.rst
  docs/cookbook/images/images-gridfs.rst
  docs/cookbook/images/images-on-entity.rst
  docs/customization/factory.rst
  docs/customization/grid.rst
  docs/customization/model.rst
  docs/customization/validation.rst
Labels: Documentation

#9997 Fix typo cookbook about emails
  docs/cookbook/emails/disabling-order-confirmation-email.rst
Labels: Documentation

#10020 [HotFix][BuildFix] Use old PhpMatcherDumper to avoid trailing slash problems
  phpstan.neon
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Routing/Matcher/Dumper/PhpMatcherDumper.php
  src/Sylius/Bundle/ResourceBundle/composer.json
Labels: Bug, Maintenance

#10023 Remove billingAddress and shippingAddress
  docs/book/customers/customer_and_shopuser.rst
Labels: Documentation

#10018 [docs] fix config directory path and added info for orm mappings in customization/model
  docs/customization/model.rst
Labels: Documentation

#9964 Making templates deprecated
  UPGRADE-2.0.md
  src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
Labels: DX

#10012 Fixed incorrect Behat MinkExtension key in the docs
  docs/contributing/code/bdd.rst
Labels: Documentation

#10029 Fix type annotation for $addToCartCommand
  src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
Labels: Bug

#10038 Fix the build on 1.3 by more flexible router overriding
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
Labels: Bug, Critical

#10040 [Fixtures] StreetAddress instead of StreetName
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Labels: Enhancement

#10039 Removed unused use statement
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
Labels: Bug

#10008 ShopUser class is now EncoderAware to provide more flexibility for ch…
  config/packages/security.yaml
  src/Sylius/Bundle/ReviewBundle/test/app/config/config.yml
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
  src/Sylius/Bundle/UserBundle/Security/UserPasswordEncoder.php
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/config.yml
  src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordEncoderSpec.php
  src/Sylius/Component/Core/Model/AdminUser.php
  src/Sylius/Component/Core/Model/AdminUserInterface.php
  src/Sylius/Component/Core/Model/ShopUser.php
  src/Sylius/Component/Core/Model/ShopUserInterface.php
Labels: Feature

#10044 [Docs] Fix docs with page object extension usage
  docs/bdd/basic-usage.rst
  docs/bdd/how-to-add-new-page.rst
Labels: Documentation

#10043 Behat JS scenarios war vol.1
  features/account/customer_account/viewing_orders_history/viewing_order_items.feature
  features/checkout/placing_an_order_with_different_scopes_for_shipping_and_taxes.feature
  features/checkout/skipping_payment_method_step_when_only_one_payment_method_is_available.feature
  features/product/adding_product_reviews/adding_product_review_as_a_customer.feature
  features/product/adding_product_reviews/adding_product_review_as_a_guest.feature
  features/product/adding_product_reviews/review_validation.feature
  features/user/managing_customers/being_able_to_create_account_for_existing_customer.feature
  src/Sylius/Behat/Page/Shop/ProductReview/CreatePage.php
Labels: Behat

#10002 Avoid deprecated notice when using symfony/config > 4.2
  phpstan.neon
  src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ChannelBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Fixture/AbstractResourceFixture.php
  src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/FixturesBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/FixturesBundle/Fixture/AbstractFixture.php
  src/Sylius/Bundle/FixturesBundle/Listener/AbstractListener.php
  src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MoneyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ResourceBundle/Routing/Configuration.php
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ThemeBundle/Configuration/ThemeConfiguration.php
  src/Sylius/Bundle/ThemeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
Labels: Maintenance

#10046 Enable strict validation for email
  composer.json
  features/user/managing_customers/customer_validation.feature
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/AdminUser.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/UserBundle/Resources/config/validation/PasswordResetRequest.xml
  src/Sylius/Bundle/UserBundle/composer.json
Labels: Feature
