Repository Sylius/Sylius, pull requests merged in 2018-03, with the labels that each got.

#9219 Improve flags support
  src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Grid/Field/name.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/flags.html.twig
Labels: Bug

#9212 [Reviews] nullable title for reviews
  app/migrations/Version20180226142349.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ReviewBundle/Resources/config/doctrine/model/Review.orm.xml
  src/Sylius/Bundle/ReviewBundle/Resources/config/validation/Review.xml
Labels: Enhancement, Feature

#9236 [ResourceBundle] make sylius.translatable_entity_locale_assigner public
  src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/translation.xml
Labels: Symfony 4.0

#9235 [ResourceBundle] make controller public by default
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
Labels: Symfony 4.0

#9233 [AttributeBundle] Fixing composer.json for ramsey/uuid
  src/Sylius/Bundle/AttributeBundle/composer.json
Labels: Bug

#9237 Fix select province in checkout address
  src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-address-book.js
  src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-province-field.js
Labels: Bug

#9185 [ResourceBundle] Add the controller tag
  src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
Labels: Feature

#9176 [Documentation] Customizing Factory
  docs/customization/factory.rst
Labels: Documentation

#9135 Fixed Customer API docs with invalid "groups" parameter
  docs/api/customers.rst
Labels: API, Documentation

#9246 Mention the need of applying migrations when upgrading 1.0 -> 1.1
  UPGRADE-1.1.md
Labels: Documentation

#9244 Remove composer.lock
  .gitignore
  composer.lock
  etc/travis/suites/application/install.sh
Labels: Maintenance, RFC

#9247 Update to ApiTestCase ^2.0 and PHPUnit ^6.0
  composer.json
Labels: Maintenance

#9248 Update to PHPUnit ^6.5
  composer.json
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/validate-behat-features
Labels: Maintenance

#9259 Various composer.json enhancements
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Component/Resource/composer.json
Labels: Enhancement, Maintenance

#9260 Remove "incenteev/composer-parameter-handler" from packages dependencies
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/FixturesBundle/composer.json
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/.gitignore
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/test/app/config/parameters.yml
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/.gitignore
  src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/config/parameters.yml
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/.gitignore
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/parameters.yml
  src/Sylius/Bundle/UserBundle/composer.json
Labels: Maintenance

#9255 Changes form channel color from text to color input type
  src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelType.php
Labels: Admin, Enhancement

#9265 Run PHPStan in Travis CI
  composer.json
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-phpstan
  phpstan.neon
  src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
Labels: Enhancement, Maintenance

#9269 Fix wrong Balrog of Morgoth name
  docs/api/admin_users.rst
  tests/Controller/AdminUserApiTest.php
  tests/Responses/Expected/admin_user/create_response.json
Labels: Bug, DX

#9267 Add PaymentMethod::instructions option to fixtures
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/PaymentMethodFixture.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/PaymentMethodFixtureTest.php
Labels: Bug, Enhancement

#9264 [Documentation][CookBook] Specific SyliusBundles extension
  docs/cookbook/configuration/extending-bundles-other-em.rst
  docs/cookbook/configuration/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#9281 [Behat] Handle multiple notifications in NotificationChecker
  src/Sylius/Behat/Exception/NotificationExpectationMismatchException.php
  src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
  src/Sylius/Behat/Service/Accessor/NotificationAccessorInterface.php
  src/Sylius/Behat/Service/NotificationChecker.php
  src/Sylius/Behat/Service/NotificationCheckerInterface.php
  src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php
Labels: Behat, Enhancement, RFC

#9266 Update ApiTestCase to ^3.0
  app/config/config_test.yml
  composer.json
  phpunit.xml.dist
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
  tests/Controller/OrderApiTest.php
  tests/Controller/PaymentMethodApiTest.php
  tests/Controller/ProductVariantApiTest.php
  tests/Controller/PromotionApiTest.php
  tests/Controller/PromotionCouponApiTest.php
  tests/Controller/ShippingMethodApiTest.php
  tests/Controller/TaxRateApiTest.php
  tests/Controller/TaxonApiTest.php
  tests/DataFixtures/ORM/resources/cart.yml
  tests/DataFixtures/ORM/resources/cart_with_items.yml
  tests/DataFixtures/ORM/resources/checkout.yml
  tests/DataFixtures/ORM/resources/customers.yml
  tests/DataFixtures/ORM/resources/shipping_categories.yml
  tests/DataFixtures/ORM/resources/tax_categories.yml
  tests/DataFixtures/ORM/resources/tax_categories_for_filtering.yml
  tests/DataFixtures/ORM/resources/tax_rates.yml
Labels: Maintenance

#9287 Fix wrong CustomerInterface type in PHPDoc
  src/Sylius/Component/Core/Model/ShopUser.php
Labels: Bug
