Repository Sylius/Sylius, pull requests merged in 2018-10, with the labels that each got.

#9754 Fix the "REST APIs" link in the documentation
  docs/api/introduction.rst
Labels: Documentation

#9751 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Maintenance

#9752 Update installation.rst for Flex
  docs/book/installation/installation.rst
Labels: Documentation

#9743 Update shipments.rst
  docs/book/orders/shipments.rst
Labels: Documentation

#9739 [Documentation] Change parameters to env variables
  docs/book/installation/installation.rst
  docs/contributing/index.rst
  docs/cookbook/emails/mailer.rst
  docs/cookbook/payments/encrypting-gateway-config.rst
Labels: Documentation

#9746 [Documentation] v1.3 Update
  docs/_images/overriding_grids.png
  docs/book/architecture/translations.rst
  docs/book/installation/installation.rst
  docs/book/installation/requirements.rst
  docs/book/installation/vagrant_installation.rst
  docs/book/introduction/environments.rst
  docs/book/themes/themes.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_field_type.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_filter.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/configuration.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/delete_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/index_resources.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/routing.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/show_resource.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/update_resource.rst
  docs/components_and_bundles/bundles/SyliusShippingBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusTaxationBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusThemeBundle/important_changes.rst
  docs/cookbook/configuration/disabling-shop-admin-api.rst
  docs/cookbook/configuration/extending-bundles-other-em.rst
  docs/cookbook/deployment/platform-sh.rst
  docs/cookbook/emails/custom-email.rst
  docs/cookbook/emails/disabling-order-confirmation-email.rst
  docs/cookbook/entities/custom-model.rst
  docs/cookbook/entities/custom-translatable-model.rst
  docs/cookbook/frontend/admin-js-and-css.rst
  docs/cookbook/images/images-gridfs.rst
  docs/cookbook/images/images-on-entity.rst
  docs/cookbook/images/images.rst
  docs/cookbook/promotions/custom-promotion-action.rst
  docs/cookbook/promotions/custom-promotion-rule.rst
  docs/cookbook/shop/disabling-localised-urls.rst
  docs/cookbook/shop/embedding-products.rst
  docs/cookbook/shop/facebook-login.rst
  docs/customization/controller.rst
  docs/customization/factory.rst
  docs/customization/flash.rst
  docs/customization/form.rst
  docs/customization/grid.rst
  docs/customization/menu.rst
  docs/customization/model.rst
  docs/customization/repository.rst
  docs/customization/state_machine.rst
  docs/customization/template.rst
  docs/customization/translation.rst
  docs/customization/validation.rst
Labels: Documentation

#9756 Allow for null hostname in ChannelFixture
  src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
Labels: Bug, Enhancement

#9646 [Admin][Product edit] Change the value of the taxons individually when checked/unchecked.
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Labels: Admin, Bug

#9755 [Documentation] Fix API example for creating a taxon
  docs/api/taxons.rst
Labels: Documentation

#9685 Update gulpfile.babel.js
  src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
Labels: Maintenance

#8093 [Order] Fixed sylius:remove-expired-carts help
  src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
Labels: Bug, DX

#8494 set gender `u` as default value - resolves #8493
  src/Sylius/Bundle/CustomerBundle/Form/Type/GenderType.php
  tests/Responses/Expected/customer/create_validation_fail_response.json
  tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
  tests/Responses/Expected/customer/update_validation_fail_response.json
Labels: Bug

#9757 Make ArrayGridProvider more performant & suitable for PHP-PM
  src/Sylius/Component/Grid/Provider/ArrayGridProvider.php
Labels: Bug, Enhancement

#9760 [CoreBundle] Make sure promotion action/rule amount is an integer
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php
Labels: Bug

#9761 [ThemeBundle] Replace "symfony/symfony" dependency with specific Symfony packages
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/ThemeBundle/composer.json
Labels: Bug, Enhancement

#9762 [Grid] Fix getting enabled grid items
  src/Sylius/Component/Grid/Definition/Grid.php
  src/Sylius/Component/Grid/spec/Definition/GridSpec.php
Labels: Bug

#9759 [GridBundle] Do not put unnecessary "andWhere" in ExpressionBuilder
  src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
  src/Sylius/Component/Grid/Filter/DateFilter.php
  src/Sylius/Component/Grid/Filter/MoneyFilter.php
  src/Sylius/Component/Grid/spec/Filter/DateFilterSpec.php
  src/Sylius/Component/Grid/spec/Filter/MoneyFilterSpec.php
Labels: Bug

#9764 [ShippingBundle] Add validation for ShippingMethod calculator
  src/Sylius/Bundle/ShippingBundle/Resources/config/validation/ShippingMethod.xml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.en.yml
Labels: Bug, Enhancement

#9758 [ThemeBundle] Fix risky tests
  src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPassTest.php
  src/Sylius/Bundle/ThemeBundle/Tests/Translation/TranslatorTest.php
  src/Sylius/Bundle/ThemeBundle/phpunit.xml.dist
Labels: Maintenance

#9763 Update "Configuring taxation" docs
  docs/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.rst
Labels: Documentation, Enhancement

#9512 [Behat] Describe percentage promotion issue
  features/checkout/order_promotion/order_promotion_integrity_validation.feature
Labels: Bug

#9765 Keep the existing pagination when changing sorting on product list page
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
Labels: Bug, Shop

#9766 Update Composer's branch-alias for 1.3
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/FixturesBundle/composer.json
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ResourceBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/ThemeBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Grid/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Mailer/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Registry/composer.json
  src/Sylius/Component/Resource/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#9772 Fix doubled province id on checkout addressing page
  src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-province-field.js
Labels: Bug, Shop

#9769 [Behat] Add scenarios on resetting password validation feature
  features/account/resetting_password_validation.feature
  src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
  src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php
  src/Sylius/Behat/Page/Shop/Account/ResetPasswordPageInterface.php
Labels: Behat, Enhancement

#9776 [Core] Make implicit dependency explicit
  src/Sylius/Component/Core/composer.json
Labels: Maintenance

#9783 Correct grammar mistake in README
  README.md
Labels: Bug, Documentation

#9770 Show localised locale names
  UPGRADE-1.4.md
  features/locale/handling_different_locales_on_multiple_channels.feature
  features/locale/switching_current_locale.feature
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php
  src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
Labels: Admin, Enhancement, Shop, UX

#9788 Update installation.rst
  docs/book/installation/installation.rst
Labels: Documentation

#9791 [Docs] Update year in copyright
  docs/conf.py
Labels: Documentation

#9786 Add SyliusShopBundle form theme
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/address.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/complete.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectShipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Form/theme.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/login.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/register.html.twig
Labels: Enhancement, Shop

#9790 Update disabling-localised-urls.rst
  docs/cookbook/shop/disabling-localised-urls.rst
Labels: Documentation

#9789 [FixtureBundle] Add autoconfiguration for instance of FixtureInterface
  docs/components_and_bundles/bundles/SyliusFixturesBundle/architecture.rst
  docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_fixture.rst
  docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_listener.rst
  src/Sylius/Bundle/FixturesBundle/DependencyInjection/Compiler/FixtureRegistryPass.php
  src/Sylius/Bundle/FixturesBundle/DependencyInjection/Compiler/ListenerRegistryPass.php
  src/Sylius/Bundle/FixturesBundle/DependencyInjection/SyliusFixturesExtension.php
  src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/Compiler/FixtureRegistryPassTest.php
  src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/Compiler/ListenerRegistryPassTest.php
  src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/DummyFixture.php
  src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/DummyListener.php
  src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/SyliusFixturesExtensionTest.php
Labels: DX, Feature

#9800 Removed leftover Symfony3 references
  docs/contributing/code/bdd.rst
  src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
  src/Sylius/Bundle/ThemeBundle/Command/AssetsInstallCommand.php
Labels: Documentation, Maintenance

#9804 [ThemeBundle] Add support for Twig namespaced paths and "templates/" top-level directory
  src/Sylius/Bundle/ThemeBundle/Locator/BundleResourceLocator.php
  src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/templating.xml
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/FirstTestTheme/TestBundle/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/FirstTestTheme/TestBundle/views/Templating/twigNamespacedVanillaOverriddenThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/FirstTestTheme/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/SecondTestTheme/TestBundle/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/SecondTestTheme/TestBundle/views/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/SecondTestTheme/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/SecondTestTheme/views/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/views/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/views/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TemplatingTest.php
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/bothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/lastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/twigNamespacedVanillaOverriddenTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/twigNamespacedVanillaOverriddenThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/TestBundle/Resources/views/Templating/twigNamespacedVanillaTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/Resources/views/Templating/bothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/Resources/views/Templating/lastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/config/config.yml
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/templates/Templating/twigNamespacedBothThemesTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/templates/Templating/twigNamespacedLastThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/templates/Templating/twigNamespacedVanillaTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/templates/bundles/TestBundle/Templating/twigNamespacedVanillaOverriddenTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/Tests/Functional/templates/bundles/TestBundle/Templating/twigNamespacedVanillaOverriddenThemeTemplate.txt.twig
  src/Sylius/Bundle/ThemeBundle/spec/Locator/BundleResourceLocatorSpec.php
  src/Sylius/Bundle/ThemeBundle/spec/Templating/Locator/TemplateLocatorSpec.php
Labels: Bug, Feature

#9805 [Shop] Fix password request & contact pages with a mobile view.
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
Labels: Shop

#9803 `purge_mode` has been rename to `mode`
  docs/components_and_bundles/bundles/SyliusFixturesBundle/builtin_listeners.rst
Labels: Bug, Documentation

#9815 remove web server bundle on prod environment
  config/bundles.php
Labels: Bug

#9796 Improve product attributes JS
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
Labels: Admin, Bug

#9817 Upgrade security checker
  composer.json
  config/packages/security_checker.yaml
  etc/travis/suites/application/script/validate-composer-security
Labels: Maintenance

#9839 [Docs] How to disable admin notifications
  docs/cookbook/configuration/disabling-admin-notifications.rst
  docs/cookbook/configuration/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#9832 Fix gulp uglify error with arrow functions
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Labels: Admin, Bug

#9841 [Documentation] Make bundle templates extension part correct
  docs/customization/template.rst
Labels: Documentation

#9833 Use SyliusShop grid default template
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/index.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Grid/_default.html.twig
Labels: DX, Shop

#9834 Use SyliusShop simple menu template
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/layout.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Menu/simple.html.twig
Labels: DX, Shop

#9830 SensioGeneratorBundle vs SymfonyMakerBundle
  docs/cookbook/entities/custom-model.rst
Labels: Documentation

#9829 Wrong usage of returned data
  docs/book/configuration/locales.rst
Labels: Bug, Documentation

#9836 [Core] Bad reverting of ShippingPercentageDiscount promotion
  features/checkout/ability_to_confirm_an_order_with_a_promotion_on_shipping.feature
  src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
Labels: Bug

#9868 [Fix] Indentation error .platform.app.yml in docs
  docs/cookbook/deployment/platform-sh.rst
Labels: Bug, Documentation

#9854 Update installation.rst
  docs/components_and_bundles/bundles/SyliusTaxationBundle/installation.rst
Labels: Documentation

#9856 #9694 Do not show bulk sections and checkboxes if bulk actions are di…
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
Labels: Bug

#9883 Hydrate promotion_rules directly on loading active promotions for a channel (1n)
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PromotionRepository.php
Labels: Enhancement

#9888 change documentation: filename of _form.yml should have the extension…
  docs/cookbook/entities/custom-translatable-model.rst
Labels: Bug, Documentation
