Repository Sylius/Sylius, pull requests merged in 2018-09, with the labels that each got.

#9691 Fixing Typo in Documentation
  docs/cookbook/frontend/admin-js-and-css.rst
Labels: Documentation

#9695 Fix resolving environment variables
  .env.dist
  .env.test.dist
Labels: Bug

#9700 Allow to use Pagerfanta in both ^1.0 and ^2.0
  src/Sylius/Bundle/GridBundle/composer.json
  src/Sylius/Component/Resource/composer.json
Labels: Enhancement

#9683 Do not run tests if not needed
  .github/CONTRIBUTING.md
  etc/travis/suites/application/is_suitable.sh
  etc/travis/suites/common/before_install.sh
  etc/travis/suites/docs/is_suitable.sh
  etc/travis/suites/packages/is_suitable.sh
Labels: Maintenance

#9708 Fix typo in Behat feature
  features/inventory/cart_inventory/verify_inventory_quantity_when_updating_cart_summary.feature
Labels: Bug, Enhancement

#9716 Move symfony/flex dependency to require-dev
  composer.json
Labels: Enhancement

#9724 PHPSpec version not specified in docs
  docs/components_and_bundles/bundles/SyliusCustomerBundle/summary.rst
  docs/components_and_bundles/bundles/SyliusInventoryBundle/summary.rst
  docs/components_and_bundles/bundles/SyliusOrderBundle/summary.rst
  docs/components_and_bundles/bundles/SyliusPromotionBundle/summary.rst
  docs/components_and_bundles/components/Grid/summary.rst
  docs/components_and_bundles/components/Resource/summary.rst
Labels: Documentation

#9718 Remaining official plugins listed in README.md file
  README.md
Labels: Documentation

#9727 Do not stale issues selected to Roadmap
  .github/stale.yml
Labels: Enhancement, Maintenance

#9729 Minimalistic UPGRADE path from Sylius 1.2 to 1.3
  UPGRADE-1.3.md
Labels: Documentation, Maintenance

#9733 Improve upgrade instructions for 1.3 release
  UPGRADE-1.3.md
Labels: Enhancement

#9736 Make Flex recipes to be based on Sylius possible (with build passing)
  UPGRADE-1.3.md
  composer.json
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
Labels: Maintenance
