Repository Sylius/Sylius, pull requests merged in 2019-09, with the labels that each got.

#10651 removed customer from customer order grid
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer_order.yml
Labels: Feature

#10632 [ShopBundle] Logged customer after completing checkout can view order in his account
  features/checkout/accessing_order_right_after_completing_checkout.feature
  features/checkout/paying_for_order/accessing_order_right_after_completing_checkout.feature
  features/checkout/paying_for_order/changing_payment_method_after_order_confirmation.feature
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutThankYouContext.php
  src/Sylius/Behat/Page/Shop/Order/ThankYouPage.php
  src/Sylius/Behat/Page/Shop/Order/ThankYouPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/ShopBundle/Resources/views/Order/thankYou.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Feature

#10660 [Fixture] Shipment and payment date are same like order
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
Labels: Feature

#10658 [Payment] Filtering payments by channel
  features/payment/managing_payments/filtering_payments_by_channel.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Payment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
Labels: Feature

#10665 Remove ShippingBundle spec from autoload-dev
  composer.json
Labels: Maintenance

#10653 [Order] Added "no payments" label for order without payment
  features/order/managing_orders/seeing_order_payment_state_as_completed_if_order_total_is_zero.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Feature

#10667 Improve GUS information notification
  src/Sylius/Bundle/CoreBundle/Command/InformAboutGUSCommand.php
Labels: Enhancement

#10670 Fix unnecessarily centered payment
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
Labels: Admin, Bug, UX

#10679 Change channel code to name
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Grid/Field/channel.html.twig
Labels: Admin, UX

#10644 [Documentation] Add tip about locked adjustments
  docs/book/orders/adjustments.rst
Labels: Documentation

#10687 Add support menu and CTAs
  src/Sylius/Bundle/AdminBundle/Resources/views/_support.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Admin, Enhancement, UX

#10695 [Admin][Product] Fix displayed stocks on product show page
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
Labels: Admin, Bug

#10666 Test doctrine migrations up & down
  app/migrations/Version20170711151342.php
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-doctrine-migrations
Labels: Maintenance

#10694 [Admin][Product] Extract some variant related templates from product show
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantContent.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantContentPricing.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantContentShipping.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantItem.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
Labels: Admin, DX

#10713 [Behat] Improve dashboard page extensibility
  src/Sylius/Behat/Page/Admin/DashboardPage.php
Labels: DX
