Repository Sylius/Sylius, pull requests merged in 2019-06, with the labels that each got.

#10417 [Admin] Order summary UI + discounts and taxes viewing logic
  features/order/managing_orders/seeing_order_aggregated_discounts.feature
  features/order/managing_orders/seeing_order_aggregated_taxes.feature
  features/order/managing_orders/seeing_order_currency_on_show.feature
  features/order/managing_orders/seeing_order_discounts.feature
  features/order/managing_orders/seeing_order_item_detailed_data.feature
  features/order/managing_orders/seeing_order_item_included_taxes.feature
  features/order/managing_orders/seeing_order_with_different_promotions.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
  src/Sylius/Behat/Resources/config/services/pages/admin/order.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_summary.html.twig
  src/Sylius/Bundle/AdminBundle/Twig/OrderUnitTaxesExtension.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Core/Model/OrderItem.php
  src/Sylius/Component/Core/Model/OrderItemInterface.php
Labels: Admin, UX

#10423 [Doc] End of bugfix support for 1.3
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing/organization/release-process.rst
Labels: Documentation

#10410 Fix typo
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
Labels: Bug

#10432 Add known errors section to UPGRADE file
  UPGRADE-1.3.md
Labels: DX, Documentation

#10429 Add admin user avatar placeholder
  src/Sylius/Bundle/AdminBundle/Resources/views/_security.html.twig
Labels: Admin, UX

#10420 Change order summary table
  features/account/customer_account/viewing_orders_history/order_is_always_placed_in_a_base_currency_of_a_channel.feature
  features/checkout/ability_to_confirm_an_order_with_a_promotion_on_shipping.feature
  features/checkout/prices_get_updated_throughout_checkout.feature
  features/checkout/seeing_order_summary/seeing_shipping_discount_on_order_summary_page.feature
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_headers.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Labels: Shop, UX

#10438 Keep all prices in the same currency in checkout
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Labels: Bug, Shop, UX

#10412 [Docs] Added tip for using group sequence validations
  docs/customization/validation.rst
Labels: Documentation

#10442 Add an alert about unsaved changes
  package.json
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-forms-list.js
  yarn.lock
Labels: Admin, UX

#10441 [Inventory][Product] Move inventory to new tab
  features/inventory/displaying_inventory_tab_on_simple_product_edit_page.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/ui/inventory/displaying_inventory_on_edit_product_page.yml
  src/Sylius/Bundle/AdminBundle/Menu/ProductFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_inventory.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_inventory.html.twig
Labels: Admin, UX

#10443 Unify shipping row on the order summary table
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Labels: Shop, UX

#10440 Fix removing taxons with numeric codes from products
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Labels: Bug

#10371 [Docs] How to find out the resource config required when customizing models
  docs/customization/index.rst
  docs/customization/map.rst.inc
  docs/customization/model.rst
  docs/customization/tips_and_tricks.rst
Labels: Documentation

#10409 Create SECURITY.md
  SECURITY.md
  etc/travis/suites/application/is_suitable.sh
Labels: Maintenance

#10384 "Getting Started with Sylius" guide
  docs/_images/getting-started-with-sylius/channel.png
  docs/_images/getting-started-with-sylius/checkout-summary.png
  docs/_images/getting-started-with-sylius/country-creation.png
  docs/_images/getting-started-with-sylius/country-index.png
  docs/_images/getting-started-with-sylius/currency.png
  docs/_images/getting-started-with-sylius/gateways.png
  docs/_images/getting-started-with-sylius/installation1.png
  docs/_images/getting-started-with-sylius/installation2.png
  docs/_images/getting-started-with-sylius/locale.png
  docs/_images/getting-started-with-sylius/logo-after.png
  docs/_images/getting-started-with-sylius/logo-before.png
  docs/_images/getting-started-with-sylius/payment-method-creation.png
  docs/_images/getting-started-with-sylius/platform-sh-deployed-application.png
  docs/_images/getting-started-with-sylius/platform-sh-project-running.png
  docs/_images/getting-started-with-sylius/platform-sh-project.png
  docs/_images/getting-started-with-sylius/plugin-installed.png
  docs/_images/getting-started-with-sylius/product-creation.png
  docs/_images/getting-started-with-sylius/product-types.png
  docs/_images/getting-started-with-sylius/shipping-calculator.png
  docs/_images/getting-started-with-sylius/shipping-cost-1.png
  docs/_images/getting-started-with-sylius/shipping-cost-2.png
  docs/_images/getting-started-with-sylius/shipping-method.png
  docs/_images/getting-started-with-sylius/zone-creation.png
  docs/_images/getting-started-with-sylius/zones-types.png
  docs/_images/installation_checklist.png
  docs/getting-started-with-sylius/basic-configuration.rst
  docs/getting-started-with-sylius/custom-business-logic.rst
  docs/getting-started-with-sylius/deployment.rst
  docs/getting-started-with-sylius/first-product.rst
  docs/getting-started-with-sylius/index.rst
  docs/getting-started-with-sylius/installation.rst
  docs/getting-started-with-sylius/map.rst.inc
  docs/getting-started-with-sylius/plugin-installation.rst
  docs/getting-started-with-sylius/shipping-and-payment.rst
  docs/getting-started-with-sylius/shop-customizations.rst
  docs/getting-started-with-sylius/summary.rst
  docs/index.rst
Labels: Documentation, Roadmap

#10444 Change dashboard view
  behat.yml.dist
  etc/travis/suites/application/script/test-behat-with-javascript
  src/Sylius/Bundle/AdminBundle/Resources/private/img/admin-logo.svg
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_customers.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_orders.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_statistics.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_associations.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_attributes.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_media.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_search.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/_login.html.twig
Labels: Admin, Feature, UX

#10389 [UI] Hide filters by default on index pages
  etc/travis/suites/application/script/test-behat-with-javascript
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
Labels: Admin, UX

#10451 [Admin] Add possibility to configure custom index route in routing
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_breadcrumb.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_breadcrumb.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
Labels: Admin, Feature

#10450 Fix interfaces mapping in Doctrine for admin user and shop user
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/ResolveShopUserTargetEntityPass.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_user.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Customer.orm.xml
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
Labels: Bug

#10404 Fix huge autocomplete queries issue
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
  src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductRepository.php
  src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
  src/Sylius/Component/Product/Repository/ProductRepositoryInterface.php
  src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
Labels: Bug, Enhancement, UX

#10191 [taxon_fixtures] Fix child taxon slug generation
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
Labels: Bug

#10449 Administrator's avatar
  app/migrations/Version20190607135638.php
  features/user/managing_administrators/adding_avatar_to_administrator.feature
  features/user/managing_administrators/changing_administrator_avatar.feature
  src/Sylius/Behat/Context/Setup/AdminUserContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php
  src/Sylius/Behat/Element/Admin/TopBarElement.php
  src/Sylius/Behat/Element/Admin/TopBarElementInterface.php
  src/Sylius/Behat/Page/Admin/Administrator/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Administrator/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/elements/admin.xml
  src/Sylius/Behat/Resources/config/suites/ui/user/managing_administrators.yml
  src/Sylius/Behat/Resources/fixtures/troll.jpg
  src/Sylius/Behat/Service/Uploader/ImageUploader.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_avatarImage.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_media.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_security.html.twig
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/EventListener/ImageUploadListener.php
  src/Sylius/Bundle/CoreBundle/Form/Type/User/AdminUserType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/User/AvatarImageType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/AdminUser.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/AvatarImage.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/AvatarImage.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/ImageUploadListenerSpec.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
  src/Sylius/Component/Core/Model/AdminUser.php
  src/Sylius/Component/Core/Model/AdminUserInterface.php
  src/Sylius/Component/Core/Model/AvatarImage.php
  src/Sylius/Component/Core/Model/ImageAwareInterface.php
  src/Sylius/Component/Core/spec/Model/AdminUserSpec.php
  src/Sylius/Component/Core/spec/Model/AvatarImageSpec.php
  tests/Responses/Expected/admin_user/create_validation_fail_response.json
  tests/Responses/Expected/admin_user/update_validation_fail_response.json
Labels: Admin, Feature, Roadmap

#10455 Improve admin product show page UI
  src/Sylius/Behat/Element/Product/ShowPage/AssociationsElement.php
  src/Sylius/Behat/Element/Product/ShowPage/VariantsElement.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_associations.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_attributes.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_configurableProduct.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_media.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_moreDetails.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_options.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_pricing.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_shipping.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_simpleProduct.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_taxonomy.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
  src/Sylius/Bundle/AdminBundle/Twig/ChannelNameExtension.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Admin, Enhancement, Roadmap, UX

#10460 AvatarImage Doctrine mapping fix
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/AvatarImage.orm.xml
Labels: Bug

#10396 [Admin] Avoid javascript in saving positions
  features/product/managing_products/sorting_products_within_a_taxon_by_position.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPage.php
  src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_taxon.yml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-product.js
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Action/updatePositions.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_position.html.twig
  src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
Labels: Admin, Enhancement

#10462 [Docs] Update Sylius versions in installation and contribution guides
  docs/contributing/code/patches.rst
  docs/contributing/documentation/overview.rst
  docs/getting-started-with-sylius/installation.rst
Labels: Documentation

#10464 Do not crash when duplicated locales are passed to the fixture
  src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
  src/Sylius/Bundle/CoreBundle/spec/Fixture/LocaleFixtureSpec.php
Labels: Bug

#10165 Product attribute fixtures improvements
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
  tests/Fixture/ProductAttributeFixturesTest.php
Labels: Bug

#10468 Remove Symfony workarounds and add conflicts
  composer.json
  phpstan.neon
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Routing/Matcher/Dumper/PhpMatcherDumper.php
Labels: Maintenance

#10467 Drop support for Symfony 4.1 and 4.2
  .travis.yml
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#10471 Add footer with Sylius version to the admin panel
  src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
Labels: Admin, UX

#10473 Update docs to follow Symfony 4 standards
  docs/book/architecture/contact.rst
  docs/book/customers/adminuser.rst
  docs/book/orders/payments.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_action.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_bulk_action.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/custom_filter.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
  docs/components_and_bundles/bundles/SyliusMailerBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusMailerBundle/using_custom_adapter.rst
  docs/components_and_bundles/bundles/SyliusMailerBundle/your_first_email.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/configuration.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/installation.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/routing.rst
  docs/components_and_bundles/bundles/SyliusResourceBundle/show_resource.rst
  docs/components_and_bundles/bundles/SyliusThemeBundle/your_first_theme.rst
  docs/cookbook/configuration/disabling-admin-notifications.rst
  docs/cookbook/configuration/disabling-shop-admin-api.rst
  docs/cookbook/configuration/extending-bundles-other-em.rst
  docs/cookbook/configuration/map.rst.inc
  docs/cookbook/deployment/platform-sh-advanced.rst
  docs/cookbook/deployment/platform-sh.rst
  docs/cookbook/emails/custom-email.rst
  docs/cookbook/emails/disabling-order-confirmation-email.rst
  docs/cookbook/emails/mailer.rst
  docs/cookbook/entities/custom-model.rst
  docs/cookbook/entities/custom-translatable-model.rst
  docs/cookbook/images/images-gridfs.rst
  docs/cookbook/images/images-on-entity.rst
  docs/cookbook/images/images.rst
  docs/cookbook/images/map.rst.inc
  docs/cookbook/index.rst
  docs/cookbook/payments/encrypting-gateway-config.rst
  docs/cookbook/promotions/custom-promotion-rule.rst
  docs/cookbook/shop/checkout.rst
  docs/cookbook/shop/disabling-guest-checkout.rst
  docs/cookbook/shop/embedding-products.rst
  docs/cookbook/shop/facebook-login.rst
  docs/customization/flash.rst
  docs/customization/form.rst
  docs/plugins/plugin-development-guide/implementation.rst
  docs/plugins/plugin-development-guide/naming.rst
Labels: DX, Documentation, Maintenance

#10472 [Admin] Index of payments
  features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
  features/payment/managing_payments/browsing_payments.feature
  features/payment/managing_payments/filtering_payments_by_state.feature
  features/payment/managing_payments/managing_of_payment_status.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Payment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/pages/admin.xml
  src/Sylius/Behat/Resources/config/services/pages/admin/payment.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/payment.yml
Labels: Admin, Feature
