Repository Sylius/Sylius, pull requests merged in 2019-07, with the labels that each got.

#10482 [Promotion] Fix Action creation doc
  docs/cookbook/promotions/custom-promotion-action.rst
Labels: Bug, Documentation

#10477 Improve bulk actions
  src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
  src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-check-all.js
  src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
Labels: Admin, UX

#10485 [Promotion] Coupon prefix and suffix
  docs/book/orders/coupons.rst
  features/promotion/managing_coupons/coupon_generate_validation.feature
  features/promotion/managing_coupons/generating_coupon.feature
  features/promotion/managing_coupons/generating_coupon_with_prefix_and_suffix.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/IndexPage.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services/pages/admin/promotion_coupon.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Generate/_form.html.twig
  src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponGeneratorInstructionType.php
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Promotion/Generator/PromotionCouponGenerator.php
  src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstruction.php
  src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstructionInterface.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorInstructionSpec.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorSpec.php
Labels: Feature

#10483 [Admin]Admin choose channel in product show page
  features/product/viewing_product_in_admin_panel/viewing_product_for_particular_channel.feature
  features/product/viewing_product_in_admin_panel/viewing_product_for_single_channel.feature
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Behat/Page/Admin/Product/ShowPage.php
  src/Sylius/Behat/Page/Admin/Product/ShowPageInterface.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
  src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_header.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Feature

#10491 [Admin] Form validation error
  features/user/managing_customer_groups/customer_group_validation.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
  src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
  src/Sylius/Behat/Page/Admin/Crud/CreatePageInterface.php
  src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/form_validation_errors_checker.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Feature

#10492 [Admin] Minor fixes customer group validation form
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.en.yml
Labels: Bug

#10401 Psalm
  composer.json
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-psalm
  psalm.xml
  src/Sylius/Component/Core/Uploader/ImageUploader.php
  symfony.lock
Labels: DX, Environment

#10496 [UPGRADE] Mention locale requirement change in UPGRADE-1.5
  UPGRADE-1.5.md
Labels: Maintenance

#10499 [Admin] Fix css file
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
Labels: Admin, Bug

#10489 Make it possible to have no shipping methods for Order fixtures
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Labels: Enhancement

#10509 [Admin] Add link to product in variant breadcrumb
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Update/_breadcrumb.html.twig
Labels: Enhancement

#10516 Fix Psalm false-positives
  composer.json
  symfony.lock
Labels: Maintenance

#10510 Add avatar preview
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_media.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
Labels: Admin, UX

#10498 Add search bar css rule for Firefox
  src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
Labels: Bug, UX

#10520 [Admin] Unify payment and shipment labels
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Common/Label/paymentState.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Common/Label/shipmentState.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payment.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
Labels: Admin, UX

#10518 [Admin] Unify order link in Orders, Payments, Shipments
  features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
  src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Payment/IndexPageInterface.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Grid/Field/number.html.twig
Labels: Admin, UX

#10522 Fix 'disabled' label
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
Labels: UX

#10531 Improve filters UI
  src/Sylius/Bundle/UiBundle/Resources/private/sass/_filters.scss
  src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/date.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/money.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
Labels: Admin, RFC, UX

#10535 [Shop] Fix passed channel context service to be composite
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
Labels: Bug

#10517 [Grid] Allow not to pass "apply_transition" button class
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/applyTransition.html.twig
Labels: Enhancement

#10536 [Docs] Make Plugins and Plugin Development Guide more visible
  docs/book/architecture/architecture.rst
  docs/book/index.rst
  docs/book/map.rst.inc
  docs/book/orders/index.rst
  docs/book/orders/map.rst.inc
  docs/book/orders/orders.rst
  docs/book/orders/payments.rst
  docs/book/orders/refunds.rst
  docs/book/plugins/approved-plugins.rst
  docs/book/plugins/creating-plugin.rst
  docs/book/plugins/index.rst
  docs/book/plugins/map.rst.inc
  docs/book/plugins/official-plugins.rst
  docs/cookbook/shop/cms.rst
  docs/customization/plugins.rst.inc
  docs/customization/template.rst
  docs/getting-started-with-sylius/plugin-installation.rst
  docs/getting-started-with-sylius/summary.rst
  docs/index.rst
  docs/plugin-development-guide/idea.rst
  docs/plugin-development-guide/implementation.rst
  docs/plugin-development-guide/index.rst
  docs/plugin-development-guide/installation.rst
  docs/plugin-development-guide/map.rst.inc
  docs/plugin-development-guide/naming.rst
  docs/plugin-development-guide/specification.rst
  docs/plugin-development-guide/summary.rst
  docs/plugins/map.rst.inc
Labels: Documentation

#10534 [Fixtures] Variant name now is concatenated options value.
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
Labels: Enhancement

#10541 Update README.md
  README.md
Labels: Maintenance

#10548 [HotFix?] Move mysql service to fix the build
  .travis.yml
Labels: Bug

#10542 [Fixtures] Product fixtures in yaml.
  src/Sylius/Bundle/CoreBundle/Fixture/CapsProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/DressProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/JeansProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/NewTshirtProductFixture.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
Labels: Enhancement

#10546 Improve filters
  src/Sylius/Bundle/UiBundle/Resources/private/sass/_filters.scss
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/date.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/money.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
Labels: Admin, UX

#10547 [Admin] Remove avatar
  features/user/managing_administrators/removing_administartor_avatar.feature
  src/Sylius/Behat/Context/Setup/AdminUserContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php
  src/Sylius/Behat/Element/Admin/TopBarElement.php
  src/Sylius/Behat/Element/Admin/TopBarElementInterface.php
  src/Sylius/Behat/Page/Admin/Administrator/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Administrator/UpdatePageInterface.php
  src/Sylius/Bundle/AdminBundle/Action/RemoveAvatarAction.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/admin_user.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-delete-avatar-image-button-visible.js
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AvatarImageRepository.php
  src/Sylius/Component/Core/Repository/AvatarImageRepositoryInterface.php
Labels: Admin, Feature

#10553 Flags are not languages
  src/Sylius/Bundle/AdminBundle/Resources/views/Common/_address.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Grid/Field/name.html.twig
  src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/flags.html.twig
Labels: Bug

#10555 [Admin][AdminUser] Improvements for removing an avatar
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/admin_user.yml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-delete-avatar-image-button-visible.js
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
Labels: Bug

#10552 [Order] Change OrderItemController methods to protected
  src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
Labels: DX

#10540 Skip oauth_user_factory_is_not_overridden test if HWIOAuthBundle is not installed
  src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
  tests/Functional/UpdatingUserPasswordEncoderTest.php
Labels: Bug

#10560 [Behat][AdminUser] Fix filename typo
  features/user/managing_administrators/removing_administrator_avatar.feature
Labels: Admin, Behat
