Repository Sylius/Sylius, pull requests merged in 2019-05, with the labels that each got.

#10352 Update documentation products.rst
  docs/book/products/products.rst
Labels: Bug, Documentation

#10356 Quick fix product variants api invalid json
  docs/api/product_variants.rst
Labels: API, Documentation

#10357 Fix wrong use statement in example
  docs/cookbook/promotions/custom-promotion-action.rst
Labels: Documentation

#10350 fix default repository for variant and association type resources
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
Labels: Bug

#10358 [Maintenance] Upgrade minimal jquery version
  package.json
  yarn.lock
Labels: Maintenance

#10360 Revert "fix default repository for variant and association type resources"
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
Labels: Bug

#10362 Update release process with dates for 1.5 - 1.7 releases
  docs/contributing/organization/release-process.rst
Labels: Documentation

#10290 [Docs] Update "Customizing Repositories"
  docs/customization/repository.rst
Labels: Documentation

#10349 [Docs] Update "Customizing Validation"
  docs/customization/validation.rst
Labels: Documentation

#10351 [Docs] Update "Customizing translations"
  docs/_images/after_customizing_translation.png
  docs/_images/before_customizing_translation.png
  docs/customization/translation.rst
Labels: Documentation

#10353 [Docs] Update "Customization flashes "
  docs/_images/flash_after_customization.png
  docs/_images/flash_before_customization.png
  docs/customization/flash.rst
Labels: Documentation

#10314 [Docs] Update "Customizing Forms"
  docs/customization/form.rst
Labels: Documentation

#10315 [Docs] Update "Customizing Factories"
  docs/customization/factory.rst
Labels: Documentation

#10299 [Docs] Update "Customizing Models"
  docs/customization/model.rst
Labels: Documentation

#10330 [Docs] Update "Customizing Controllers"
  docs/customization/controller.rst
Labels: Documentation

#10359 [Docs] Update "Customizing Grids"
  docs/customization/grid.rst
Labels: Documentation

#10348 [Docs] Update "customizing menus"
  docs/_images/admin_panel_customer_menu.png
  docs/_images/admin_panel_order_menu.png
  docs/_images/admin_panel_product_menu.png
  docs/_images/admin_panel_variant_menu.png
  docs/customization/menu.rst
Labels: Documentation

#10365 [Admin][Promotion] Fix removing taxon used in promotion rule
  features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_taxon.feature
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Behat/Context/Transform/TaxonContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Context/Ui/Admin/RemovingTaxonContext.php
  src/Sylius/Behat/NotificationType.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_promotions.yml
  src/Sylius/Behat/Resources/config/suites/ui/taxonomy/managing_taxons.yml
  src/Sylius/Behat/Service/NotificationChecker.php
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/TaxonDeletionListenerSpec.php
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
  src/Sylius/Component/Core/Promotion/Updater/Rule/HasTaxonRuleUpdater.php
  src/Sylius/Component/Core/Promotion/Updater/Rule/TaxonAwareRuleUpdaterInterface.php
  src/Sylius/Component/Core/Promotion/Updater/Rule/TotalOfItemsFromTaxonRuleUpdater.php
  src/Sylius/Component/Core/spec/Promotion/Updater/Rule/HasTaxonRuleUpdaterSpec.php
  src/Sylius/Component/Core/spec/Promotion/Updater/Rule/TotalOfItemsFromTaxonRuleUpdaterSpec.php
Labels: Bug

#10378 update documentation how to use api
  docs/cookbook/api/api.rst
Labels: Documentation

#10380 [Behat] Fix duplicate step definition
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
Labels: Bug

#10383 [Behat] Make feature filenames consistent with others
  features/product/viewing_products/accessing_product_page_via_permalink.feature
  features/shipping/managing_shipments/accessing_shipments_order_from_shipment_index.feature
Labels: Behat

#10228 Improve taxon UI
  features/taxonomy/managing_taxons/deleting_taxon.feature
  src/Sylius/Behat/Page/Admin/Product/IndexPage.php
  src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPage.php
  src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-taxon-tree.js
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_taxonomy.scss
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/index.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithoutButtons.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/create.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/update.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Admin, UX

#10386 [Build Fix][Behat] Change scenarios to @javascript due to taxon tree changes
  features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_taxon.feature
Labels: Bug

#10388 Fix product show page margins
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_breadcrumb.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_configurableProduct.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_simpleProduct.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/show.html.twig
Labels: Admin, UX

#10391 [Admin][Product] Show page fixes
  src/Sylius/Behat/Context/Setup/ProductTaxonContext.php
  src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
  src/Sylius/Behat/Element/Product/ShowPage/MediaElement.php
Labels: Admin, Bug

#10364 As an Administrator, I want always to have proper option values selected while editing a product variant
  features/product/managing_product_variants/seeing_correct_option_values_while_editing_product_variant.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
  src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php
  src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php
  src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php
Labels: Bug

#10375 [Docs] Update "Customizing State Machine"
  docs/customization/state_machine.rst
Labels: Documentation

#10342 [Fixture] Togglable default locale loading
  src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
  src/Sylius/Bundle/CoreBundle/spec/Fixture/LocaleFixtureSpec.php
Labels: Enhancement

#10394 Fix error caused by the taxon tree
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-taxon-tree.js
Labels: Admin, UX

#10372 Image display in edit form
  src/Sylius/Bundle/AdminBundle/Resources/views/Form/imagesTheme.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
Labels: Bug

#10407 Bump the Sylius release versions in docs
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing/code/patches.rst
Labels: Documentation

#10406 [Fixtures] Added random generated order complete date
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Labels: DX, Enhancement

#10392 improved code quality
  src/Sylius/Behat/Context/Setup/PaymentContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Setup/ShippingContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/RegistrationAfterCheckoutContext.php
  src/Sylius/Behat/Element/Product/ShowPage/VariantsElement.php
  src/Sylius/Behat/Page/Admin/Promotion/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Zone/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Service/ResponseLoader.php
  src/Sylius/Bundle/CoreBundle/Application/SyliusPluginTrait.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/Handler/ResourceDeleteHandlerSpec.php
  src/Sylius/Bundle/OrderBundle/Form/DataMapper/OrderItemQuantityDataMapper.php
  src/Sylius/Bundle/PayumBundle/Action/Offline/StatusAction.php
  src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
  src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php
  src/Sylius/Component/Attribute/AttributeType/CheckboxAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/DateAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/DatetimeAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/IntegerAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/PercentAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/SelectAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/TextAttributeType.php
  src/Sylius/Component/Attribute/AttributeType/TextareaAttributeType.php
  src/Sylius/Component/Core/Resolver/EligibleDefaultShippingMethodResolver.php
  src/Sylius/Component/User/Security/PasswordUpdater.php
Labels: DX

#10355 Adding a coupon generator command
  src/Sylius/Bundle/PromotionBundle/Command/GenerateCouponsCommand.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/command.xml
  src/Sylius/Bundle/PromotionBundle/Tests/Command/GenerateCouponsCommandTest.php
Labels: Feature

#10399 Add info into install command about need of setting the locale in symfony config
  src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php
Labels: DX

#10400 Add discounts and totals in the cart
  features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_an_item_in_order_when_tax_rate_included_in_price.feature
  features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_shipping_when_tax_rate_included_in_price.feature
  features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_whole_order_when_tax_rate_included_in_price.feature
  features/taxation/applying_taxes/applying_correct_taxes_for_product_with_tax_rate_included_in_price.feature
  features/taxation/applying_taxes/applying_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
  features/taxation/applying_taxes/not_applying_taxes_for_products_without_tax_category.feature
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php
  src/Sylius/Bundle/ShopBundle/Twig/OrderTaxesTotalExtension.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Shop
