Repository Sylius/Sylius, pull requests merged in 2019-04, with the labels that each got.

#10242 Fix variant without options values generation
  features/product/managing_product_variants/preventing_the_generation_of_products_variants_from_options_without_any_values.feature
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
  src/Sylius/Behat/Page/Admin/ProductVariant/GeneratePage.php
  src/Sylius/Behat/Page/Admin/ProductVariant/GeneratePageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/generate.html.twig
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php
  src/Sylius/Bundle/ProductBundle/Resources/config/services/form.xml
  src/Sylius/Component/Product/Generator/ProductVariantGenerator.php
  src/Sylius/Component/Resource/Exception/VariantWithNoOptionsValuesException.php
Labels: Bug

#10280 [Travis] Update mysql version to speed up builds
  .travis.yml
  etc/travis/suites/application/before_script.sh
Labels: Bug

#10276 Upgrade flex to use composer dump-env
  .env
  composer.json
  etc/travis/suites/application/install.sh
Labels: Maintenance

#10279 [Documentation][ResourceBundle] 7.1. Overriding the Template and Criteria invalid config
  docs/components_and_bundles/bundles/SyliusResourceBundle/index_resources.rst
Labels: Documentation

#10283 [UserBundle] Fix user comparaison on user delete listener
  src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UserDeleteListenerSpec.php
Labels: Bug

#10271 select filter + filter shipment by state
  docs/components_and_bundles/bundles/SyliusGridBundle/filters.rst
  features/shipping/managing_shipments/filtering_shipments_by_state.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services/pages/admin/shipment.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/GridBundle/Form/Type/Filter/SelectFilterType.php
  src/Sylius/Bundle/GridBundle/Resources/config/services/filters.xml
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/select.html.twig
  src/Sylius/Component/Grid/Filter/SelectFilter.php
Labels: Admin, Feature

#10250 See Manage coupons from template edit promotion
  features/promotion/managing_promotions/accessing_the_coupons_management_from_the_promotion_page.feature
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Event/ManageCouponsMenuBuilderEvent.php
  src/Sylius/Bundle/AdminBundle/Menu/ManageCouponsMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_toolbar.html.twig
  src/Sylius/Bundle/AdminBundle/spec/Event/ManageCouponsMenuBuilderEventSpec.php
Labels: Feature

#10233 Payment status at order history page
  features/account/customer_account/viewing_orders_history/viewing_payment_status_for_an_order.feature
  src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/orderPaymentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/singlePaymentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
Labels: Feature, UX

#10234 Orders shipment status
  features/account/customer_account/viewing_orders_history/viewing_shipment_status_on_a_placed_order_show_page.feature
  src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/orderShipmentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/singleShipmentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_shipments.html.twig
Labels: Feature, UX

#10258 Changing shipment state in shipment index
  features/shipping/managing_shipments/managing_of_shipments_status.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.en.yml
Labels: Feature

#10289 Fix re-authenticating for impersonated users
  config/packages/security.yaml
  src/Sylius/Behat/Service/SecurityService.php
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
Labels: Bug

#10178 fixes #10173, wrong regular expression for locale
  config/routes/sylius_shop.yaml
  docs/cookbook/shop/disabling-localised-urls.rst
  features/locale/browsing_shop_in_different_than_default_locale.feature
Labels: Bug

#10281 Improved: Product fixture (fixed #10272)
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductFixtureTest.php
Labels: Feature

#10294 [Docs] Fix presentation of "How to configure mailer" cookbook
  docs/cookbook/emails/mailer.rst
Labels: Documentation

#10298 [DOC][Installation] Fix minor typo
  docs/book/installation/installation.rst
Labels: Documentation

#10301 Adopt Symfony 4 directory structure in docs
  docs/cookbook/frontend/admin-js-and-css.rst
Labels: Documentation

#10240 #9965 Feature/local in sylius install
  src/Sylius/Behat/Context/Cli/InstallerContext.php
  src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
  src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php
  src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetupInterface.php
Labels: Feature

#10260 Show order directly from shipments page
  features/shipping/managing_shipments/access_shipments_order_from_shipment_index.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
Labels: Feature

#10304 [Docs] Update contributing guide
  docs/contributing/documentation/overview.rst
Labels: Documentation

#10318 [Admin][Promotion] Update promotion menu builder name to be consistent with other
  src/Sylius/Bundle/AdminBundle/Event/PromotionMenuBuilderEvent.php
  src/Sylius/Bundle/AdminBundle/Menu/PromotionUpdateMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_toolbar.html.twig
  src/Sylius/Bundle/AdminBundle/spec/Event/PromotionMenuBuilderEventSpec.php
Labels: Admin, DX, Enhancement

#10309 Do not depend on transient dependencies for "symfony/intl" package
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
Labels: Maintenance

#10209 [Shop] Use first variant image on a cart page
  config/packages/test/sylius_uploader.yaml
  config/packages/test_cached/sylius_uploader.yaml
  features/cart/shopping_cart/having_proper_product_image_displayed_in_cart.feature
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
  src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
  src/Sylius/Behat/Service/Uploader/ImageUploader.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
Labels: Feature

#10310 [PromotionCoupon] Non reusable coupons after cancelling the orders
  app/migrations/Version20190416073011.php
  features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
  features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_usage_limit.feature
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/_form.html.twig
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionCouponTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/PromotionCoupon.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Core/Model/PromotionCoupon.php
  src/Sylius/Component/Core/Model/PromotionCouponInterface.php
  src/Sylius/Component/Core/Promotion/Modifier/OrderPromotionsUsageModifier.php
  src/Sylius/Component/Core/spec/Model/PromotionCouponSpec.php
  src/Sylius/Component/Core/spec/Promotion/Modifier/OrderPromotionsUsageModifierSpec.php
  tests/Responses/Expected/promotion_coupon/create_validation_fail_response.json
Labels: Feature

#10199 Allowing options to be given with resource[0].id syntax
  src/Sylius/Bundle/ResourceBundle/Grid/Parser/OptionsParser.php
  src/Sylius/Bundle/ResourceBundle/spec/Grid/Parser/OptionsParserSpec.php
Labels: Feature

#10308 Fix base locale
  src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
Labels: Bug

#10325 Extract Mailer component & bundle
  composer.json
  phpspec.yml.dist
  src/Sylius/Bundle/MailerBundle/.gitignore
  src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MailerBundle/DependencyInjection/SyliusMailerExtension.php
  src/Sylius/Bundle/MailerBundle/LICENSE
  src/Sylius/Bundle/MailerBundle/README.md
  src/Sylius/Bundle/MailerBundle/Renderer/Adapter/EmailTwigAdapter.php
  src/Sylius/Bundle/MailerBundle/Resources/config/services.xml
  src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
  src/Sylius/Bundle/MailerBundle/SyliusMailerBundle.php
  src/Sylius/Bundle/MailerBundle/composer.json
  src/Sylius/Bundle/MailerBundle/phpspec.yml.dist
  src/Sylius/Bundle/MailerBundle/phpunit.xml.dist
  src/Sylius/Bundle/MailerBundle/spec/Renderer/Adapter/EmailTwigAdapterSpec.php
  src/Sylius/Bundle/MailerBundle/spec/Sender/Adapter/SwiftMailerAdapterSpec.php
  src/Sylius/Bundle/MailerBundle/test/app/AppKernel.php
  src/Sylius/Bundle/MailerBundle/test/app/config/config.yml
  src/Sylius/Bundle/MailerBundle/test/app/config/parameters.yml
  src/Sylius/Bundle/MailerBundle/test/app/console
  src/Sylius/Bundle/MailerBundle/test/src/Tests/SyliusMailerBundleTest.php
  src/Sylius/Component/Mailer/.gitignore
  src/Sylius/Component/Mailer/Event/EmailRenderEvent.php
  src/Sylius/Component/Mailer/Event/EmailSendEvent.php
  src/Sylius/Component/Mailer/Factory/EmailFactory.php
  src/Sylius/Component/Mailer/Factory/EmailFactoryInterface.php
  src/Sylius/Component/Mailer/LICENSE
  src/Sylius/Component/Mailer/Model/Email.php
  src/Sylius/Component/Mailer/Model/EmailInterface.php
  src/Sylius/Component/Mailer/Provider/DefaultSettingsProvider.php
  src/Sylius/Component/Mailer/Provider/DefaultSettingsProviderInterface.php
  src/Sylius/Component/Mailer/Provider/EmailProvider.php
  src/Sylius/Component/Mailer/Provider/EmailProviderInterface.php
  src/Sylius/Component/Mailer/README.md
  src/Sylius/Component/Mailer/Renderer/Adapter/AbstractAdapter.php
  src/Sylius/Component/Mailer/Renderer/Adapter/AdapterInterface.php
  src/Sylius/Component/Mailer/Renderer/RenderedEmail.php
  src/Sylius/Component/Mailer/Sender/Adapter/AbstractAdapter.php
  src/Sylius/Component/Mailer/Sender/Adapter/AdapterInterface.php
  src/Sylius/Component/Mailer/Sender/Sender.php
  src/Sylius/Component/Mailer/Sender/SenderInterface.php
  src/Sylius/Component/Mailer/SyliusMailerEvents.php
  src/Sylius/Component/Mailer/composer.json
  src/Sylius/Component/Mailer/phpspec.yml.dist
  src/Sylius/Component/Mailer/spec/Factory/EmailFactorySpec.php
  src/Sylius/Component/Mailer/spec/Model/EmailSpec.php
  src/Sylius/Component/Mailer/spec/Provider/EmailProviderSpec.php
  src/Sylius/Component/Mailer/spec/Sender/SenderSpec.php
Labels: Maintenance

#10316 [Admin][Product] Access the variants management from product edit page
  docs/customization/menu.rst
  features/product/managing_products/accessing_variants_management_from_product_edit_page.feature
  src/Sylius/Behat/Context/Ui/Admin/BrowsingProductVariantsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AdminBundle/Menu/ProductUpdateMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Update/_toolbar.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Menu/top.html.twig
Labels: Admin, Feature, Roadmap

#10328 Remove dead configuration related to pre-stable Sylius RBAC
  docs/cookbook/deployment/platform-sh.rst
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml
Labels: Maintenance

#10331 [Shop] Update grid action and filter keys to decouple shop from admin
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Action/show.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Filter/string.html.twig
  src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/composer.json
Labels: Bug, Shop

#10320 fix OrderBundle depends on Core component #10319
  src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
  src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
Labels: Bug

#10335 Bring back "pay" grid action for backwards compatibility
  composer.json
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Grid/Action/_pay_deprecated.html.twig
  src/Sylius/Bundle/ShopBundle/composer.json
Labels: Bug

#10338 Removing unused service
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
Labels: Bug

#10340 Fix #9646 by removing lambdas in JS file
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Labels: Bug

#10341 Revert "Fix base locale"
  src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
Labels: Bug, Maintenance
