Repository Sylius/Sylius, pull requests merged in 2019-11, with the labels that each got.

#10812 [Shop] Hide shipping costs for orders with virtual products
  features/cart/shopping_cart/seeing_shipping_costs_only_when_required.feature
  features/checkout/seeing_order_summary/seeing_shipping_total_on_order_summary_page.feature
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
Labels: Shop, UX

#10811 Explicitly list deprecated things in the code & solve Twig deprecations
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php
  src/Sylius/Bundle/AddressingBundle/Twig/ProvinceNamingExtension.php
  src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php
  src/Sylius/Bundle/AdminBundle/Twig/ShopExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/ProductVariantsPricesExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/VariantResolverExtension.php
  src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
  src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php
  src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
  src/Sylius/Bundle/MoneyBundle/Twig/ConvertMoneyExtension.php
  src/Sylius/Bundle/MoneyBundle/Twig/FormatMoneyExtension.php
  src/Sylius/Bundle/OrderBundle/Twig/AggregateAdjustmentsExtension.php
  src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php
  src/Sylius/Bundle/ShopBundle/Twig/OrderTaxesTotalExtension.php
  src/Sylius/Bundle/UiBundle/Twig/PercentageExtension.php
  src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
Labels: Enhancement, Maintenance

#10820 Rename shop user factory to help autowiring
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
Labels: Enhancement

#10821 Specify PHP version for SymfonyInsights
  .symfony.insight.yaml
Labels: Maintenance

#10819 Fixed: Typo/artifact
  src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php
Labels: Bug

#10818 [Payum][Checkout] Pass address data to PayPal after checkout
  src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
  src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
Labels: Feature

#10823 Remove unnecessary +x chmod on some files
  docs/book/themes/themes.rst
  src/Sylius/Bundle/ReviewBundle/Resources/config/doctrine/model/Review.orm.xml
  src/Sylius/Bundle/ReviewBundle/Resources/config/doctrine/model/Reviewer.orm.xml
  src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
Labels: Maintenance

#10825 Fixed: Typo at grid configuration example
  docs/components_and_bundles/bundles/SyliusGridBundle/configuration.rst
Labels: Bug, Documentation

#10803 Add Webpack Encore
  .gitignore
  composer.json
  config/bundles.php
  config/packages/assets.yaml
  config/packages/prod/webpack_encore.yaml
  config/packages/webpack_encore.yaml
  package.json
  src/Sylius/Bundle/AdminBundle/Resources/private/entry.js
  src/Sylius/Bundle/AdminBundle/Resources/views/_scripts.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/private/entry.js
  src/Sylius/Bundle/ShopBundle/Resources/views/_scripts.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
  symfony.lock
  webpack.config.js
  yarn.lock
Labels: DX, RFC, UX

#10822 Fix typo in TaxonomyElementInterface classname
  src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
  src/Sylius/Behat/Element/Product/ShowPage/TaxonomyElement.php
  src/Sylius/Behat/Element/Product/ShowPage/TaxonomyElementInterface.php
Labels: Bug, Maintenance

#10824 Use SessionInterface instead of Session in UserImpersonator
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
Labels: Enhancement, Maintenance

#10806 [Order] include order promotion adjustments in order promotion total
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/spec/Model/OrderSpec.php
Labels: Bug

#10827 New Webpack approach
  .gitignore
  composer.json
  config/bundles.php
  config/packages/assets.yaml
  config/packages/prod/webpack_encore.yaml
  config/packages/webpack_encore.yaml
  symfony.lock
Labels: Bug

#10805 [Addressing] Make sure the CountryNameExtension::translateCountryIsoCode() always returns a string
  src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php
  src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php
Labels: Enhancement

#10826 Execute PHPUnit tests inside AdminApiBundle
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/phpunit.xml.dist
Labels: Bug, Maintenance

#10734 Added: TimestampableInterface to core TaxonInterface (fixes #10728)
  src/Sylius/Component/Core/Model/TaxonInterface.php
Labels: Bug

#10831 [Docs] Theming Guide: Webpack Encore v1
  docs/index.rst
  docs/theming/index.rst
  docs/theming/map.rst.inc
  docs/theming/webpack.rst
Labels: Documentation

#10829 Remove Symfony ^3.4 support on the master branch
  .travis.yml
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#10832 Do not merge promotion action configuration
  src/Sylius/Component/Promotion/Model/PromotionAction.php
  src/Sylius/Component/Promotion/spec/Model/PromotionActionSpec.php
Labels: Bug

#10835 Improve deprecation message for "Sylius\Bundle\CoreBundle\Application\Kernel"
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
Labels: Enhancement, Maintenance

#10834 Remove usage of deprecated "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()"
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ChannelBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Fixture/AbstractResourceFixture.php
  src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MoneyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
Labels: Enhancement, Maintenance, Symfony 5

#10840 [Psalm] Treat PossiblyUndefined* and PossiblyFalse* as errors
  psalm.xml
  src/Sylius/Bundle/CoreBundle/Installer/Requirement/ExtensionsRequirements.php
  src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderItem.php
Labels: Enhancement, Maintenance

#10842 [Docs] Update core team
  docs/contributing/organization/core-team.rst
Labels: Bug, Documentation

#10841 [Docs] Include link to ShopApi docs to REST API Reference
  docs/api/index.rst
Labels: Documentation, Enhancement

#10844 Clarify BC promise for final controllers
  docs/contributing/code/bc.rst
Labels: Documentation, Enhancement

#10837 Remove unused templating engine from RemoveAvatarAction
  src/Sylius/Bundle/AdminBundle/Action/RemoveAvatarAction.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
Labels: Enhancement, Maintenance

#10845 [Psalm] Fix the build
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ChannelBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/MoneyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductsToProductAssociationsTransformer.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
Labels: Bug

#10843 [Psalm] Treat checks from level 5 as errors
  psalm.xml
  src/Sylius/Bundle/AdminApiBundle/Fixture/Factory/ApiAccessTokenExampleFactory.php
  src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeChoicesCollectionType.php
  src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/UniqueReviewerEmailValidator.php
  src/Sylius/Bundle/MoneyBundle/Form/DataTransformer/SyliusMoneyTransformer.php
  src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php
  src/Sylius/Component/Promotion/Action/PromotionApplicator.php
Labels: Enhancement, Maintenance

#10847 Deprecate Stripe Checkout due to lacking support for SCA
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en.yml
Labels: Admin, Enhancement

#10849 Move ShopApi reference to main menu
  docs/_themes/sylius_rtd_theme/layout.html
  docs/api/index.rst
Labels: Documentation, Enhancement

#10848 Update Webpack docs
  docs/theming/webpack.rst
Labels: Documentation, Enhancement

#10836 Do not use deprecated Symfony events
  psalm.xml
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/ChannelBundle/Context/FakeChannel/FakeChannelPersister.php
  src/Sylius/Bundle/ChannelBundle/spec/Context/FakeChannel/FakeChannelPersisterSpec.php
  src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
  src/Sylius/Bundle/CoreBundle/EventListener/UserCartRecalculationListener.php
  src/Sylius/Bundle/LocaleBundle/Listener/RequestLocaleSetter.php
  src/Sylius/Bundle/LocaleBundle/spec/Listener/RequestLocaleSetterSpec.php
  src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
  src/Sylius/Bundle/ShopBundle/EventListener/SessionCartSubscriber.php
  src/Sylius/Bundle/ShopBundle/EventListener/UserImpersonatedListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
  src/Sylius/Bundle/UiBundle/Menu/Event/MenuBuilderEvent.php
  src/Sylius/Bundle/UserBundle/Event/UserEvent.php
Labels: Enhancement, Symfony 5

#10855 [Docs] Open external links in a new tab
  docs/_themes/sylius_rtd_theme/layout.html
Labels: Documentation, Enhancement, UX

#10857 Change readme banner
  README.md
Labels: Maintenance

#10853 [Behat][Admin][Order] Fix scenarios for displaying promotions on 1.6 after upmerge
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
Labels: Admin, Behat, Bug

#10854 [Behat][Admin][Order] Fix scenarios for displaying promotions on master after upmerge
  features/order/managing_orders/seeing_order_discounts.feature
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
Labels: Admin, Behat, Bug

#10859 [Psalm] Treat MethodSignatureMismatch as errors
  psalm.xml
  src/Sylius/Component/Attribute/Model/Attribute.php
  src/Sylius/Component/Core/Model/Product.php
  src/Sylius/Component/Payment/Model/PaymentMethod.php
  src/Sylius/Component/Product/Model/Product.php
  src/Sylius/Component/Product/Model/ProductAssociationType.php
  src/Sylius/Component/Product/Model/ProductAttribute.php
  src/Sylius/Component/Product/Model/ProductOption.php
  src/Sylius/Component/Product/Model/ProductOptionValue.php
  src/Sylius/Component/Product/Model/ProductVariant.php
  src/Sylius/Component/Shipping/Model/ShippingMethod.php
  src/Sylius/Component/Taxonomy/Model/Taxon.php
Labels: Enhancement, Maintenance

#10865 [Admin][Promotion] Fix the prevention of generating too many coupons
  features/promotion/managing_coupons/being_unable_to_generate_too_many_coupons_with_prefix_and_suffix.feature
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
  src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php
  src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php
  src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php
  src/Sylius/Component/Promotion/spec/Generator/PercentageGenerationPolicySpec.php
Labels: Bug

#10861 Add Bootstrap based theming guide
  docs/theming/bootstrap-theme.rst
  docs/theming/index.rst
  docs/theming/map.rst.inc
Labels: Documentation

#10860 [Channel] channel types
  app/migrations/Version20191119131635.php
  features/channel/managing_channels/adding_channel.feature
  features/channel/managing_channels/editing_channel.feature
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  src/Sylius/Behat/Context/Ui/ThemeContext.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
  src/Sylius/Behat/Page/Admin/Channel/IndexPage.php
  src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Channel/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/pages/admin/channel.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/channel.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Channel/Grid/Field/type.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Common/Macro/icons.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Common/_channel.html.twig
  src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelType.php
  src/Sylius/Bundle/ChannelBundle/Resources/config/doctrine/model/Channel.orm.xml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Channel/Model/Channel.php
  src/Sylius/Component/Channel/Model/ChannelInterface.php
  src/Sylius/Component/Channel/Model/ChannelTypes.php
  tests/Responses/Expected/channel/create_validation_fail_response.json
  tests/Responses/Expected/channel/update_validation_fail_response.json
Labels: Admin, Feature

#10873 [Psalm] Fix the build after Symfony 4.4 update
  psalm.xml
  src/Sylius/Bundle/AdminApiBundle/Command/CreateClientCommand.php
  src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
  src/Sylius/Bundle/CoreBundle/Command/CheckRequirementsCommand.php
  src/Sylius/Bundle/CoreBundle/Command/InformAboutGUSCommand.php
  src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
  src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php
  src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
  src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
  src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
  src/Sylius/Bundle/ShopBundle/EventListener/SessionCartSubscriber.php
  src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php
  src/Sylius/Component/User/Model/User.php
Labels: Critical, Maintenance

#10880 [Promotion] Improve coupon generation validation message
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
Labels: Admin, UX

#10875 Revert changes causing BC break
  config/secrets/dev/.gitignore
  config/secrets/prod/.gitignore
  config/secrets/test/.gitignore
  config/secrets/test_cached/.gitignore
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Attribute/Model/Attribute.php
  src/Sylius/Component/Core/Model/Product.php
  src/Sylius/Component/Payment/Model/PaymentMethod.php
  src/Sylius/Component/Product/Model/Product.php
  src/Sylius/Component/Product/Model/ProductAssociationType.php
  src/Sylius/Component/Product/Model/ProductAttribute.php
  src/Sylius/Component/Product/Model/ProductOption.php
  src/Sylius/Component/Product/Model/ProductOptionValue.php
  src/Sylius/Component/Product/Model/ProductVariant.php
  src/Sylius/Component/Shipping/Model/ShippingMethod.php
  src/Sylius/Component/Taxonomy/Model/Taxon.php
Labels: Bug, Critical, Maintenance

#10890 Fix build - remove redundant validation message part
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
Labels: Bug

#10891 Update release process docs for 1.2
  docs/contributing/organization/release-process.rst
Labels: Documentation

#10889 [Fixtures] Update product names
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
Labels: Enhancement

#10883 Rework Behat testing from classes/ids to attributes for login and registration pages
  src/Sylius/Behat/Context/Setup/UserContext.php
  src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
  src/Sylius/Behat/Element/Shop/Account/RegisterElement.php
  src/Sylius/Behat/Page/Shop/Account/LoginPage.php
  src/Sylius/Behat/Page/Shop/Account/LoginPageInterface.php
  src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPage.php
  src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPageInterface.php
  src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php
  src/Sylius/Behat/Page/Shop/HomePage.php
  src/Sylius/Behat/Page/Shop/HomePageInterface.php
  src/Sylius/Behat/Service/Resolver/CurrentPageResolver.php
  src/Sylius/Behat/Service/Resolver/CurrentPageResolverInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Login/_form.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_security.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Register/_form.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/login.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/register.html.twig
  src/Sylius/Bundle/UiBundle/Form/Type/SecurityLoginType.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/messages.html.twig
  src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TestHtmlAttributeExtension.php
  src/Sylius/Bundle/UserBundle/Form/Type/UserRequestPasswordResetType.php
  src/Sylius/Bundle/UserBundle/Form/Type/UserResetPasswordType.php
  src/Sylius/Component/User/Model/User.php
Labels: Behat, DX
