Repository Sylius/Sylius, pull requests merged in 2020-04, with the labels that each got.

#11291 [API][Homepage] Latest products
  features/homepage/viewing_latest_products.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Client/RequestInterface.php
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
  src/Sylius/Bundle/ApiBundle/DataProvider/LatestProductCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/context_builders.xml
  src/Sylius/Bundle/ApiBundle/Serializer/ContextKeys.php
  src/Sylius/Bundle/ApiBundle/SerializerContextBuilder/ChannelContextBuilder.php
  src/Sylius/Bundle/ApiBundle/SerializerContextBuilder/LocaleContextBuilder.php
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/LatestProductCollectionDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/ChannelContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/LocaleContextBuilderSpec.php
Labels: API, Feature

#11307 [API][Product] Product sorting by name
  features/product/managing_products/sorting_products.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorLocalesContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
  src/Sylius/Bundle/ApiBundle/Filters/TranslationOrderNameFilter.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: API, Feature

#11315 [UI] Fix stylesheets problem on the login page
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
Labels: Admin, Bug, UX

#11317 Fix BC breaks introduced with new template event system
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
Labels: Bug

#11316 [Api][Homepage] menu taxons
  features/homepage/viewing_only_taxons_from_menu_taxon.feature
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Context/Ui/Shop/HomepageContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
  src/Sylius/Bundle/ApiBundle/DataProvider/TaxonFromChannelMenuTaxonCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/context_builders.xml
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/LatestProductCollectionDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/TaxonFromChannelMenuTaxonCollectionDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/ChannelContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/LocaleContextBuilderSpec.php
Labels: API, Feature

#11318 [API][Product] Add subscriber for generating slug automatically
  features/product/managing_products/editing_product_slug.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductSlugEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/ProductSlugEventSubscriberSpec.php
Labels: API, Enhancement

#11322 Fix Psalm docblock marked as a regular one
  src/Sylius/Component/User/Model/User.php
Labels: Bug

#11321 [API] Extract services configs + fixes to product slug event subscriber
  src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicator.php
  src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductSlugEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/applicators.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
Labels: API, DX, Enhancement

#11264 [Minor] Move doctrine filters to doctrine folder in api bundle
  src/Sylius/Bundle/ApiBundle/Doctrine/Filters/ExchangeRateFilter.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: Enhancement

#11323 [Symfony 5] Upgrade to PHPUnit 8 and DependencyInjectionTest 4
  composer.json
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/CountryChoiceTypeTest.php
  src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/ZoneChoiceTypeTest.php
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php
  symfony.lock
Labels: Maintenance

#11029 Try out Behat packages supporting Symfony 5
  composer.json
Labels: Maintenance

#11325 [Minor][API] Add interfaces to applicators
  src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicator.php
  src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicatorInterface.php
  src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicator.php
  src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicatorInterface.php
  src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicator.php
  src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicatorInterface.php
  src/Sylius/Bundle/ApiBundle/Applicator/ProductReviewStateMachineTransitionApplicator.php
  src/Sylius/Bundle/ApiBundle/Applicator/ProductReviewStateMachineTransitionApplicatorInterface.php
  src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicator.php
  src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicatorInterface.php
Labels: Enhancement

#11332 [API] disable input on stateMachine transition endpoints
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
Labels: API, Enhancement

#11334 [ShopBundle] Add missing form_theme declaration
  src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
Labels: Bug, Shop

#11329 Make taxon comparable
  src/Sylius/Component/Core/Model/Taxon.php
  src/Sylius/Component/Core/spec/Model/TaxonSpec.php
Labels: Bug, RFC

#11129 impersonate user in new tab
  features/admin/impersonating_customers.feature
  src/Sylius/Behat/Context/Ui/Admin/ImpersonatingCustomersContext.php
  src/Sylius/Behat/Page/Admin/Administrator/ImpersonateUserPage.php
  src/Sylius/Behat/Page/Admin/Administrator/ImpersonateUserPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/pages/admin.xml
  src/Sylius/Behat/Resources/config/services/pages/admin/impersonate_user.xml
  src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
Labels: Bug

#11018 Fix: Check PropertyPath value for add error to form
  src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
Labels: Bug

#11226 Initializing adjustments before the order item is processed
  src/Sylius/Component/Order/Model/OrderItemUnit.php
Labels: DX

#11319 [API] product association type
  features/product/managing_product_association_types/adding_product_association_type.feature
  features/product/managing_product_association_types/browsing_product_association_types.feature
  features/product/managing_product_association_types/deleting_multiple_product_association_types.feature
  features/product/managing_product_association_types/deleting_product_association_type.feature
  features/product/managing_product_association_types/editing_product_association_type.feature
  features/product/managing_product_association_types/filtering_product_association_types.feature
  features/product/managing_product_association_types/product_association_type_unique_code_validation.feature
  features/product/managing_product_association_types/product_association_type_validation.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductAssociationTypesContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/product/managing_product_association_types.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationTypeTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductAssociationType.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductAssociationTypeTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: API, Feature

#11191 Separated order items subtotal calculation logic from twig extension
  .travis.yml
  composer.json
  etc/travis/suites/packages/before_install.sh
  psalm.xml
  src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculator.php
  src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculatorInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php
  src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php
  src/Sylius/Bundle/ShopBundle/composer.json
  symfony.lock
Labels: DX, Enhancement

#11341 [Maintenance] Upgrade packages dependencies & fix 1.6 build
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Environment, Maintenance

#11342 [Maintenance] Remove memory swap
  .travis.yml
  etc/travis/suites/packages/before_install.sh
Labels: Maintenance

#11337 [API] Association types improvements
  features/product/managing_product_association_types/editing_product_association_type.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductAssociationTypesContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductAssociationTypesContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
Labels: API, Enhancement

#11351 [HOTFIX] Travis memory upgrade & turned off composer scripts
  composer.json
  etc/travis/suites/application/before_install.sh
  etc/travis/suites/application/install.sh
  src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php
  src/Sylius/Bundle/ShopBundle/composer.json
Labels: Maintenance

#11352 [Maintenance][Travis] Upgrade php memory to 6G
  etc/travis/suites/application/before_install.sh
Labels: Maintenance

#11354 [Doc] Describe menu taxon on channel
  docs/_images/channel_menu_taxon.png
  docs/_images/channel_menu_with_menu_taxon.png
  docs/book/configuration/channels.rst
Labels: Documentation

#11356 [API] Registering shop users
  .env
  bin/install-packages
  composer.json
  config/packages/messenger.yaml
  etc/travis/suites/application/before_install.sh
  etc/travis/suites/common/before_install.sh
  features/account/registering.feature
  features/account/registering_validation.feature
  features/account/renewing_account_after_deletion.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
  src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php
  src/Sylius/Behat/Context/Setup/UserContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/account/customer_registration.yml
  src/Sylius/Behat/Resources/config/suites/ui/account/customer_registration.yml
  src/Sylius/Bundle/ApiBundle/Command/RegisterShopUser.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/RegisterShopUserHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/RegisterShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/RegisterShopUser.xml
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueShopUserEmail.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueShopUserEmailValidator.php
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RegisterShopUserHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/UniqueShopUserEmailValidatorSpec.php
  symfony.lock
Labels: API, Feature

#11359 [Docs][Plus] Resolving inventory stocks after shipment
  docs/book/index.rst
  docs/book/products/multi_source_inventory.rst
Labels: Documentation

#11364 fix #11362 : ignore channel locale listener on profiler routes
  src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
Labels: Bug, Enhancement

#11363 Introduce Probot Autolabeler
  .github/autolabeler.yml
Labels: Maintenance

#11357 Add notice about moved templates during upgrade
  UPGRADE-1.7.md
Labels: Bug

#11360 Admin filtering promotions by coupon code
  features/promotion/managing_promotions/filtering_promotions_by_coupon_code.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Page/Admin/Promotion/IndexPage.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml
Labels: Admin, Feature

#11339 [Fixtures] Add possibility to specify menu taxon
  src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
Labels: Enhancement, Feature

#11116 Fixed: Hardcoded locale at Behat product transformer
  src/Sylius/Behat/Context/Transform/ProductContext.php
  src/Sylius/Behat/Resources/config/services/contexts/transform.xml
Labels: Bug

#11379 Use hwi/oauth-bundle:^1.0 in packages
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Core/composer.json
Labels: Maintenance

#11380 Use !default for SCSS variables to allow overriding them
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
  src/Sylius/Bundle/UiBundle/Resources/private/sass/_variables.scss
Labels: Bug

#11369 [Docs] Don't use $HOME in SymfonyCloud deployment cookbook
  docs/cookbook/deployment/symfonycloud.rst
Labels: Documentation

#11387 Remove the doc reference to a promotion action that no longer exists in Core.
  docs/book/orders/promotions.rst
Labels: Documentation

#11396 [Hot-fix] Conflict API Platform 2.5.5 to fix the build
  composer.json
Labels: Bug, Maintenance

#11388 [Shipment] Remove shipment index and add show shipment from order button
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Show/_breadcrumb.html.twig
Labels: Admin, UX

#11390 Bug #9738 Fix nested form collections
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js
  src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
Labels: Bug

#11398 [Docs] Fix typos
  UPGRADE-1.0.md
  UPGRADE-1.3.md
  docs/api/taxons.rst
  docs/book/customers/customer_pools.rst
  docs/book/installation/sylius_plus_installation.rst
  docs/book/organization/backward-compatibility-promise.rst
  docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
  docs/cookbook/emails/mailer.rst
  docs/cookbook/frontend/google-analytics.rst
  docs/cookbook/images/images.rst
Labels: Documentation, Maintenance

#11403 Fix Autolabeler configuration
  .github/autolabeler.yml
Labels: Bug, Maintenance

#11402 [API] Remove custom menu taxon endpoint
  config/packages/security.yaml
  features/homepage/viewing_only_taxons_from_menu_taxon.feature
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
  src/Sylius/Bundle/ApiBundle/Context/TokenBasedUserContext.php
  src/Sylius/Bundle/ApiBundle/Context/UserContextInterface.php
  src/Sylius/Bundle/ApiBundle/DataProvider/TaxonCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
  src/Sylius/Bundle/ApiBundle/spec/Context/TokenBasedUserContextSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/TaxonCollectionDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/TaxonFromChannelMenuTaxonCollectionDataProviderSpec.php
Labels: API, Enhancement

#11406 Automatically add API label
  .github/autolabeler.yml
Labels: Maintenance

#11404 [API] Channel switching
  features/homepage/viewing_only_taxons_from_menu_taxon.feature
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
  src/Sylius/Component/Core/Test/Services/DefaultUnitedStatesChannelFactory.php
  src/Sylius/Component/Core/spec/Test/Services/DefaultUnitedStatesChannelFactorySpec.php
Labels: API, Feature

#11397 [API] Unified admin and shop paths
  UPGRADE-1.8.md
  config/packages/security.yaml
  src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php
  src/Sylius/Behat/Service/ApiSecurityService.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationTypeTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/RegisterShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShipmentUnit.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethodTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml
  src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php
  src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php
  src/Sylius/Bundle/ApiBundle/docs/authorization.md
Labels: API, Maintenance

#11411 [API] Add missing access control
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
Labels: API, Bug
