Repository Sylius/Sylius, pull requests merged in 2020-02, with the labels that each got.

#11082 [Admin] Feed dashboard graph with real data
  src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_chart.html.twig
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/dashboard.xml
  src/Sylius/Component/Core/Dashboard/SalesDataProvider.php
  src/Sylius/Component/Core/Dashboard/SalesDataProviderInterface.php
  src/Sylius/Component/Core/Dashboard/SalesSummary.php
  src/Sylius/Component/Core/Dashboard/SalesSummaryInterface.php
  src/Sylius/Component/Core/spec/Dashboard/SalesSummarySpec.php
  tests/DataFixtures/ORM/resources/year_sales.yml
  tests/Functional/SalesDataProviderTest.php
Labels: Feature

#11066 [Shipment] Ship a shipment with tracking code on the list
  features/shipping/managing_shipments/browsing_shipments.feature
  features/shipping/managing_shipments/managing_of_shipments_status.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Grid/Action/shipWithTrackingCode.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Grid/_ship.html.twig
Labels: Admin, Feature

#11093 [Behats] Rework password, profile update, change password, pages
  src/Sylius/Behat/Page/Shop/Account/ChangePasswordPage.php
  src/Sylius/Behat/Page/Shop/Account/ChangePasswordPageInterface.php
  src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
  src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePageInterface.php
  src/Sylius/Behat/Page/Shop/Account/VerificationPage.php
  src/Sylius/Behat/Page/Shop/Account/VerificationPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig
Labels: Behat, DX

#11097 [Composer] Add conflicts to fix build for Symfony 3.4
  composer.json
Labels: Bug, Maintenance

#11075 Fix testing migrations
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-doctrine-migrations
Labels: Bug

#11094 [Fixtures] Fulfill 60% orders fixtures
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
Labels: DX, Enhancement

#11096 [Behats] Cart summary page - test attributes added
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_coupon.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_items.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_update.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
Labels: Behat, DX

#11105 [Fixtures] Change order for orders
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
Labels: Enhancement

#11101 [Behat] Rework testing product reviews to use test attributes
  features/product/adding_product_reviews/adding_product_review_as_a_customer.feature
  features/product/adding_product_reviews/adding_product_review_as_a_guest.feature
  features/product/adding_product_reviews/review_validation.feature
  src/Sylius/Behat/Context/Ui/Shop/ProductReviewContext.php
  src/Sylius/Behat/Page/Shop/ProductReview/CreatePage.php
  src/Sylius/Behat/Page/Shop/ProductReview/CreatePageInterface.php
  src/Sylius/Behat/Page/Shop/ProductReview/IndexPage.php
  src/Sylius/Behat/Page/Shop/ProductReview/IndexPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_form.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/index.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
Labels: Behat, DX

#11104 [Behat] Rework testing customer orders to use test attributes
  src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
  src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Show/_breadcrumb.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/orderPaymentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/orderShipmentState.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_shipments.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
Labels: Behat, DX

#11103 [Behat] Add attributes to registration page and fix summary page.
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Page/Shop/Account/RegisterPage.php
  src/Sylius/Behat/Page/Shop/Account/RegisterPageInterface.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
Labels: Behat, DX

#11100 [Behats] Rework address book tests
  src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePageInterface.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPageInterface.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddress.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddressForm.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_countryCode.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
Labels: Behat, DX

#11108 Make ShopBillingData a resource
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ShopBillingData.orm.xml
  src/Sylius/Component/Core/Model/ShopBillingData.php
  src/Sylius/Component/Core/Model/ShopBillingDataInterface.php
Labels: DX, Enhancement

#11106 [Dashboard] Sales on dashboard updated
  features/admin/dashboard.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_statistics.html.twig
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Core/Dashboard/DashboardStatisticsProvider.php
  src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
  src/Sylius/Component/Core/spec/Dashboard/DashboardStatisticsProviderSpec.php
Labels: Admin, Enhancement

#11086 [Shipment] Add shipment show page
  features/shipping/managing_shipments/seeing_shipment_details.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/ShowPage.php
  src/Sylius/Behat/Page/Admin/Shipment/ShowPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/pages/admin/shipment.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Grid/_ship.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Show/_breadcrumb.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Show/_header.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/show.html.twig
Labels: Admin, Feature

#11089 [Shipment] Add date when shipment has been shipped
  app/migrations/Version20200202104152.php
  features/order/managing_orders/seeing_shipment_shipping_date.feature
  features/shipping/managing_shipments/shipping_a_shipment_from_shipment_list.feature
  psalm.xml
  src/Sylius/Behat/Context/Hook/CalendarContext.php
  src/Sylius/Behat/Context/Setup/CalendarContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/contexts/hook.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
  src/Sylius/Behat/Resources/config/suites/ui/shipping/managing_shipments.yml
  src/Sylius/Behat/Service/Provider/Calendar.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_shipment.yml
  src/Sylius/Bundle/ShippingBundle/Assigner/ShippingDateAssigner.php
  src/Sylius/Bundle/ShippingBundle/Assigner/ShippingDateAssignerInterface.php
  src/Sylius/Bundle/ShippingBundle/Provider/Calendar.php
  src/Sylius/Bundle/ShippingBundle/Provider/DateTimeProvider.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/doctrine/model/Shipment.orm.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/spec/Assigner/ShippingDateAssignerSpec.php
  src/Sylius/Bundle/ShippingBundle/spec/Provider/CalendarSpec.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Shipping/Model/Shipment.php
  src/Sylius/Component/Shipping/Model/ShipmentInterface.php
Labels: Feature

#11113 [Docs][Plus] Splitting shipments
  docs/book/orders/shipments.rst
Labels: Documentation

#11119 [Docs] Sphinx instalation guide
  docs/contributing/documentation/overview.rst
Labels: Documentation

#11114 Fixed wrongly calculated order-item subtotal
  features/order/managing_orders/seeing_order_with_different_promotions.feature
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
Labels: Admin, Bug

#11124 Template events for shop's cart
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_checkout.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_coupon.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_items.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_popupContent.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_suggestions.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_update.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Block/_widgetButton.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_checkout.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_coupon.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_items.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_suggestions.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_update.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
Labels: DX, Enhancement, Feature

#11126 Template events for layout, footer, header
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_footer.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_footerContent.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_internetExplorerAdditions.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_menuTaxon.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_stylesheets.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_footer.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
Labels: DX, Enhancement, Feature

#11131 Template events minor fix for Shop/Cart
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
Labels: DX, Enhancement

#11128 Currencies API + first approach to API Behat tests
  features/currency/managing_currencies/adding_currency.feature
  features/currency/managing_currencies/browsing_currencies.feature
  features/currency/managing_currencies/currency_unique_code_validation.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php
  src/Sylius/Behat/Context/Api/Admin/NotificationContext.php
  src/Sylius/Behat/Context/Setup/AdminApiSecurityContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/suites/ui/currency/managing_currencies.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
Labels: Behat, DX, Feature

#11130 Add documentation to deploy Sylius to SymfonyCloud
  docs/cookbook/deployment/map.rst.inc
  docs/cookbook/deployment/symfonycloud.rst
  docs/cookbook/index.rst
Labels: Documentation

#11134 Adding documentation of the order processor
  docs/_images/sylius_order_processor.png
  docs/book/orders/orders.rst
Labels: Documentation

#11139 Disable clicked button
  src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
Labels: UX

#11065 user provider fix exception
  src/Sylius/Bundle/CoreBundle/spec/OAuth/UserProviderSpec.php
  src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php
  src/Sylius/Bundle/UserBundle/spec/Provider/EmailProviderSpec.php
  src/Sylius/Bundle/UserBundle/spec/Provider/UsernameOrEmailProviderSpec.php
  src/Sylius/Bundle/UserBundle/spec/Provider/UsernameProviderSpec.php
Labels: Bug

#11137 [Docs] Improve installation steps
  docs/contributing/documentation/overview.rst
Labels: Bug, Documentation

#11142 [Docs] Mention Minimum stability in plus installation
  docs/book/installation/sylius_plus_installation.rst
Labels: Documentation

#11152 Update Mink-related libraries to allow for Symfony 5
  composer.json
  symfony.lock
Labels: Maintenance

#11144 [API] Product options - update vol.1
  features/product/managing_product_options/adding_product_option.feature
  features/product/managing_product_options/editing_product_option.feature
  features/product/managing_product_options/managing_values_of_product_option.feature
  features/product/managing_product_options/product_option_unique_code_validation.feature
  features/product/managing_product_options/product_option_validation.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
  src/Sylius/Behat/Context/Api/Admin/NotificationContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOption.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValue.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValueTranslation.xml
Labels: API, Feature

#11156 Add link to product detail page
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
Labels: UX

#11154 Filter variables passed to legacy Sonata block events
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Block/_legacySonataEvent.html.twig
  src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LegacySonataBlockPass.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Resources/views/Block/_legacySonataEvent.html.twig
  src/Sylius/Bundle/UiBundle/SyliusUiBundle.php
  src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php
Labels: Bug

#11159 [Behat] Fix missing html attributes coverage
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
  src/Sylius/Behat/Page/Shop/Product/IndexPage.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Labels: DX, Maintenance

#11160 Mark new template events implementation as experimental
  src/Sylius/Bundle/UiBundle/Block/BlockEventListener.php
  src/Sylius/Bundle/UiBundle/Command/DebugTemplateEventCommand.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LegacySonataBlockPass.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
Labels: DX, Maintenance

#11157 [API] Product options vol.2
  features/product/managing_product_options/product_option_validation.feature
  features/product/managing_product_options/sorting_product_options_by_position.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
Labels: API, Feature

#11148 [API][Behat] configure tax categories as API resource with tests
  features/taxation/managing_tax_categories/adding_tax_category.feature
  features/taxation/managing_tax_categories/deleting_tax_category.feature
  features/taxation/managing_tax_categories/editing_tax_category.feature
  features/taxation/managing_tax_categories/tax_category_unique_code_validation.feature
  features/taxation/managing_tax_categories/tax_category_validation.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
  src/Sylius/Behat/Context/Api/Admin/NotificationContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoriesContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/taxation/managing_tax_categories.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serializer/TaxCategory.xml
Labels: API
