Repository Sylius/Sylius, pull requests merged in 2020-10, with the labels that each got.

#11896 [Api][Order]Viewing order details
  features/account/customer_account/viewing_orders_history/seeing_province_created_manually_in_order_history.feature
  features/account/customer_account/viewing_orders_history/viewing_order_items.feature
  features/account/customer_account/viewing_orders_history/viewing_order_items_with_proper_names.feature
  features/account/customer_account/viewing_orders_history/viewing_payment_status_for_an_order.feature
  features/account/customer_account/viewing_orders_history/viewing_shipment_status_on_a_placed_order_show_page.feature
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/account/customer.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  src/Sylius/Component/Core/Formatter/StringInflector.php
Labels: API

#11898 Improve 1.8 migrations upgrade instructions
  UPGRADE-1.8.md
  etc/migrations-1.8.sh
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
Labels: Bug, Maintenance

#11891 [Api] orders index for customer's account
  features/account/customer_account/viewing_orders_history/seeing_customer_orders_placed_as_guest.feature
  features/account/customer_account/viewing_orders_history/viewing_only_my_orders.feature
  features/account/customer_account/viewing_orders_history/viewing_orders.feature
  src/Sylius/Behat/Context/Api/Shop/AccountContext.php
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Setup/UserContext.php
  src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/account/customer.yml
  src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
  src/Sylius/Bundle/ApiBundle/DataProvider/OrderCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderCollectionDataProviderSpec.php
  src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
Labels: API

#11901 [1.8] Fix migration generation
  src/Sylius/Bundle/AdminApiBundle/DependencyInjection/SyliusAdminApiExtension.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
Labels: Enhancement, Maintenance

#11904 [API] Separate providers for shop and admin users
  UPGRADE-1.8.md
  config/packages/security.yaml
  src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Service/ApiSecurityService.php
  src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml
  src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php
  src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php
Labels: API, Bug

#11882 Use DQL instead of repository to fetch product attributes
  src/Sylius/Bundle/CoreBundle/Migrations/Version20171003103916.php
Labels: Bug, Environment

#11911 Removing typehint for Symfony 4.4 compatibility
  composer.json
  src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/EmptyPropertyListExtractor.php
Labels: Bug

#11909 [Address] Improve province validation
  features/checkout/addressing_order/choosing_province_for_country.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Context/Transform/ProvinceContext.php
  src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
  src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php
  src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php
Labels: API

#11912 [Admin][API][Shipment] Add filtering shipments by a shipping method
  features/shipping/managing_shipments/filtering_shipments_by_shipping_method.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
  src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: API, Admin, Feature

#11916 End of maintenance date fixed
  docs/book/organization/release-cycle.rst
Labels: Hacktoberfest

#11906 [Api] Add validation for add to cart command
  features/cart/shopping_cart/adding_product_to_cart.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddItemToCart.xml
Labels: API

#11930 Branch update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement

#11934 Update ChangeItemQuantityInCart
  src/Sylius/Bundle/ApiBundle/Command/Cart/ChangeItemQuantityInCart.php
Labels: API, Enhancement

#11929 [API] Add missing experimental annotations
  src/Sylius/Bundle/ApiBundle/Command/CommandAwareDataTransformerInterface.php
  src/Sylius/Bundle/ApiBundle/Command/SubresourceIdAwareInterface.php
Labels: Bug, DX

#11923 Keep it consistent with simple quotes
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
Labels: DX, Enhancement

#11932 [Minor][API] Add missing messenger handler interfaces
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/AddressOrderHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/CompleteOrderHandler.php
Labels: API, Enhancement

#11947 [API] Add removed feature
  features/account/customer_account/editing_customer_profile.feature
Labels: API

#11940 [Maintenance] Adjusting symfony.lock to lowest supported PHP version
  symfony.lock
Labels: Maintenance

#11924 [Api] Change payment method after checkout
  features/checkout/paying_for_order/changing_offline_payment_method_after_order_confirmation.feature
  features/checkout/paying_for_order/changing_payment_method_after_order_confirmation.feature
  features/checkout/preventing_cart_from_being_modified_after_checkout.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutThankYouContext.php
  src/Sylius/Behat/Page/Shop/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/api/checkout/paying_for_order.yml
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChoosePaymentMethodHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php
Labels: API

#11946 Changed behavior of string inflector
  src/Sylius/Component/Core/Formatter/StringInflector.php
  src/Sylius/Component/Core/Test/Tests/StringInflectorTest.php
  src/Sylius/Component/Core/Test/phpunit.xml.dist
Labels: Bug

#11939 [API]Seeing shipping cost of order
  features/cart/shopping_cart/resolving_default_shipping_method_in_cart_summary_for_simple_products.feature
  features/cart/shopping_cart/seeing_shipping_costs_only_when_required.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Setup/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
Labels: Feature

#11938 [API][AddressBook] Adding new address
  features/account/customer_account/address_book/adding_address.feature
  features/account/customer_account/address_book/adding_address_validation.feature
  features/account/customer_account/address_book/address_province_validation.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Shop/AddressContext.php
  src/Sylius/Behat/Context/Transform/AddressContext.php
  src/Sylius/Behat/Context/Transform/CountryContext.php
  src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/account/address_book.yml
  src/Sylius/Bundle/ApiBundle/DataPersister/AddressDataPersister.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/AddressDataPersisterSpec.php
Labels: API

#11953 [Docs] Announce 1.9 release period
  docs/book/organization/release-cycle.rst
Labels: Documentation

#11957 Minor CS fixes detected by ECS
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Bundle/AdminApiBundle/SectionResolver/AdminApiUriBasedSectionResolver.php
  src/Sylius/Bundle/AdminBundle/SectionResolver/AdminUriBasedSectionResolver.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
  src/Sylius/Bundle/CoreBundle/SectionResolver/SectionCannotBeResolvedException.php
  src/Sylius/Bundle/CoreBundle/SectionResolver/UriBasedSectionProvider.php
  src/Sylius/Bundle/ShopBundle/SectionResolver/ShopUriBasedSectionResolver.php
  src/Sylius/Bundle/ShopBundle/spec/SectionResolver/ShopUriBasedSectionResolverSpec.php
  src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonType.php
Labels: Bug, DX

#11958 [Core] Decouple cart collector from shop
  src/Sylius/Bundle/CoreBundle/Resources/views/Collector/cart.html.twig
  src/Sylius/Bundle/CoreBundle/Resources/views/Common/Macro/money.html.twig
Labels: Bug, DX

#11961 [API][AddressBook] Setting default address
  features/account/customer_account/address_book/setting_default_address.feature
  src/Sylius/Behat/Context/Api/Shop/AddressContext.php
  src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
Labels: API

#11963 [API][AddressBook] Minor fixes to api behats
  src/Sylius/Behat/Context/Api/Shop/AddressContext.php
Labels: Behat, Enhancement

#11928 Adding select type to doc
  docs/book/products/attributes.rst
Labels: Documentation

#11972 [Maintenance] Conflict symfony doctrine bridge
  composer.json
Labels: Bug, Maintenance

#11950 [Core][Channel] Add contact phone number to channel
  features/channel/managing_channels/adding_channel.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingChannelsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
  src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201017150005.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_support.html.twig
  src/Sylius/Component/Core/Model/Channel.php
  src/Sylius/Component/Core/Model/ChannelInterface.php
  src/Sylius/Component/Core/spec/Model/ChannelSpec.php
  tests/Controller/ChannelApiTest.php
  tests/Responses/channel/create_validation_fail_response.json
  tests/Responses/channel/update_validation_fail_response.json
Labels: Admin, Feature, Shop

#11871 Patch for Unable to extends ShopBillingData [#11625]
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
Labels: Bug

#11971 [API] Seeing promotions total in cart
  features/promotion/receiving_discount/applying_only_promotions_enabled_for_given_channel.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/promotion/receiving_discount.yml
Labels: API, Feature

#11973 [API] [My Account] Edit addressbook
  features/account/customer_account/address_book/editing_address.feature
  src/Sylius/Behat/Context/Api/Shop/AddressContext.php
  src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
  src/Sylius/Behat/Resources/config/suites/api/account/address_book.yml
Labels: API

#11964 [API][AddressBook] Protect addresses with new firewall
  UPGRADE-1.9.md
  config/packages/security.yaml
  features/account/customer_account/address_book/preventing_not_logged_user_from_operations_on_address_book.feature
  features/account/customer_account/address_book/viewing_addresses.feature
  features/account/customer_account/address_book/viewing_empty_address_book.feature
  src/Sylius/Behat/Context/Api/Shop/AddressContext.php
  src/Sylius/Behat/Context/Transform/AddressContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Bundle/ApiBundle/DataProvider/AddressItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
Labels: API
