Repository Sylius/Sylius, pull requests merged in 2020-01, with the labels that each got.

#10988 Template events system - refactoring & HTML debug comments
  phpstan.neon
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php
  src/Sylius/Bundle/UiBundle/Resources/config/services.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/template_event.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/SyliusUiExtensionTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/TemplateEventTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/html/context.html.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/html/first.html.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/context.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/first.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/second.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/third.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/templateEvents.html.twig
  src/Sylius/Bundle/UiBundle/Twig/MergeRecursiveExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockRegistrySpec.php
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TemplateBlockRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TemplateEventRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Twig/TemplateEventExtensionSpec.php
Labels: DX, Enhancement

#11005 SyliusGridBundle downgrade lock
  composer.json
  psalm.xml
Labels: Bug

#10996 Making functions protected in Product for more flexible extenidng
  src/Sylius/Component/Product/Model/Product.php
Labels: DX, Enhancement

#10991 Template events system - replace topbar with newly introduced events
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_currencySwitcher.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_localeSwitcher.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Block/Layout/_securityWidget.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/UiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Resources/views/Block/_legacySonataEvent.html.twig
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/SyliusUiExtensionTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/TemplateEventTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/contextTemplateBlock/block.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/contextTemplateBlock.txt.twig
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockRegistrySpec.php
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TemplateBlockRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TemplateEventRendererSpec.php
Labels: Enhancement

#10990 Template events system - data collector & profiler
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/debug/template_event.xml
  src/Sylius/Bundle/UiBundle/Resources/views/DataCollector/icon.svg
  src/Sylius/Bundle/UiBundle/Resources/views/DataCollector/templateBlock.html.twig
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/SyliusUiExtensionTest.php
Labels: DX, Feature

#10989 Template events system - CLI command for debugging
  src/Sylius/Bundle/UiBundle/Command/DebugTemplateEventCommand.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/template_event.xml
Labels: DX, Feature

#10938 [Payum][Paypal] Use full price instead of discounted one
  src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
  src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
Labels: Bug

#11014 Use template blocks for our homepage
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_aboutUs.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_banner.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_latestProducts.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_latestProductsCarousel.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_newsletter.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_productsGrid.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/index.html.twig
Labels: DX, Enhancement

#11013 Fix typo in PromotionCouponFactoryInterface
  src/Sylius/Component/Promotion/Factory/PromotionCouponFactoryInterface.php
Labels: Bug

#11008 Change footer url
  src/Sylius/Bundle/AdminBundle/Resources/views/Email/layout.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Email/layout.html.twig
Labels: Bug, UX

#11010 [HomePage][Behat] Rework behats - home page
  src/Sylius/Behat/Page/Shop/HomePage.php
  src/Sylius/Behat/Page/Shop/HomePageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_currencySwitch.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_localeSwitch.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_security.html.twig
Labels: DX, Enhancement

#11011 [Contact][Behat] Rework behats - contact page
  src/Sylius/Behat/Page/ErrorPage.php
  src/Sylius/Behat/Page/Shop/Contact/ContactPage.php
  src/Sylius/Behat/Page/Shop/Contact/ContactPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
Labels: DX, Enhancement

#11009 Rework behats after checkout and thanks page
  src/Sylius/Behat/Page/Shop/Order/ShowPage.php
  src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php
  src/Sylius/Behat/Page/Shop/Order/ThankYouPage.php
  src/Sylius/Behat/Page/Shop/Order/ThankYouPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Order/thankYou.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
Labels: DX, Shop

#11012 [Channel][Taxon][Shop] Menu taxon on channel
  app/migrations/Version20200110132702.php
  features/channel/managing_channels/adding_new_channel_with_menu_taxon.feature
  features/channel/managing_channels/editing_menu_taxon_on_channel.feature
  features/homepage/viewing_only_taxons_from_menu_taxon.feature
  features/taxonomy/managing_taxons/deleting_taxon.feature
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Setup/TaxonomyContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Context/Ui/Admin/RemovingTaxonContext.php
  src/Sylius/Behat/Context/Ui/Shop/HomepageContext.php
  src/Sylius/Behat/Element/Shop/MenuElement.php
  src/Sylius/Behat/Element/Shop/MenuElementInterface.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
  src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Channel/UpdatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/elements/shop.xml
  src/Sylius/Behat/Resources/config/suites/ui/channel/managing_channels.yml
  src/Sylius/Behat/Resources/config/suites/ui/homepage/viewing_products.yml
  src/Sylius/Behat/Resources/config/suites/ui/taxonomy/managing_taxons.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Channel.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/TaxonDeletionListenerSpec.php
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_horizontalMenu.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
  src/Sylius/Component/Channel/spec/Model/ChannelSpec.php
  src/Sylius/Component/Core/Model/Channel.php
  src/Sylius/Component/Core/Model/ChannelInterface.php
  src/Sylius/Component/Core/spec/Model/ChannelSpec.php
  src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
  tests/Controller/ChannelApiTest.php
  tests/Responses/Expected/channel/create_validation_fail_response.json
  tests/Responses/Expected/channel/create_with_extra_response.json
  tests/Responses/Expected/channel/update_validation_fail_response.json
Labels: Feature

#11020 Require LiipImagineBundle ^2.3
  composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
Labels: Maintenance

#11022 Clarify release process regarding PHP versions + update the table
  docs/contributing/organization/release-process.rst
Labels: Maintenance

#11021 Require PHP ^7.3
  .travis.yml
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#10762 [Docs] Added Docs and Instructions for how to store images on AWS-S3
  docs/cookbook/images/images-on-aws-s3.rst
  docs/cookbook/images/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#11019 [Documentation] Add hint about disabling autowire when extending a controller
  docs/customization/controller.rst
Labels: Documentation

#10984 Upgrade to Sonata Block Bundle ^4.0
  composer.json
  config/bundles.php
  config/packages/sonata_core.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/composer.json
  symfony.lock
Labels: Maintenance

#11027 [Maintenance] Update github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bug

#10995 Move Taxation core service from TaxationBundle to CoreBundle
  src/Sylius/Bundle/CoreBundle/Resources/config/services/taxation.xml
  src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
Labels: Bug

#10970 Require Symfony ^4.4
  .travis.yml
  composer.json
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/test/app/AppKernel.php
  src/Sylius/Bundle/AttributeBundle/test/app/config/config.yml
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/SyliusOrderExtensionTest.php
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/OrderBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/ProductBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ProductBundle/test/app/config/config.yml
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/PercentageDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Symfony 5

#11017 [Behat][Checkout] Add html attributes for testing JS functionality in checkout pages
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_choice.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_choice.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_province.html.twig
Labels: Behat, DX, Shop

#11032 Rework behats - summaryOrderPage
  features/checkout/paying_for_order/paying_offline_during_checkout_as_guest.feature
  features/checkout/prices_get_updated_throughout_checkout.feature
  src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
  src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Complete/_form.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Complete/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Complete/_navigation.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_steps.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_promotion.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_addresses.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_shipments.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_table.html.twig
Labels: Behat, DX, Shop

#11040 Happy New Year!
  LICENSE
  docs/conf.py
  docs/contributing/code/license.rst
  src/Sylius/Bundle/AddressingBundle/LICENSE
  src/Sylius/Bundle/AdminApiBundle/LICENSE
  src/Sylius/Bundle/AdminBundle/LICENSE
  src/Sylius/Bundle/AttributeBundle/LICENSE
  src/Sylius/Bundle/ChannelBundle/LICENSE
  src/Sylius/Bundle/CurrencyBundle/LICENSE
  src/Sylius/Bundle/CustomerBundle/LICENSE
  src/Sylius/Bundle/InventoryBundle/LICENSE
  src/Sylius/Bundle/LocaleBundle/LICENSE
  src/Sylius/Bundle/MoneyBundle/LICENSE
  src/Sylius/Bundle/OrderBundle/LICENSE
  src/Sylius/Bundle/PaymentBundle/LICENSE
  src/Sylius/Bundle/PayumBundle/LICENSE
  src/Sylius/Bundle/ProductBundle/LICENSE
  src/Sylius/Bundle/PromotionBundle/LICENSE
  src/Sylius/Bundle/ReviewBundle/LICENSE
  src/Sylius/Bundle/ShippingBundle/LICENSE
  src/Sylius/Bundle/ShopBundle/LICENSE
  src/Sylius/Bundle/TaxationBundle/LICENSE
  src/Sylius/Bundle/TaxonomyBundle/LICENSE
  src/Sylius/Bundle/UiBundle/LICENSE
  src/Sylius/Bundle/UserBundle/LICENSE
  src/Sylius/Component/Addressing/LICENSE
  src/Sylius/Component/Attribute/LICENSE
  src/Sylius/Component/Core/LICENSE
  src/Sylius/Component/Currency/LICENSE
  src/Sylius/Component/Customer/LICENSE
  src/Sylius/Component/Inventory/LICENSE
  src/Sylius/Component/Locale/LICENSE
  src/Sylius/Component/Order/LICENSE
  src/Sylius/Component/Payment/LICENSE
  src/Sylius/Component/Product/LICENSE
  src/Sylius/Component/Promotion/LICENSE
  src/Sylius/Component/Shipping/LICENSE
  src/Sylius/Component/Taxation/LICENSE
  src/Sylius/Component/Taxonomy/LICENSE
  src/Sylius/Component/User/LICENSE
Labels: Maintenance

#11039 [Checkout] Add missing unit test for using deprecated different billing address flag
  tests/Controller/CheckoutAddressingApiTest.php
Labels: API

#11044 [Docs] Fix docs build
  docs/_themes/sylius_rtd_theme/layout.html
Labels: Bug, Documentation

#11043 [Address] Change addresses order
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_addresses.html.twig
Labels: Admin, UX

#11036 Template events reloaded: improved HTML debug, improved code structure, added _event variable to the context
  src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/debug/template_event.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/template_event.xml
  src/Sylius/Bundle/UiBundle/Tests/Functional/TemplateEventTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/first.txt.twig
  src/Sylius/Bundle/UiBundle/spec/Renderer/DelegatingTemplateEventRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/HtmlDebugTemplateBlockRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/HtmlDebugTemplateEventRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TemplateBlockRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TwigTemplateBlockRendererSpec.php
Labels: DX, Enhancement, Feature

#11052 Disabled all buttons from the column after click
  src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/applyTransition.html.twig
Labels: Admin, UX

#11051 [Docs] Update resource documentation
  docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
Labels: Documentation

#11057 Move "php-http/guzzle6-adapter" to "require-dev"
  composer.json
Labels: Enhancement, Maintenance

#11050 Add dashboard chart
  UPGRADE-1.7.md
  package.json
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_chart.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig
  yarn.lock
Labels: Admin, Feature

#11055 Define countries for a channel
  app/migrations/Version20200122082429.php
  docs/book/configuration/channels.rst
  features/channel/managing_channels/adding_channel.feature
  features/checkout/addressing_order/restricting_list_of_countries_available_for_addressing.feature
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
  src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
  src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
  src/Sylius/Bundle/CoreBundle/Form/Extension/AddressTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Core/Model/Channel.php
  src/Sylius/Component/Core/Model/ChannelInterface.php
  tests/Responses/Expected/channel/create_validation_fail_response.json
  tests/Responses/Expected/channel/update_validation_fail_response.json
Labels: Feature

#11058 Revert "Move "php-http/guzzle6-adapter" to "require-dev""
  composer.json
Labels: Bug, Critical

#11054 [Documentation] Sylius Plus features documentation v1
  docs/_images/sylius_plus/admin_return_request_refund.png
  docs/_images/sylius_plus/admin_return_request_repair.png
  docs/_images/sylius_plus/admin_return_request_replacement.png
  docs/_images/sylius_plus/admin_return_request_show.png
  docs/_images/sylius_plus/admin_return_requests.png
  docs/_images/sylius_plus/banner.png
  docs/_images/sylius_plus/business_unit_form.png
  docs/_images/sylius_plus/business_units.png
  docs/_images/sylius_plus/channel_business_unit.png
  docs/_images/sylius_plus/customer_pools_menu.png
  docs/_images/sylius_plus/inventory_source_shipment.png
  docs/_images/sylius_plus/inventory_source_stock_management.png
  docs/_images/sylius_plus/inventory_sources_index.png
  docs/_images/sylius_plus/order_return_request.png
  docs/_images/sylius_plus/product_variant_stock_management.png
  docs/_images/sylius_plus/return_request_form.png
  docs/_themes/sylius_rtd_theme/static/css/sylius-custom.css
  docs/book/configuration/channels.rst
  docs/book/customers/customer_pools.rst
  docs/book/customers/index.rst
  docs/book/customers/map.rst.inc
  docs/book/installation/index.rst
  docs/book/installation/map.rst.inc
  docs/book/installation/sylius_plus_installation.rst
  docs/book/introduction/introduction.rst
  docs/book/orders/index.rst
  docs/book/orders/map.rst.inc
  docs/book/orders/refunds.rst
  docs/book/orders/returns.rst
  docs/book/products/index.rst
  docs/book/products/inventory.rst
  docs/book/products/map.rst.inc
  docs/book/products/multi_source_inventory.rst
Labels: Documentation

#11067 [Fixture] Extend fixtures
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
Labels: DX

#11059 Rendering multiple dependent template events at once + admin-side CRUD events
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Block/_legacySonataEvent.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_header.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_header.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_header.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/index.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/update.html.twig
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Resources/views/Block/_include.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/DataCollector/templateBlock.html.twig
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/SyliusUiExtensionTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/TemplateEventTest.php
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/multipleEvents/genericFirst.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/multipleEvents/genericSecond.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/multipleEvents/specific.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/blocks/txt/first.txt.twig
  src/Sylius/Bundle/UiBundle/Tests/Functional/templates/multipleEvents.txt.twig
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockRegistrySpec.php
  src/Sylius/Bundle/UiBundle/spec/Registry/TemplateBlockSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/DelegatingTemplateEventRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/HtmlDebugTemplateBlockRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/HtmlDebugTemplateEventRendererSpec.php
  src/Sylius/Bundle/UiBundle/spec/Renderer/TwigTemplateBlockRendererSpec.php
Labels: Enhancement, Feature

#11072 Replace "_include.html.twig" template event blocks with a simpler solution
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/Resources/views/Block/_include.html.twig
Labels: DX, Enhancement

#11078 [Checkout] Add note to UPGRADE file about switching billing and shipping addresses
  UPGRADE-1.7.md
Labels: DX, Maintenance

#11079 [Docs] Add organization section to The Book + set up Sphinx redirections
  docs/_exts/sphinxcontrib-redirects/__init__.py
  docs/book/index.rst
  docs/book/installation/upgrading.rst
  docs/book/map.rst.inc
  docs/book/organization/backward-compatibility-promise.rst
  docs/book/organization/index.rst
  docs/book/organization/map.rst.inc
  docs/book/organization/release-cycle.rst
  docs/book/organization/team.rst
  docs/conf.py
  docs/contributing/code/index.rst
  docs/contributing/code/map.rst.inc
  docs/contributing/index.rst
  docs/contributing/map.rst.inc
  docs/contributing/organization/core-team.rst
  docs/contributing/organization/index.rst
  docs/contributing/organization/map.rst.inc
  docs/contributing/organization/vision-and-strategy.rst
  docs/redirection_map
Labels: Documentation, Enhancement

#11080 [Fixtures] Replace Cook Islands with New Zealand
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
Labels: Enhancement

#10870 Allow guest checkout no matter what
  docs/book/orders/checkout.rst
  features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerCheckoutGuestType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml
Labels: Feature

#11071 Template events for admin's layout
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Block/_legacySonataEvent.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_channelLinksWidget.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_logo.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_notificationWidget.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_search.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_security.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_sidebarToggle.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/Block/_support.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_channelLinks.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_flashes.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_notification.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_scripts.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_styles.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_channelLinks.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_flashes.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_logo.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_notification.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_scripts.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_search.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_security.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_support.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Block/_legacySonataEvent.html.twig
Labels: DX, Enhancement, Feature

#11083 [Behat] Fix missing Behat step
  features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
Labels: Bug
