Repository Sylius/Sylius, pull requests merged in 2020-12, with the labels that each got.

#12108 [CI] GitHub Actions setup improvements
  .github/workflows/application.yml
  .github/workflows/packages.yml
Labels: Maintenance

#12115 [CI] Improve DX while debugging failed Behat scenarios
  .github/workflows/application.yml
  behat.yml.dist
  composer.json
  symfony.lock
Labels: Maintenance

#12109 [API] placing order on multiple channels with api
  features/checkout/placing_order_on_multi_channel/placing_an_order_on_multiple_channels_with_different_currency.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
  src/Sylius/Behat/Context/Setup/CartContext.php
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Ui/ChannelContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
  src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
  src/Sylius/Bundle/ApiBundle/Command/Cart/PickupCart.php
  src/Sylius/Bundle/ApiBundle/Command/ChannelCodeAwareInterface.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/ChannelCodeAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php
Labels: API

#12118 Original price is not required in UI
  src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
Labels: UX

#12117 Remove pamil/prophecy-common from require-dev dependencies
  composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php
Labels: Maintenance

#11951 [Api] Be able to change authorization header
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/ApiPlatformIriClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Client/RequestInterface.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
Labels: API, Behat, Enhancement

#12114 [Behat]Javascript tests helper
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Ui/Admin/NotificationContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Service/Helper/JavaScriptTestHelper.php
  src/Sylius/Behat/Service/Helper/JavaScriptTestHelperInterface.php
Labels: Behat, DX

#12107 Api platform payment
  src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php
  src/Sylius/Bundle/ApiBundle/Payment/PaymentConfigurationProviderInterface.php
  src/Sylius/Bundle/ApiBundle/Provider/CompositePaymentConfigurationProvider.php
  src/Sylius/Bundle/ApiBundle/Provider/CompositePaymentConfigurationProviderInterface.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/api_payment_methods.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/payments.xml
  src/Sylius/Bundle/ApiBundle/spec/Provider/CompositePaymentConfigurationProviderSpec.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php
  src/Sylius/Component/Core/Repository/PaymentRepositoryInterface.php
Labels: API

#12123 [Behat] Introduce test helper for more JS tests and increase timeout
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Service/Helper/JavaScriptTestHelperInterface.php
Labels: Behat, DX

#12055 Change route prefixes in security.yaml
  UPGRADE-1.8.md
  config/packages/security.yaml
Labels: API

#12120 Fix doctrine migrations config in UPGRADE-1.8.md
  UPGRADE-1.8.md
Labels: Maintenance

#12060 [PoC] Add parameter to be able to disable prepending doctrine migrations
  src/Sylius/Bundle/AdminApiBundle/DependencyInjection/SyliusAdminApiExtension.php
  src/Sylius/Bundle/AdminApiBundle/Tests/DependencyInjection/SyliusAdminApiExtensionTest.php
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/PrependDoctrineMigrationsTrait.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/CoreBundle/composer.json
Labels: DX, Documentation, Maintenance, RFC

#12125 [Maintenance] Add retry to github action
  .github/workflows/application.yml
Labels: Maintenance

#12127 [Maintenance] Move dependency from require-dev to require in CoreBundle and AdminApiBundle composers
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
Labels: Dependencies, Maintenance

#12078 [Behat] refactor of cart and checkout contexts
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
Labels: Behat, DX

#12140 Temporarily lock on Resource 1.6.*
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
  symfony.lock
Labels: Maintenance

#12149 Improve retrying Behat and reduce failure rate
  .github/workflows/application.yml
  src/Sylius/Behat/Service/Setter/CookieSetter.php
Labels: Bug, Maintenance

#12153 [API] prevent checkout skipping shipping step
  features/checkout/prevent_skipping_checkout_steps.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
Labels: API, Feature

#12154 [API] show possible shipping methods for order
  features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_order_total.feature
  features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_total_weight.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/shipping/applying_shipping_method_rules.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
Labels: API, Feature

#12155 [CI] Add timeouts to GitHub Actions
  .github/workflows/application.yml
  .github/workflows/documentation.yml
  .github/workflows/packages.yml
Labels: Maintenance

#12116 [Adjustment] Add more details to adjustment and make shipment adjustable
  UPGRADE-1.9.md
  features/order/managing_orders/order_details/seeing_order_aggregated_taxes.feature
  features/order/managing_orders/order_details/seeing_order_shipping_taxes.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201208105207.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_order.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Adjustment.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Shipment.orm.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Adjustment.orm.xml
  src/Sylius/Component/Core/Model/Adjustment.php
  src/Sylius/Component/Core/Model/AdjustmentInterface.php
  src/Sylius/Component/Core/Model/Shipment.php
  src/Sylius/Component/Core/Model/ShipmentInterface.php
  src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
  src/Sylius/Component/Core/Taxation/Applicator/OrderItemUnitsTaxesApplicator.php
  src/Sylius/Component/Core/Taxation/Applicator/OrderItemsTaxesApplicator.php
  src/Sylius/Component/Core/Taxation/Applicator/OrderShipmentTaxesApplicator.php
  src/Sylius/Component/Core/spec/Model/AdjustmentSpec.php
  src/Sylius/Component/Core/spec/Model/ShipmentSpec.php
  src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
  src/Sylius/Component/Core/spec/Taxation/Applicator/OrderItemUnitsTaxesApplicatorSpec.php
  src/Sylius/Component/Core/spec/Taxation/Applicator/OrderItemsTaxesApplicatorSpec.php
  src/Sylius/Component/Core/spec/Taxation/Applicator/OrderShipmentTaxesApplicatorSpec.php
  src/Sylius/Component/Order/Factory/AdjustmentFactory.php
  src/Sylius/Component/Order/Factory/AdjustmentFactoryInterface.php
  src/Sylius/Component/Order/Model/Adjustment.php
  src/Sylius/Component/Order/Model/AdjustmentInterface.php
  src/Sylius/Component/Order/spec/Factory/AdjustmentFactorySpec.php
  src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php
  tests/Responses/order/cart_show_response.json
  tests/Responses/order/order_canceled_show_response.json
  tests/Responses/order/order_fulfilled_show_response.json
  tests/Responses/order/order_payed_show_response.json
  tests/Responses/order/order_shipped_show_response.json
  tests/Responses/order/order_shipped_with_tracking_show_response.json
  tests/Responses/order/order_show_response.json
  tests/Responses/order/order_with_coupon_based_promotion_show_response.json
  tests/Responses/order/order_with_promotion_show_response.json
Labels: Admin, DX, Maintenance, RFC

#12156 Update resource_layer.rst
  docs/book/architecture/resource_layer.rst
Labels: Documentation

#12110 Add behat scenario with free order
  features/checkout/adding_product_with_promotion_that_makes_the_order_free.feature
Labels: Documentation, Maintenance

#12161 Add tag no-api to scenario
  features/checkout/prevent_skipping_checkout_steps.feature
Labels: Behat

#12162 [Api][Checkout] Shipping fees on multi-channel
  features/checkout/shipping_order/seeing_shipping_fee_on_multiple_channels.feature
  src/Sylius/Behat/Context/Setup/CartContext.php
Labels: API, Feature

#12163 [CI] Switch from ubuntu-latest to ubuntu-18.04
  .github/workflows/application.yml
  .github/workflows/documentation.yml
  .github/workflows/packages.yml
Labels: Maintenance

#12139 [Api] Locale code on checkout
  features/checkout/picking_up_the_cart_with_the_locale_other_than_the_default.feature
  features/checkout/seeing_order_summary/seeing_order_locale.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
  src/Sylius/Bundle/ApiBundle/Command/Cart/PickupCart.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php
Labels: API, Feature

#12164 update upgrade file after changes with tax adjustment
  UPGRADE-1.9.md
Labels: Documentation, Maintenance

#12165 [Api] Check currency on channel
  features/currency/switching_current_currency.feature
  src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/currency/currencies.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml
Labels: API, Feature

#12082 [Promotions] Replace wrong names
  features/cart/shopping_cart/viewing_cart_summary.feature
  features/product/viewing_products/accessing_product_wich_does_not_exist.feature
  features/promotion/receiving_discount/receiving_discount_from_promotion_with_multiple_actions.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_items_on_price_range.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_products_from_specific_taxon.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_specific_products.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_items_on_price_range.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_products_from_specific_taxon.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_specific_products.feature
  features/promotion/receiving_discount/receiving_stacked_promotions_with_changing_context.feature
Labels: Behat

#12178 [API] Browsing promotions
  features/promotion/managing_promotions/browsing_promotions.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/promotion/managing_promotions.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Promotion.xml
Labels: API

#12169 [CI] Ignore dependabot/* branch pushes, build PRs only
  .github/workflows/application.yml
Labels: Maintenance

#12189 Notify about failed jobs
  .github/workflows/application.yml
  .github/workflows/documentation.yml
  .github/workflows/packages.yml
Labels: Maintenance

#12179 [API] deleting promotions
  features/promotion/managing_promotions/deleting_promotion.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
Labels: API

#12184 [Api][AdminUser][AvatarImage][Channel][Currency][Customer] Refactor api serialization groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AdminUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AvatarImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/ChangePasswordShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/RegisterShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShopBillingData.xml
Labels: API, BC Break, Enhancement, Maintenance

#12196 [CI] Ignore depenabot pushes & allow for triggering manual workflows
  .github/workflows/application.yml
  .github/workflows/documentation.yml
  .github/workflows/packages.yml
Labels: Maintenance

#11794 Fixed deprecated `Intl` component usage
  src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php
  src/Sylius/Component/Locale/Converter/LocaleConverter.php
  src/Sylius/Component/Locale/Model/Locale.php
Labels: DX, Dependencies

#12201 [BUG-FIX] display customer email if user is not logged in
  features/checkout/seeing_purchaser_identifier_in_checkout_page.feature
  src/Sylius/Behat/Context/Setup/ShopSecurityContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_header.html.twig
Labels: Bug, Shop

#12188 [Api][Order] Refactor api serialization groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/AddItemToCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ApplyCouponToCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ChangeItemQuantityInCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/RemoveItemFromCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/AddressOrder.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/CompleteOrder.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml
Labels: API, BC Break, Enhancement

#12214 Add conflict liminas/liminas-code 4.0.0
  composer.json
Labels: Bug, Maintenance

#12213 Upgrade psalm
  composer.json
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/Sylius/Component/Core/Customer/Statistics/CustomerStatistics.php
  src/Sylius/Component/Core/Customer/Statistics/CustomerStatisticsProvider.php
  src/Sylius/Component/Taxation/Model/TaxRate.php
  src/Sylius/Component/User/Model/User.php
Labels: Bug, Maintenance

#12215 Update CONFLICTS.MD
  CONFLICTS.md
Labels: Bug, Maintenance

#12209 Add friendsofphp/proxy-manager-lts for ocramius/proxy-manager
  composer.json
Labels: Bug, Maintenance

#11758 Allow newer "doctrine/doctrine-bundle" to match upcoming ResourceBundle reqs
  composer.json
Labels: Dependencies

#12216 Update release cycle with Sylius 1.9 information
  docs/book/organization/release-cycle.rst
Labels: Documentation
