Repository Sylius/Sylius, pull requests merged in 2021-02, with the labels that each got.

#12295 [Api] Fix CommandAwareInputDataTransformer
  src/Sylius/Bundle/ApiBundle/DataTransformer/CommandAwareInputDataTransformer.php
  src/Sylius/Bundle/ApiBundle/spec/DataTransformer/CommandAwareInputDataTransformerSpec.php
Labels: API

#12291 Fix Taxon collection API name
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
Labels: API

#12288 Add proper date in licenses
  LICENSE
  src/Sylius/Bundle/AddressingBundle/LICENSE
  src/Sylius/Bundle/AdminApiBundle/LICENSE
  src/Sylius/Bundle/AdminBundle/LICENSE
  src/Sylius/Bundle/ApiBundle/LICENSE
  src/Sylius/Bundle/AttributeBundle/LICENSE
  src/Sylius/Bundle/ChannelBundle/LICENSE
  src/Sylius/Bundle/CurrencyBundle/LICENSE
  src/Sylius/Bundle/CustomerBundle/LICENSE
  src/Sylius/Bundle/InventoryBundle/LICENSE
  src/Sylius/Bundle/LocaleBundle/LICENSE
  src/Sylius/Bundle/MoneyBundle/LICENSE
  src/Sylius/Bundle/OrderBundle/LICENSE
  src/Sylius/Bundle/PaymentBundle/LICENSE
  src/Sylius/Bundle/PayumBundle/LICENSE
  src/Sylius/Bundle/ProductBundle/LICENSE
  src/Sylius/Bundle/PromotionBundle/LICENSE
  src/Sylius/Bundle/ReviewBundle/LICENSE
  src/Sylius/Bundle/ShippingBundle/LICENSE
  src/Sylius/Bundle/ShopBundle/LICENSE
  src/Sylius/Bundle/TaxationBundle/LICENSE
  src/Sylius/Bundle/TaxonomyBundle/LICENSE
  src/Sylius/Bundle/UiBundle/LICENSE
  src/Sylius/Bundle/UserBundle/LICENSE
  src/Sylius/Component/Addressing/LICENSE
  src/Sylius/Component/Attribute/LICENSE
  src/Sylius/Component/Core/LICENSE
  src/Sylius/Component/Currency/LICENSE
  src/Sylius/Component/Customer/LICENSE
  src/Sylius/Component/Inventory/LICENSE
  src/Sylius/Component/Locale/LICENSE
  src/Sylius/Component/Order/LICENSE
  src/Sylius/Component/Payment/LICENSE
  src/Sylius/Component/Product/LICENSE
  src/Sylius/Component/Promotion/LICENSE
  src/Sylius/Component/Shipping/LICENSE
  src/Sylius/Component/Taxation/LICENSE
  src/Sylius/Component/Taxonomy/LICENSE
  src/Sylius/Component/User/LICENSE
Labels: API, Admin, Invalid, Shop

#12296 Typo fix
  docs/customization/fixtures.rst
Labels: Documentation

#12290 [Docs] Upgrade sphinx installation guide
  docs/book/contributing/documentation/overview.rst
Labels: Documentation

#12297 Bump up requirements to PHP 7.4
  .github/workflows/application.yml
  .github/workflows/packages.yml
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminApiBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: API, Admin, Maintenance, Shop

#12301 [API] Add missing api and no-api tags
  features/account/customer_account/redirect_when_already_signed_in.feature
  features/account/customer_account/viewing_orders_history/order_is_always_placed_in_a_base_currency_of_a_channel.feature
  features/account/resetting_password_redirect.feature
  features/cart/shopping_cart/changing_display_currency_of_cart.feature
  features/cart/shopping_cart/currency_rounding_edge_case.feature
  features/cart/shopping_cart/having_proper_product_image_displayed_in_cart.feature
  features/checkout/adding_product_with_promotion_that_makes_the_order_free.feature
  features/checkout/addressing_order/having_default_address_preselected.feature
  features/checkout/addressing_order/having_only_possible_country_preselected.feature
  features/checkout/addressing_order/returning_from_addressing_step_to_shop_homepage.feature
  features/checkout/addressing_order/returning_to_addressing_step_with_a_different_shipping_address.feature
  features/checkout/addressing_order/sign_in_during_addressing_step.feature
  features/checkout/having_new_addresses_saved_in_address_book.feature
  features/checkout/having_registration_account_form_prefilled_after_checkout.feature
  features/checkout/paying_for_order/returning_from_payment_step_to_one_of_previous_steps.feature
  features/checkout/placing_an_order_after_moving_back_in_checkout.feature
  features/checkout/placing_order_on_multi_channel/placing_an_order_on_a_single_channel_store.feature
  features/checkout/prices_get_updated_throughout_checkout.feature
  features/checkout/registering_account_after_checkout.feature
  features/checkout/returning_from_order_summary_page_to_one_of_previous_steps.feature
  features/checkout/seeing_purchaser_identifier_in_checkout_page.feature
  features/checkout/skipping_shipping_step_when_order_does_not_require_any_shipping.feature
  features/promotion/applying_promotion_coupon/applying_promotion_coupon.feature
  features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_full_percentage.feature
  features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
  features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_usage_limit.feature
  features/promotion/receiving_discount/receiving_discount_in_order_of_promotions_priority.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_cart.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_items_on_price_range.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_products_from_specific_taxon.feature
  features/promotion/receiving_discount/receiving_fixed_discount_on_specific_products.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_items_on_price_range.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_products_from_specific_taxon.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature
  features/promotion/receiving_discount/receiving_percentage_discount_on_specific_products.feature
  features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
  features/promotion/receiving_discount/receiving_stacked_promotions_with_changing_context.feature
  src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
Labels: API

#12230 [Api][ShippingMethod][ShopBillingData][TaxCategory][Taxon][TaxonTranslation][Zone][ZoneMemberRefactor] serializations groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/AddItemToCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShopBillingData.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxCategory.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/View/CartShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Zone.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ZoneMember.xml
Labels: API, BC Break, Enhancement, Maintenance

#12289 [Docs] Add docs for LoyaltyRule[Api]
  docs/book/index.rst
  docs/book/loyalty/loyalty_rule.rst
  docs/conf.py
Labels: API, Documentation

#12304 Update PHPStan configuration
  .github/workflows/application.yml
  phpstan.neon.dist
Labels: Maintenance

#12303 Remove lock file from cache hashes in CI
  .github/workflows/application.yml
Labels: Maintenance

#12278 [API] move security parameters to bundles
  UPGRADE-1.9.md
  config/packages/security.yaml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
Labels: API, Admin, Maintenance, Shop

#12312 [CI] Ignore changes in "adr" directory
  .github/workflows/application.yml
Labels: Maintenance

#12319 Fix the appearance of the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12323 Change the order of sections in the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12326 Fixes in the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12331 Add note about removing Twig route config in the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12322 update documentation for creating custom model
  docs/_images/make_entity_error.png
  docs/cookbook/entities/custom-model.rst
  docs/customization/menu.rst
Labels: API, Admin, Documentation, Maintenance, Shop

#12332 Reorganize UPGRADE-1.9 file to extract steps for Symfony v5.2
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12328 update documentation for creating custom resource controller
  docs/customization/controller.rst
Labels: DX, Documentation

#12313 Change package type from "project" to "library"
  composer.json
Labels: DX, Enhancement

#12333 [API] remove promotion coupon
  features/promotion/applying_promotion_coupon/removing_promotion_coupon.feature
  src/Sylius/Behat/Context/Api/Shop/PromotionContext.php
  src/Sylius/Behat/Context/Setup/CartContext.php
  src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_coupon.yml
  src/Sylius/Bundle/ApiBundle/Command/Cart/ApplyCouponToCart.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/ApplyCouponToCartHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/ApplyCouponToCart.xml
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/ApplyCouponToCartHandlerSpec.php
Labels: API

#12338 [DOCS] Updating the controller customization
  docs/customization/controller.rst
Labels: Documentation

#12342 Fixes according to composer require commands in the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12347 Remove roadmap links for now
  README.md
Labels: Maintenance

#12351 [Doc] remove generator bundle info (deprecated)
  docs/cookbook/entities/custom-model.rst
Labels: Documentation

#12352 [Frontend] add box with info about api identifiers
  composer.json
  src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig
Labels: API, Documentation, Maintenance

#12364 [Adjustment] Update new migrations not to execute if the changes already exist in db
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php
Labels: DX, Maintenance

#12363 [Maintenance] Run test suite for MySQL 8.0
  .github/workflows/application.yml
Labels: Maintenance

#12311 [ADR] Unified API prefix
  adr/2021_02_05_unified_api_prefix.md
Labels: Documentation, Maintenance

#12365 [Adjustment] Update down methods of new migrations not to execute if the changes already exist in db
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php
Labels: DX, Maintenance

#12367 change swagger API info color to blue
  src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig
Labels: API

#12366 [API] change variants to iri + tests
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
Labels: API

#12373 Move some steps to different section in the UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: DX, Maintenance

#12378 [Bug-fix] Fix default form problem with _token field
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
Labels: Admin, Bug

#12357 Replace zendframework/zend-stdlib with laminas/laminas-stdlib
  composer.json
  etc/psalm/LaminasPriorityQueueStub.php
  etc/psalm/ZendPriorityQueueStub.php
  psalm.xml
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Component/Channel/Context/CompositeChannelContext.php
  src/Sylius/Component/Channel/Context/RequestBased/CompositeRequestResolver.php
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/Context/CompositeCurrencyContext.php
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/Context/CompositeLocaleContext.php
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/Context/CompositeCartContext.php
  src/Sylius/Component/Order/Processor/CompositeOrderProcessor.php
  src/Sylius/Component/Order/composer.json
  symfony.lock
Labels: Maintenance

#12126 Fix incorrect money format being used
  src/Sylius/Bundle/CoreBundle/Resources/views/Collector/cart.html.twig
Labels: Bug

#12360 [API] Password reset
  features/account/resetting_password.feature
  features/account/resetting_password_validation.feature
  src/Sylius/Behat/Context/Api/EmailContext.php
  src/Sylius/Behat/Context/Api/Shop/LoginContext.php
  src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/email.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/account/login.yml
  src/Sylius/Bundle/ApiBundle/Command/LocaleCodeAwareInterface.php
  src/Sylius/Bundle/ApiBundle/Command/RequestResetPasswordToken.php
  src/Sylius/Bundle/ApiBundle/Command/SendResetPasswordEmail.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/RequestResetPasswordTokenHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/SendResetPasswordEmailHandler.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LocaleCodeAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PasswordReset.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/ResetPassword.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/ResetPassword.xml
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendResetPasswordEmailHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/TestKernel.php
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/ApiBundle/phpunit.xml.dist
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/SendResetPasswordEmailHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/Mailer/Emails.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_mailer.yml
  src/Sylius/Bundle/CoreBundle/Resources/views/Email/passwordReset.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Email/passwordReset.html.twig
Labels: API, Shop

#12383 [API] ProductVariant serialization with new key "price"
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantSerializer.php
  src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php
Labels: API

#12329 [Api] Add test app for ApiBundle
  bin/test-package
  phpstan.neon
  psalm.xml
  src/Sylius/Bundle/ApiBundle/.gitignore
  src/Sylius/Bundle/ApiBundle/README.md
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/ApiBundle/fixtures/.gitignore
  src/Sylius/Bundle/ApiBundle/phpunit.xml.dist
  src/Sylius/Bundle/ApiBundle/test/.env
  src/Sylius/Bundle/ApiBundle/test/.env.test
  src/Sylius/Bundle/ApiBundle/test/.gitignore
  src/Sylius/Bundle/ApiBundle/test/bin/console
  src/Sylius/Bundle/ApiBundle/test/config/api_resources/Foo.xml
  src/Sylius/Bundle/ApiBundle/test/config/api_resources/FooSyliusResource.xml
  src/Sylius/Bundle/ApiBundle/test/config/api_resources/Promotion.xml
  src/Sylius/Bundle/ApiBundle/test/config/api_resources/Taxon.xml
  src/Sylius/Bundle/ApiBundle/test/config/bootstrap.php
  src/Sylius/Bundle/ApiBundle/test/config/bundles.php
  src/Sylius/Bundle/ApiBundle/test/config/config.yaml
  src/Sylius/Bundle/ApiBundle/test/config/doctrine/Foo.orm.xml
  src/Sylius/Bundle/ApiBundle/test/config/doctrine/FooSyliusResource.orm.xml
  src/Sylius/Bundle/ApiBundle/test/config/doctrine/Taxon.orm.xml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/administrator.yaml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/channel.yaml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/foo.yaml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/foo_sylius_resource.yaml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/promotions.yaml
  src/Sylius/Bundle/ApiBundle/test/config/fixtures/taxons.yaml
  src/Sylius/Bundle/ApiBundle/test/config/jwt/.gitkeep
  src/Sylius/Bundle/ApiBundle/test/config/jwt/private-test.pem
  src/Sylius/Bundle/ApiBundle/test/config/jwt/public-test.pem
  src/Sylius/Bundle/ApiBundle/test/config/routing.yaml
  src/Sylius/Bundle/ApiBundle/test/config/security.yaml
  src/Sylius/Bundle/ApiBundle/test/config/serialization/Foo.xml
  src/Sylius/Bundle/ApiBundle/test/config/serialization/FooSyliusResource.xml
  src/Sylius/Bundle/ApiBundle/test/config/serialization/Taxon.xml
  src/Sylius/Bundle/ApiBundle/test/config/services.php
  src/Sylius/Bundle/ApiBundle/test/public/index.php
  src/Sylius/Bundle/ApiBundle/test/src/Entity/Foo.php
  src/Sylius/Bundle/ApiBundle/test/src/Entity/FooSyliusResource.php
  src/Sylius/Bundle/ApiBundle/test/src/Entity/Taxon.php
  src/Sylius/Bundle/ApiBundle/test/src/Kernel.php
  src/Sylius/Bundle/ApiBundle/test/src/Tests/FooSyliusResourceTest.php
  src/Sylius/Bundle/ApiBundle/test/src/Tests/FooTest.php
  src/Sylius/Bundle/ApiBundle/test/src/Tests/PromotionTest.php
  src/Sylius/Bundle/ApiBundle/test/src/Tests/SetUpTestsTrait.php
  src/Sylius/Bundle/ApiBundle/test/src/Tests/TaxonTest.php
Labels: API, Maintenance
