Repository Sylius/Sylius, pull requests merged in 2021-10, with the labels that each got.

#13165 [HotFix] Add conflict to doctrine/orm to fix the problem with creating taxons
  CONFLICTS.md
  composer.json
Labels: Maintenance, Bug

#13162 [docs] typofixes
  docs/bdd/how-to-use-transformers.rst
  docs/book/architecture/emails.rst
  docs/book/orders/returns.rst
  docs/book/themes/themes.rst
  docs/customization/model.rst
Labels: Documentation

#13168 [CatalogPromotion] Minor fixes after renaming rule to scope
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: UX

#13169 [Catalog Promotions] Reapply CP after changing its taxons
  features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_on_taxon_once_its_data_changes.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
Labels: Documentation
