Repository Sylius/Sylius, pull requests merged in 2021-01, with the labels that each got.

#12218 Remove laminas/laminas-code conflict
  .github/workflows/application.yml
  CONFLICTS.md
  composer.json
Labels: Dependencies, Maintenance

#12205 [Api][Product] Refactor api serialization groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
Labels: API, BC Break, Enhancement, Maintenance

#12206 [Api][OrderItem][OrderItemUnit] Refactor api serialization groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItemUnit.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItemUnit.xml
Labels: API, BC Break, Enhancement, Maintenance

#12212 [Api][Promotion][Province] Refactor api serialization groups
  UPGRADE-1.8.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Province.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml
Labels: API, BC Break, Enhancement, Maintenance

#12210 [BUG-FIX] [Checkout] Change email addressing step
  features/checkout/ability_to_change_email_during_checkout.feature
  src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_form.html.twig
Labels: Bug, Documentation, Maintenance, Shop, UX

#12231 Add conflict with polyfill-mbstring 1.22.0
  CONFLICTS.md
  composer.json
Labels: Bug, Maintenance

#12234 Backport symfony/polyfill-mbstring:1.22.0 conflict to make the build passing on 1.8
  CONFLICTS.md
  composer.json
Labels: Maintenance

#12233 [Bug] Add Twig verification to check is taxon is enabled
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
Labels: Bug, Shop

#12246 [OrderProcessor] Fix clearing tax adjustments
  features/order/managing_orders/order_details/seeing_order_shipping_taxes.feature
  src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php
  src/Sylius/Component/Core/spec/OrderProcessing/OrderTaxesProcessorSpec.php
Labels: Bug

#12248 Make upgrade of serializations easier to read
  UPGRADE-1.8.md
Labels: Maintenance

#12256 Ability to create non-translatable attributes fixtures + info about non-translatable attributes.
  docs/book/products/attributes.rst
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/ProductAttributeFixture.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
Labels: Documentation

#12260 [Minor][Documentation] Improve attribute documentation
  docs/book/products/attributes.rst
Labels: Documentation

#12255 Auto-merge passing dependabot PRs
  .github/workflows/auto-merge.yml
Labels: Maintenance

#12258 [Docs] Add steps to upgrade jms configuration in UPGRADE-1.9 file
  UPGRADE-1.9.md
Labels: Documentation, Maintenance

#12220 Fix event deprecations
  src/Sylius/Bundle/CoreBundle/EventListener/UserCartRecalculationListener.php
  src/Sylius/Bundle/CoreBundle/spec/EventListener/UserCartRecalculationListenerSpec.php
  src/Sylius/Bundle/UserBundle/Controller/UserController.php
  src/Sylius/Bundle/UserBundle/Event/UserEvent.php
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
  src/Sylius/Bundle/UserBundle/spec/Security/UserLoginSpec.php
Labels: Symfony 5

#12257 [API] change new-api prefix to api
  UPGRADE-1.9.md
  config/packages/fos_rest.yaml
  config/packages/security.yaml
  docs/api/unified_api/authorization.rst
  docs/api/unified_api/introduction.rst
  src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php
  src/Sylius/Behat/Service/ApiSecurityService.php
  src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Country.yml
  src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Province.yml
  src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Zone.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/routing.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Channel.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Customer.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.OrderItem.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Payment.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.PaymentMethod.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Product.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.ProductVariant.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Promotion.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.PromotionCoupon.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Shipment.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.ShippingMethod.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.TaxRate.yml
  src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.Taxon.yml
  src/Sylius/Bundle/ApiBundle/Provider/PathPrefixProvider.php
  src/Sylius/Bundle/ApiBundle/docs/authorization.md
  src/Sylius/Bundle/ApiBundle/spec/Context/TokenValueBasedCartContextSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Provider/PathPrefixProviderSpec.php
  src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.ExchangeRate.yml
  src/Sylius/Bundle/LocaleBundle/Resources/config/serializer/Model.Locale.yml
  src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAssociationType.yml
  src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAttribute.yml
  src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductOption.yml
  src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.ShipmentUnit.yml
  src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.ShippingCategory.yml
  src/Sylius/Bundle/TaxationBundle/Resources/config/serializer/Model.TaxCategory.yml
  tests/Controller/ProductVariantApiTest.php
Labels: API, Documentation, Maintenance

#12270 [Cart] change remove order item from PATCH method to DELETE method
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Bundle/ApiBundle/Command/Cart/RemoveItemFromCart.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/RemoveItemFromCartHandler.php
  src/Sylius/Bundle/ApiBundle/Controller/DeleteOrderItemAction.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/RemoveItemFromCartHandlerSpec.php
Labels: API

#12274 Fix no identifier defined error in ApiPlatform 2.6
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Commands/RegisterShopUser.xml
Labels: API

#12281 Add conflict with api-platform/core:^2.6
  CONFLICTS.md
  composer.json
Labels: Maintenance

#12283 Getting back to customer details in admin panel.
  src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Order/Index/_breadcrumb.html.twig
Labels: Admin

#12272 [Docs] fix for admin RBAC channels
  docs/book/customers/admin_user.rst
Labels: Documentation

#12284 [Psalm] Fix build by casting to string in sprintf methods
  CONFLICTS.md
  composer.json
  docs/api/admin_api/locales.rst
  src/Sylius/Behat/Context/Api/Admin/ManagingLocalesContext.php
  src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
  src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20171003103916.php
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
  src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
  tests/Responses/locale/create_validation_fail_response.json
Labels: Bug, Documentation, Maintenance

#12287 [API] Search products by name within specific taxon
  features/product/viewing_products/searching_products_by_name_within_specific_taxon.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Client/RequestInterface.php
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: API

#12282 [Shipment] Applying discounts and taxes for each shipment
  features/order/managing_orders/order_details/seeing_order_aggregated_discounts.feature
  features/order/managing_orders/order_details/seeing_order_aggregated_taxes.feature
  features/order/managing_orders/order_details/seeing_order_shipping_fees.feature
  features/order/managing_orders/order_details/seeing_order_shipping_taxes.feature
  features/order/managing_orders/order_details/seeing_order_shipping_total.feature
  features/order/managing_orders/order_details/seeing_order_shipping_total_with_applied_promotion_and_taxes.feature
  src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/suites/domain/order/managing_orders.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
  src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
  src/Sylius/Component/Core/Taxation/Applicator/OrderShipmentTaxesApplicator.php
  src/Sylius/Component/Core/spec/Promotion/Action/ShippingPercentageDiscountPromotionActionCommandSpec.php
  src/Sylius/Component/Core/spec/Taxation/Applicator/OrderShipmentTaxesApplicatorSpec.php
Labels: Admin, Documentation, Enhancement, Maintenance
