Repository Sylius/Sylius, pull requests merged in 2022-06, with the labels that each got.

#14038 [Behat] Refactor to use PHP 7.4 syntax
  rector.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Client/ResponseChecker.php
  src/Sylius/Behat/Context/Api/Admin/AjaxContext.php
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/LocaleContext.php
  src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Setup/TaxonomyContext.php
  src/Sylius/Behat/Context/Transform/ProductContext.php
  src/Sylius/Behat/Context/Transform/ShippingCalculatorContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
  src/Sylius/Behat/Context/Ui/BrowserContext.php
  src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
  src/Sylius/Behat/Element/Product/IndexPage/VerticalMenuElement.php
  src/Sylius/Behat/Element/Shop/MenuElement.php
  src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
  src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/ProductVariant/IndexPage.php
  src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
  src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
  src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Zone/CreatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/HomePage.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Service/Helper/JavaScriptTestHelper.php
  src/Sylius/Behat/Service/JQueryHelper.php
  src/Sylius/Behat/Service/Setter/CookieSetter.php
Labels: Enhancement, DX, Behat

#14045 [Rector] Configure PHP version up to 8.0
  rector.php
Labels: Enhancement, DX

#14047 Remove auto commenting feature on 1.10 & 1.11 as well
  .github/workflows/application.yml
Labels: Maintenance, Bug

#13998 Split Sylius packages in Github Actions
  .github/workflows/split-repo.yml
Labels: Maintenance

#14049 Revert "Split Sylius packages in Github Actions"
  .github/workflows/split-repo.yml
Labels: Maintenance, Bug

#14046 Mention 1.10 full support drop in the documentation
  docs/book/organization/release-cycle.rst
Labels: Documentation

#14042 [Symfony 6] Fix command arguments denormalizer return typehint
  src/Sylius/Bundle/ApiBundle/Serializer/CommandArgumentsDenormalizer.php
Labels: API, Bug

#14041 [Addressing] Prevent deleting zones and provinces that are zone members
  features/addressing/managing_countries/managing_provinces_of_country.feature
  features/addressing/managing_zones/deleting_zone.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php
  src/Sylius/Behat/Context/Setup/ZoneContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/api/addressing/managing_countries.yml
  src/Sylius/Behat/Resources/config/suites/ui/addressing/managing_countries.yml
  src/Sylius/Bundle/AddressingBundle/EventListener/ZoneMemberIntegrityListener.php
  src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services/checkers.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php
  src/Sylius/Bundle/ApiBundle/DataPersister/CountryDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ZoneDataPersister.php
  src/Sylius/Bundle/ApiBundle/Exception/ProvinceCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ZoneCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/CountryDataPersisterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/ZoneDataPersisterSpec.php
  src/Sylius/Component/Addressing/Checker/CountryProvincesDeletionChecker.php
  src/Sylius/Component/Addressing/Checker/CountryProvincesDeletionCheckerInterface.php
  src/Sylius/Component/Addressing/Checker/ZoneDeletionChecker.php
  src/Sylius/Component/Addressing/Checker/ZoneDeletionCheckerInterface.php
  src/Sylius/Component/Addressing/spec/Checker/CountryProvincesDeletionCheckerSpec.php
  src/Sylius/Component/Addressing/spec/Checker/ZoneDeletionCheckerSpec.php
Labels: API, Bug

#14062 Fix ProductSlugDocumentationNormalizer
  src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php
Labels: API, Bug

#14059 [Addressing] Enable orphan removal for zone members
  features/addressing/managing_countries/managing_provinces_of_country.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Setup/ZoneContext.php
  src/Sylius/Behat/Context/Transform/ProvinceContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Resources/config/suites/api/addressing/managing_countries.yml
  src/Sylius/Behat/Resources/config/suites/ui/addressing/managing_countries.yml
  src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml
Labels: Bug

#14058 [Admin][Zones] Choosing disabled country as a zone member made possible for admin user
  features/addressing/managing_zones/adding_zone.feature
  src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
  src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneType.php
  src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/CountryChoiceTypeTest.php
  src/Sylius/Bundle/AdminBundle/Resources/views/Zone/_form.html.twig
Labels: UX, Admin

#14067 [Addressing] Fix adding and removing zone members again (with API coverage only)
  features/addressing/managing_zones/editing_zone.feature
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/ZoneDenormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php
Labels: API

#14071 [Addressing] Minor refactor
  src/Sylius/Behat/Context/Transform/ZoneMemberContext.php
  src/Sylius/Bundle/ApiBundle/Serializer/ZoneDenormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php
Labels: API

#14068 [Symfony 6] Fix user component
  src/Sylius/Component/User/Model/User.php
  src/Sylius/Component/User/Model/UserInterface.php
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, API, Bug

#14063 [Symfony 6] Fix Shipping bundle
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ShippingBundle/test/app/config/config.yml
Labels: Maintenance, Bug

#14064 [Symfony 6] Fix Promotion bundle
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PromotionBundle/test/app/config/config.yml
Labels: Maintenance, Bug

#14023 [DOCS] Add docs about deploy platforms
  docs/getting-started-with-sylius/deployment.rst
Labels: Documentation

#14050 [docker][docs]Create Docker Compose configuration file for documentation
  docs/.dockerignore
  docs/Dockerfile
  docs/README.md
  docs/docker-compose.yml
Labels: Documentation, Maintenance, Docker

#14085 [Migrations] Minimum price migration fixed
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220614124639.php
Labels: Bug

#14081 Change deprecated PHPStan config
  phpstan.neon.dist
Labels: Enhancement, DX

#14082 Revert ReflectionExtractor hot-fix
  phpstan.neon.dist
  psalm.xml
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/ReflectionExtractorHotfixPass.php
  src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/ReflectionExtractor.php
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
Labels: Enhancement, DX, API

#14095 [Fixtures] Add a fixture listener for removing images
  src/Sylius/Bundle/CoreBundle/Fixture/Listener/ImagesPurgerListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/ImagesPurgerListenerSpec.php
Labels: Enhancement, DX

#13573 [UI] Disable session storage for autocomplete dropdowns
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
Labels: UX, Bug

#14091 [Docs] Upgrade Plus installation guide
  docs/book/installation/sylius_plus_installation.rst
Labels: Documentation

#14074 [Symfony 6] Fix user bundle
  .github/workflows/packages.yml
  src/Sylius/Bundle/UserBundle/.gitignore
  src/Sylius/Bundle/UserBundle/Authentication/AuthenticationSuccessHandler.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Compiler/RemoveUserPasswordEncoderPass.php
  src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php
  src/Sylius/Bundle/UserBundle/SyliusUserBundle.php
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/Compiler/RemoveUserPasswordEncoderPassTest.php
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/config.yml
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationSuccessHandlerSpec.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php
  src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordHasherSpec.php
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Bug

#14106 [Maintenance] Composer allow plugins finally sorted out + removal of symfony thanks
  composer.json
Labels: Maintenance, Dependencies

#14090 Fix calculate order item subtotal
  src/Sylius/Component/Core/Model/OrderItem.php
  src/Sylius/Component/Core/spec/Model/OrderItemSpec.php
Labels: Bug

#14102 [Fixtures] Fix removing images before suite
  src/Sylius/Bundle/CoreBundle/Fixture/Listener/ImagesPurgerListener.php
  src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/ImagesPurgerListenerSpec.php
Labels: Bug

#14101 [Template][Events] Part of new UI bundle events for security and grid
  src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Body/_navigation.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Body/_pagination.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Body/_table.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/_content.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_content.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/Form/_credentials.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/Form/_submit.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/_error.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/_login.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Security/_logo.html.twig
Labels: DX, Admin, Shop

#14108 [Templates] Move grid events to UI bundle
  src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
  src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/Resources/config/app/events.yaml
Labels: UX, Admin

#14113 [Fix][Maintenance] Cart item data mapper adjusted to be Sf6 compatible
  src/Sylius/Bundle/OrderBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/OrderBundle/test/app/config/config.yml
Labels: Maintenance, Bug

#14112 [Documentation][Plus] Add missing step for updating security file during installation
  docs/book/installation/sylius_plus_installation.rst
  docs/book/installation/sylius_plus_upgrading.rst
Labels: Documentation
