Repository Sylius/Sylius, pull requests merged in 2022-10, with the labels that each got.

#14392 Fix build after API Platform 2.7.1 release
  composer-require-checker.json
  src/Sylius/Bundle/ApiBundle/Serializer/ShippingMethodNormalizer.php
Labels: Maintenance, API, Bug

#14243 Revert temporary build fix
  .github/workflows/application.yml
Labels: Maintenance

#14390 [GitHub Actions] Add builds for API Platform ~2.6.0
  .github/workflows/application.yml
Labels: Maintenance, API

#14397 [Docs] Fix 1.12 release dates
  docs/book/organization/release-cycle.rst
Labels: Documentation, Bug

#14197 [Docs] Describe Sylius architectural drivers
  docs/book/architecture/architecture.rst
  docs/book/architecture/drivers.rst
  docs/book/architecture/index.rst
  docs/book/architecture/map.rst.inc
Labels: Documentation

#14337 [Maintenance] Mention Gaufrette filesystem adapter in the upgrade file
  UPGRADE-1.12.md
Labels: Maintenance

#14144 [Documentation] Fix incorrect translation domain in implementation
  docs/book/plugins/guide/implementation.rst
Labels: Documentation

#14376 Fix no-js Behat scenarios for Symfony 6
  .github/workflows/docker.yml
  .github/workflows/documentation.yml
  .github/workflows/refactor.yml
  composer-require-checker.json
  composer.json
  config/services_test.yaml
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Context/Setup/PromotionContext.php
  src/Sylius/Behat/Context/Transform/LexicalContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Service/Converter/IriConverter.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/catalog_promotion.yaml
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Symfony/Routing/CachedRouteNameResolver.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/Symfony6PrivateServicesPass.php
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
  src/Sylius/Bundle/OrderBundle/Form/DataMapper/OrderItemQuantityDataMapper.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
  src/Sylius/Bundle/UserBundle/Controller/UserController.php
  tests/Api/Shop/OrdersTest.php
  tests/Api/Shop/PaymentMethodsTest.php
  tests/Api/Shop/ShippingMethodsTest.php
  tests/Api/Utils/OrderPlacerTrait.php
  tests/Controller/SessionAwareAjaxTest.php
Labels: Maintenance, Admin, Shop, API, Bug

#14398 Allow ramsey/uuid ^4.0 to avoid PHP 8.1 warning
  composer.json
Labels: Enhancement, DX

#14410 [Documentation] Remove the tip about ShopApiPlugin from the architecture page
  docs/book/architecture/architecture.rst
Labels: Documentation

#14296 [Core] Create CustomerProvider
  UPGRADE-API-1.12.md
  src/Sylius/Bundle/CoreBundle/Provider/CustomerProvider.php
  src/Sylius/Bundle/CoreBundle/Provider/CustomerProviderInterface.php
  src/Sylius/Bundle/CoreBundle/Resolver/CustomerResolver.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/spec/Provider/CustomerProviderSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Resolver/CustomerResolverSpec.php
  src/Sylius/Component/Core/Exception/CustomerNotFoundException.php
Labels: Maintenance

#14414 [Github Actions] Make timeout for non-JS build longer
  .github/workflows/application.yml
Labels: Maintenance, Bug

#14420 [Hot-fix] Conflict with newest AP that changes a Customer->User response
  CONFLICTS.md
  composer.json
Labels: Maintenance, Bug

#14406 [API][Behat] Add note about behat client changes
  UPGRADE-API-1.12.md
Labels: Maintenance

#14246 [DOCS] Add note about min node version
  docs/book/installation/requirements.rst
Labels: Documentation

#14156 [DOCS] Cookbook of how to modify placed order
  docs/_images/cookbook/administration/editing-orders/checkout.png
  docs/_images/cookbook/administration/editing-orders/completed-checkout.png
  docs/_images/cookbook/administration/editing-orders/customer.png
  docs/_images/cookbook/administration/editing-orders/new-order.png
  docs/_images/cookbook/administration/editing-orders/old-order.png
  docs/_images/cookbook/administration/editing-orders/order.png
  docs/_images/cookbook/administration/editing-orders/orders-page.png
  docs/_images/cookbook/administration/editing-orders/shop.png
  docs/cookbook/administration/editing-orders.rst
  docs/cookbook/administration/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#14427 tax rates filter feature
  features/taxation/managing_tax_rates/tax_rates_filtration/filtering_tax_rates_by_end_date.feature
  features/taxation/managing_tax_rates/tax_rates_filtration/filtering_tax_rates_by_start_date.feature
  src/Sylius/Behat/Context/Setup/TaxationContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
  src/Sylius/Behat/Element/Admin/TaxRate/FilterElement.php
  src/Sylius/Behat/Element/Admin/TaxRate/FilterElementInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/services/elements/admin.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/tax_rate.yml
Labels: Feature, Admin

#14430 [DX] Fix versions for triggered deprecations
  src/Sylius/Bundle/AdminBundle/Action/Account/RenderResetPasswordPageAction.php
  src/Sylius/Bundle/AdminBundle/Action/Account/RequestPasswordResetAction.php
  src/Sylius/Bundle/AdminBundle/Action/Account/ResetPasswordAction.php
  src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/Action/ResendShipmentConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/AdminBundle/Storage/FilterStorage.php
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
  src/Sylius/Bundle/CoreBundle/Storage/CartSessionStorage.php
  src/Sylius/Bundle/ShopBundle/EventListener/CustomerEmailUpdaterListener.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
Labels: DX, Maintenance, Admin, Shop

#14426 [Docs][CatalogPromotions][Messenger] Failure transports
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#14421 [DOCS] Add info about supervisors
  docs/book/installation/installation.rst
Labels: Documentation

#14433 Fix - move RedirectPathExtension from Admin bundle to Ui bundle
  src/Sylius/Bundle/AdminBundle/Controller/RedirectHandler.php
  src/Sylius/Bundle/AdminBundle/EventListener/AdminFilterSubscriber.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/spec/Controller/RedirectHandlerSpec.php
  src/Sylius/Bundle/AdminBundle/spec/EventListener/AdminFilterSubscriberSpec.php
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Storage/FilterStorage.php
  src/Sylius/Bundle/UiBundle/Storage/FilterStorageInterface.php
  src/Sylius/Bundle/UiBundle/Twig/RedirectPathExtension.php
  src/Sylius/Bundle/UiBundle/spec/Storage/FilterStorageSpec.php
  tests/Twig/RedirectPathExtensionTest.php
Labels: Admin, Bug

#14247 [DOCS] Add info about mailer in installation doc
  docs/book/installation/installation.rst
Labels: Documentation

#14362 Using the new template namespace syntax in the doc
  docs/customization/factory.rst
Labels: Documentation

#14442 [Hot-fix] Conflict with the newest AP that changes a Customer->User response
  CONFLICTS.md
  composer.json
Labels: Maintenance, Dependencies, Bug

#14384 [API] Use tokenValue instead of id
  src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php
Labels: API

#14445 [Hot-fix] Conflict with the SymfonyMockerContainer 1.0.6 due to incompatible version with Symfony 4.x
  CONFLICTS.md
  composer.json
Labels: Maintenance, Dependencies, Bug

#14444 Remove SymfonyMockerContainer fork
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
Labels: Maintenance

#14379 [Admin] Cart promotions translations for labels
  features/promotion/managing_promotions/adding_promotion_in_different_languages.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
  src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_promotions.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/Show/_translations.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_form.html.twig
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionTranslation.xml
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220926113252.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionTranslationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionType.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/PromotionTranslation.orm.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
  src/Sylius/Component/Promotion/Model/Promotion.php
  src/Sylius/Component/Promotion/Model/PromotionInterface.php
  src/Sylius/Component/Promotion/Model/PromotionTranslation.php
  src/Sylius/Component/Promotion/Model/PromotionTranslationInterface.php
  src/Sylius/Component/Promotion/spec/Model/PromotionSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionTranslationSpec.php
  tests/Api/Admin/PromotionTest.php
  tests/Api/Responses/Expected/admin/post_promotion_response.json
Labels: Feature, Admin, API

#14443 [API][Behat] Add note about behat request changes
  UPGRADE-API-1.12.md
Labels: Maintenance

#14188 [DOCS] Disabling guest api checkout
  docs/cookbook/shop/disabling-guest-checkout.rst
Labels: Documentation, Maintenance

#14459 [Hot-fix] Do not fail scenario after 422 response page
  src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
  src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
Labels: Bug

#14458 Fix packages branch-aliases
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API, Bug

#14464 Change all package versions to 1.12
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Product/composer.json
Labels: Maintenance, Admin, Shop, API

#14462 [CI] Tests for Symfony ~6.0.0 and static checks for APIP ~2.6.0
  .github/workflows/application.yml
Labels: Maintenance

#14461 Update documentation about migrating to Webpack
  docs/book/frontend/overview.rst
  docs/cookbook/frontend/map.rst.inc
  docs/cookbook/frontend/migrating-to-webpack-1-11-or-earlier.rst
  docs/cookbook/frontend/migrating-to-webpack-1-12-or-later.rst
  docs/cookbook/index.rst
Labels: Documentation, Frontend

#14053 Upgrade phpstan to level 2
  composer.json
  phpstan.neon.dist
  src/Sylius/Behat/Client/ResponseChecker.php
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/CustomerContext.php
  src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
  src/Sylius/Bundle/AddressingBundle/Controller/ProvinceController.php
  src/Sylius/Bundle/AddressingBundle/EventListener/ZoneMemberIntegrityListener.php
  src/Sylius/Bundle/AdminBundle/EventListener/AdminFilterSubscriber.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Symfony/Routing/CachedRouteNameResolver.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ResendVerificationEmailHandler.php
  src/Sylius/Bundle/ApiBundle/Context/TokenValueBasedCartContext.php
  src/Sylius/Bundle/ApiBundle/DataProvider/CustomerItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenPaymentMethodEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderPaymentMethodEligibilityValidator.php
  src/Sylius/Bundle/ChannelBundle/Context/FakeChannel/FakeChannelContext.php
  src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
  src/Sylius/Bundle/CoreBundle/Command/JwtConfigurationCommand.php
  src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
  src/Sylius/Bundle/CoreBundle/EventListener/CanonicalizerListener.php
  src/Sylius/Bundle/CoreBundle/EventListener/CircularDependencyBreakingErrorListener.php
  src/Sylius/Bundle/CoreBundle/EventListener/DefaultUsernameORMListener.php
  src/Sylius/Bundle/CoreBundle/EventListener/XFrameOptionsSubscriber.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
  src/Sylius/Bundle/LocaleBundle/Context/RequestBasedLocaleContext.php
  src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php
  src/Sylius/Bundle/PromotionBundle/Tests/Command/GenerateCouponsCommandTest.php
  src/Sylius/Bundle/ShopBundle/EventListener/CustomerEmailUpdaterListener.php
  src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
  src/Sylius/Bundle/ShopBundle/EventListener/SessionCartSubscriber.php
  src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UserBundle/Authentication/AuthenticationSuccessHandler.php
  src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php
  src/Sylius/Bundle/UserBundle/EventListener/UpdateUserEncoderListener.php
  src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php
  src/Sylius/Component/Channel/Context/CachedPerRequestChannelContext.php
  src/Sylius/Component/Channel/Context/RequestBased/ChannelContext.php
  src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
  symfony.lock
Labels: Enhancement, Admin, Shop, API

#14454 [Behat] Move scenario from Plus
  features/cart/shopping_cart/adding_product_to_cart.feature
Labels: Behat

#14468 Lower hashing alogirthm memory cost in test
  config/packages/test/security.yaml
Labels: Maintenance, Bug

#14402 [Api] fix order normalization groups
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
Labels: API

#14473 Fixes in Order serialization after changes on 1.11
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
Labels: API, Bug

#14476 Delay 1.12 release for a few days
  docs/book/organization/release-cycle.rst
Labels: Documentation, Maintenance

#14472 Bring back security.authentication_manager alias if needed
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/Symfony5AuthenticationManagerPass.php
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
Labels: Bug

#14477 [Docs] Add warning about restricting Symfony version before Sylius installation
  docs/book/installation/installation.rst
  docs/getting-started-with-sylius/installation.rst
Labels: Documentation

#14479 [Maintenance] Allow APIP 2.7.2
  CONFLICTS.md
  composer.json
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
Labels: Maintenance, API, Dependencies

#14490 [Maintenance] Kernel cleanup
  src/Kernel.php
Labels: Maintenance

#14496 [README] Switch Sylius naming from platform to framework
  README.md
Labels: Maintenance

#14498 Allow stable Resource (1.10), Grid (1.12) and Fixtures (1.8)
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance

#14499 Separate pipeline for non-JS tests on unstable Symfony version
  .github/workflows/application.yml
Labels: Maintenance

#14400 [Maintenance] `extra.symfony.require` configuration introduced
  composer.json
Labels: Documentation, Maintenance

#14501 [Maintenance] Removal of direct unneeded dependency on proxy manager LTS
  CONFLICTS.md
  composer.json
Labels: Maintenance

#14435 Include 1.13 branch in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Maintenance

#14502 [Maintenance] Improve deprecation notice
  src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
Labels: Enhancement, DX
