Repository Sylius/Sylius, pull requests merged in 2022-02, with the labels that each got.

#13556 [Behat] Scenario for creating an exclusive catalog promotion
  features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
  src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotion.xml
  tests/Api/Admin/CatalogPromotionsTest.php
  tests/Api/DataFixtures/ORM/catalog_promotion.yaml
  tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotion_response.json
  tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotions_response.json
  tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_response.json
  tests/Api/Responses/Expected/admin/catalog_promotion/put_catalog_promotion_response.json
Labels: Enhancement, Behat, API

#13580 Bump Psalm version to 4.19 (php 8.1 support)
  composer.json
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AvatarImageRepository.php
  src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
  src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductTaxonToTaxonTransformer.php
  src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductVariantsToCodesTransformer.php
  src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductsToCodesTransformer.php
  src/Sylius/Bundle/CoreBundle/Form/DataTransformer/TaxonsToCodesTransformer.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php
  src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductsToProductAssociationsTransformer.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponToCodeType.php
  src/Sylius/Bundle/UserBundle/Form/UserVerifiedAtToBooleanTransformer.php
  src/Sylius/Bundle/UserBundle/Provider/EmailProvider.php
  src/Sylius/Bundle/UserBundle/Provider/UsernameOrEmailProvider.php
  src/Sylius/Bundle/UserBundle/Provider/UsernameProvider.php
  src/Sylius/Component/Core/Model/Channel.php
  src/Sylius/Component/Core/Model/OrderItem.php
  src/Sylius/Component/Core/Model/PaymentMethod.php
  src/Sylius/Component/Core/Model/ProductVariant.php
  src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
  src/Sylius/Component/Core/Resolver/ChannelBasedPaymentMethodsResolver.php
  src/Sylius/Component/Core/Resolver/DefaultPaymentMethodResolver.php
  src/Sylius/Component/Order/Model/OrderItem.php
  src/Sylius/Component/Payment/Resolver/CompositeMethodsResolver.php
  src/Sylius/Component/Payment/Resolver/PaymentMethodsResolver.php
  src/Sylius/Component/Product/Model/ProductOption.php
  src/Sylius/Component/Promotion/Model/Promotion.php
  src/Sylius/Component/Shipping/Resolver/CompositeMethodsResolver.php
  src/Sylius/Component/Taxonomy/Model/Taxon.php
  src/Sylius/Component/User/Model/User.php
Labels: Maintenance

#13577 [Catalog Promotion] Removal of unused function
  src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/CatalogPromotionRepository.php
  src/Sylius/Component/Promotion/Repository/CatalogPromotionRepositoryInterface.php
Labels: Enhancement, DX

#13578 [Catalog Promotion] add update variant event to messenger routing
  src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
Labels: Enhancement

#13581 [Catalog Promotion] Refactor - rename AllCatalogPromotionsProcessor
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionCreatedListener.php
  src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionEndedListener.php
  src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionFailedListener.php
  src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionUpdatedListener.php
  src/Sylius/Bundle/CoreBundle/Processor/AllProductVariantsCatalogPromotionsProcessor.php
  src/Sylius/Bundle/CoreBundle/Processor/AllProductVariantsCatalogPromotionsProcessorInterface.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/processors.xml
  src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionCreatedListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionEndedListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionFailedListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionUpdatedListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Processor/AllProductVariantsCatalogPromotionsProcessorSpec.php
Labels: Enhancement

#13585 [Catalog Promotion] [Docs] docs updated
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#13576 [Catalog Promotion] Select more data during processing to avoid inefficient db calls
  src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php
  src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/CatalogPromotionRepository.php
Labels: Feature, Performance

#13584 Update catalog promotion instantly if date is set on future
  src/Sylius/Bundle/CoreBundle/Announcer/CatalogPromotionAnnouncer.php
  src/Sylius/Bundle/CoreBundle/spec/Announcer/CatalogPromotionAnnouncerSpec.php
Labels: Bug

#13561 [Docs] Mention autoconfiguration case when extending the form
  docs/customization/form.rst
Labels: Documentation, Bug

#13579 [Catalog Promotion] Move catalog promotion processing after the fixture execution
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/promotion.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php
Labels: Feature, Performance

#13563 [API][UI][Behat][Refactor] OriginalUnitPrice property on the OrderItem entity
  UPGRADE-1.11.md
  UPGRADE-API-1.11.md
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/OrderItemNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/OrderItemNormalizerSpec.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20211129213836.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220127150747.php
  src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItem.orm.xml
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
  src/Sylius/Bundle/ShopBundle/Twig/OrderItemOriginalPriceToDisplayExtension.php
  src/Sylius/Bundle/ShopBundle/spec/Twig/OrderItemOriginalPriceToDisplayExtensionSpec.php
  src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php
  src/Sylius/Component/Core/spec/OrderProcessing/OrderPricesRecalculatorSpec.php
  src/Sylius/Component/Order/Model/OrderItem.php
  src/Sylius/Component/Order/Model/OrderItemInterface.php
  src/Sylius/Component/Order/spec/Model/OrderItemSpec.php
  tests/Api/Responses/Expected/admin/get_order_response.json
  tests/Api/Responses/Expected/shop/add_item_response.json
  tests/Api/Responses/Expected/shop/get_order_items_response.json
  tests/Api/Responses/Expected/shop/get_order_response.json
  tests/Api/Responses/Expected/shop/updated_payment_method_on_order_response.json
Labels: Maintenance, Shop, API

#13591 [Catalog Promotion][Docs] update CP scopes docs
  docs/cookbook/promotions/custom-catalog-promotion-scope.rst
Labels: Documentation

#13593 [Catalog Promotions] State processing after fixtures load
  src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php
Labels: Bug

#13587 [CatalogPromotion] batch configuration size made a part of config
  src/Sylius/Bundle/CoreBundle/CommandDispatcher/ApplyCatalogPromotionsOnVariantsCommandDispatcherInterface.php
  src/Sylius/Bundle/CoreBundle/CommandDispatcher/BatchedApplyCatalogPromotionsOnVariantsCommandDispatcher.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/CoreBundle/spec/CommandDispatcher/BatchedApplyCatalogPromotionsOnVariantsCommandDispatcherSpec.php
Labels: Enhancement

#13592 [Migration] add migration to messenger if transport is configured to doctrine
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220203115813.php
Labels: Bug

#13595 [Docs] Configuring catalog promotions batch sizes explained
  docs/cookbook/index.rst
  docs/cookbook/promotions/catalog-promotion-performance.rst
  docs/cookbook/promotions/map.rst.inc
Labels: Documentation

#13596 [Cookbook] Minor fixes in custom catalog promotion scope
  docs/cookbook/promotions/custom-catalog-promotion-scope.rst
Labels: Documentation

#13594 [Catalog Promotion][Test] Assert proper batch size configuration
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
Labels: Enhancement, DX

#13597 Core Configuration style and tests improvements
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingErrorListenerPassTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingExceptionListenerPassTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
Labels: Enhancement

#13542 Specify explicit priorities for all form type extensions
  UPGRADE-1.11.md
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml
Labels: DX, Maintenance, Admin

#13588 Use semantic ui view instead of deprecated semantic_ui_translated
  UPGRADE-1.11.md
  src/Sylius/Bundle/UiBundle/Resources/views/Macro/pagination.html.twig
Labels: Maintenance, Bug

#13431 FIX: Avoid passing empty needle to strpos()
  src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php
  src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php
Labels: Documentation, Maintenance, Bug

#13624 [CatalogPromotions] Refactor processing catalog promotions states to use commands
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Command/UpdateCatalogPromotionState.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/UpdateCatalogPromotionStateHandler.php
  src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php
  src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionStateChangedListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/CommandHandler/UpdateCatalogPromotionStateHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionStateChangedListenerSpec.php
Labels: Enhancement, DX

#13630 [Docs][Catalog Promotion] Warning added to docs
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#13611 Optimize variant autocomplete selector
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_variant.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php
  src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php
  tests/Controller/AdminProductVariantAjaxTest.php
  tests/DataFixtures/ORM/resources/product_variants.yml
  tests/Responses/ajax/product_variant/index_response.json
Labels: Admin

#13620 Changes in Catalog Promotions validation
  adr/2022_02_09_catalog_promotions_validation.md
  docs/cookbook/promotions/custom-catalog-promotion-action.rst
  docs/cookbook/promotions/custom-catalog-promotion-scope.rst
  features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/FixedDiscountActionValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForProductsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForTaxonsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForVariantsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/PercentageDiscountActionValidator.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/FixedDiscountActionValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForProductsScopeValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForTaxonsScopeValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForVariantsScopeValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/PercentageDiscountActionValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Checker/ProductVariantForCatalogPromotionEligibility.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionAction/FixedDiscountActionValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForProductsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForTaxonsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForVariantsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionScope/ForProductsScopeConfigurationType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionScope/ForTaxonsScopeConfigurationType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionScope/ForVariantsScopeConfigurationType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/validators.xml
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionAction/FixedDiscountActionValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForProductsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForTaxonsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForVariantsScopeValidatorSpec.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/PercentageDiscountActionConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
  tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_with_invalid_actions_response.json
Labels: Enhancement, Documentation, Maintenance, Admin, API

#13627 Move ScopeValidatorInterface to PromotionBundle
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForProductsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForTaxonsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/ForVariantsScopeValidator.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForProductsScopeValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForTaxonsScopeValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/CatalogPromotion/ForVariantsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForProductsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForTaxonsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/CatalogPromotionScope/ForVariantsScopeValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Validator/Constraints/CatalogPromotionScopeValidator.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForProductsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForTaxonsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/CatalogPromotionScope/ForVariantsScopeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Validator/Constraints/CatalogPromotionScopeValidatorSpec.php
  src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionScope/ScopeValidatorInterface.php
Labels: Enhancement, Documentation, DX, API, Bug

#13635 [Docs] Drop warning about active, not applied promotions as states are handled in async manner as well
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#13607 [Catalog Promotion][UI] Fixed error when trying to save catalog promotion with empty percentage discount value
  features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php
Labels: Bug

#13604 [CatalogPromotion][UI][Shop] Fixed label displaying after option change
  features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotion_on_products_with_options.feature
  src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Transform/ProductOptionValueContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
  src/Sylius/Behat/Resources/config/services/contexts/transform.xml
  src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_catalog_promotions.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variantsPricing.html.twig
Labels: Shop

#13639 [UI][CatalogPromotion] Fix to not displaying duplicated validation message for fixed discount action
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
Labels: UX, Admin, Bug

#13644 [Maintenance] Minor clean up of UPGRADE files for Sylius 1.11
  UPGRADE-1.11.md
  UPGRADE-API-1.11.md
Labels: Maintenance

#13647 Update Sylius supported versions
  docs/book/organization/release-cycle.rst
Labels: Documentation

#13641 [ADR] Declaring services as public in container
  adr/2022_02_11_declaring_services_in_container.md
Labels: Documentation, Maintenance

#13650 [Documentation] Update installation guide for Plus
  docs/book/installation/sylius_plus_installation.rst
  docs/book/installation/sylius_plus_upgrading.rst
Labels: Documentation

#13658 [Documentation] Adjust installation guide for Plus on 1.11
  docs/book/installation/sylius_plus_installation.rst
Labels: Documentation

#13661 [DX] Adding a helpful error message to the ResetPasswordHandler
  src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ResetPasswordHandler.php
Labels: DX, API

#13488 feat: use sass instead of node-sass
  UPGRADE-1.11.md
  package.json
  src/Sylius/Bundle/AdminBundle/gulpfile.babel.js
  src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
Labels: Maintenance, Admin, Shop

#13651 [Admin][API] Catalog promotion actions validation fixed
  features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
  features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php
  src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/MoneyIntToLocalizedStringTransformer.php
  src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/PercentFloatToLocalizedStringTransformer.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/PercentageDiscountActionConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php
Labels: Admin, Bug

#13660 [CLI] Cancel unpaid orders command
  features/cli/cancel_unpaid_orders.feature
  src/Sylius/Behat/Context/Cli/CancelUnpaidOrdersContext.php
  src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Resources/config/services/contexts/cli.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/cli/canceling_unpaid_orders.yml
  src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
Labels: Bug

#13680 [Maintenance] Move note about asset management changes from 1.11 to 1.12 UPGRADE file
  UPGRADE-1.11.md
  UPGRADE-1.12.md
Labels: Maintenance, Bug

#13684 [Product][API][Bug] Fixed product sorting by translated names
  features/product/viewing_products/viewing_sorted_products.feature
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TranslationOrderNameAndLocaleFilter.php
Labels: API, Bug

#13659 API Upgrade file updated after ShippingMethod endpoints changes
  UPGRADE-API-1.12.md
Labels: Maintenance

#13687 [Behat][API] Remove duplicated steps in ProductContext
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
Labels: Behat, API, Bug

#13636 [Payment method] Listing payment method
  UPGRADE-API-1.12.md
  features/checkout/paying_for_order/viewing_available_payment_methods_based_on_current_channel.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Context/Setup/ChannelContext.php
  src/Sylius/Behat/Context/Setup/PaymentContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutPaymentContext.php
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/checkout/paying_for_order.yml
  src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
  src/Sylius/Bundle/ApiBundle/DataProvider/CartPaymentMethodsSubresourceDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/PaymentMethodsCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/Filter/PaymentMethodFilter.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/CartPaymentMethodsSubresourceDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/PaymentMethodsCollectionDataProviderSpec.php
  tests/Api/DataFixtures/ORM/payment_method.yaml
  tests/Api/Responses/Expected/shop/get_payment_methods_response.json
  tests/Api/Responses/Expected/shop/payment_method/get_payment_methods_for_cart_and_payment_response.json
  tests/Api/Responses/Expected/shop/payment_method/get_payment_methods_for_uncompleted_filters_response.json
  tests/Api/Responses/Expected/shop/payment_method/get_payment_methods_response.json
  tests/Api/Shop/PaymentMethodsTest.php
Labels: Documentation, Maintenance, API

#13692 [Admin] Fix for floating point amount on fixed action in catalog promotion.
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
Labels: DX, Admin, Bug

#13676 [Cart] Fix retrieving/overriding cart of logged in user by guest
  UPGRADE-1.10.md
  adr/2022_02_21_using_cart_by_guest_and_logged_in_customer.md
  behat.yml.dist
  features/checkout/preventing_from_claiming_cart_of_wrong_user.feature
  src/Sylius/Behat/Context/Setup/ShopSecurityContext.php
  src/Sylius/Behat/Context/Ui/Shop/AuthorizationContext.php
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
  src/Sylius/Behat/Service/SessionManager.php
  src/Sylius/Behat/Service/SessionManagerInterface.php
  src/Sylius/Behat/spec/Service/SessionManagerSpec.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220210135918.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
  src/Sylius/Bundle/ShopBundle/EventListener/ShopCartBlamerListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/ShopCartBlamerListenerSpec.php
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
  src/Sylius/Component/Core/Cart/Resolver/CreatedByGuestFlagResolver.php
  src/Sylius/Component/Core/Cart/Resolver/CreatedByGuestFlagResolverInterface.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
  src/Sylius/Component/Core/spec/Cart/Resolver/CreatedByGuestFlagResolverSpec.php
Labels: Maintenance, Shop, Bug

#13695 [Order] Change getters and setters to use a proper flag name
  src/Sylius/Bundle/ShopBundle/EventListener/ShopCartBlamerListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/ShopCartBlamerListenerSpec.php
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
Labels: Shop, Bug

#13691 [Docs] Force user to login during checkout
  docs/cookbook/api/how_force_login_already_registered_user_during_checkout.rst
  docs/cookbook/api/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation, Maintenance, Admin, API

#13698 [Docs] Path fix for validator in API force login cookbook
  docs/cookbook/api/how_force_login_already_registered_user_during_checkout.rst
Labels: Documentation

#13575 [DX] add correct return type to getAdjustments method
  src/Sylius/Component/Order/Model/AdjustableInterface.php
Labels: Enhancement, DX

#13699 [Documentation] Add reference to the cookbook about forcing login in API
  docs/book/orders/checkout.rst
Labels: Documentation, API

#13700 [Order] Fix getters and setters to use a proper flag name after upmerge issue
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
Labels: Bug
