Repository Sylius/Sylius, pull requests merged in 2022-03, with the labels that each got.

#13716 [Documentation] Fix start date of development 1.12 version
  docs/book/organization/release-cycle.rst
Labels: Documentation, Maintenance

#13710 [UI] Layout improvements and sticky columns
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_layout.scss
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_sidebarToggle.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/layout.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Index/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/create.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/update.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
Labels: UX, Admin

#13679 [Docs] [AdminBundle] fix minor typo
  docs/book/products/pricing.rst
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
Labels: Documentation, Admin

#13708 [Locale] Add header based locale context
  docs/book/api/index.rst
  docs/book/api/map.rst.inc
  docs/book/api/translations.rst
  src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestHeaderBasedLocaleContextSpec.php
  tests/Api/Responses/Expected/shop/product/get_product_with_de_DE_locale_translation.json
  tests/Api/Shop/ProductsTest.php
Labels: Enhancement, Documentation, Bug

#13704 Update PHP Version in installation doc
  docs/book/installation/installation.rst
Labels: Documentation

#13729 [Maintenance] Fix 1.9 build
  .github/workflows/application.yml
  CONFLICTS.md
  composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/UserBundle/spec/Provider/UsernameOrEmailProviderSpec.php
  symfony.lock
Labels: Maintenance, API

#13730 [Maintenance] Add conflict to symfony/framework-bundle to fix problem with solving path prefix in API scenarios
  CONFLICTS.md
  composer.json
Labels: Maintenance, Bug

#13732 [Hot-fix] Conflict with symfony/dependency-injection even more
  composer.json
Labels: Bug

#13725 [PaypalExpress] Dont take shipping tax adjustment to shipping cost
  src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
  src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
Labels: Bug

#13750 [Admin][Shop] placehold.it replaced to local placeholders
  src/Sylius/Behat/Element/Admin/TopBarElement.php
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_avatarImage.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_mainImage.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_media.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_mainImage.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
  src/Sylius/Bundle/UiBundle/Resources/private/img/200x200.png
  src/Sylius/Bundle/UiBundle/Resources/private/img/400x300.png
  src/Sylius/Bundle/UiBundle/Resources/private/img/50x50.png
Labels: Admin, Shop, Bug

#13738 [Docs] Synchronous messenger transport
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#13723 [Docs] Deployment on artifakt
  docs/_images/cookbook/deployment/artifakt/build.png
  docs/_images/cookbook/deployment/artifakt/create_environment.png
  docs/_images/cookbook/deployment/artifakt/create_project.png
  docs/_images/cookbook/deployment/artifakt/deploy.png
  docs/_images/cookbook/deployment/artifakt/domain_name.png
  docs/_images/cookbook/deployment/artifakt/github_settings.png
  docs/cookbook/deployment/artifakt.rst
  docs/cookbook/deployment/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#13737 [Admin] Fix undefined labels in taxon autocomplete
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
  src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionScope/ForTaxonsScopeConfigurationType.php
  src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
  tests/Controller/AdminTaxonAjaxTest.php
  tests/DataFixtures/ORM/resources/taxons.yml
  tests/Responses/ajax/taxon/index_response.json
  tests/Responses/ajax/taxon/specific_taxon_response.json
Labels: Admin, Bug

#13751 [Docs] Blank line removed
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#13731 [Taxation] Add validation of negative tax rate
  features/taxation/managing_tax_rates/tax_rate_validation.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
  src/Sylius/Bundle/TaxationBundle/Resources/config/validation/TaxRate.xml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.en.yml
Labels: Bug

#13734 [JS] add empty value to autocomplete selects
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
Labels: Bug

#13735 [Docs] add note to translation
  docs/book/api/translations.rst
Labels: Documentation

#13432 Update SalesDataProvider.php
  src/Sylius/Component/Core/Dashboard/SalesDataProvider.php
Labels: Admin, Bug

#13736 [Maintenance] Testing with PHP 8.1
  .github/workflows/application.yml
  .github/workflows/packages.yml
  composer.json
  phpspec.yml.dist
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/Dashboard/SalesDataProvider.php
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API

#12538 [Behat] Allow to use some useful methods on Order show page
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
Labels: Behat

#13770 [ADR] Clean up existing ADRs mostly by updating their statuses
  adr/2020_03_03_api_product_option_values.md
  adr/2020_03_03_api_translations.md
  adr/2020_03_03_feature_coverage_in_api.md
  adr/2020_11_12_registration_of_handlers_in_message_buses.md
  adr/2020_11_18_sending_emails_via_api.md
  adr/2021_04_15_using_iri_as_api_resource_identifier_in_request_instead_of_code_id.md
Labels: DX, Maintenance

#13775 [Behat][API] Change the undefined step to create a configurable product instead of simple one
  features/product/managing_products/editing_product_slug.feature
Labels: Behat, Bug

#13696 [API] UPGRADE file parameter names fixed
  UPGRADE-API-1.12.md
Labels: Maintenance

#13778 [Maintenance][API] Decouple resource metadata from ResetPasswordHandler
  UPGRADE-API-1.12.md
  src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ResetPasswordHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/ResetPasswordHandlerSpec.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php
Labels: Documentation, DX, Maintenance, API

#13782 [Plus] Fix Sylius installation guide
  docs/book/installation/sylius_plus_installation.rst
Labels: Documentation, Bug

#13769 [Core][Shipping] Fix estimated shipping costs
  UPGRADE-1.10.md
  features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_order_total.feature
  features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_total_weight.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
Labels: Maintenance, Shop, API, Bug

#13772 [ADR][API] Update ADR for providing locales after changing the approach
  adr/2021_07_05_api_providing_locales_available_in_active_channel.md
  adr/2022_03_15_api_providing_locales_available_in_active_channel.md
Labels: DX, Maintenance

#13785 [Upgrade] Add more details to UPGRADE-API-1.12.md
  UPGRADE-API-1.12.md
Labels: Maintenance

#13724 Fix disappearing products in Admin Panel when translation for current locale is missing
  features/product/managing_products/sorting_products.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/IndexPage.php
  src/Sylius/Behat/Page/Admin/Product/IndexPageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Field/name.html.twig
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Admin

#13790 [Maintenance] Update UPGRADE-1.11.md
  UPGRADE-1.11.md
Labels: Maintenance

#13744 [Maintenance]Ignore phpstan.neon file
  .gitignore
Labels: Documentation, Maintenance, Admin, Shop, Bug

#13799 [Core][Shipping] Deprecate processing shipments before recalculating prices
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
Labels: Maintenance

#13787 [ADR] Use raw data in commands and events
  adr/2022_03_18_raw_data_in_command_and_events.md
Labels: Maintenance

#13795 [ADR] Remove flush() from handlers.
  adr/2022_03_24_remove_flush_from_handlers.md
Labels: Maintenance

#11850 Fix redirection when there is a trailing slash in the products list path
  features/product/viewing_products/redirecting_to_products_when_there_is_a_trailing_slash_in_path.feature
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml
Labels: Maintenance, Shop, Bug

#13753 [UI] Replacing the placeholder avatar with an icon
  src/Sylius/Behat/Element/Admin/TopBarElement.php
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_avatarImage.html.twig
Labels: Documentation, Maintenance, Admin

#13801 [Behat] added context to manage non-collection subresources
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Client/RequestInterface.php
  src/Sylius/Behat/Context/Api/Admin/ManagingChannelsContext.php
Labels: Enhancement, DX, API

#13709 Fix fatal error when OPCache preloading is used
  UPGRADE-1.11.md
  phpstan.neon.dist
  psalm.xml
  src/Sylius/Bundle/AdminBundle/Controller/CustomerStatisticsController.php
  src/Sylius/Bundle/AdminBundle/Controller/Dashboard/StatisticsController.php
  src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
  src/Sylius/Bundle/ShopBundle/Controller/ContactController.php
  src/Sylius/Bundle/ShopBundle/Controller/CurrencySwitchController.php
  src/Sylius/Bundle/ShopBundle/Controller/HomepageController.php
  src/Sylius/Bundle/ShopBundle/Controller/LocaleSwitchController.php
  src/Sylius/Bundle/ShopBundle/Controller/SecurityWidgetController.php
  src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
Labels: Maintenance, Admin, Shop, Bug

#13803 [Admin][JS] Applying all the options selected for an attribute of type multiple select fixed
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
Labels: UX, Admin, Bug

#13806 Refreshed shop theme
  src/Sylius/Bundle/ShopBundle/Resources/private/img/homepage-banner.jpg
  src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
  src/Sylius/Bundle/ShopBundle/Resources/private/scss/theme.scss
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_banner.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Layout/Footer/Grid/_pre_footer.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_footer.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
Labels: UX, Shop

#13809 [Documentation] Fix build by specifying jinja2 version requirement
  docs/requirements.txt
Labels: Documentation, Bug

#13802 [Docs] Add a guide on how to deal with file access problems in the wkhtmltopdf
  docs/cookbook/payments/custom-invoice.rst
  docs/cookbook/payments/customizing-credit-memo.rst
Labels: Documentation
