Repository Sylius/Sylius, pull requests merged in 2022-12, with the labels that each got.

#14595 [Fix] Filtering out disabled channel scenario
  src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
Labels: Bug

#14529 Prepare for releasing @sylius-ui/frontend npm package
  .npmignore
  package.json
Labels: DX, Frontend

#14036 [Docker] Allow overriding ports in docker-compose.yml
  .docker/dev/php.ini
  docker-compose.yml
Labels: Docker

#14570 [CS][DX] Fix ECS refactoring
  ecs.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php
  src/Sylius/Bundle/ApiBundle/Command/Account/SendAccountRegistrationEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Account/SendAccountVerificationEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Account/VerifyCustomerAccount.php
  src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
  src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerCheckoutGuestType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerGuestType.php
  src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php
  src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LegacySonataBlockPass.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php
  src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php
  src/Sylius/Component/Core/Model/ChannelPricing.php
  src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
Labels: DX, Maintenance, Shop, API

#14614 Run behat using dual session as javascript scenario
  features/checkout/preventing_from_claiming_cart_of_wrong_user.feature
Labels: Bug

#14574 [API] Fix missing address serialization for phone number and company name
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
  tests/Api/Responses/Expected/shop/updated_billing_address_on_order_response.json
  tests/Api/Shop/OrdersTest.php
Labels: API

#14616 [Psalm] Skip deprecated in Symfony 6.2 class and interface
  psalm.xml
Labels: Maintenance

#14618 Use MakerBundle instead of SensioGeneratorBundle
  docs/cookbook/entities/custom-translatable-model.rst
Labels: Documentation

#14602 [GitHub Actions] Restrict "Refactor" workflow to Sylius/Sylius repo
  .github/workflows/refactor.yml
Labels: Maintenance

#14617 [maintenance] - remove docker pipelines
  .github/workflows/docker.yml
Labels: Maintenance, Docker

#14600 [ProductAssociation] Show product associations within current channel only
  features/product/viewing_products/viewing_product_associations.feature
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductAssociationRepository.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_product.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product_association.yml
  src/Sylius/Component/Core/Repository/ProductAssociationRepositoryInterface.php
Labels: Shop, Bug

#14621 [PHPUnit] Adjust contract tests after upmerge
  features/product/viewing_products/viewing_product_associations.feature
  tests/Api/Responses/Expected/shop/updated_billing_address_on_order_response.json
  tests/Api/Shop/OrdersTest.php
Labels: Bug

#14619 Update catalog_promotions.rst
  docs/book/products/catalog_promotions.rst
Labels: Documentation

#14587 Add gitattributes on bundles
  src/Sylius/Bundle/AddressingBundle/.gitattributes
  src/Sylius/Bundle/AdminBundle/.gitattributes
  src/Sylius/Bundle/ApiBundle/.gitattributes
  src/Sylius/Bundle/AttributeBundle/.gitattributes
  src/Sylius/Bundle/ChannelBundle/.gitattributes
  src/Sylius/Bundle/CoreBundle/.gitattributes
  src/Sylius/Bundle/CurrencyBundle/.gitattributes
  src/Sylius/Bundle/CustomerBundle/.gitattributes
  src/Sylius/Bundle/InventoryBundle/.gitattributes
  src/Sylius/Bundle/LocaleBundle/.gitattributes
  src/Sylius/Bundle/MoneyBundle/.gitattributes
  src/Sylius/Bundle/OrderBundle/.gitattributes
  src/Sylius/Bundle/PaymentBundle/.gitattributes
  src/Sylius/Bundle/PayumBundle/.gitattributes
  src/Sylius/Bundle/ProductBundle/.gitattributes
  src/Sylius/Bundle/PromotionBundle/.gitattributes
  src/Sylius/Bundle/ReviewBundle/.gitattributes
  src/Sylius/Bundle/ShippingBundle/.gitattributes
  src/Sylius/Bundle/ShopBundle/.gitattributes
  src/Sylius/Bundle/TaxationBundle/.gitattributes
  src/Sylius/Bundle/TaxonomyBundle/.gitattributes
  src/Sylius/Bundle/UiBundle/.gitattributes
  src/Sylius/Bundle/UserBundle/.gitattributes
Labels: Enhancement

#14632 [Documentation] Extend the maintenance period of Sylius 1.11 by one month
  docs/book/organization/release-cycle.rst
Labels: Documentation, Maintenance

#14633 [Documentation] Remove Sylius 1.12 scope from the release cycle page
  docs/_images/planned_1_12_scope.png
  docs/book/organization/release-cycle.rst
Labels: Documentation

#13820 [Doc] Add depth to theme configuration
  docs/book/themes/themes.rst
Labels: Documentation

#14608 [UI][Shop][Cart] Reset chosen options on refresh in firefox
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
Labels: Shop

#14634 [API] Fix ProductVariantNormalizer exception catching
  src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php
Labels: API

#13207 Changing replacement interface as previous one does not exist
  src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
Labels: Bug

#12099 Make link buttons with confirmation modal work again
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-bulk-action-require-confirmation.js
  src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-require-confirmation.js
Labels: Bug

#14289 [Api] Change int to integer in ProductVariant and ShippingMethod documentation normalizers
  src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php
  src/Sylius/Bundle/ApiBundle/Swagger/ShippingMethodDocumentationNormalizer.php
Labels: API, Bug

#14525 Adding skipIf for migrations to allow future runs when they should apply
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220203115813.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220407131547.php
Labels: Bug

#14575 [DX] Add EditorConfig for test API responses
  tests/Api/Responses/.editorconfig
Labels: DX

#14641 Updated twig/intl-extra to allow v3
  composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
Labels: Admin, Shop

#14571 Create admin user with CLI
  src/Sylius/Bundle/AdminBundle/Command/CreateAdminUserCommand.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Tests/Command/CreateAdminUserCommandTest.php
Labels: Admin

#14580 [Enchancement] Optimize memory usage by sylius:remove-expired-carts command
  src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php
  src/Sylius/Bundle/OrderBundle/spec/Remover/ExpiredCartsRemoverSpec.php
  src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
Labels: Enhancement

#14625 [Fix][Shop] Conditional adding of logout listener
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Compiler/LogoutListenerPass.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/SyliusShopBundle.php
  src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/Compiler/LogoutListenerPassTest.php
Labels: Shop, Bug

#14642 Fix invalid API errors normalization
  UPGRADE-API-1.11.md
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/FlattenExceptionNormalizerDecoratorCompilerPass.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/LegacyErrorHandlingCompilerPass.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/FlattenExceptionNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/HydraErrorNormalizer.php
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/FlattenExceptionNormalizerDecoratorCompilerPassTest.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/LegacyErrorHandlingCompilerPassTest.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/FlattenExceptionNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/HydraErrorNormalizerSpec.php
Labels: Maintenance, API, Bug

#14645 Move Upgrade API from 1.11.11 to 1.11.12 section to the top of file
  UPGRADE-API-1.11.md
Labels: Documentation, Maintenance

#14646 Adjust FlattenException and HydraError normalizers to Symfony 5.4
  UPGRADE-API-1.12.md
  psalm.xml
  src/Sylius/Behat/Context/Api/Admin/ResettingPasswordContext.php
  src/Sylius/Behat/Context/Api/Shop/LoginContext.php
  src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
  src/Sylius/Bundle/ApiBundle/Serializer/FlattenExceptionNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/HydraErrorNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/FlattenExceptionNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/HydraErrorNormalizerSpec.php
Labels: Maintenance, API

#14643 [ProductAssociation] Fix empty product associations
  features/product/viewing_products/viewing_product_associations.feature
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductAssociationRepository.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_association.html.twig
Labels: Shop, Bug

#14661 [Maintenance][Psalm] Add LifecycleEventArgs to deprecated classes
  phpstan.neon.dist
  psalm.xml
Labels: Maintenance

#14491 Upgrade PHPStan to level 3
  phpstan.neon.dist
  src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LoggedInCustomerEmailAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LoggedInCustomerEmailIfNotSetAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/Serializer/ShippingMethodNormalizer.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/CountryTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
  src/Sylius/Bundle/CoreBundle/Provider/FlashBagProvider.php
  src/Sylius/Bundle/PayumBundle/Request/GetStatus.php
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php
  src/Sylius/Bundle/ShopBundle/Router/LocaleStrippingRouter.php
  src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php
  src/Sylius/Bundle/UserBundle/Provider/EmailProvider.php
  src/Sylius/Bundle/UserBundle/Provider/UsernameOrEmailProvider.php
  src/Sylius/Bundle/UserBundle/Provider/UsernameProvider.php
  src/Sylius/Component/Channel/Context/SingleChannelContext.php
  src/Sylius/Component/Core/Factory/ChannelFactory.php
  src/Sylius/Component/Core/Model/Address.php
  src/Sylius/Component/Core/Model/CatalogPromotion.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  src/Sylius/Component/Core/Model/OrderItem.php
  src/Sylius/Component/Core/Model/OrderItemUnit.php
  src/Sylius/Component/Core/Model/Payment.php
  src/Sylius/Component/Core/Model/Product.php
  src/Sylius/Component/Core/Model/ProductVariant.php
  src/Sylius/Component/Core/Model/Promotion.php
  src/Sylius/Component/Core/Model/Shipment.php
  src/Sylius/Component/Core/Model/ShippingMethod.php
  src/Sylius/Component/Core/Payment/Provider/OrderPaymentProvider.php
  src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php
  src/Sylius/Component/Core/spec/Model/OrderItemUnitSpec.php
  src/Sylius/Component/Payment/Resolver/DefaultPaymentMethodResolver.php
  src/Sylius/Component/Shipping/Resolver/DefaultShippingMethodResolver.php
Labels: Admin, Shop, API

#13157 Add missing space to taxes <tr>
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Labels: Shop

#12712 Fix sprintf parameters order
  src/Sylius/Component/Product/Resolver/AvailableProductOptionValuesResolver.php
  src/Sylius/Component/Product/spec/Resolver/AvailableProductOptionValuesResolverSpec.php
Labels: DX, Bug

#14660 [Maintenance] PHPUnit upgrade to ^9.5
  composer.json
  src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/CountryChoiceTypeTest.php
  src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/ZoneChoiceTypeTest.php
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/Tests/ApiPlatform/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
  src/Sylius/Bundle/ApiBundle/Tests/ApiPlatform/Bridge/Symfony/Routing/RouteNameResolverTest.php
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendAccountRegistrationEmailHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendAccountVerificationEmailHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendContactRequestHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendOrderConfirmationEmailHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendResetPasswordEmailHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Converter/IriToIdentifierConverterTest.php
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/Tests/Form/Type/AttributeType/SelectAttributeTypeTest.php
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/Tests/Fixture/OptionsResolver/LazyOptionTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Form/Type/Taxon/ProductTaxonAutocompleteChoiceTypeTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Mailer/OrderEmailManagerTest.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/Tests/Command/GenerateCouponsCommandTest.php
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/phpunit.xml.dist
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Core/composer.json
  tests/Functional/Bundles/ApiBundle/CommandHandler/SendAccountRegistrationEmailHandlerTest.php
  tests/Functional/Bundles/ApiBundle/CommandHandler/SendAccountVerificationEmailHandlerTest.php
  tests/Functional/Bundles/ApiBundle/CommandHandler/SendResetPasswordEmailHandlerTest.php
Labels: DX, Maintenance, Admin, API

#14594 Fix postgres builds
  features/promotion/complex_promotions.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
  src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
Labels: Maintenance, Admin

#14662 Improve loading taxons
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/taxon.yml
  src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
  src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
Labels: Admin, Shop, Performance

#14654 Add a cookbook about dealing with multiple channels in console commands
  docs/cookbook/cli/handle-multiple-channels-in-cli.rst
  docs/cookbook/cli/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation
