Repository Sylius/Sylius, pull requests merged in 2023-12, with the labels that each got.

#15579 [Behat] Unify the Currency Handling in Behat Scenarios
  features/account/customer_account/viewing_orders_history/viewing_order_only_from_current_channel.feature
  features/admin/dashboard.feature
  features/admin/dashboard_per_channel.feature
  features/cart/shopping_cart/adding_product_with_discounted_catalog_price_to_cart.feature
  features/cart/shopping_cart/adding_product_with_variants_with_discounted_catalog_price_to_cart.feature
  features/cart/shopping_cart/resolving_default_shipping_method_in_cart_summary_based_on_method_position.feature
  features/checkout/ability_to_change_email_during_checkout.feature
  features/checkout/placing_an_order_with_different_scopes_for_shipping_and_taxes.feature
  features/checkout/seeing_order_summary/seeing_discount_on_order_item_on_summary_page.feature
  features/checkout/seeing_purchaser_identifier_in_checkout_page.feature
  features/checkout/shipping_order/preventing_not_available_shipping_method_selection.feature
  features/order/managing_orders/cancelling_order_with_promotion.feature
  features/order/managing_orders/order_filtration/filtering_orders_by_total_in_different_currencies.feature
  features/order/managing_orders/order_filtration/filtering_orders_by_variants.feature
  features/order/managing_orders/order_history/tracking_changes_on_order_addresses.feature
  features/product/managing_product_variants/checking_products_in_the_shop_while_editing_their_product_variants.feature
  features/product/managing_product_variants/generating_product_variant.feature
  features/product/managing_product_variants/generating_product_variant_validation.feature
  features/product/managing_product_variants/product_variant_validation.feature
  features/product/managing_product_variants/removing_product_variant_price_from_obsolete_channel.feature
  features/product/managing_products/editing_product.feature
  features/product/managing_products/product_validation.feature
  features/product/viewing_price_history/accessing_price_history_from_simple_product.feature
  features/product/viewing_product_in_admin_panel/viewing_applied_catalog_promotions_details_for_a_simple_product.feature
  features/promotion/applying_catalog_promotions/applying_catalog_promotions_price_calculation.feature
  features/promotion/managing_promotions/adding_promotion_with_action_in_different_channels.feature
  features/promotion/managing_promotions/adding_promotion_with_filter.feature
  features/promotion/managing_promotions/adding_promotion_with_rule.feature
  features/promotion/managing_promotions/adding_promotion_with_rule_in_different_channels.feature
  features/promotion/receiving_discount/receiving_discounts_with_product_minimum_price_specified.feature
  features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
  features/promotion/receiving_discount/receiving_stacked_promotions_with_changing_context.feature
  features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_items_total.feature
  features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_total_weight.feature
  features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_items_total.feature
  features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_items_total_with_taxes_and_promotions.feature
  features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_total_weight.feature
  features/shipping/managing_shipping_methods/seeing_errors_in_shipping_method_charges.feature
  features/user/managing_customers/seeing_orders_statistics_on_customer_details_page.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Transform/LexicalContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
Labels: DX, Behat

#15568 [ApiBundle] Update validation message for command argument types.
  src/Sylius/Bundle/ApiBundle/Exception/InvalidRequestArgumentException.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/CommandNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandDenormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandNormalizerSpec.php
Labels: API, Bug

#15583 [Api][Test] Update promotion test response check
  tests/Api/Admin/PromotionsTest.php
  tests/Api/DataFixtures/ORM/promotion/channel.yaml
  tests/Api/Responses/Expected/admin/promotion/post_promotion_with_invalid_actions_response.json
  tests/Api/Responses/Expected/admin/promotion/post_promotion_with_invalid_rules_response.json
Labels: DX

#15565 [DOC] Fix display link in authorize page
  docs/cookbook/payments/authorize.rst
Labels: Documentation

#15516 [Maintenance][Behat] Add suite isolation
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
  behat.yml.dist
  composer.json
  features/product/managing_product_attributes/editing_select_product_attribute.feature
  features/taxonomy/managing_taxons/adding_taxon_with_parent.feature
Labels: DX, Maintenance, CI

#15595 Remove redundant denormalization check
  src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php
Labels: API

#15596 Update merge instructions in upmerge_pr.yaml
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance, CI

#15587 [CI] Update Symfony versions in builds
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-unstable.yaml
  .github/workflows/matrix.json
  composer.json
Labels: Maintenance, Admin, Shop, API, CI

#15602 Add the sylius-labs/suite-tags-extension package
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  behat.yml.dist
  composer.json
  features/order/managing_orders/order_filtration/filtering_orders_by_variants.feature
  features/product/managing_product_attributes/editing_select_product_attribute.feature
  features/taxonomy/managing_taxons/adding_taxon_for_with_parent.feature
Labels: Maintenance, CI

#15603 Fix build
  .github/workflows/matrix.json
Labels: Maintenance, CI

#15553 Cover "Order details" scenarios in API
  features/order/managing_orders/order_details/seeing_order.feature
  features/order/managing_orders/order_details/seeing_order_aggregated_discounts.feature
  features/order/managing_orders/order_details/seeing_order_aggregated_taxes.feature
  features/order/managing_orders/order_details/seeing_order_currency_on_show.feature
  features/order/managing_orders/order_details/seeing_order_discounts.feature
  features/order/managing_orders/order_details/seeing_order_item_detailed_data.feature
  features/order/managing_orders/order_details/seeing_order_item_included_taxes.feature
  features/order/managing_orders/order_details/seeing_order_item_taxes.feature
  features/order/managing_orders/order_details/seeing_order_items_with_proper_names.feature
  features/order/managing_orders/order_details/seeing_order_new_state_after_customers_checkout.feature
  features/order/managing_orders/order_details/seeing_order_payment_state_as_completed_if_free_order_coupon_was_applied.feature
  features/order/managing_orders/order_details/seeing_order_payment_state_as_completed_if_order_total_is_zero.feature
  features/order/managing_orders/order_details/seeing_order_shipment_state_after_checkout.feature
  features/order/managing_orders/order_details/seeing_order_shipment_state_as_shipped_if_there_is_not_shipments_to_deliver.feature
  features/order/managing_orders/order_details/seeing_order_shipping_fees.feature
  features/order/managing_orders/order_details/seeing_order_shipping_taxes.feature
  features/order/managing_orders/order_details/seeing_order_shipping_total_with_applied_promotion_and_taxes.feature
  features/order/managing_orders/order_details/seeing_order_with_different_promotions.feature
  features/order/managing_orders/order_details/seeing_order_with_items.feature
  features/order/managing_orders/order_details/seeing_order_without_shipping_address.feature
  features/order/managing_orders/order_details/seeing_province_created_manually_on_order_page.feature
  features/order/managing_orders/order_details/seeing_shipment_shipping_date.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/RequestFactory.php
  src/Sylius/Behat/Client/RequestFactoryInterface.php
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Resources.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Resources/config/suites/api/order/managing_orders.yml
  src/Sylius/Bundle/ApiBundle/Controller/GetOrderAdjustmentsAction.php
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/OrderAdjustmentsTypeDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Adjustment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
  src/Sylius/Component/Core/Model/Adjustment.php
  src/Sylius/Component/Core/Model/AdjustmentInterface.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  tests/Api/Admin/OrdersTest.php
  tests/Api/Responses/Expected/admin/order/get_adjustments_for_a_given_order_response.json
  tests/Api/Responses/Expected/admin/order/get_order_response.json
  tests/Api/Responses/Expected/admin/order/gets_orders_for_customer_response.json
  tests/Api/Responses/Expected/shop/add_item_response.json
  tests/Api/Responses/Expected/shop/create_cart_response.json
  tests/Api/Responses/Expected/shop/create_cart_with_default_locale_response.json
  tests/Api/Responses/Expected/shop/get_order_response.json
  tests/Api/Responses/Expected/shop/order_completion/order_with_free_non_shippable_items_response.json
  tests/Api/Responses/Expected/shop/order_completion/order_with_non_shippable_items_response.json
  tests/Api/Responses/Expected/shop/order_completion/order_with_shippable_and_non_shippable_items_response.json
  tests/Api/Responses/Expected/shop/updated_billing_address_on_order_response.json
  tests/Api/Responses/Expected/shop/updated_payment_method_on_order_response.json
Labels: API

#15601 [PHPStan] Baseline File Regeneration
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php
  src/Sylius/Bundle/AddressingBundle/Validator/Constraints/UniqueProvinceCollectionValidator.php
  src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ZoneCannotContainItselfValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/AccountVerificationTokenEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/AddingEligibleProductVariantToCartValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/AdminResetPasswordTokenNonExpiredValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChangedItemQuantityInCartValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CheckoutCompletionValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenPaymentMethodEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenShippingMethodEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ConfirmResetPasswordValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectChangeShopUserConfirmPasswordValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectOrderAddressValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderItemAvailabilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderNotEmptyValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderPaymentMethodEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderProductEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderShippingMethodEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ShipmentAlreadyShippedValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ShopUserNotVerifiedValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ShopUserResetPasswordTokenExistsValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ShopUserResetPasswordTokenNotExpiredValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/SingleValueForProductVariantOptionValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueReviewerEmailValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueShopUserEmailValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/UpdateCartEmailNotAllowedValidator.php
  src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidAttributeValueValidator.php
  src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidSelectAttributeConfigurationValidator.php
  src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidTextAttributeConfigurationValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/CartItemAvailabilityValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/ChannelCodeCollectionValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/ChannelDefaultLocaleEnabledValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/ExistingChannelCodeValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllPricesDefinedValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllVariantPricesDefinedValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/LocalesAwareValidAttributeValueValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/OrderPaymentMethodEligibilityValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/OrderProductEligibilityValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/RegisteredUserValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/TranslationForExistingLocalesValidator.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/UniqueReviewerEmailValidator.php
  src/Sylius/Bundle/CurrencyBundle/Validator/Constraints/DifferentSourceTargetCurrencyValidator.php
  src/Sylius/Bundle/CurrencyBundle/Validator/Constraints/UniqueCurrencyPairValidator.php
  src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php
  src/Sylius/Bundle/ProductBundle/Validator/ProductVariantCombinationValidator.php
  src/Sylius/Bundle/ProductBundle/Validator/UniqueSimpleProductCodeValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionActionValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionScopeValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/CouponGenerationAmountValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionDateRangeValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionSubjectCouponValidator.php
Labels: DX, Maintenance

#15385 [Maintenance] Add more deprecations
  UPGRADE-1.13.md
  src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
  src/Sylius/Bundle/ShippingBundle/Provider/DateTimeProvider.php
Labels: Maintenance

#15549 Validate payment method's gateway configuration
  UPGRADE-1.13.md
  config/packages/_sylius.yaml
  features/payment/managing_payment_methods/editing_payment_method.feature
  features/payment/managing_payment_methods/payment_method_validation.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Page/Admin/PaymentMethod/CreatePage.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/GatewayConfig.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
  src/Sylius/Bundle/CoreBundle/Form/Extension/PaymentMethodTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/PaymentMethod.xml
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
  src/Sylius/Bundle/PayumBundle/Form/Type/PaypalGatewayConfigurationType.php
  src/Sylius/Bundle/PayumBundle/Form/Type/StripeGatewayConfigurationType.php
  src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/validation/GatewayConfig.xml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.en.yml
  src/Sylius/Bundle/PayumBundle/Tests/DependencyInjection/SyliusPayumExtensionTest.php
  src/Sylius/Bundle/PayumBundle/Validator/Constraints/GatewayFactoryExists.php
  src/Sylius/Bundle/PayumBundle/Validator/GatewayFactoryExistsValidator.php
  src/Sylius/Bundle/PayumBundle/Validator/GroupsGenerator/GatewayConfigGroupsGenerator.php
  src/Sylius/Bundle/PayumBundle/spec/Validator/GatewayFactoryExistsValidatorSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Validator/GroupsGenerator/GatewayConfigGroupsGeneratorSpec.php
Labels: Maintenance, Admin, Shop, API

#15386 [Maintenance] Remove leftover deprecations
  src/Sylius/Behat/Service/SecurityService.php
  src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneChoiceType.php
  src/Sylius/Bundle/AddressingBundle/test/app/config/config.yml
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
  src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
  src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
  src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
  src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/ShippingBundle/Provider/Calendar.php
  src/Sylius/Bundle/ShippingBundle/Provider/DateTimeProvider.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/spec/Assigner/ShippingDateAssignerSpec.php
  src/Sylius/Bundle/ShippingBundle/spec/Provider/CalendarSpec.php
  src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonSlugController.php
  src/Sylius/Bundle/UiBundle/Block/BlockEventListener.php
  src/Sylius/Bundle/UiBundle/Storage/FilterStorage.php
  src/Sylius/Component/Product/Resolver/DefaultProductVariantResolver.php
  src/Sylius/Component/Product/spec/Resolver/DefaultProductVariantResolverSpec.php
Labels: Maintenance

#15612 Bump all Symfony dependencies' versions to ^6.4
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API

#15613 ECS Fixes
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/RequestFactory.php
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Promotion/GeneratePromotionCouponHandler.php
  src/Sylius/Bundle/ApiBundle/Controller/GetOrderAdjustmentsAction.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderItemAvailabilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Promotion/GeneratePromotionCouponHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/CatalogPromotionWorkflowTest.php
  src/Sylius/Bundle/PayumBundle/Validator/GatewayFactoryExistsValidator.php
  src/Sylius/Bundle/PayumBundle/spec/Validator/GatewayFactoryExistsValidatorSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Validator/GroupsGenerator/GatewayConfigGroupsGeneratorSpec.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorSpec.php
  tests/Api/Admin/CatalogPromotionsTest.php
  tests/Api/Admin/PaymentMethodsTest.php
  tests/Api/Admin/ProductAssociationTypesTest.php
  tests/Api/Admin/ProductAttributesTest.php
  tests/Api/Admin/ProductOptionsTest.php
  tests/Api/Admin/ProductVariantsTest.php
  tests/Api/Admin/ProductsTest.php
  tests/Api/Admin/PromotionCouponsTest.php
  tests/Api/Admin/PromotionsTest.php
  tests/Api/Admin/ShippingMethodsTest.php
  tests/Api/Admin/TaxonsTest.php
Labels: Maintenance, API

#15610 `JavaScriptTestHelper`: Interval Increase
  src/Sylius/Behat/Resources/config/services.xml
Labels: Enhancement

#15614 [Admin][UI] Fix csrf error breaking admin form
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/Form/_content.html.twig
Labels: UX, Admin, Bug

#15609 [Maintenance][API] Marking more inapplicable scenarios with no-api
  features/admin/redirecting_on_login_after_being_logout.feature
  features/cart/shopping_cart/clearing_cart_after_logging_out.feature
  features/currency/managing_currencies/editing_currency.feature
  features/inventory/managing_inventory/browsing_inventory.feature
  features/inventory/managing_inventory/filtering_inventory_by_code.feature
  features/inventory/managing_inventory/filtering_inventory_by_name.feature
  features/product/adding_product_reviews/adding_product_review_as_a_customer.feature
  features/promotion/managing_promotions/accessing_the_coupons_management_from_the_promotion_page.feature
  features/taxonomy/managing_taxons/reordering_taxon.feature
Labels: Maintenance, API

#15615 Use serialized name when displaying an error about a wrong request field type
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandDenormalizerSpec.php
Labels: API

#15616 [API] Finish covering taxation scenarios
  features/taxation/managing_tax_categories/editing_tax_category.feature
  features/taxation/managing_tax_rates/adding_tax_rate.feature
  features/taxation/managing_tax_rates/editing_tax_rate.feature
  features/taxation/managing_tax_rates/tax_rate_validation.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxRatesContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
  src/Sylius/Bundle/ApiBundle/Serializer/TaxRateDenormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/TaxRateDenormalizerSpec.php
  tests/Api/Admin/TaxRatesTest.php
  tests/Api/Responses/Expected/admin/tax_rate/post_tax_rate_with_no_amount_response.json
Labels: API

#15435 [Checkout] Prevent extra fields when login in on addressing page
  features/checkout/addressing_order/sign_in_during_addressing_step.feature
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
  src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
Labels: Shop, Bug

#14286 Prevent eager loading hundreds of countries
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
Labels: Enhancement, Maintenance

#15627 Add an endpoint exposing customer's statistics
  src/Sylius/Bundle/ApiBundle/Controller/GetCustomerStatisticsAction.php
  src/Sylius/Bundle/ApiBundle/Query/GetCustomerStatistics.php
  src/Sylius/Bundle/ApiBundle/QueryHandler/GetCustomerStatisticsHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CustomerStatistics.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PerChannelCustomerStatistics.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/controllers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/query_handlers.xml
  src/Sylius/Bundle/ApiBundle/spec/QueryHandler/GetCustomerStatisticsHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
  tests/Api/Admin/CustomersTest.php
  tests/Api/DataFixtures/ORM/order/fulfilled_order.yaml
  tests/Api/Responses/Expected/admin/customer/get_customer_statistics_response.json
Labels: Admin, API

#15635 [API][Behat] covering tests for managing promotions
  features/product/managing_products/modifying_taxons_assigned_to_an_existing_product.feature
  features/promotion/applying_catalog_promotions/not_reapplying_catalog_promotions_on_variants_once_products_taxon_changes.feature
  features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_on_variants_once_products_taxon_changes.feature
  features/promotion/managing_catalog_promotions/sorting_catalog_promotions.feature
  features/promotion/tracking_usage/checking_promotion_usage.feature
  features/promotion/tracking_usage/decreasing_promotion_coupon_usage_after_cancelling_order.feature
  features/promotion/tracking_usage/decreasing_promotion_usage_after_cancelling_order.feature
  features/promotion/tracking_usage/increasing_promotion_coupon_usage_after_placing_order.feature
  features/promotion/tracking_usage/increasing_promotion_usage_after_placing_order.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductTaxonsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductTaxonsContext.php
  src/Sylius/Behat/Resources/config/suites/api/promotion/managing_promotions.yml
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductTaxonDataPersister.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/ProductTaxonDataPersisterSpec.php
  tests/Api/Admin/ProductTaxonsTest.php
  tests/Api/DataFixtures/ORM/product/product_taxon.yaml
  tests/Api/Responses/Expected/admin/channel/get_channel_response.json
  tests/Api/Responses/Expected/admin/product_taxon/get_product_taxon_response.json
  tests/Api/Responses/Expected/admin/product_taxon/get_product_taxons_response.json
  tests/Api/Responses/Expected/admin/product_taxon/post_product_taxon_response.json
  tests/Api/Responses/Expected/admin/product_taxon/put_product_taxon_response.json
Labels: API

#15636 [ECS] Ordered Types Fixer
  ecs.php
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Client/RequestBuilder.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
  src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/Action/ResendShipmentConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/ApiBundle/Query/GetCustomerStatistics.php
  src/Sylius/Bundle/ApiBundle/QueryHandler/GetCustomerStatisticsHandler.php
  src/Sylius/Bundle/ApiBundle/Tests/Converter/IriToIdentifierConverterTest.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/TaxRateDenormalizerSpec.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Listener/CatalogPromotionStateChangedListener.php
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
  src/Sylius/Bundle/CoreBundle/Provider/FlashBagProvider.php
  src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php
  src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/MoneyIntToLocalizedStringTransformer.php
  src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/PercentFloatToLocalizedStringTransformer.php
  src/Sylius/Bundle/TaxonomyBundle/Repository/TaxonTreeRepositoryInterface.php
  src/Sylius/Bundle/UiBundle/Storage/FilterStorage.php
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
  src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
  tests/Api/JsonApiTestCase.php
Labels: Enhancement, DX, Admin, API

#15642 [Admin] Add official support submenu in admin panel
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.af.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ar.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.be.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.bg.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ca.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.cs.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.da.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de_CH.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.el.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.es.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.et.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fa.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fi.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fr.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.he.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.hr.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.hu.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.id.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.is.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.it.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ja.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ko.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.lt.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.lv.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.mn.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.no.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.pt_BR.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ro.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.ru.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sk.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sq.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sr.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sr_CS.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.sv.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.th.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.tr.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.uk.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.vi.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.zh_CN.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.zh_TW.yml
  src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
Labels: Admin

#15628 [PromotionBundle] Update validation process of promotion actions/rules
  UPGRADE-1.13.md
  config/packages/_sylius.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/ContainsProductConfigurationType.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/NthOrderConfigurationType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/PromotionAction.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/PromotionRule.xml
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/FixedDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/PercentageDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitFixedDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitPercentageDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Rule/CartQuantityConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Rule/ItemTotalConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionAction.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionRule.xml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/SyliusPromotionExtensionTest.php
  src/Sylius/Bundle/PromotionBundle/Validator/Constraints/PromotionActionGroup.php
  src/Sylius/Bundle/PromotionBundle/Validator/Constraints/PromotionActionType.php
  src/Sylius/Bundle/PromotionBundle/Validator/Constraints/PromotionRuleGroup.php
  src/Sylius/Bundle/PromotionBundle/Validator/Constraints/PromotionRuleType.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionActionGroupValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionActionTypeValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionRuleGroupValidator.php
  src/Sylius/Bundle/PromotionBundle/Validator/PromotionRuleTypeValidator.php
  src/Sylius/Bundle/PromotionBundle/spec/Validator/PromotionActionGroupValidatorSpec.php
  src/Sylius/Bundle/PromotionBundle/spec/Validator/PromotionActionTypeValidatorSpec.php
  src/Sylius/Bundle/PromotionBundle/spec/Validator/PromotionRuleGroupValidatorSpec.php
  src/Sylius/Bundle/PromotionBundle/spec/Validator/PromotionRuleTypeValidatorSpec.php
  tests/Api/Admin/PromotionsTest.php
  tests/Api/Responses/Expected/admin/promotion/post_promotion_with_invalid_actions_response.json
  tests/Api/Responses/Expected/admin/promotion/post_promotion_with_invalid_rules_response.json
Labels: Maintenance, API

#15646 [API][Admin] Allow using float for amount in tax rates
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/TaxRateDenormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/TaxRateDenormalizerSpec.php
  tests/Api/Admin/TaxRatesTest.php
Labels: API, Bug

#15630 Finish covering managing product-related resources
  features/product/managing_product_reviews/editing_product_review.feature
  features/product/managing_product_reviews/filtering_product_reviews.feature
  features/product/managing_product_reviews/recalculating_product_average_rating.feature
  features/product/managing_product_variants/sorting_product_variants_within_product_by_position.feature
  src/Sylius/Behat/Context/Api/Admin/BrowsingProductVariantsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductVariantsContext.php
  src/Sylius/Behat/Context/Ui/Admin/BrowsingProductVariantsContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites/api/product/managing_product_variants.yml
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/ProductReviewDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
  tests/Api/Responses/Expected/admin/product/get_product_response.json
  tests/Api/Responses/Expected/admin/product/get_products_response.json
  tests/Api/Responses/Expected/admin/product/post_product_response.json
  tests/Api/Responses/Expected/admin/product/put_product_response.json
  tests/Api/Responses/Expected/admin/product_review/get_product_reviews.json
  tests/Api/Responses/Expected/admin/product_variant/get_product_variants_response.json
Labels: API

#15650 Update the example response of the Customer's statistics endpoint
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/CustomerDocumentationModifier.php
Labels: API

#15640 [PromotionBundle] Deprecate PromotionCouponGeneratorInstructionInterface
  UPGRADE-1.13.md
  src/Sylius/Bundle/PromotionBundle/Command/GenerateCouponsCommand.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponGeneratorInstructionType.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionCouponGeneratorInstruction.xml
  src/Sylius/Bundle/PromotionBundle/Validator/CouponGenerationAmountValidator.php
  src/Sylius/Bundle/PromotionBundle/spec/Validator/CouponGenerationAmountValidatorSpec.php
  src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactory.php
  src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactoryInterface.php
  src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstruction.php
  src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstructionInterface.php
  src/Sylius/Component/Promotion/spec/Exception/FailedGenerationExceptionSpec.php
  src/Sylius/Component/Promotion/spec/Factory/PromotionCouponGeneratorInstructionFactorySpec.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorInstructionSpec.php
Labels: Maintenance

#15655 [Unit] `OrderPlacerTrait` Refactor
  tests/Api/Admin/OrdersTest.php
  tests/Api/Admin/PaymentsTest.php
  tests/Api/Shop/CheckoutCompletionTest.php
  tests/Api/Shop/OrdersTest.php
  tests/Api/Shop/PaymentsTest.php
  tests/Api/Utils/OrderPlacerTrait.php
Labels: DX

#15662 Add running "Refactor" workflow daily
  .github/workflows/refactor.yaml
Labels: Maintenance, CI

#15652 [UI] Improved Statistics Scenarios
  features/admin/dashboard.feature
  features/admin/dashboard_per_channel.feature
  features/admin/statistics.feature
  features/admin/statistics_per_channel.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Transform/ChannelContext.php
  src/Sylius/Behat/Context/Ui/Admin/DashboardContext.php
  src/Sylius/Behat/Page/Admin/DashboardPage.php
  src/Sylius/Behat/Page/Admin/DashboardPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/ui/admin/dashboard.yaml
Labels: DX, Behat, Maintenance, Admin, API

#15660 [API] Finish covering managing orders
  features/cart/shopping_cart/allowing_access_only_for_correctly_logged_in_users.feature
  features/order/managing_orders/handling_order_shipment/placing_order_with_shipment.feature
  features/order/managing_orders/handling_order_shipment/shipping_order.feature
  features/order/managing_orders/order_details/being_unable_to_see_cart.feature
  features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
  features/shipping/managing_shipments/accessing_shipments_order_from_shipment_index.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Context/Setup/CartContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites/api/order/managing_orders.yml
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryExtension/OrderExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/SyliusApiExtensionTest.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryExtension/OrderExtensionSpec.php
  tests/Api/Admin/CustomersTest.php
  tests/Api/Admin/OrdersTest.php
  tests/Api/DataFixtures/ORM/order/fulfilled.yaml
  tests/Api/Responses/Expected/admin/order/gets_orders_for_customer_response.json
Labels: Admin, API

#13043 [Docs] Update themes.rst
  docs/book/themes/themes.rst
Labels: Documentation

#14448 [DOCS] Add info about mailer to 1.12
  docs/book/installation/installation.rst
  docs/cookbook/emails/mailer.rst
Labels: Documentation

#15672 Typo cart-flow.rst
  docs/book/orders/cart-flow.rst
Labels: Documentation

#15664 Move validation groups parameters to appropriate bundle configs
  UPGRADE-1.13.md
  config/packages/_sylius.yaml
  src/Sylius/Bundle/PaymentBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
  src/Sylius/Bundle/PayumBundle/Resources/config/validation/GatewayConfig.xml
  src/Sylius/Bundle/PayumBundle/Tests/DependencyInjection/SyliusPayumExtensionTest.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/app/config.yml
Labels: Maintenance

#13777 [Locale] Change language negotiation to RFC 4647 based
  UPGRADE-1.12.md
  docs/book/api/translations.rst
  features/checkout/picking_up_the_cart_with_the_locale_other_than_the_default.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestHeaderBasedLocaleContextSpec.php
  tests/Api/JsonApiTestCase.php
  tests/Api/Shop/ProductsTest.php
Labels: Documentation, Maintenance, Bug

#15677 Define permissions for all workflows
  .github/workflows/auto-merge.yaml
  .github/workflows/ci__full.yaml
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci__unstable.yaml
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  .github/workflows/ci_packages-unstable.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
  .github/workflows/documentation.yaml
  .github/workflows/refactor.yaml
  .github/workflows/social-media-notifications.yaml
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance
