Repository Sylius/Sylius, pull requests merged in 2023-01, with the labels that each got.

#14668 Improve "Handle multiple channels in CLI" cookbook
  docs/cookbook/cli/handle-multiple-channels-in-cli.rst
Labels: Documentation

#13689 Fix typo in sylius_order state machine callback
  composer.json
  phpunit.xml.dist
  src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
  src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePage.php
  src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
  src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/CancelOrderStateMachineCallbackPass.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/BackwardsCompatibility/CancelOrderStateMachineCallbackPassTest.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/phpunit.xml.dist
  src/Sylius/Component/Addressing/Checker/CountryProvincesDeletionChecker.php
Labels: DX, Bug

#14682 It's 2023! 🎉
  LICENSE
  docs/book/contributing/code/license.rst
  docs/conf.py
  src/Sylius/Bundle/AddressingBundle/LICENSE
  src/Sylius/Bundle/AdminBundle/LICENSE
  src/Sylius/Bundle/AttributeBundle/LICENSE
  src/Sylius/Bundle/ChannelBundle/LICENSE
  src/Sylius/Bundle/CurrencyBundle/LICENSE
  src/Sylius/Bundle/CustomerBundle/LICENSE
  src/Sylius/Bundle/InventoryBundle/LICENSE
  src/Sylius/Bundle/LocaleBundle/LICENSE
  src/Sylius/Bundle/MoneyBundle/LICENSE
  src/Sylius/Bundle/OrderBundle/LICENSE
  src/Sylius/Bundle/PaymentBundle/LICENSE
  src/Sylius/Bundle/PayumBundle/LICENSE
  src/Sylius/Bundle/ProductBundle/LICENSE
  src/Sylius/Bundle/PromotionBundle/LICENSE
  src/Sylius/Bundle/ReviewBundle/LICENSE
  src/Sylius/Bundle/ShippingBundle/LICENSE
  src/Sylius/Bundle/ShopBundle/LICENSE
  src/Sylius/Bundle/TaxationBundle/LICENSE
  src/Sylius/Bundle/TaxonomyBundle/LICENSE
  src/Sylius/Bundle/UiBundle/LICENSE
  src/Sylius/Bundle/UserBundle/LICENSE
  src/Sylius/Component/Addressing/LICENSE
  src/Sylius/Component/Attribute/LICENSE
  src/Sylius/Component/Core/LICENSE
  src/Sylius/Component/Currency/LICENSE
  src/Sylius/Component/Customer/LICENSE
  src/Sylius/Component/Inventory/LICENSE
  src/Sylius/Component/Locale/LICENSE
  src/Sylius/Component/Order/LICENSE
  src/Sylius/Component/Payment/LICENSE
  src/Sylius/Component/Product/LICENSE
  src/Sylius/Component/Promotion/LICENSE
  src/Sylius/Component/Shipping/LICENSE
  src/Sylius/Component/Taxation/LICENSE
  src/Sylius/Component/Taxonomy/LICENSE
  src/Sylius/Component/User/LICENSE
Labels: Documentation, Admin, Shop

#14678 [UX] Fix cart button on small screens
  src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Widget/_popup.html.twig
Labels: UX, Shop, Bug

#14669 Wrong Rounding of the prices in the percentage discount catalog promotions
  features/promotion/applying_catalog_promotions/applying_catalog_promotions_price_calculation.feature
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Calculator/PercentageDiscountPriceCalculator.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Calculator/PercentageDiscountPriceCalculatorSpec.php
Labels: Bug

#14691 [Fix] Symfony container reanimation after friendsofsymfony/rest-bundle: 3.5.0 release
  phpstan.neon.dist
  src/Sylius/Bundle/ApiBundle/Serializer/FlattenExceptionNormalizer.php
  src/Sylius/Bundle/UiBundle/composer.json
Labels: API, Bug

#14694 [Composer] Remove conflict with doctrine/annotations: ^2.0
  src/Sylius/Bundle/UiBundle/composer.json
Labels: Maintenance, Dependencies

#14696 Remove yarn.lock file
  .gitignore
  yarn.lock
Labels: DX, Frontend

#14700 Add a conflict for doctrine/migrations:3.5.3
  CONFLICTS.md
  composer.json
Labels: Maintenance, Dependencies

#14701 [API] Fix IRI converter catching homepage
  src/Sylius/Bundle/ApiBundle/Converter/IriToIdentifierConverter.php
  src/Sylius/Bundle/ApiBundle/Tests/Converter/IriToIdentifierConverterTest.php
Labels: API, Bug

#14683 Extract authorized user assignment to separate method/ cp to 1.11
  features/cart/shopping_cart/clearing_cart_after_logging_out.feature
  features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/BlameCartHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
  src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/BlameCartHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/PickupCartHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php
  src/Sylius/Bundle/ShopBundle/EventListener/ShopCartBlamerListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/ShopCartBlamerListenerSpec.php
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
  src/Sylius/Component/Core/spec/Model/OrderSpec.php
Labels: Shop, API, Bug

#14685 Default ORDER BY for all entities and their relationships
  UPGRADE-1.11.md
  phpstan.neon.dist
  src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Country.orm.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/SqlWalker/OrderByIdentifierSqlWalker.php
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/CatalogPromotion.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricing.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Customer.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/PaymentMethod.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductImage.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Promotion.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Shipment.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ShippingMethod.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Taxon.orm.xml
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItem.orm.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItemUnit.orm.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductAssociation.orm.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductOption.orm.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/CatalogPromotion.orm.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/doctrine/model/Shipment.orm.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/doctrine/model/ShippingMethod.orm.xml
  src/Sylius/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxCategory.orm.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml
  src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/User.orm.xml
  tests/Functional/AbstractOrmTestCase.php
  tests/Functional/Doctrine/Dump/Model.php
  tests/Functional/Doctrine/Mock/ConnectionMock.php
  tests/Functional/Doctrine/Mock/DatabasePlatformMock.php
  tests/Functional/Doctrine/Mock/DriverConnectionMock.php
  tests/Functional/Doctrine/Mock/DriverMock.php
  tests/Functional/Doctrine/Mock/DriverResultMock.php
  tests/Functional/Doctrine/Mock/StatementMock.php
  tests/Functional/OrderByIdentifierSqlWalkerTest.php
Labels: Maintenance, Bug

#14707 Add note to UPGRADE-1.12 file about default order by for all entities
  UPGRADE-1.12.md
Labels: Maintenance

#14177 [Docs] Fix API docs for Shop User token response
  src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php
Labels: API

#14706 [Promotion][UI] Fix hardcoded "sylius_promotion" selector
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
Labels: UX, Admin

#14708 Add missing final keywords to Spec tests
  src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/CountryDataPersisterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/ZoneDataPersisterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php
  src/Sylius/Component/Addressing/spec/Checker/CountryProvincesDeletionCheckerSpec.php
  src/Sylius/Component/Addressing/spec/Checker/ZoneDeletionCheckerSpec.php
Labels: Maintenance, API

#14715 [Core] Fix default query hint config
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
Labels: Bug

#14667 [Maintenance][CI] Remove github actions deprecations
  .github/workflows/application.yml
Labels: Maintenance

#14655 Improve error handling while password resetting
  src/Sylius/Behat/Context/Api/Admin/ResettingPasswordContext.php
  src/Sylius/Behat/Context/Api/Shop/LoginContext.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/CoreBundle/Security/UserPasswordResetter.php
  src/Sylius/Bundle/CoreBundle/spec/Security/UserPasswordResetterSpec.php
  src/Sylius/Bundle/UserBundle/Exception/UserNotFoundException.php
Labels: API

#14713 [Core] Optimize UnpaidOrdersStateUpdater
  UPGRADE-1.13.md
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
  src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php
  src/Sylius/Component/Core/spec/Updater/UnpaidOrdersStateUpdaterSpec.php
Labels: Enhancement, Maintenance

#14693 [Feature] Allows `row_attr` on form rows
  src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
Labels: Feature

#14724 As an Admin, I want to modify taxons of a product
  features/product/managing_products/modifying_taxons_assigned_to_an_existing_product.feature
  features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_on_variants_once_products_taxon_changes.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductTaxonsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Context/Api/Resources.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductTaxonsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites/api/product/managing_products.yml
  src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml
  src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductTaxonDataPersister.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/ProductTaxonDataPersisterSpec.php
Labels: Feature, API

#14710 Refactor CI
  .github/workflows/application.yml
  .github/workflows/ci.yaml
  .github/workflows/ci_e2e-customs.yml
  .github/workflows/ci_e2e-mariadb.yml
  .github/workflows/ci_e2e-mysql.yml
  .github/workflows/ci_e2e-pgsql.yml
  .github/workflows/ci_packages.yml
  .github/workflows/ci_static-checks.yml
  .github/workflows/packages.yml
  RoboFile.php
  composer.json
  config/packages/test/webpack_encore.yaml
  config/packages/test_cached/webpack_encore.yaml
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
Labels: Maintenance, CI

#14733 Update generating-invoice-after-payment.rst
  docs/cookbook/payments/generating-invoice-after-payment.rst
Labels: Documentation

#14731 [Fix] Request stack with null request
  src/Sylius/Bundle/AddressingBundle/EventListener/ZoneMemberIntegrityListener.php
  src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php
  src/Sylius/Bundle/ApiBundle/Serializer/FlattenExceptionNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/HydraErrorNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/FlattenExceptionNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/HydraErrorNormalizerSpec.php
  src/Sylius/Bundle/ShopBundle/EventListener/OrderCustomerIpListener.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderCustomerIpListenerSpec.php
Labels: Shop, API

#13835 chore: Replace NBSP by Space in doc
  docs/cookbook/images/images-on-entity.rst
Labels: Documentation

#14721 Added forgotten import to docblock.
  docs/cookbook/shipping-methods/custom-shipping-method-rule.rst
Labels: Documentation

#14581 Fix dev dockerfile: add curl
  .docker/dev/Dockerfile
Labels: Docker

#14735 Refactor not to use RequestStack::getMasterRequest()
  phpstan.neon.dist
  psalm.xml
  src/Sylius/Bundle/AddressingBundle/EventListener/ZoneMemberIntegrityListener.php
  src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php
  src/Sylius/Bundle/ApiBundle/Context/TokenValueBasedCartContext.php
  src/Sylius/Bundle/ApiBundle/spec/Context/TokenValueBasedCartContextSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/FlattenExceptionNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/HydraErrorNormalizerSpec.php
  src/Sylius/Bundle/ChannelBundle/Context/FakeChannel/FakeChannelContext.php
  src/Sylius/Bundle/ChannelBundle/spec/Context/FakeChannel/FakeChannelContextSpec.php
  src/Sylius/Bundle/LocaleBundle/Context/RequestBasedLocaleContext.php
  src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestBasedLocaleContextSpec.php
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestHeaderBasedLocaleContextSpec.php
  src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderCustomerIpListenerSpec.php
  src/Sylius/Component/Channel/Context/CachedPerRequestChannelContext.php
  src/Sylius/Component/Channel/Context/RequestBased/ChannelContext.php
  src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php
  src/Sylius/Component/Channel/spec/Context/RequestBased/ChannelContextSpec.php
Labels: Maintenance, Shop, API

#14734 Adjust GitHub Actions jobs' names
  .github/workflows/ci.yaml
  .github/workflows/ci_e2e-custom.yml
  .github/workflows/ci_e2e-mariadb.yml
  .github/workflows/ci_e2e-mysql.yml
  .github/workflows/ci_e2e-pgsql.yml
  .github/workflows/ci_static-checks.yml
Labels: Maintenance, CI

#12996 Remove sylius.model.shop_billing_data.class
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
Labels: Maintenance, API, Bug

#13448 Remove wrong trailing space in test attribute
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
Labels: Documentation, Maintenance, Shop

#14577 Product taxon position don't affect parent taxon - API
  .github/workflows/application.yml
  features/product/viewing_products/viewing_products_from_specific_taxon_sorted_by_position.feature
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsByTaxonExtension.php
  src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TaxonFilter.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsByTaxonExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Filter/Doctrine/TaxonFilterSpec.php
Labels: Maintenance, API

#14745 Fix static analysis after upmerge
  src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TaxonFilter.php
  src/Sylius/Bundle/ApiBundle/spec/Filter/Doctrine/TaxonFilterSpec.php
Labels: Maintenance, API

#14698 ApiBundle fixes in composer.js
  src/Sylius/Bundle/ApiBundle/composer.json
Labels: API

#14736 Updated UPGRADE-1.11.md to add a BC Break on channel pricing
  UPGRADE-1.11.md
Labels: Maintenance

#14742 Refactor Workflows to use two type of builds
  .github/workflows/auto-merge.yaml
  .github/workflows/ci__full.yaml
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
  .github/workflows/documentation.yaml
  .github/workflows/matrix.json
  .github/workflows/refactor.yaml
Labels: Maintenance, CI

#14747 Make build notifier running always event on failed builds
  .github/workflows/ci__full.yaml
Labels: Maintenance, CI

#14665 [Feature][Command] CreateAdminUserCommand - add AdminUser entity validation
  src/Sylius/Bundle/AdminBundle/Command/CreateAdminUserCommand.php
  src/Sylius/Bundle/AdminBundle/Exception/CreateAdminUserFailedException.php
  src/Sylius/Bundle/AdminBundle/Message/CreateAdminUser.php
  src/Sylius/Bundle/AdminBundle/MessageHandler/CreateAdminUserHandler.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Tests/Command/CreateAdminUserCommandTest.php
  src/Sylius/Bundle/AdminBundle/Tests/MessageHandler/Admin/CreateAdminUserHandlerTest.php
Labels: Admin, Future, Bug

#14716 [Messenger] Use parameters in the configuration
  .env
  .env.test
  .env.test_cached
  UPGRADE-1.12.md
  docker-compose.test.yml
  src/Sylius/Bundle/AdminBundle/test/.env
  src/Sylius/Bundle/ApiBundle/test/.env
  src/Sylius/Bundle/CoreBundle/Migrations/Version20220203115813.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
  src/Sylius/Bundle/CoreBundle/test/.env
Labels: Enhancement, DX, Maintenance, Bug

#14737 Add a custom workflow for Symfony 6.3
  .github/workflows/ci_e2e-custom.yaml
Labels: Maintenance, CI

#14749 Port of Sylius 1.13 CI to Sylius 1.12
  .github/workflows/application.yml
  .github/workflows/ci__full.yaml
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci_e2e-custom.yml
  .github/workflows/ci_e2e-mariadb.yml
  .github/workflows/ci_e2e-mysql.yml
  .github/workflows/ci_e2e-pgsql.yml
  .github/workflows/ci_packages.yml
  .github/workflows/ci_static-checks.yml
  .github/workflows/matrix.json
  .github/workflows/packages.yml
  RoboFile.php
  composer.json
  config/packages/test/webpack_encore.yaml
  config/packages/test_cached/webpack_encore.yaml
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/CountryDataPersisterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/ZoneDataPersisterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Component/Addressing/spec/Checker/CountryProvincesDeletionCheckerSpec.php
  src/Sylius/Component/Addressing/spec/Checker/ZoneDeletionCheckerSpec.php
Labels: Maintenance, API

#14752 Fix workflows file extensions after downmerge
  .github/workflows/auto-merge.yaml
  .github/workflows/ci__full.yaml
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
  .github/workflows/documentation.yaml
  .github/workflows/refactor.yaml
Labels: Maintenance

#14753 Fix typo in notify-about-build-status workflow job
  .github/workflows/ci__full.yaml
Labels: Maintenance

#14562 Update embedding products snippet in documentation
  docs/cookbook/shop/embedding-products.rst
Labels: Documentation

#14381 [Maintenance] Note behat changes due to Mailer usage
  UPGRADE-1.12.md
Labels: Maintenance

#14722 [User] Allow configuring `lastLogin` tracking frequency
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
  src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
Labels: Enhancement, RFC

#14755 [Maintenance][ApiBundle] Move test app into `Tests` dir
  .github/workflows/packages.yml
  phpstan.neon.dist
  psalm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/.env
  src/Sylius/Bundle/ApiBundle/Tests/Application/.env.test
  src/Sylius/Bundle/ApiBundle/Tests/Application/.gitignore
  src/Sylius/Bundle/ApiBundle/Tests/Application/bin/console
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/Foo.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/FooSyliusResource.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/bootstrap.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/bundles.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/Foo.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/FooSyliusResource.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/Taxon.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/administrator.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/channel.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/foo.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/foo_sylius_resource.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/promotions.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/taxons.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/jwt/.gitkeep
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/jwt/private-test.pem
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/jwt/public-test.pem
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/routing.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/security.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/serialization/Foo.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/serialization/FooSyliusResource.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/serialization/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/services.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/public/index.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Command/FooCommand.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/CommandHandler/FooHandler.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/Foo.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/FooSyliusResource.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/Taxon.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Kernel.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/DisablingApiTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/DisablingDocumentationTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/FooApiCommandTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/FooSyliusResourceTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/FooTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/PromotionTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/SetUpTestsTrait.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/SyliusConfigMergeTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/TaxonTest.php
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/ApiBundle/phpunit.xml.dist
Labels: Maintenance, Bug

#14762 Add missing interface to OrderIntegrityChecker
  src/Sylius/Bundle/ShopBundle/EventListener/OrderIntegrityChecker.php
  src/Sylius/Bundle/ShopBundle/EventListener/OrderIntegrityCheckerInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderIntegrityCheckerSpec.php
Labels: Enhancement, DX, Shop

#14773 [Maintenance][UserBundle] Fix UserLastLoginSubscriber arguments
  docs/components_and_bundles/bundles/SyliusUserBundle/summary.rst
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
  src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php
  src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
Labels: Documentation, Bug

#14770 Fix typo in notify-about-build-status workflow job
  .github/workflows/ci__full.yaml
  .github/workflows/ci__minimal.yaml
Labels: Maintenance

#14416 [Product] Fixed product attribute translations #11570
  features/product/managing_products/adding_select_attribute_in_different_locales.feature
  src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
  src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
  src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
Labels: Maintenance, Admin, Bug

#14556 Hide "View in your store" widget in case ShopBundle disabled
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_channelLinks.html.twig
Labels: RFC, Documentation, Maintenance, Admin, Bug

#14780 [Product] Add missing LocaleContextInterface in ProductAttributeController after upmerge from 1.11
  src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
Labels: Maintenance, Bug

#14174 [Admin] Fix 500 error when showing cart in admin panel
  features/order/managing_orders/order_details/being_unable_to_see_cart.feature
  src/Sylius/Behat/Context/Transform/CartContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Resources/config/services/contexts/transform.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
Labels: Admin, Bug

#14576 Fix notInRangeMessage usage for a few Range validations
  features/promotion/managing_coupons/coupon_generate_validation.feature
  features/promotion/managing_promotions/promotion_validation.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitPercentageDiscountConfigurationType.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionCouponGeneratorInstruction.xml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
Labels: Bug
