Repository Sylius/Sylius, pull requests merged in 2023-06, with the labels that each got.

#15014 Change prority for custom ChannelContext
  docs/book/configuration/channels.rst
Labels: Documentation

#15059 Upgrade PHPStan to level 5
  phpstan.neon.dist
  src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/UpdateCartHandler.php
  src/Sylius/Bundle/ApiBundle/Controller/GetProductBySlugAction.php
  src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectOrderAddressValidator.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/ApplyCatalogPromotionsOnVariantsHandler.php
  src/Sylius/Bundle/CoreBundle/Context/CustomerAndChannelBasedCartContext.php
  src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
  src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
  src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductsToProductAssociationsTransformer.php
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/BuildAttributesFormSubscriber.php
  src/Sylius/Bundle/ShopBundle/Controller/ContactController.php
  src/Sylius/Bundle/ShopBundle/EventListener/UserImpersonatedListener.php
  src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Component/Core/Factory/CartItemFactory.php
  src/Sylius/Component/Core/Model/CatalogPromotion.php
  src/Sylius/Component/Core/Model/Product.php
  src/Sylius/Component/Core/Model/Promotion.php
  src/Sylius/Component/Core/Model/ShippingMethod.php
  src/Sylius/Component/Core/Promotion/Checker/Eligibility/PromotionCouponPerCustomerUsageLimitEligibilityChecker.php
  src/Sylius/Component/Core/Promotion/Checker/Rule/NthOrderRuleChecker.php
  src/Sylius/Component/Core/Promotion/Checker/Rule/TotalOfItemsFromTaxonRuleChecker.php
  src/Sylius/Component/Core/StateResolver/CheckoutStateResolver.php
  src/Sylius/Component/Core/StateResolver/OrderStateResolver.php
Labels: Admin, Shop, API

#15075 Add a conflict for doctrine/orm:2.15.2
  CONFLICTS.md
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Promotion/composer.json
Labels: Maintenance, Admin, API

#15083 Remove deprecated EventSubscriberInterface
  UPGRADE-FROM-1.12-WITH-PRICE-HISTORY-PLUGIN-TO-1.13-LEGACY.md
  src/Sylius/Bundle/CoreBundle/PriceHistory/EventListener/ChannelPricingLogEntryEventListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/subscribers.xml
  src/Sylius/Bundle/CoreBundle/spec/PriceHistory/EventListener/ChannelPricingLogEntryEventListenerSpec.php
Labels: Maintenance

#15037 [Docs] add image to entity via one-to-one association
  docs/cookbook/images/image-on-entity.rst
  docs/cookbook/images/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#15063 [API] Allow overriding xml resource mapping
  composer-require-checker.json
  composer.json
  psalm.xml
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Merger/LegacyResourceMetadataMerger.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Merger/MetadataMergerInterface.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/MergingXmlExtractor.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/ExtractorMergingCompilerPass.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/Country.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/fixtures/channel.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/SyliusConfigMergeTest.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/ExtractorMergingCompilerPassTest.php
  src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/Metadata/Merger/LegacyResourceMetadataMergerSpec.php
Labels: Enhancement, DX, API

#15096 [Fix] Remove redundant conflict entries
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
Labels: Maintenance

#15086 [Fixture] Improve LazyOption performance
  src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/LazyOption.php
Labels: Enhancement, DX

#15095 Viewing children taxons API scenario ceverage
  features/product/viewing_products/viewing_children_taxons_from_specific_taxon.feature
  src/Sylius/Behat/Context/Api/Shop/TaxonContext.php
  src/Sylius/Behat/Context/Transform/TaxonContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
Labels: Behat, API

#15103 Seeing order locale API scenario coverage
  features/checkout/seeing_order_summary/seeing_order_locale.feature
Labels: Behat, API

#15068 View only available associations for product
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ProductItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/AvailableProductAssociationsInProductCollectionExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/spec/DataProvider/ProductItemDataProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AvailableProductAssociationsInProductCollectionExtensionSpec.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
  src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
  tests/Api/DataFixtures/ORM/product/products_with_associations.yaml
  tests/Api/Responses/Expected/shop/product/get_products_collection_with_associations_response.json
  tests/Api/Shop/ProductsTest.php
Labels: API

#15092 Cover Seeing payment method instructions behat API scenario
  features/checkout/paying_for_order/seeing_payment_method_instructions_after_checkout.feature
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
Labels: Behat, API

#15104 Fixes after reviews
  features/checkout/paying_for_order/seeing_payment_method_instructions_after_checkout.feature
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AvailableProductAssociationsInProductCollectionExtensionSpec.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
Labels: Enhancement, API

#15085 [API][Products] Viewing diagonal variants options
  features/product/viewing_products/viewing_diagonal_variant_options.feature
  src/Sylius/Behat/Client/Request.php
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
  src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
Labels: API

#15106 [Maintenance] Update the remaining copyright blocks
  src/Sylius/Behat/Resources/config/services/contexts/api/common.xml
  src/Sylius/Behat/Resources/config/services/pages/admin/price_history.xml
  src/Sylius/Behat/Resources/config/suites/api/product/viewing_price_history.yml
  src/Sylius/Behat/Resources/config/suites/api/product/viewing_price_history_after_catalog_promotions.yml
  src/Sylius/Behat/Resources/config/suites/api/taxation/managing_tax_rates.yml
  src/Sylius/Behat/Resources/config/suites/api/taxon/managing_taxons_ajax.yml
  src/Sylius/Behat/Resources/config/suites/domain/product/managing_price_history.yml
  src/Sylius/Behat/Resources/config/suites/ui/product/accessing_price_history.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ChannelPriceHistoryConfig.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ChannelPricingLogEntry.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPriceHistoryConfig.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricingLogEntry.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTaxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/Country.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPriceHistoryConfig.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricingLogEntry.orm.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/checkers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/command_dispatcher.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/command_handler.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/logger.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/processors.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/product_variant_map.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/ChannelPriceHistoryConfig.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductTaxon.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/PromotionTranslation.orm.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionTranslation.xml
  tests/Api/Admin/ChannelPriceHistoryConfigTest.php
  tests/Api/Admin/ChannelPricingLogEntryTest.php
  tests/Api/Admin/CountriesTest.php
  tests/Api/Admin/CurrenciesTest.php
  tests/Api/Admin/CustomerGroupsTest.php
  tests/Api/Admin/ExchangeRatesTest.php
  tests/Api/Admin/ProductReviewsTest.php
  tests/Api/Admin/PromotionsTest.php
  tests/Api/Admin/ProvincesTest.php
  tests/Api/Admin/ShippingCategoriesTest.php
  tests/Api/Admin/ShippingMethodsTest.php
  tests/Api/Admin/TaxCategoriesTest.php
  tests/Api/Admin/TaxRatesTest.php
  tests/Api/Admin/TaxonsTest.php
  tests/Api/Utils/UserLoginTrait.php
  tests/Functional/CatalogPromotionRemovalAnnouncerTest.php
Labels: Maintenance, API

#15109 Add workflow for automatic upmerge PR creating
  .github/workflows/upmerge_pr.yaml
Labels: DX, Maintenance

#15113 Fix auto upmerge workflow
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance, CI

#15112 [Scenarios] Add @no-api tag for `Addressing an order and sign in scenario`
  features/checkout/addressing_order/filling_shipping_address_details_as_guest_with_existing_account.feature
Labels: API

#12555 Fix misleading signing in the admin panel feature description
  features/admin/signing_in_to_administration_panel.feature
Labels: Behat

#15087 [Maintenance][API] Fix ChangedItemQuantityInCart validator alias
  UPGRADE-API-1.13.md
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChangedItemQuantityInCart.php
Labels: Maintenance, API

#15084 Update Sylius 1.12 with PriceHistoryPlugin to Sylius 1.13 upgrade file
  UPGRADE-FROM-1.12-WITH-PRICE-HISTORY-PLUGIN-TO-1.13-LEGACY.md
  UPGRADE-FROM-1.12-WITH-PRICE-HISTORY-PLUGIN-TO-1.13.md
Labels: Maintenance

#15061 Performance improvement of SingleChannelContext
  src/Sylius/Bundle/ChannelBundle/Doctrine/ORM/ChannelRepository.php
  src/Sylius/Component/Channel/Context/SingleChannelContext.php
  src/Sylius/Component/Channel/Repository/ChannelRepositoryInterface.php
  src/Sylius/Component/Channel/spec/Context/SingleChannelContextSpec.php
Labels: Enhancement

#15116 Ignore ApiPlatform\Core\Api\IriConverterInterface DeprecatedClass Psalm error
  psalm.xml
Labels: Maintenance

#15121 Fix CI
  .github/workflows/upmerge_pr.yaml
  composer.json
  phpstan-baseline.neon
Labels: Maintenance, CI

#15110 Include children taxons while executing InForTaxonsScopeVariantChecker
  features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_taxon.feature
  phpstan-baseline.neon
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Checker/InForTaxonsScopeVariantChecker.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/checkers.xml
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/Checker/InForTaxonsScopeVariantCheckerSpec.php
  src/Sylius/Bundle/TaxonomyBundle/Repository/TaxonTreeRepository.php
  src/Sylius/Bundle/TaxonomyBundle/Repository/TaxonTreeRepositoryInterface.php
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/tree_repository.xml
Labels: Bug

#15122 [API] Cover signing in validation
  features/account/signing_in_validation.feature
  src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Component/Channel/Context/SingleChannelContext.php
  src/Sylius/Component/User/Model/CredentialsHolderInterface.php
Labels: Behat, API

#15130 Add conflict to symfony/validator 5.4.25, 6.2.12 and 6.3.1
  CONFLICTS.md
  composer.json
Labels: Maintenance, Bug

#15026 Allow removing locales
  features/locale/managing_locales/removing_locale.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingLocalesContext.php
  src/Sylius/Behat/Context/Setup/ProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/api/locale/managing_locales.yml
  src/Sylius/Behat/Resources/config/suites/ui/locale/managing_locales.yml
  src/Sylius/Bundle/AdminBundle/EventListener/LocaleListener.php
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/locale.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/locale.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en.yml
  src/Sylius/Bundle/AdminBundle/spec/EventListener/LocaleListenerSpec.php
  src/Sylius/Bundle/ApiBundle/DataPersister/LocaleDataPersister.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/ApiBundle/spec/DataPersister/LocaleDataPersisterSpec.php
  src/Sylius/Bundle/LocaleBundle/Checker/Exception/LocaleIsUsedException.php
  src/Sylius/Bundle/LocaleBundle/Checker/LocaleUsageChecker.php
  src/Sylius/Bundle/LocaleBundle/Checker/LocaleUsageCheckerInterface.php
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/spec/Checker/LocaleUsageCheckerSpec.php
  tests/Api/Admin/LocalesTest.php
Labels: Feature, Admin, API

#15135 Revert "Add support for Bunnyshell (#15134)"
  .bunnyshell/docker/nginx/Dockerfile
  .bunnyshell/docker/nginx/default.conf.template
  .bunnyshell/docker/php/Dockerfile
  .bunnyshell/docker/php/entrypoints/migrations-entrypoint
  .bunnyshell/docker/php/entrypoints/php-entrypoint
  .bunnyshell/docker/php/files/crontab
  .bunnyshell/docker/php/prod/opcache.ini
  .bunnyshell/docker/php/prod/php.ini
  .bunnyshell/templates/preview/bunnyshell.yaml
  .dockerignore
  .github/workflows/bunnyshell_cleanup-envs.yaml
  .github/workflows/bunnyshell_delete-preview-env.yaml
  .github/workflows/bunnyshell_deploy-preview-env.yaml
  .github/workflows/bunnyshell_start-preview-env.yaml
  .github/workflows/bunnyshell_stop-preview-env.yaml
  config/packages/prod/monolog.yaml
Labels: Maintenance, Docker, CI

#15108 Prevent changing payment method of cancelled order
  features/checkout/paying_for_order/preventing_changing_the_payment_method_of_a_cancelled_order.feature
  src/Sylius/Behat/Context/Api/Common/ResponseContext.php
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
  src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
  src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/suites/api/checkout/paying_for_order.yml
  src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
  src/Sylius/Bundle/ApiBundle/Changer/PaymentMethodChanger.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
  src/Sylius/Bundle/ApiBundle/Exception/PaymentMethodCannotBeChangedException.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/validation/ChangePaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CanPaymentMethodBeChanged.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/CanPaymentMethodBeChangedValidator.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChoosePaymentMethodHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/CanPaymentMethodBeChangedValidatorSpec.php
  tests/Api/Responses/Expected/shop/updated_payment_method_on_cancelled_order_response.json
  tests/Api/Shop/OrdersTest.php
  tests/Api/Utils/OrderPlacerTrait.php
Labels: Behat, API
