Repository Sylius/Sylius, pull requests merged in 2023-02, with the labels that each got.

#14779 [Admin] Change homepage path variable to use snake case
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_channelLinks.html.twig
Labels: DX, Admin

#14782 Fix the wrong DQL alias in OrderByIdentifierSqlWalker
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/SqlWalker/OrderByIdentifierSqlWalker.php
  tests/Functional/Doctrine/Mock/DriverConnectionMock.php
  tests/Functional/OrderByIdentifierSqlWalkerTest.php
Labels: Bug

#14783 [Admin] Fix 500 when resending order confirmation email for a cart
  src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
Labels: Maintenance, Admin, Bug

#14785 Remove scheduled full build
  .github/workflows/ci__full.yaml
Labels: Maintenance, CI

#14758 [API] Priorities in data transformers
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/CommandDataTransformerPass.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/CommandDataTransformerPassTest.php
Labels: Enhancement, DX, API

#14761 fix(layout): removed admin-layout__topbar height
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_layout.scss
Labels: Admin, Frontend

#14786 Fix CI Full to run both 1.12 and 1.13
  .github/workflows/ci__full.yaml
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
Labels: Maintenance, CI

#14756 [API] Get admin detail information
  src/Sylius/Bundle/ApiBundle/EventListener/AdminAuthenticationSuccessListener.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/EventListener/AdminAuthenticationSuccessListenerSpec.php
  tests/Api/Responses/Expected/admin/log_in_admin_response.json
Labels: API

#14754 Add PHP 8.2 to workflows
  .github/workflows/ci_static-checks.yaml
  .github/workflows/matrix.json
Labels: Maintenance, CI

#14789 Fix product attribute value normalizer
  src/Sylius/Bundle/ApiBundle/Serializer/ProductAttributeValueNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php
Labels: API

#14728 [API] Fix admin's side can't create new taxonomy
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
  tests/Api/Admin/TaxonsTest.php
  tests/Api/Responses/Expected/admin/taxon/get_taxon_response.json
  tests/Api/Responses/Expected/admin/taxon/get_taxons_response.json
  tests/Api/Responses/Expected/admin/taxon/post_taxon_response.json
Labels: API

#14055 Fix channel color in fixture
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
Labels: Maintenance

#12752 [ADR] Strategy for resource internationalization in API
  adr/2021_06_24_api_content_internationalization.md
Labels: Maintenance

#14561 [DOCS] Sylius components attribute
  docs/components_and_bundles/components/Attribute/basic_usage.rst
  docs/components_and_bundles/components/Attribute/index.rst
  docs/components_and_bundles/components/Attribute/installation.rst
  docs/components_and_bundles/components/Attribute/interfaces.rst
  docs/components_and_bundles/components/Attribute/models.rst
Labels: Documentation

#14026 [Minor] Typo fixes and small code improvement
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderShopUserItemExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderVisitorItemExtension.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderShopUserItemExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderVisitorItemExtensionSpec.php
Labels: API

#13313 [Behat] add scenario for disabled admin
  features/admin/blocking_login_for_disabled_administrators.feature
  src/Sylius/Behat/Context/Setup/AdminUserContext.php
  src/Sylius/Behat/Resources/config/suites/api/admin/login.yml
  src/Sylius/Behat/Resources/config/suites/ui/admin/login.yml
Labels: Behat, Maintenance

#12556 Add an option to use icon-only buttons on grids
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/applyTransition.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/create.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/delete.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/show.html.twig
  src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/update.html.twig
Labels: Feature

#13440 Add documentation for non-labeled actions
  docs/customization/grid.rst
Labels: Documentation

#13044 [Maintenance] Added promotion form theme override in UPGRADE-1.9.md
  UPGRADE-1.9.md
Labels: Maintenance

#13913 [Architecture] Ensure HTTP errors are not dispatched in command handlers
  src/Sylius/Bundle/ApiBundle/phparkitect.php
Labels: API

#14792 Add adjusting shop regex section to disabling-localised-urls.rst
  docs/cookbook/shop/disabling-localised-urls.rst
Labels: Documentation

#14802 Update versions in the "Submitting a Patch" doc
  docs/_exts/ultimatereplacement/__init__.py
  docs/book/contributing/code/patches.rst
  docs/conf.py
Labels: Documentation

#14531 Update sylius_plus_installation.rst
  docs/book/installation/sylius_plus_installation.rst
Labels: Documentation

#14804 Fix CI
  CONFLICTS.md
  composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
Labels: Maintenance, CI

#14797 [API] Prepend configuration with API Platform mapping
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/SyliusApiExtensionTest.php
Labels: DX, Maintenance, API

#14803 Logout Admin User after being disabled
  features/admin/blocking_login_for_disabled_administrators.feature
  src/Sylius/Behat/Context/Api/Admin/LoginContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
  src/Sylius/Behat/Context/Setup/AdminUserContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/admin/security.yml
  src/Sylius/Behat/Resources/config/suites/ui/admin/security.yml
  src/Sylius/Component/Core/Model/AdminUser.php
Labels: Bug

#14808 Fix url in links
  docs/getting-started-with-sylius/deployment.rst
Labels: Documentation

#14805 Remove possibility to add Stripe as a payment method when package is missing
  composer-require-checker.json
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/UnregisterStripeGatewayTypePass.php
  src/Sylius/Bundle/PayumBundle/SyliusPayumBundle.php
Labels: Bug

#14801 Add a missing orders prefix to routes in Admin Panel
  UPGRADE-1.12.md
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
Labels: Maintenance, Admin, Bug

#14813 [Shop] Fix displaying discount on list view when original price is lower than current
  features/product/viewing_products/viewing_different_discounted_price_for_different_product_variants.feature
  features/product/viewing_products/viewing_product_price_on_products_list.feature
  features/product/viewing_products/viewing_products_discounted_price.feature
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Box/_content.html.twig
Labels: UX, Shop, Bug

#14818 Improve SEO
  docs/_themes/sylius_rtd_theme/layout.html
  docs/book/contributing/documentation/format.rst
  docs/book/contributing/documentation/standards.rst
  docs/conf.py
  docs/requirements.txt
Labels: Documentation

#14822 [CI] Remove PHP 8.2 from packages tests of the unmaintained Swiftmailer
  .github/workflows/matrix.json
Labels: Maintenance, Bug, CI

#14824 [Orders][API] Change cart item delete HTTP response code to 204
  src/Sylius/Bundle/ApiBundle/Controller/DeleteOrderItemAction.php
  tests/Api/Shop/OrdersTest.php
Labels: API, Bug

#14798 Reorder order's sidebar in admin
  src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
Labels: Feature, UX, Admin

#14763 [Documentation][Cookbook] Add Vue Storefront installation guide
  docs/cookbook/index.rst
  docs/cookbook/shop/map.rst.inc
  docs/cookbook/shop/vue-storefront.rst
Labels: Documentation, Frontend

#13582 [Documentation] Fix overwriting templates path
  docs/book/themes/bootstrap-theme.rst
Labels: Documentation

#14826 Fix order by composite keys in OrderByIdentifierSqlWalker
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/SqlWalker/OrderByIdentifierSqlWalker.php
  tests/Functional/Doctrine/Dump/CompositeKeysModel.php
  tests/Functional/OrderByIdentifierSqlWalkerTest.php
Labels: Bug

#14811 Cover managing the tax rates in API
  features/taxation/managing_tax_rates/adding_tax_rate.feature
  features/taxation/managing_tax_rates/deleting_multiple_tax_rates.feature
  features/taxation/managing_tax_rates/deleting_tax_rate.feature
  features/taxation/managing_tax_rates/editing_tax_rate.feature
  features/taxation/managing_tax_rates/tax_rate_unique_code_validation.feature
  features/taxation/managing_tax_rates/tax_rate_validation.feature
  features/taxation/managing_tax_rates/tax_rates_filtration/filtering_tax_rates_by_end_date.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxRatesContext.php
  src/Sylius/Behat/Context/Api/Resources.php
  src/Sylius/Behat/Page/Admin/TaxRate/UpdatePage.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites.yml
  src/Sylius/Behat/Resources/config/suites/api/taxation/managing_tax_rates.yml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
  tests/Api/Admin/TaxRatesTest.php
  tests/Api/DataFixtures/ORM/tax_rates.yaml
  tests/Api/Responses/Expected/admin/tax_rate/get_tax_rate_response.json
  tests/Api/Responses/Expected/admin/tax_rate/get_tax_rates_response.json
  tests/Api/Responses/Expected/admin/tax_rate/patch_tax_rate_response.json
  tests/Api/Responses/Expected/admin/tax_rate/post_tax_rate_response.json
  tests/Api/Responses/Expected/admin/tax_rate/put_tax_rate_response.json
Labels: Feature, API

#11121 Fixed: Calculator at TaxRate fixtures
  tests/DataFixtures/ORM/resources/tax_rates.yml
Labels: Potential Bug, Do not stale
