Repository Sylius/Sylius, pull requests merged in 2023-09, with the labels that each got.

#15254 Deprecate unused ProductOptionChoiceType
  UPGRADE-1.13.md
  src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionChoiceType.php
Labels: Maintenance

#15280 Prevent throwing 500 while finalizing an order when at least one item has become tracked
  features/order/managing_orders/handling_order_payment/finalizing_order_payment.feature
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Bundle/CoreBundle/EventListener/PaymentPreCompleteListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.en.yaml
Labels: Admin, Bug

#12894 Make CheckoutResolver fail safe
  UPGRADE-1.12.md
  src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
  src/Sylius/Bundle/CoreBundle/spec/Checkout/CheckoutResolverSpec.php
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
Labels: Maintenance, Shop, Bug

#15292 Provide autoconfiguration with attributes for ApiBundle
  src/Sylius/Bundle/ApiBundle/Attribute/AsCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/Attribute/AsDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Attribute/AsPaymentConfigurationProvider.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/SyliusApiExtensionTest.php
  src/Sylius/Bundle/ApiBundle/Tests/Stub/CommandDataTransformerStub.php
  src/Sylius/Bundle/ApiBundle/Tests/Stub/DocumentationModifierStub.php
  src/Sylius/Bundle/ApiBundle/Tests/Stub/PaymentConfigurationProviderStub.php
Labels: DX, API

#15297 Provide autoconfiguration with attributes for PaymentBundle
  src/Sylius/Bundle/PaymentBundle/Attribute/AsPaymentMethodsResolver.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
  src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/SyliusPaymentExtensionTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/Stub/PaymentMethodsResolverStub.php
  src/Sylius/Bundle/PaymentBundle/composer.json
Labels: DX

#15301 Provide autoconfiguration with attributes for PayumBundle
  src/Sylius/Bundle/PayumBundle/Attribute/AsGatewayConfigurationType.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
  src/Sylius/Bundle/PayumBundle/Tests/DependencyInjection/SyliusPayumExtensionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Stub/GatewayConfigurationTypeStub.php
  src/Sylius/Bundle/PayumBundle/composer.json
Labels: DX

#15293 Provide autoconfiguration with attributes for CoreBundle
  src/Sylius/Bundle/CoreBundle/Attribute/AsCatalogPromotionApplicatorCriteria.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsCatalogPromotionPriceCalculator.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsEntityObserver.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsOrderItemUnitsTaxesApplicator.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsOrderItemsTaxesApplicator.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsProductVariantMapProvider.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsTaxCalculationStrategy.php
  src/Sylius/Bundle/CoreBundle/Attribute/AsUriBasedSectionResolver.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/CatalogPromotionApplicatorCriteriaStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/CatalogPromotionPriceCalculatorStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/EntityObserverStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/OrderItemUnitsTaxesApplicatorStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/OrderItemsTaxesApplicatorStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/ProductVariantMapProviderStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/TaxCalculationStrategyStub.php
  src/Sylius/Bundle/CoreBundle/Tests/Stub/UriBasedSectionResolverStub.php
Labels: DX

#15294 Provide autoconfiguration with attributes for CurrencyBundle
  src/Sylius/Bundle/CurrencyBundle/Attribute/AsCurrencyContext.php
  src/Sylius/Bundle/CurrencyBundle/DependencyInjection/SyliusCurrencyExtension.php
  src/Sylius/Bundle/CurrencyBundle/Tests/DependencyInjection/SyliusCurrencyExtensionTest.php
  src/Sylius/Bundle/CurrencyBundle/Tests/Stub/CurrencyContextStub.php
  src/Sylius/Bundle/CurrencyBundle/composer.json
Labels: DX

#15296 Improve autoconfiguration with attributes for OrderBundle
  src/Sylius/Bundle/OrderBundle/Attribute/AsCartContext.php
  src/Sylius/Bundle/OrderBundle/Attribute/AsOrderProcessor.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
Labels: DX

#15298 Improve autoconfiguration with attributes for ProductBundle
  src/Sylius/Bundle/ProductBundle/Attribute/AsProductVariantResolver.php
  src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
  src/Sylius/Bundle/ProductBundle/composer.json
Labels: DX

#15304 Provide autoconfiguration with attributes for TaxationBundle
  src/Sylius/Bundle/TaxationBundle/Attribute/AsTaxCalculator.php
  src/Sylius/Bundle/TaxationBundle/DependencyInjection/SyliusTaxationExtension.php
  src/Sylius/Bundle/TaxationBundle/Tests/DependencyInjection/SyliusTaxationExtensionTest.php
  src/Sylius/Bundle/TaxationBundle/Tests/Stub/TaxCalculatorStub.php
  src/Sylius/Bundle/TaxationBundle/composer.json
Labels: DX

#15303 Provide autoconfiguration with attributes for ShippingBundle
  src/Sylius/Bundle/ShippingBundle/Attribute/AsShippingCalculator.php
  src/Sylius/Bundle/ShippingBundle/Attribute/AsShippingMethodResolver.php
  src/Sylius/Bundle/ShippingBundle/Attribute/AsShippingMethodRuleChecker.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/SyliusShippingExtension.php
  src/Sylius/Bundle/ShippingBundle/Tests/DependencyInjection/SyliusShippingExtensionTest.php
  src/Sylius/Bundle/ShippingBundle/Tests/Stub/ShippingCalculatorStub.php
  src/Sylius/Bundle/ShippingBundle/Tests/Stub/ShippingMethodResolverStub.php
  src/Sylius/Bundle/ShippingBundle/Tests/Stub/ShippingMethodRuleCheckerStub.php
  src/Sylius/Bundle/ShippingBundle/composer.json
Labels: DX

#15302 Provide autoconfiguration with attributes for PromotionBundle
  src/Sylius/Bundle/PromotionBundle/Attribute/AsPromotionAction.php
  src/Sylius/Bundle/PromotionBundle/Attribute/AsPromotionCouponEligibilityChecker.php
  src/Sylius/Bundle/PromotionBundle/Attribute/AsPromotionEligibilityChecker.php
  src/Sylius/Bundle/PromotionBundle/Attribute/AsPromotionRuleChecker.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/SyliusPromotionExtensionTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/Stub/PromotionActionStub.php
  src/Sylius/Bundle/PromotionBundle/Tests/Stub/PromotionCouponEligibilityCheckerStub.php
  src/Sylius/Bundle/PromotionBundle/Tests/Stub/PromotionEligibilityCheckerStub.php
  src/Sylius/Bundle/PromotionBundle/Tests/Stub/PromotionRuleCheckerStub.php
  src/Sylius/Bundle/PromotionBundle/composer.json
Labels: DX

#15299 Provide autoconfiguration with attributes for AttributeBundle
  src/Sylius/Bundle/AttributeBundle/Attribute/AsAttributeType.php
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/SyliusAttributeExtension.php
  src/Sylius/Bundle/AttributeBundle/Tests/DependencyInjection/SyliusAttributeExtensionTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Stub/AttributeTypeStub.php
  src/Sylius/Bundle/AttributeBundle/composer.json
Labels: DX

#15300 Provide autoconfiguration with attributes for ChannelBundle
  src/Sylius/Bundle/ChannelBundle/Attribute/AsChannelContext.php
  src/Sylius/Bundle/ChannelBundle/Attribute/AsRequestBasedChannelResolver.php
  src/Sylius/Bundle/ChannelBundle/DependencyInjection/SyliusChannelExtension.php
  src/Sylius/Bundle/ChannelBundle/Tests/DependencyInjection/SyliusChannelExtensionTest.php
  src/Sylius/Bundle/ChannelBundle/Tests/Stub/ChannelContextStub.php
  src/Sylius/Bundle/ChannelBundle/Tests/Stub/RequestBestChannelResolverStub.php
  src/Sylius/Bundle/ChannelBundle/composer.json
Labels: DX

#15267 [Maintenance] Update dev symfony version to 5.4.*
  composer.json
Labels: Maintenance

#15289 Enable Sylius API for app environments
  config/packages/_sylius.yaml
Labels: Environment

#15264 Cart promotion Action Update
  docs/book/orders/cart-promotions.rst
Labels: Documentation

#15305 Add missing admin:taxon:update group to TaxonTranslation's locale field
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
Labels: API

#15272 Fix "jumping" taxons while moving up or down
  UPGRADE-1.12.md
  features/taxonomy/managing_taxons/reordering_taxon.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
  src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
  src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
  src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-taxon.js
  src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig
  src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
Labels: Maintenance, Admin, Bug

#15268 Fix configuring amount for cart promotions item percentage discount actions
  features/promotion/managing_promotions/adding_promotion_with_action.feature
  features/promotion/managing_promotions/seeing_correct_percantage_discounts_while_editing_promotion_with_action_and_decimal_places.feature
  src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
  src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php
  src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitPercentageDiscountConfigurationType.php
Labels: Admin, Bug

#15290 Add a note about payment-related events
  docs/book/orders/payments.rst
Labels: Documentation

#15307 Add a deprecation for the sylius_admin_ajax_taxon_move route
  UPGRADE-1.13.md
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
  src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php
Labels: Maintenance, Admin

#15277 Prevent removing product/taxon if it is already used in promotion rule
  UPGRADE-1.12.md
  features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_product.feature
  features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_taxon.feature
  features/promotion/managing_promotions/prevent_from_removing_products_that_are_used_in_promotion_rules.feature
  features/promotion/managing_promotions/prevent_from_removing_taxons_that_are_used_in_promotion_rules.feature
  src/Sylius/Behat/Context/Api/Admin/RemovingProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/RemovingProductContext.php
  src/Sylius/Behat/Context/Ui/Admin/RemovingTaxonContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/api/promotion/managing_promotions.yml
  src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductDeletionEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/ProductDeletionEventSubscriberSpec.php
  src/Sylius/Bundle/CoreBundle/EventListener/ProductDeletionListener.php
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/ProductDeletionListenerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/EventListener/TaxonDeletionListenerSpec.php
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
  src/Sylius/Component/Core/Promotion/Checker/ProductInPromotionRuleChecker.php
  src/Sylius/Component/Core/Promotion/Checker/ProductInPromotionRuleCheckerInterface.php
  src/Sylius/Component/Core/Promotion/Checker/TaxonInPromotionRuleChecker.php
  src/Sylius/Component/Core/Promotion/Checker/TaxonInPromotionRuleCheckerInterface.php
  src/Sylius/Component/Core/spec/Promotion/Checker/ProductInPromotionRuleCheckerSpec.php
  src/Sylius/Component/Core/spec/Promotion/Checker/TaxonInPromotionRuleCheckerSpec.php
Labels: Maintenance, API, Bug

#15281 Only show "View More" button when there are accepted reviews
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/Reviews/_viewMore.html.twig
Labels: Shop

#15278 Deprecate ContainsProductRuleUpdater and TotalOfItemsFromTaxonRuleUpdater
  UPGRADE-1.13.md
  src/Sylius/Component/Core/Promotion/Updater/Rule/ContainsProductRuleUpdater.php
  src/Sylius/Component/Core/Promotion/Updater/Rule/TotalOfItemsFromTaxonRuleUpdater.php
Labels: Maintenance

#15309 Update the banner in the README.md
  README.md
Labels: Maintenance

#15317 [doc] plugin naming - new plugin structure
  docs/book/plugins/guide/naming.rst
Labels: Documentation

#15263 Update default Rules of cart promotion
  docs/book/orders/cart-promotions.rst
Labels: Documentation

#15311 [API] fix prefix url on locale api path
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
Labels: API

#15312 Prepare the 2.0 branch
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_packages-unstable.yaml
  .github/workflows/ci_packages.yaml
  .github/workflows/matrix.json
  RoboFile.php
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API

#15314 Remove gulp
  .github/workflows/ci_e2e-custom.yaml
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  .gitignore
  UPGRADE-2.0.md
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  gulpfile.babel.js
  package.json
  psalm.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_logo.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_scripts.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_styles.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_mainImage.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_media.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_mainImage.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Security/_content.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Security/_logo.html.twig
  src/Sylius/Bundle/AdminBundle/gulpfile.babel.js
  src/Sylius/Bundle/AdminBundle/test/config/packages/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/CoreBundle/Resources/views/Email/adminPasswordReset.html.twig
  src/Sylius/Bundle/CoreBundle/Resources/views/Email/layout.html.twig
  src/Sylius/Bundle/CoreBundle/test/config/packages/config.yaml
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_header.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_banner.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Layout/Footer/Grid/_plus.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Layout/Header/_logo.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_scripts.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/error.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/error403.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/error404.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/error500.html.twig
  src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
  src/Sylius/Bundle/UiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/SyliusUiExtensionTest.php
Labels: DX, Maintenance, Admin, Shop, API

#15322 Add optional message to API cannot be removed exceptions
  src/Sylius/Bundle/ApiBundle/Exception/ProductCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProvinceCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ShippingMethodCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ZoneCannotBeRemoved.php
Labels: DX, API

#15327 Bump Symfony dependencies' versions
  .github/workflows/matrix.json
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API

#15325 Replace EntityManager type-hints in the constructors with EntityManagerInterface
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/RemoveCatalogPromotionHandler.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/RemoveInactiveCatalogPromotionHandler.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AttributeRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductOptionRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PromotionRepository.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/CommandHandler/RemoveCatalogPromotionHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/CommandHandler/RemoveInactiveCatalogPromotionHandlerSpec.php
Labels: DX

#15328 Add missing method on interface for shop based cart context
  UPGRADE-2.0.md
  src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
  src/Sylius/Component/Order/Context/ResettableCartContextInterface.php
Labels: Maintenance

#15330 Add upmerging from 1.13 to 2.0
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance, CI

#15324 Prevent from removing taxon that is in use by a promotion rule
  UPGRADE-API-1.13.md
  features/promotion/managing_promotions/prevent_from_removing_taxons_that_are_used_in_promotion_rules.feature
  src/Sylius/Behat/Context/Api/Admin/RemovingTaxonContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites/api/promotion/managing_promotions.yml
  src/Sylius/Bundle/ApiBundle/EventSubscriber/TaxonDeletionEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/Exception/TaxonCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/ProductDeletionEventSubscriberSpec.php
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/TaxonDeletionEventSubscriberSpec.php
Labels: Maintenance, API, Bug

#12543 Change default Liip loader and resolver names
  UPGRADE-2.0.md
  config/packages/liip_imagine.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
Labels: DX, Maintenance, Docker

#15315 Provide the State Machine abstraction
  composer.json
  config/packages/workflow.yaml
  psalm.xml
  src/Sylius/Bundle/AdminBundle/test/config/packages/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/state_machines.xml
  src/Sylius/Bundle/CoreBundle/StateMachine/CompositeStateMachine.php
  src/Sylius/Bundle/CoreBundle/StateMachine/Exception/StateMachineExecutionException.php
  src/Sylius/Bundle/CoreBundle/StateMachine/StateMachineInterface.php
  src/Sylius/Bundle/CoreBundle/StateMachine/SymfonyWorkflowAdapter.php
  src/Sylius/Bundle/CoreBundle/StateMachine/Transition.php
  src/Sylius/Bundle/CoreBundle/StateMachine/TransitionInterface.php
  src/Sylius/Bundle/CoreBundle/StateMachine/WinzouStateMachineAdapter.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/StateMachineCompositeTest.php
  src/Sylius/Bundle/CoreBundle/Twig/StateMachineExtension.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/spec/StateMachine/CompositeStateMachineSpec.php
  src/Sylius/Bundle/CoreBundle/spec/StateMachine/SymfonyWorkflowAdapterSpec.php
  src/Sylius/Bundle/CoreBundle/spec/StateMachine/WinzouStateMachineAdapterSpec.php
  src/Sylius/Bundle/CoreBundle/test/config/packages/config.yaml
  src/Sylius/Bundle/CoreBundle/test/config/packages/state_machine.yaml
  src/Sylius/Bundle/CoreBundle/test/src/Model/BlogPost.php
  src/Sylius/Bundle/CoreBundle/test/src/Model/Comment.php
  symfony.lock
Labels: DX, Admin, API

#15335 Minor typo fix in deprecation message in ZoneChoiceType
  src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneChoiceType.php
Labels: DX

#15333 [CoreBundle] Add missed deprecation block
  UPGRADE-1.13.md
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
Labels: Maintenance

#15343 [CI] Fix logs uploading
  .github/workflows/matrix.json
  composer.json
Labels: Maintenance, CI

#15346 [Maintenance] Deprecate `OrderItemsSubtotalCalculatorInterface`
  UPGRADE-1.13.md
  psalm.xml
  src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculatorInterface.php
  src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
  src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php
Labels: Maintenance, Shop

#15351 [AdminBundle] Corrected deprecation messages
  src/Sylius/Bundle/AdminBundle/Resources/views/Email/orderConfirmation.html.twig
  src/Sylius/Bundle/ShopBundle/Resources/views/Email/orderConfirmation.html.twig
Labels: DX, Maintenance, Admin, Shop

#15338 [CoreBundle] Move the PaymentFixture class in a proper namespace and deprecate other code
  UPGRADE-1.13.md
  phpstan.neon.dist
  src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
  src/Sylius/Bundle/CoreBundle/Fixture/PaymentFixture.php
  src/Sylius/Bundle/CoreBundle/Provider/SessionProvider.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
Labels: DX, Maintenance, Admin

#15337 [ProductBundle] Remove deprecations
  phpstan-baseline.neon
  src/Sylius/Bundle/ProductBundle/Controller/ProductSlugController.php
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php
  src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionChoiceType.php
  src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueChoiceType.php
  src/Sylius/Bundle/ProductBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/GenerateProductVariantsSubscriberSpec.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
Labels: DX, Maintenance

#15336 [CoreBundle] Remove deprecations
  UPGRADE-2.0.md
  ecs.php
  phpstan-baseline.neon
  psalm.xml
  src/Sylius/Bundle/CoreBundle/Application/Kernel.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Command/RemoveInactiveCatalogPromotion.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/RemoveInactiveCatalogPromotionHandler.php
  src/Sylius/Bundle/CoreBundle/CatalogPromotion/Processor/CatalogPromotionRemovalProcessor.php
  src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
  src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
  src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/CancelOrderStateMachineCallbackPass.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/SyliusPriceHistoryLegacyAliasesPass.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
  src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
  src/Sylius/Bundle/CoreBundle/Installer/Requirement/FilesystemRequirements.php
  src/Sylius/Bundle/CoreBundle/Provider/SessionProvider.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/command_handlers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
  src/Sylius/Bundle/CoreBundle/Storage/CartSessionStorage.php
  src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
  src/Sylius/Bundle/CoreBundle/Templating/Helper/ProductVariantsPricesHelper.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/BackwardsCompatibility/CancelOrderStateMachineCallbackPassTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/SyliusPriceHistoryLegacyAliasesPassTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/CoreBundle/Twig/ProductVariantsPricesExtension.php
  src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php
  src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/CommandHandler/RemoveInactiveCatalogPromotionHandlerSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/ProductVariantsPricesHelperSpec.php
  src/Sylius/Bundle/CoreBundle/test/src/Kernel.php
Labels: DX, Maintenance

#15339 [AdminBundle] Remove deprecations
  src/Sylius/Bundle/AdminBundle/Action/Account/RenderResetPasswordPageAction.php
  src/Sylius/Bundle/AdminBundle/Action/Account/RequestPasswordResetAction.php
  src/Sylius/Bundle/AdminBundle/Action/Account/ResetPasswordAction.php
  src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/Action/ResendShipmentConfirmationEmailAction.php
  src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
  src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/sylius/sylius_mailer.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.cs.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de_CH.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fr.yml
  src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_chart.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Email/orderConfirmation.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_channelLinksWidget.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_channelLinks.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_flashes.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_logo.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_notification.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_scripts.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_search.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_security.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_styles.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/_support.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
  src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php
  src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php
Labels: DX, Maintenance, Admin

#15366 [Api][Attribute] Add types enum to product attribute schema
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/AttributeTypeDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
Labels: API

#15364 [Component/Core] Deprecate ProductAwareRuleUpdaterInterface
  UPGRADE-1.13.md
  psalm.xml
  src/Sylius/Component/Core/Promotion/Updater/Rule/ProductAwareRuleUpdaterInterface.php
Labels: Maintenance

#15275 Optimize matching zones to a given address
  src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php
  src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest.php
  src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml
  src/Sylius/Bundle/AddressingBundle/Tests/Repository/ZoneRepositoryTest.php
  src/Sylius/Bundle/AddressingBundle/Tests/Repository/ZoneRepositoryTest/fixtures.yaml
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AddressingBundle/phpunit.xml.dist
  src/Sylius/Bundle/AddressingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/AddressingBundle/test/app/config/parameters.yml
  src/Sylius/Bundle/AddressingBundle/test/var/db.sql
  src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php
  src/Sylius/Component/Addressing/Repository/ZoneRepositoryInterface.php
  src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php
Labels: Performance

#15369 [CoreBundle] Removal of the rest of deprecated code
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
  src/Sylius/Bundle/AttributeBundle/Validator/Constraints/AttributeTypeValidator.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/AttributeTypeValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/Fixture/PaymentFixture.php
Labels: DX, Maintenance

#15373 [Api] Mark bulk delete scenarios as @no-api
  features/addressing/managing_zones/deleting_multiple_zones.feature
  features/channel/managing_channels/deleting_multiple_channels.feature
  features/currency/managing_exchange_rates/deleting_multiple_exchange_rates.feature
  features/payment/managing_payment_methods/deleting_multiple_payment_methods.feature
  features/product/managing_product_association_types/deleting_multiple_product_association_types.feature
  features/product/managing_product_options/deleting_multiple_product_options.feature
  features/product/managing_product_reviews/deleting_multiple_product_reviews.feature
  features/product/managing_product_variants/deleting_multiple_product_variants.feature
  features/product/managing_products/deleting_multiple_products.feature
  features/promotion/managing_coupons/deleting_multiple_coupons.feature
  features/promotion/managing_promotions/deleting_multiple_promotions.feature
  features/shipping/managing_shipping_categories/deleting_multiple_shipping_categories.feature
  features/shipping/managing_shipping_methods/deleting_multiple_shipping_methods.feature
  features/taxation/managing_tax_categories/deleting_multiple_tax_categories.feature
  features/taxation/managing_tax_rates/deleting_multiple_tax_rates.feature
  features/user/managing_administrators/deleting_multiple_administrators.feature
  features/user/managing_customer_groups/deleting_multiple_customer_groups.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductAssociationTypesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxRatesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php
Labels: Maintenance, API

#15345 [Maintenance] Remove components' deprecations
  UPGRADE-2.0.md
  phpstan-baseline.neon
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChooseShippingMethodHandlerSpec.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Component/Channel/Context/ChannelNotFoundException.php
  src/Sylius/Component/Channel/Repository/ChannelRepositoryInterface.php
  src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
  src/Sylius/Component/Shipping/Checker/ShippingMethodEligibilityChecker.php
  src/Sylius/Component/Shipping/Checker/ShippingMethodEligibilityCheckerInterface.php
  src/Sylius/Component/Shipping/Resolver/ShippingMethodsResolver.php
  src/Sylius/Component/Shipping/ShipmentUnitTransitions.php
  src/Sylius/Component/Shipping/spec/Checker/ShippingMethodEligibilityCheckerSpec.php
  src/Sylius/Component/Taxation/Resolver/TaxRateResolver.php
  src/Sylius/Component/User/Model/User.php
  src/Sylius/Component/User/Model/UserInterface.php
  src/Sylius/Component/User/Security/PasswordUpdater.php
  src/Sylius/Component/User/Security/UserPasswordEncoderInterface.php
  src/Sylius/Component/User/Security/UserPbkdf2PasswordEncoder.php
  src/Sylius/Component/User/spec/Security/PasswordUpdaterSpec.php
  src/Sylius/Component/User/spec/Security/UserPbkdf2PasswordEncoderSpec.php
Labels: DX, Maintenance, API

#15376 Component core deprecate order interface methods
  UPGRADE-1.13.md
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Component/Core/Model/OrderInterface.php
Labels: DX, Maintenance

#15262 [Maintenance] Deprecate using `parentId` in TaxonSlugController
  UPGRADE-1.13.md
  src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonSlugController.php
Labels: Maintenance

#15380 [ShippingBundle] Change deprecated Calendar class
  UPGRADE-1.13.md
  phpstan.neon.dist
  psalm.xml
  src/Sylius/Bundle/ShippingBundle/Provider/Calendar.php
  src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonSlugController.php
Labels: DX, Maintenance

#15372 [Bunnyshell] Bump the PHP version to 8.2 in the php Dockerfile
  .bunnyshell/docker/php/Dockerfile
Labels: Docker
