Repository Sylius/Sylius, pull requests merged in 2024-10, with the labels that each got.

#17059 [API] Make Province endpoints to be subresources of Country
  src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Api/Resources.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/Province.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/Province.xml
  src/Sylius/Bundle/ApiBundle/Tests/Resolver/PathPrefixBasedOperationResolverTest.php
  tests/Api/Admin/ProvincesTest.php
  tests/Api/Responses/admin/country/get_countries_response.json
  tests/Api/Responses/admin/country/get_provinces_response.json
  tests/Api/Responses/admin/country/post_country_response.json
  tests/Api/Responses/admin/country/put_country_response.json
  tests/Api/Responses/admin/province/get_province_response.json
  tests/Api/Responses/admin/province/put_province_response.json
  tests/Api/Responses/shop/country/get_countries_from_channel_response.json
  tests/Api/Responses/shop/country/get_countries_response.json
  tests/Api/Responses/shop/country/get_country_response.json
  tests/Api/Responses/shop/province/get_province_response.json
  tests/Api/Shop/ProvincesTest.php
Labels: API

#17048 Add possibility to remove option values from Product Option
  features/admin/product/managing_product_options/managing_values_of_product_option.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php
  src/Sylius/Behat/Element/Admin/ProductOption/FormElement.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/suites/api/product/managing_product_options.yml
  src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_options.yml
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteExceptionListener.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteListener.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_option/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_option/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/spec/EventListener/ResourceDeleteExceptionListenerSpec.php
  src/Sylius/Bundle/AdminBundle/spec/EventListener/ResourceDeleteListenerSpec.php
  src/Sylius/Bundle/AdminBundle/templates/product_option/form/sections/values/value/button_delete.html.twig
  src/Sylius/Bundle/ApiBundle/Exception/ProductOptionValueCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ProductOption.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/state_processors.xml
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/PaymentMethod/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ProductAttribute/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ProductOption/PersistProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ShippingMethod/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Zone/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/PaymentMethod/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ProductAttribute/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ProductOption/PersistProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ShippingMethod/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Zone/RemoveProcessorSpec.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
  src/Sylius/Bundle/CoreBundle/EventListener/ProductOptionValueDeletionListener.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20240926122944.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20240927155535.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/ProductOptionValueDeletionListenerSpec.php
  src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
  src/Sylius/Component/Core/Exception/ResourceDeleteException.php
  src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php
Labels: Feature, Admin

#17061 Deprecate templating helpers
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/CoreBundle/Templating/Helper/CheckoutStepsHelper.php
  src/Sylius/Bundle/CoreBundle/Templating/Helper/PriceHelper.php
  src/Sylius/Bundle/CoreBundle/Templating/Helper/VariantResolverHelper.php
  src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/VariantResolverExtension.php
  src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
  src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
  src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
  src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
  src/Sylius/Bundle/InventoryBundle/Templating/Helper/InventoryHelper.php
  src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php
  src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
  src/Sylius/Bundle/MoneyBundle/Resources/config/services.xml
  src/Sylius/Bundle/MoneyBundle/Resources/config/services/integrations/currency.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/OrderBundle/Templating/Helper/AdjustmentsHelper.php
  src/Sylius/Bundle/OrderBundle/Twig/AggregateAdjustmentsExtension.php
Labels: Maintenance

#17071 [Composer] Bump sylius/mailer-bundle to 2.1 version
  .github/workflows/ci_e2e-custom.yaml
  composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
Labels: Maintenance, Dependencies

#17073 [Maintenance] Fix packages in definitions of deprecated services + add missing notes
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php
  src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/MoneyBundle/Resources/config/services.xml
  src/Sylius/Bundle/MoneyBundle/Resources/config/services/integrations/currency.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
Labels: Maintenance

#17076 Deprecate ResourceDeleteSubcriber
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
Labels: Maintenance

#17077 Add note about ResourceDeleteSubcriber class being removed in 2.0
  UPGRADE-2.0.md
Labels: Maintenance

#17075 Remove deprecated templating helpers and symfony/templating dependency
  UPGRADE-2.0.md
  composer.json
  src/Sylius/Bundle/CoreBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/CoreBundle/Templating/Helper/CheckoutStepsHelper.php
  src/Sylius/Bundle/CoreBundle/Templating/Helper/PriceHelper.php
  src/Sylius/Bundle/CoreBundle/Templating/Helper/VariantResolverHelper.php
  src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php
  src/Sylius/Bundle/CoreBundle/Twig/VariantResolverExtension.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/CheckoutStepsHelperSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/PriceHelperSpec.php
  src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/VariantResolverHelperSpec.php
  src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
  src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
  src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
  src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
  src/Sylius/Bundle/InventoryBundle/Templating/Helper/InventoryHelper.php
  src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/spec/Templating/Helper/InventoryHelperSpec.php
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
  src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php
  src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
  src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/OrderBundle/Templating/Helper/AdjustmentsHelper.php
  src/Sylius/Bundle/OrderBundle/Twig/AggregateAdjustmentsExtension.php
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/OrderBundle/spec/Templating/Helper/AdjustmentsHelperSpec.php
  src/Sylius/Bundle/UiBundle/composer.json
  symfony.lock
Labels: Maintenance, Dependencies

#17088 Fix name of argument in deprecation trigger for PriceExtension
  src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php
Labels: Maintenance

#17084 Add live components routes for the admin and shop section
  config/routes/ux_live_component.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/customer.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/dashboard.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/order.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_attribute.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_option.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/shipment.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/taxon.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/zone.xml
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/Navbar/ShopPreviewComponent.php
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/account.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/account.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/cart.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/checkout.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/product.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/product_review.xml
  src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LiveComponentTagPass.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/Compiler/LiveComponentTagPassTest.php
  src/Sylius/Bundle/UiBundle/Tests/DependencyInjection/ConfigurationTest.php
Labels: Enhancement, DX

#17096 [AttributeBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/AttributeBundle/Resources/config/services.xml
  src/Sylius/Bundle/AttributeBundle/Resources/config/services/attribute_types.xml
Labels: Maintenance

#17095 [AddressingBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services/checkers.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/AddressingBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
Labels: Maintenance

#17098 [ChannelBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php
  src/Sylius/Bundle/ChannelBundle/Resources/config/services.xml
  src/Sylius/Bundle/ChannelBundle/Tests/DependencyInjection/SyliusChannelExtensionTest.php
Labels: Maintenance

#17070 Fix comparison of order items
  src/Sylius/Component/Core/Model/OrderItem.php
Labels: Bug

#17085 [API] Refactor commands in ApiBundle
  src/Sylius/Bundle/ApiBundle/Attribute/TokenAware.php
  src/Sylius/Bundle/ApiBundle/Command/Account/ResetPassword.php
  src/Sylius/Bundle/ApiBundle/Command/Account/SendAccountRegistrationEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Account/SendResetPasswordEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Account/SendShopUserVerificationEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Account/VerifyShopUser.php
  src/Sylius/Bundle/ApiBundle/Command/Admin/Account/ResetPassword.php
  src/Sylius/Bundle/ApiBundle/Command/Cart/BlameCart.php
  src/Sylius/Bundle/ApiBundle/Command/Cart/InformAboutCartRecalculation.php
  src/Sylius/Bundle/ApiBundle/Command/Checkout/SendOrderConfirmation.php
  src/Sylius/Bundle/ApiBundle/Command/Checkout/SendShipmentConfirmationEmail.php
  src/Sylius/Bundle/ApiBundle/Command/Customer/RemoveShopUser.php
  src/Sylius/Bundle/ApiBundle/Command/Promotion/GeneratePromotionCoupon.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Account/SendResetPasswordEmailHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/InformAboutCartRecalculationHandler.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/SendOrderConfirmationHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/AdminUserPassword.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/CustomerPassword.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/CustomerVerification.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/admin/state_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/context_builders.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/shop/state_providers.xml
  src/Sylius/Bundle/ApiBundle/StateProvider/Admin/AdminUser/ResetPasswordProvider.php
  src/Sylius/Bundle/ApiBundle/StateProvider/Shop/ShopUser/ResetPasswordProvider.php
  src/Sylius/Bundle/ApiBundle/StateProvider/Shop/ShopUser/VerifyShopUserProvider.php
  src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/ResetPasswordHandlerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProvider/Admin/AdminUser/ResetPasswordProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProvider/Shop/ShopUser/ResetPasswordProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProvider/Shop/ShopUser/VerifyShopUserProviderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/AdminResetPasswordTokenNonExpiredValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/CheckoutCompletionValidatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ConfirmResetPasswordValidatorSpec.php
  src/Sylius/Bundle/CoreBundle/Command/Admin/Account/ResetPassword.php
  src/Sylius/Bundle/CoreBundle/spec/CommandHandler/Admin/Account/ResetPasswordHandlerSpec.php
Labels: DX, API

#17120 Add gedmo/doctrine-extensions conflict
  CONFLICTS.md
  composer.json
Labels: Maintenance, Dependencies, Bug

#17106 [Theming] Move ThemeBundle dependency to ShopBundle
  UPGRADE-2.0.md
  composer.json
  src/Sylius/Bundle/AdminBundle/templates/channel/form/sections/look_and_feel/theme.html.twig
  src/Sylius/Bundle/AdminBundle/test/config/bundles.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
  src/Sylius/Bundle/ShopBundle/Form/Extension/ChannelTypeExtension.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/context.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/sylius_admin.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/sylius_admin/form.xml
  src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/SyliusShopExtensionTest.php
  src/Sylius/Bundle/ShopBundle/Theme/ChannelBasedThemeContext.php
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/ShopBundle/spec/Theme/ChannelBasedThemeContextSpec.php
Labels: Maintenance, Shop, Dependencies

#17121 Add conflict to gedmo/doctrine-extensions in ApiBundle
  src/Sylius/Bundle/ApiBundle/CONFLICTS.md
  src/Sylius/Bundle/ApiBundle/composer.json
Labels: Maintenance, API, Dependencies, Bug

#15950 [PaymentRequest] Automatically cancel all pending payment requests when the payment method gets changed
  features/hybrid/checkout/changing_payment_method/cancelling_payment_request_when_payment_method_is_changed.feature
  features/shop/checkout/paying_for_order/cancelling_payment_request_when_payment_method_is_changed.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentRequestsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Api/Shop/PaymentRequestContext.php
  src/Sylius/Behat/Context/Setup/PaymentRequestContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentRequestsContext.php
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Behat/Resources/config/suites/api/checkout/paying_for_order.yml
  src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
  src/Sylius/Bundle/PaymentBundle/Canceller/PaymentRequestCanceller.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
  src/Sylius/Bundle/PaymentBundle/Doctrine/ORM/PaymentRequestRepository.php
  src/Sylius/Bundle/PaymentBundle/EventListener/PaymentMethodChangeEventListener.php
  src/Sylius/Bundle/PaymentBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/canceller.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/SyliusPaymentExtensionTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/EventListener/PaymentMethodChangeEventListenerTest.php
  src/Sylius/Bundle/PaymentBundle/spec/Canceller/PaymentRequestCancellerSpec.php
  src/Sylius/Component/Payment/Canceller/PaymentRequestCancellerInterface.php
  src/Sylius/Component/Payment/Repository/PaymentRequestRepositoryInterface.php
Labels: Maintenance, API

#17086 [Behat] assigning ip address scenarios
  features/admin/order/managing_orders/assigning_customer_ip_address_to_placed_order.feature
  features/hybrid/checkout/assigning_customer_ip_address_to_placed_order.feature
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Context/Setup/OrderContext.php
  src/Sylius/Behat/Context/Setup/ShopSecurityContext.php
  src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
  src/Sylius/Behat/Page/Admin/Order/ShowPage.php
  src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
  src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/order/show.yaml
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/general/ip_address.html.twig
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml
  src/Sylius/Bundle/ShopBundle/EventListener/OrderCustomerIpListener.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderCustomerIpListenerSpec.php
  tests/Api/Responses/admin/order/get_order.json
Labels: Behat, API

#17128 [Maintenance] Remove swiftmailer leftovers
  docs/book/installation/installation.rst
  docs/cookbook/emails/mailer.rst
Labels: Documentation, Maintenance

#17122 [Composer] Bump minimal version of APIP 3.4 + related improvements
  composer.json
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Extractor/XmlResourceExtractor.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/XmlResourceExtractorCompilerPass.php
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/resources/Channel.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/api_platform/resources/Currency.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Tests/MergingConfigsTest.php
  src/Sylius/Bundle/ApiBundle/composer.json
Labels: API, Dependencies

#17111 [OrderBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Behat/Resources/config/services/contexts/domain.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
  src/Sylius/Bundle/OrderBundle/Console/Command/RemoveExpiredCartsCommand.php
  src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
  src/Sylius/Bundle/OrderBundle/Resources/config/app/state_machine.yml
  src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/integrations/doctrine/orm.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services/twig.xml
Labels: DX, Maintenance

#17130 Correct the parameter name for states that should be cancelled, when payment method is changed
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
  src/Sylius/Bundle/PaymentBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/canceller.xml
  src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/SyliusPaymentExtensionTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/EventListener/PaymentMethodChangeEventListenerTest.php
  src/Sylius/Bundle/PaymentBundle/spec/Canceller/PaymentRequestCancellerSpec.php
Labels: Enhancement

#17125 [LocaleBundle] Unification of service names - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
Labels: Maintenance

#17123 [CurrencyBundle] Unification of service names
  src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/product.xml
Labels: DX, Maintenance

#17124 [InventoryBundle] Unification of service names
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/SyliusInventoryExtension.php
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
Labels: DX, Maintenance

#17127 [MoneyBundle] Unification of service names
  src/Sylius/Bundle/MoneyBundle/Resources/config/services.xml
  src/Sylius/Bundle/MoneyBundle/Resources/config/services/integrations/currency.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/product.xml
Labels: DX, Maintenance

#17132 Create LICENSE_OF_TRADEMARK_AND_LOGO
  LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#17138 Remove winzouStateMachineBundle from packages' test applications to support ResourceBundle 1.12
  src/Sylius/Bundle/AddressingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/AttributeBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ChannelBundle/test/app/AppKernel.php
  src/Sylius/Bundle/CurrencyBundle/test/app/AppKernel.php
  src/Sylius/Bundle/CustomerBundle/test/app/AppKernel.php
  src/Sylius/Bundle/InventoryBundle/test/app/AppKernel.php
  src/Sylius/Bundle/LocaleBundle/test/app/AppKernel.php
  src/Sylius/Bundle/MoneyBundle/test/app/AppKernel.php
  src/Sylius/Bundle/OrderBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PaymentBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ProductBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php
  src/Sylius/Bundle/ShippingBundle/test/app/AppKernel.php
  src/Sylius/Bundle/TaxationBundle/test/app/AppKernel.php
  src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/AppKernel.php
  src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php
Labels: Maintenance, Dependencies

#17141 Update upgrade file
  UPGRADE-2.0.md
Labels: DX, Maintenance

#17112 [ProductBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Behat/Resources/config/services/contexts/domain.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Resources/config/services/contexts/ui.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/templating.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services/integrations/doctrine/orm.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services/validators.xml
Labels: DX, Maintenance

#17144 [Docs] Fix readthedocs configuration file
  docs/conf.py
  docs/requirements.txt
Labels: Documentation, Maintenance, Bug

#17140 [Maintenance] Resolve gedmo/doctrine-extension conflict
  CONFLICTS.md
  composer.json
Labels: Maintenance

#17126 [LocaleBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component.xml
Labels: Maintenance

#17142 [OrderBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
Labels: Maintenance

#17146 [ProductBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Compiler/DefaultProductVariantResolverCompilerPass.php
  src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ProductBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/ProductBundle/SyliusProductBundle.php
  src/Sylius/Bundle/ProductBundle/Tests/DependencyInjection/Compiler/DefaultProductVariantResolverCompilerPassTest.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component/product.xml
Labels: Maintenance

#17133 [PromotionBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/command_handlers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
  src/Sylius/Bundle/PromotionBundle/Controller/PromotionCouponController.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/criteria.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/eligibility_checkers.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/integrations/doctrine/orm.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
Labels: Maintenance

#17150 [Admin] Fix hardcoded hello
  src/Sylius/Bundle/AdminBundle/templates/shared/components/navbar/user.html.twig
Labels: Admin

#17147 [Composer] Bump Resource and Grid bundles to the last stable releases
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
  symfony.lock
Labels: Maintenance, Dependencies

#17148 [CI] Remove currently unneeded custom build
  .github/workflows/ci__full_1_12.yaml
  .github/workflows/ci__full_1_13.yaml
  .github/workflows/ci__full_2_0.yaml
  .github/workflows/ci__minimal.yaml
  .github/workflows/ci_e2e-custom.yaml
Labels: Maintenance, CI

#17139 [Composer] Remove conflict to doctrine/orm
  CONFLICTS.md
  UPGRADE-1.13.md
  UPGRADE-API-1.13.md
  composer.json
  phpstan-baseline.neon
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
  src/Sylius/Bundle/ReviewBundle/EventListener/ReviewChangeListener.php
  src/Sylius/Bundle/ReviewBundle/spec/EventListener/ReviewChangeListenerSpec.php
  src/Sylius/Bundle/TaxationBundle/composer.json
  tests/Api/DataFixtures/ORM/customer.yaml
Labels: Dependencies, Bug

#17152 [PromotionBundle] Unification of service names - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
Labels: Maintenance

#17087 Add applied coupon box
  src/Sylius/Behat/Context/Ui/Shop/CartContext.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
  src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Cart/FormComponent.php
  src/Sylius/Bundle/ShopBundle/templates/cart/index/form/sections/general/coupon.html.twig
  src/Sylius/Bundle/ShopBundle/templates/icons/trash.svg
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: UX, Shop

#17149 [Admin] Add image lightbox
  src/Sylius/Bundle/AdminBundle/Resources/assets/entrypoint.js
  src/Sylius/Bundle/AdminBundle/Resources/assets/scripts/spotlight.js
  src/Sylius/Bundle/AdminBundle/package.json
  src/Sylius/Bundle/AdminBundle/templates/product/show/content/page_body/media.html.twig
Labels: UX, Admin

#17153 [PromotionBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/CompositePromotionCouponEligibilityCheckerPass.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/CompositePromotionEligibilityCheckerPass.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterPromotionActionsPass.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterRuleCheckersPass.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/eligibility_checkers.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/PromotionBundle/Tests/Console/Command/GenerateCouponsCommandTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/CompositePromotionCouponEligibilityCheckerPassTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/CompositePromotionEligibilityCheckerPassTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterPromotionActionsPassTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterRuleCheckersPassTest.php
Labels: Maintenance

#17093 Create the "Services naming convention" ADR
  adr/2024_10_03_services_naming_convention.md
Labels: DX, Maintenance

#17064 Preventing Payment and Shipment Step Completion Without a Selected Method - Test Coverage
  features/shop/checkout/paying_for_order/preventing_payment_step_completion_without_a_selected_method.feature
  features/shop/checkout/shipping_order/preventing_shipping_step_completion_without_a_selected_method.feature
  src/Sylius/Behat/Client/ApiClientInterface.php
  src/Sylius/Behat/Client/ApiPlatformClient.php
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
  src/Sylius/Behat/Context/Setup/Checkout/AddressContext.php
  src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
  src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
  src/Sylius/Behat/Resources/config/services.xml
  src/Sylius/Behat/Resources/config/services/contexts/setup.xml
  src/Sylius/Behat/Service/Factory/AddressFactory.php
  src/Sylius/Behat/Service/Factory/AddressFactoryInterface.php
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/form/navigation.html.twig
Labels: Behat, Shop

#17159 [Shop] Add image lightbox
  src/Sylius/Bundle/ShopBundle/Resources/assets/entrypoint.js
  src/Sylius/Bundle/ShopBundle/Resources/assets/scripts/spotlight.js
  src/Sylius/Bundle/ShopBundle/package.json
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/images.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/images/main_image.html.twig
Labels: UX, Shop

#17169 Update README.md
  README.md
Labels: Maintenance

#17160 [API] Add documentation modifier for removing non-API routes
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/NotPrefixedRoutesRemovalDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Tests/OpenApi/Documentation/NotPrefixedRoutesRemovalDocumentationModifierTest.php
Labels: API, Bug

#17162 Fix session unavailable in locale context
  src/Sylius/Component/Core/Locale/Context/StorageBasedLocaleContext.php
  src/Sylius/Component/Core/spec/Locale/Context/StorageBasedLocaleContextSpec.php
Labels: Bug

#17176 Revert "[CI] Use default env in MySQL workflow"
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/matrix.json
Labels: Maintenance, CI

#17179 Improvements for Shipping and Payment steps in the Checkout
  features/shop/checkout/shipping_order/preventing_shipping_step_completion_without_a_selected_method.feature
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/form/navigation.html.twig
Labels: Shop, Bug

#17168 Depreciate PercentageDiscountActionConfigurationType and move to CoreBundle
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
Labels: Maintenance

#17157 [ReviewBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
  src/Sylius/Bundle/ReviewBundle/Resources/config/integrations/doctrine/orm.xml
  src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
Labels: Maintenance

#17167 [ShippingBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners/workflow/shipment.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/integrations/doctrine/orm.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/registry.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/validator.xml
Labels: Maintenance

#17186 [TaxonomyBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/integrations/doctrine/orm.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/tree_repository.xml
Labels: Maintenance

#17187 [UserBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
  src/Sylius/Bundle/UserBundle/Resources/config/services/integrations/doctrine/orm.xml
Labels: Maintenance

#17181 [UiBundle] Unification of service names and add deprecations
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/UiBundle/Console/Command/DebugTemplateEventCommand.php
  src/Sylius/Bundle/UiBundle/ContextProvider/ContextProviderInterface.php
  src/Sylius/Bundle/UiBundle/ContextProvider/DefaultContextProvider.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php
  src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php
  src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateEventRenderer.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php
  src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php
  src/Sylius/Bundle/UiBundle/Resources/config/services.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/context_provider.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/debug/template_event.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/template_event.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
Labels: Maintenance

#17198 [API] Fix configuration of Payment Request resource + refactor POST endpoint
  src/Sylius/Behat/Context/Api/Shop/PaymentRequestContext.php
  src/Sylius/Behat/Context/Setup/PaymentRequestContext.php
  src/Sylius/Bundle/ApiBundle/Command/Payment/AddPaymentRequest.php
  src/Sylius/Bundle/ApiBundle/CommandHandler/Payment/AddPaymentRequestHandler.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/PaymentRequest.xml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
  src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/AddPaymentRequestHandlerTest.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenPaymentRequestActionEligibilityValidator.php
  tests/Api/Shop/PaymentRequestsTest.php
Labels: API, Bug

#17211 Use Twig Extra package
  UPGRADE-2.0.md
  composer.json
  config/bundles.php
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/index/content/grid/filters.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/helper/table.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/accordion/attributes/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/grid/filters.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/grid/table.html.twig
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
  src/Sylius/Bundle/UiBundle/Twig/RouteExistsExtension.php
  src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TestHtmlAttributeExtension.php
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UiBundle/spec/Twig/RouteExistsExtensionSpec.php
  src/Sylius/Bundle/UiBundle/spec/Twig/SortByExtensionSpec.php
  symfony.lock
Labels: Dependencies

#17212 [UiBundle] Deprecate classes and services moved to TwigExtra package
  UPGRADE-1.14.md
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php
  src/Sylius/Bundle/UiBundle/Twig/TestHtmlAttributeExtension.php
Labels: Maintenance

#17209 [TaxonomyBundle] Unification os service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
  src/Sylius/Bundle/TaxonomyBundle/Resources/config/services/tree_repository.xml
Labels: Maintenance

#17205 [ShippingBundle] Unification of service name
  UPGRADE-2.0.md
  src/Sylius/Bundle/ApiBundle/Resources/config/services/shop/state_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_shipment.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/CompositeShippingMethodEligibilityCheckerPass.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/validator.xml
Labels: Maintenance

#17203 [ReviewBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_product_review.yml
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
  src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
Labels: Maintenance

#17185 [TaxationBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
Labels: DX, Maintenance

#17210 [UserBundle] Unification of service names
  UPGRADE-2.0.md
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
Labels: Maintenance

#17218 [Admin] Dynamic always open menu items
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/sidebar/menu/menu.html.twig
Labels: DX, Admin

#17189 [ShopBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/storage.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/url.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/ShopBundle/Resources/views/Account/Menu/_content.html.twig
Labels: Maintenance

#17219 [Behat] Normalize whitespace characters in string
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
Labels: Behat, Bug

#17223 [Core] Deprecate sylius_core.state_machine configuration parameter
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
Labels: Maintenance

#17225 [CI] Remove payment-request branch from upmerges
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance, CI

#17199 [AdminBundle] Unification of service names
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Menu/PromotionUpdateMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/admin_user.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/catalog_promotion.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/security.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/integrations/shop.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/provider.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_headerMenu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_menu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_headerWidget.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Update/_toolbar.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/_form.html.twig
Labels: Maintenance

#17228 [ShopBundle] Unification of service name - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/ShopBundle/Controller/HomepageController.php
  src/Sylius/Bundle/ShopBundle/Controller/SecurityWidgetController.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
Labels: Maintenance, Shop

#17227 [ShopBundle] Unification of services names
  UPGRADE-2.0.md
  config/routes/sylius_shop.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterUriBasedSectionResolverPassTest.php
  src/Sylius/Bundle/PayumBundle/Resources/config/services/integrations/sylius_shop/order_pay/providers.xml
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Compiler/BackwardsCompatibility/ReplaceEmailManagersPass.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/Compiler/LogoutListenerPass.php
  src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
  src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/contact.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/order.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/routing/security.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/context.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/storage.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/url.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/controllers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/handlers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/offline/providers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/providers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/resolvers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/twig.xml
  src/Sylius/Bundle/ShopBundle/SyliusShopBundle.php
  src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/Compiler/BackwardsCompatibility/ReplaceEmailManagersPassTest.php
  src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/SyliusShopExtensionTest.php
  src/Sylius/Bundle/ShopBundle/templates/account/layout.html.twig
Labels: Maintenance, Shop

#17215 [UiBundle] Deprecate FilterStorage and FilterStorageInterface classes
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/UiBundle/Storage/FilterStorage.php
  src/Sylius/Bundle/UiBundle/Storage/FilterStorageInterface.php
Labels: Maintenance

#17180 [Maintenance] Update exception catching when storage is unavailable while getting current locale
  src/Sylius/Component/Core/Locale/Context/StorageBasedLocaleContext.php
  src/Sylius/Component/Core/spec/Locale/Context/StorageBasedLocaleContextSpec.php
Labels: DX, Maintenance

#17238 [AdminBundle] Unification os services name - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Controller/Dashboard/StatisticsController.php
  src/Sylius/Bundle/AdminBundle/Menu/CustomerShowMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/OrderShowMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductUpdateMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_headerMenu.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_headerWidget.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/Update/_toolbar.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/Product/_form.html.twig
  src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/_form.html.twig
Labels: Maintenance

#17239 [AdminBundle] Unification os services name
  UPGRADE-2.0.md
  src/Sylius/Bundle/AdminBundle/Form/Extension/Promotion/Action/ProductFilterConfigurationTypeExtension.php
  src/Sylius/Bundle/AdminBundle/Form/Extension/Promotion/Action/TaxonFilterConfigurationTypeExtension.php
  src/Sylius/Bundle/AdminBundle/Menu/CustomerShowMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/OrderShowMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductUpdateMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/integrations/shop.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/product/form.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/query_function.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_attribute.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/error_template_finder.xml
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/sidebar/menu.html.twig
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterUriBasedSectionResolverPassTest.php
Labels: Maintenance

#17233 [PaymentBundle] Unification of services names
  UPGRADE-1.14.md
  src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkers.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
Labels: Maintenance

#17236 [Product] Fix `AvailableProductOptionValuesResolverInterface` Base Service ID
  src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
Labels: DX, Maintenance

#17234 [Order] Add Autowireable Service Aliases
  src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
Labels: DX, Maintenance

#17229 [UI] Improve product show page view
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/images/main_image.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/images/thumbnails.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/overview/images/thumbnails/thumbnail.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/summary.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/summary/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/info/summary/prices/price.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/components/order_item/product_info.html.twig
Labels: UX, Shop

#17243 Decouple CoreBundle from UiBundle
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/bundles.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/test/config/bundles.php
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
Labels: Enhancement, DX, Maintenance

#17222 Make Winzou State Machine the optional dependency
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/matrix.json
  UPGRADE-2.0.md
  composer-require-checker.json
  composer.json
  config/bundles.php
  phpstan.neon.dist
  src/Sylius/Abstraction/StateMachine/composer.json
  src/Sylius/Abstraction/StateMachine/config/services.xml
  src/Sylius/Abstraction/StateMachine/config/services/integrations/winzou.xml
  src/Sylius/Abstraction/StateMachine/src/DependencyInjection/SyliusStateMachineAbstractionExtension.php
  src/Sylius/Abstraction/StateMachine/tests/Unit/WinzouStateMachineAdapterTest.php
  src/Sylius/Bundle/AdminBundle/test/config/bundles.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/bundles.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_catalog_promotion.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_order.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_order_checkout.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_order_payment.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_order_shipping.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_payment.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_payment_request.yaml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_product_review.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/winzou_state_machine/sylius_shipment.yml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/StateMachineCompositeTest.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/test/config/bundles.php
  src/Sylius/Bundle/CoreBundle/test/config/packages/state_machine.yaml
  src/Sylius/Bundle/PaymentBundle/test/app/AppKernel.php
  symfony.lock
  tests/Api/Utils/OrderPlacerTrait.php
Labels: Maintenance, Dependencies

#17248 [CI] Use default env in MySQL workflow
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/matrix.json
Labels: Maintenance, CI

#17258 Fix 1.13 build by temporarily disabling problematic promotion scenarios
  features/promotion/managing_promotions/adding_promotion_in_different_languages.feature
  features/promotion/managing_promotions/adding_promotion_with_action_in_different_channels.feature
  features/promotion/managing_promotions/adding_promotion_with_rule_in_different_channels.feature
  features/promotion/managing_promotions/promotion_validation.feature
  src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
Labels: Behat, Maintenance, CI

#17246 [UserBundle] Deprecate pin configuration parameter
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php
  src/Sylius/Bundle/ShopBundle/Resources/config/app/sylius/sylius_mailer.yml
  src/Sylius/Bundle/UserBundle/Controller/UserController.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/EventListener/MailerListener.php
  src/Sylius/Bundle/UserBundle/Mailer/Emails.php
  src/Sylius/Bundle/UserBundle/UserEvents.php
Labels: Maintenance

#17241 [API] Rename and deprecate route parameters
  UPGRADE-API-1.14.md
  config/packages/security.yaml
  config/routes/sylius_api.yaml
  docs/cookbook/shop/disabling-guest-checkout.rst
  docs/customization/api/modifying_endpoints.rst
  src/Sylius/Behat/Resources/config/services/api.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
  src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/contexts.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/routing.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/security.yaml
Labels: Maintenance, API

#17235 [UserBundle] Deprecate security related classes and services that will be removed in 2.0
  UPGRADE-1.14.md
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Bundle/UserBundle/Security/UserLoginInterface.php
  src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php
  src/Sylius/Component/User/Security/UserPasswordHasherInterface.php
Labels: Maintenance

#17155 [Security] Remove security thingies
  UPGRADE-2.0.md
  config/packages/security.yaml
  phpstan-baseline.neon
  src/Sylius/Behat/Context/Cli/ChangeAdminPasswordContext.php
  src/Sylius/Behat/Resources/config/services/contexts/cli.xml
  src/Sylius/Bundle/AdminBundle/spec/Provider/LoggedInAdminUserProviderSpec.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241012081014.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241012081606.php
  src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/spec/EventListener/UserRegistrationListenerSpec.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Compiler/DecorateUserCheckerPass.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
  src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/User.orm.xml
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
  src/Sylius/Bundle/UserBundle/Security/UserLogin.php
  src/Sylius/Bundle/UserBundle/Security/UserLoginInterface.php
  src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php
  src/Sylius/Bundle/UserBundle/SyliusUserBundle.php
  src/Sylius/Bundle/UserBundle/spec/Security/UserLoginSpec.php
  src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordHasherSpec.php
  src/Sylius/Component/User/Model/AdvancedUserInterface.php
  src/Sylius/Component/User/Model/CredentialsHolderInterface.php
  src/Sylius/Component/User/Model/User.php
  src/Sylius/Component/User/Model/UserInterface.php
  src/Sylius/Component/User/Security/Checker/EnabledUserChecker.php
  src/Sylius/Component/User/Security/Checker/UserChecker.php
  src/Sylius/Component/User/Security/PasswordUpdater.php
  src/Sylius/Component/User/Security/UserPasswordHasherInterface.php
  src/Sylius/Component/User/composer.json
  src/Sylius/Component/User/spec/Security/PasswordUpdaterSpec.php
  src/Sylius/Component/User/tests/Security/Checker/EnabledUserCheckerTest.php
  src/Sylius/Component/User/tests/Security/Checker/UserCheckerTest.php
Labels: Maintenance

#17242 [PayumBundle] Unification os services name
  UPGRADE-1.14.md
  src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
  src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
  src/Sylius/Bundle/PayumBundle/Form/Type/PaypalGatewayConfigurationType.php
  src/Sylius/Bundle/PayumBundle/Form/Type/StripeGatewayConfigurationType.php
  src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/extension.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/factory.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/provider.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/PayumBundle/Validator/Constraints/GatewayFactoryExists.php
  src/Sylius/Bundle/PayumBundle/Validator/GatewayFactoryExistsValidator.php
  src/Sylius/Bundle/PayumBundle/Validator/GroupsGenerator/GatewayConfigGroupsGenerator.php
Labels: Maintenance

#17240 [Security] Rename API firewalls
  UPGRADE-2.0.md
  config/packages/security.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/security.yaml
  src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
Labels: Maintenance

#17262 Replace deprecated DOMNodeInserted event with MutationObserver
  features/promotion/managing_promotions/adding_promotion_with_action_in_different_channels.feature
  features/promotion/managing_promotions/adding_promotion_with_rule_in_different_channels.feature
  src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
Labels: Admin, Bug

#17251 [PaymentBundle] Unification of services names
  UPGRADE-2.0.md
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/shop/state_providers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/controllers.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/normalizer.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/processors.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/provider.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/offline/providers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/twig.xml
Labels: Maintenance

#17265 [UserBundle] Fix wrongly deprecated pin related services
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
Labels: Maintenance

#17255 add info about trademark and logo
  src/Sylius/Abstraction/StateMachine/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AddressingBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AdminBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ApiBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AttributeBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ChannelBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CoreBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CurrencyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CustomerBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/InventoryBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/LocaleBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/MoneyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/OrderBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PaymentBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PayumBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ProductBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PromotionBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ReviewBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ShippingBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ShopBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/TaxationBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/TaxonomyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/UiBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/UserBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Addressing/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Attribute/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Channel/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Core/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Currency/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Customer/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Inventory/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Locale/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Order/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Payment/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Product/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Promotion/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Review/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Shipping/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Taxation/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Taxonomy/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/User/LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#17252 [Shop] Add priorities to hooks
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/address_book/create.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/address_book/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/address_book/update.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/change_password.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/common/create.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/common/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/common/show.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/common/update.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/dashboard.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/forgotten_password.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/login.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/order/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/order/show.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/profile_update.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/register.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/register_thank_you.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/reset_password.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/base.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/cart/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/address.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/complete.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_payment.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_shipping.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/shared.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/contact/contact_request.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/errors/error403.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/errors/error404.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/errors/error500.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/homepage/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/order/show.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/order/thank_you.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product/show.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/create.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/address.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/error.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/form/address.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/form/select_payment.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/grid.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/order/summary.yaml
Labels: Shop

#17259 [UserBundle] Remove pin configuration parameter and related things
  UPGRADE-2.0.md
  docs/components_and_bundles/bundles/SyliusUserBundle/summary.rst
  src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/mailer.xml
  src/Sylius/Bundle/CoreBundle/spec/EventListener/MailerListenerSpec.php
  src/Sylius/Bundle/ShopBundle/Resources/config/app/sylius/sylius_mailer.yml
  src/Sylius/Bundle/UserBundle/Controller/UserController.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
  src/Sylius/Bundle/UserBundle/EventListener/MailerListener.php
  src/Sylius/Bundle/UserBundle/Mailer/Emails.php
  src/Sylius/Bundle/UserBundle/Resources/config/services.xml
  src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/UserBundle/UserEvents.php
  src/Sylius/Component/User/Security/Generator/UniquePinGenerator.php
  src/Sylius/Component/User/spec/Security/Generator/UniquePinGeneratorSpec.php
Labels: Maintenance

#17244 [Core] Deprecate sylius_core.autoconfigure_with_attributes configuration parameter
  UPGRADE-1.14.md
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
Labels: Maintenance

#17245 [Core][Order] Remove autoconfigure_with_attributes configuration parameters
  UPGRADE-2.0.md
  docs/components_and_bundles/bundles/SyliusOrderBundle/processors.rst
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
  src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/SyliusOrderExtensionTest.php
Labels: DX, Maintenance

#17263 [API] Rename route parameters
  UPGRADE-API-1.14.md
  UPGRADE-API-2.0.md
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/section_resolver.xml
Labels: Maintenance, API

#17192 [Maintenance] Remove deprecated configuration nodes
  UPGRADE-2.0.md
  src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ChannelBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
Labels: Maintenance

#17275 [ApiBundle] Unification of services names - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/ApiBundle/ApiPlatform/ApiResourceConfigurationMerger.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Merger/LegacyResourceMetadataMerger.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/ResourceMetadataPropertyValueResolver.php
  src/Sylius/Bundle/ApiBundle/DataPersister/AddressDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/AdminUserDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ChannelDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/CountryDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/CustomerDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/LocaleDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/MessengerDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/PaymentMethodDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductAttributeDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductTaxonDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ProductVariantDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/PromotionCouponDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/PromotionDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ShippingMethodDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/TranslatableDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataPersister/ZoneDataPersister.php
  src/Sylius/Bundle/ApiBundle/DataProvider/AccountResetPasswordItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/AdminOrderItemAdjustmentsSubresourceDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/AdminResetPasswordItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ChannelAwareItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ChannelsCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/CustomerItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/OrderAdjustmentsSubresourceDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemAdjustmentsSubresourceDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemUnitItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/PaymentItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/PaymentMethodsCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ProductAttributesSubresourceDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ProductItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ShipmentItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/ShippingMethodsCollectionDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataProvider/VerifyCustomerAccountItemDataProvider.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/ChannelCodeAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/CommandAwareInputDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/CommandDataTransformerInterface.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LocaleCodeAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LoggedInCustomerEmailAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LoggedInCustomerEmailIfNotSetAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/LoggedInShopUserIdAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/OrderTokenValueAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/ShipmentIdAwareInputCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/DataTransformer/SubresourceIdAwareCommandDataTransformer.php
  src/Sylius/Bundle/ApiBundle/EventListener/PostgreSQLDriverExceptionListener.php
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/ApiBundle/Validator/CatalogPromotion/PercentageDiscountActionValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/Constraints/AccountVerificationTokenEligibilityValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/ResourceApiInputDataPropertiesValidator.php
  src/Sylius/Bundle/ApiBundle/Validator/ResourceInputDataPropertiesValidatorInterface.php
Labels: Maintenance

#17270 [PayumBundle] Unification os services name
  UPGRADE-2.0.md
  config/services_test_cached_payum.yaml
  src/Sylius/Bundle/PaymentBundle/Validator/Constraints/GatewayFactoryExists.php
  src/Sylius/Bundle/PaymentBundle/Validator/Constraints/GatewayFactoryExistsValidator.php
  src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/extension.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/factory.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/integrations/sylius_shop/order_pay/providers.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/order_pay.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/action.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/command_handler.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/command_provider.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/context.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/factory.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/processor.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/resolver.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/provider.xml
Labels: Maintenance

#17204 Packages cleanups
  UPGRADE-2.0.md
  package.json
  src/Sylius/Bundle/AdminBundle/package.json
  src/Sylius/Bundle/ShopBundle/package.json
Labels: Maintenance

#17177 Symfony ux icons
  composer.json
  config/bundles.php
  src/Sylius/Bundle/ShopBundle/Resources/assets/icons/bag.svg
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/_icons.scss
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/main.scss
  src/Sylius/Bundle/ShopBundle/templates/account/address_book/common/content/address/actions/edit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main_section/buttons/change_password.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main_section/buttons/edit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main_section/buttons/verify.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/order/grid/action/pay.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/order/show/content/header/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/cart/index/form/sections/general/coupon.html.twig
  src/Sylius/Bundle/ShopBundle/templates/form/theme.html.twig
  src/Sylius/Bundle/ShopBundle/templates/icons/adjustments.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/check.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/chevron-down.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/chevron-left.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/chevron-right.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/chevron-up.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/credit-card.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/facebook.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/instagram.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/lock.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/menu.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/pencil.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/plus.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/search.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/selector.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/star.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/trash.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/twitter-x.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/user.svg
  src/Sylius/Bundle/ShopBundle/templates/icons/x.svg
  src/Sylius/Bundle/ShopBundle/templates/product/index/page/body/main/filters/search/clear.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/index/page/body/main/filters/search/submit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/components/header/cart.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/flashes.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/helpers/accordion.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/icon.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/footer/content/payment_methods.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/cart_button.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/logged_in_user/desktop/welcome_message.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/logged_in_user/mobile/menu.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/visitor/desktop/user_icon.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/visitor/mobile.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/taxon_hamburger.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/grid/table/sorting.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/navigation_buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/pagination/pagerfanta.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/rating.html.twig
  src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/UiBundle/Resources/config/packages/ux_icons.yaml
  src/Sylius/Bundle/UiBundle/composer.json
  symfony.lock
Labels: Shop, Dependencies

#17277 Clean and bump all dependencies
  CONFLICTS.md
  composer.json
  config/bundles.php
  config/packages/http_discovery.yaml
  config/packages/nyholm_psr7.yaml
  phpstan-baseline.neon
  src/Sylius/Abstraction/StateMachine/composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/AdminBundle/test/config/bundles.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/bundles.php
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/CoreBundle/Resources/config/app/nyholm_psr7.yaml
  src/Sylius/Bundle/CoreBundle/Tests/Provider/ChannelBasedProductTranslationProviderTest.php
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CoreBundle/test/config/bundles.php
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/CONFLICTS.md
  src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
  symfony.lock
Labels: Maintenance, Dependencies

#17274 [CoreBundle] Unification of services names - fix
  UPGRADE-1.14.md
  src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/PathHiderDocumentationModifier.php
  src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/applicators.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/calculators.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/checkers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/command_handlers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/processors.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/command_dispatcher.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/price_history/listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/shipping.xml
  src/Sylius/Bundle/CoreBundle/Theme/ChannelBasedThemeContext.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/storage.xml
Labels: Maintenance

#17284 [Composer] Bump doctrine/collections dependency
  composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/User/composer.json
  tests/Api/DataFixtures/ORM/cart.yaml
  tests/Api/DataFixtures/ORM/cart/promotion.yaml
  tests/Api/DataFixtures/ORM/catalog_promotion/catalog_promotion.yaml
  tests/Api/DataFixtures/ORM/payment_method.yaml
  tests/Api/DataFixtures/ORM/product/product.yaml
  tests/Api/DataFixtures/ORM/product/product_option.yaml
  tests/Api/DataFixtures/ORM/product/product_variant.yaml
  tests/Api/DataFixtures/ORM/product/product_variant_with_lowest_price.yaml
  tests/Api/DataFixtures/ORM/product/product_variant_with_original_price.yaml
  tests/Api/DataFixtures/ORM/product/product_with_many_locales.yaml
  tests/Api/DataFixtures/ORM/product/products_with_associations.yaml
  tests/Api/DataFixtures/ORM/promotion/promotion.yaml
  tests/Api/DataFixtures/ORM/shipping_method.yaml
  tests/Api/DataFixtures/ORM/statistics.yaml
  tests/Api/DataFixtures/ORM/taxonomy.yaml
  tests/Api/Responses/admin/channel_pricing_log_entry/get_channel_pricing_log_entries_response.json
Labels: Maintenance, API, Dependencies

#17291 [ShippingBundle] Unification of services names
  UPGRADE-2.0.md
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
Labels: Maintenance

#16096 Adding an index for the `address_log_entries`
  src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/AddressLogEntry.orm.xml
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241018075040.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241018081002.php
Labels: Enhancement, Performance

#17298 [CoreBundle] Add missing license file
  src/Sylius/Bundle/CoreBundle/LICENSE
Labels: Maintenance

#17297 Add info about trademark and logo to bundles and components in 1.14
  src/Sylius/Abstraction/StateMachine/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AddressingBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AdminBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ApiBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/AttributeBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ChannelBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CoreBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CurrencyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/CustomerBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/InventoryBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/LocaleBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/MoneyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/OrderBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PaymentBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PayumBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ProductBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/PromotionBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ReviewBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ShippingBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/ShopBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/TaxationBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/TaxonomyBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/UiBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Bundle/UserBundle/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Addressing/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Attribute/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Channel/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Core/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Currency/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Customer/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Inventory/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Locale/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Order/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Payment/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Product/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Promotion/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Review/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Shipping/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Taxation/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/Taxonomy/LICENSE_OF_TRADEMARK_AND_LOGO
  src/Sylius/Component/User/LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#17288 [ApiBundle] Unify of section provider
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Admin/Promotion/PromotionCoupon/PostResultExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Common/EnabledExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Country/ChannelBasedExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/ChannelAndLocaleBasedExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/EnabledExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/EnabledWithinProductAssociationExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/TaxonBasedExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Taxon/ChannelBasedExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Taxon/EnabledChildrenExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/GeneratedPromotionCouponsNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductVariantNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ShippingMethodNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/SerializationGroupsSupportTrait.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Admin/Promotion/PromotionCoupon/PostResultExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Common/EnabledExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Country/ChannelBasedExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Product/ChannelAndLocaleBasedExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Product/EnabledExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Product/EnabledWithinProductAssociationExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Product/TaxonBasedExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Taxon/ChannelBasedExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Taxon/EnabledChildrenExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/GeneratedPromotionCouponsNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductVariantNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ShippingMethodNormalizerSpec.php
  tests/Api/DataFixtures/ORM/product/product_variant_with_original_price.yaml
  tests/Api/Responses/shop/order_item/get_order_item_by_guest.json
  tests/Api/Responses/shop/order_item/get_order_item_by_user.json
Labels: Enhancement, API

#17290 Refactor Filters structure
  adr/2024_10_22_filters_structure_refactor.md
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ChannelsAwareChannelFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ExchangeRateFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ProductPriceOrderFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ProductVariantCatalogPromotionFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ProductVariantOptionValueFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/TaxonFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/TranslationOrderNameAndLocaleFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Common/TranslationOrderLocaleExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/CatalogPromotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ExchangeRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/admin/filters.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/shop/filters.xml
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/Filter/TaxonFilterSpec.php
Labels: API

#17304 [Maintenance] Move php-http/message-factory back to require to fix Sylius-Standard
  composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
Labels: Maintenance

#17295 [Product] Replace the use of VariantWithNoOptionsValuesException from Resource with a custom one
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php
  src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/GenerateProductVariantsSubscriberSpec.php
  src/Sylius/Component/Product/Exception/ProductWithoutOptionsException.php
  src/Sylius/Component/Product/Exception/ProductWithoutOptionsValuesException.php
  src/Sylius/Component/Product/Generator/ProductVariantGenerator.php
  src/Sylius/Component/Product/Generator/ProductVariantGeneratorInterface.php
  src/Sylius/Component/Product/spec/Generator/ProductVariantGeneratorSpec.php
Labels: Enhancement

#17301 [Maintenance] Remove APIP deprecations
  src/Sylius/Behat/Context/Api/Admin/BrowsingCatalogPromotionProductVariantsContext.php
  src/Sylius/Behat/Context/Api/Admin/CreatingProductVariantContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingCustomersContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingProductTaxonsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingTaxRatesContext.php
  src/Sylius/Behat/Context/Api/Shop/CartContext.php
  src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
  src/Sylius/Behat/Context/Api/Shop/LoginContext.php
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Api/Shop/ProductContext.php
  src/Sylius/Behat/Context/Api/Shop/ProductReviewContext.php
  src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
  src/Sylius/Behat/Context/Api/Shop/TaxonContext.php
  src/Sylius/Behat/spec/Service/Converter/IriConverterSpec.php
  src/Sylius/Bundle/ApiBundle/ApiPlatform/Routing/IriConverter.php
  src/Sylius/Bundle/ApiBundle/Controller/GetProductBySlugAction.php
  src/Sylius/Bundle/ApiBundle/Converter/IriToIdentifierConverter.php
  src/Sylius/Bundle/ApiBundle/Creator/ProductImageCreator.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ChannelsAwareChannelFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ProductVariantCatalogPromotionFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/ProductVariantOptionValueFilter.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/TaxonFilter.php
  src/Sylius/Bundle/ApiBundle/EventListener/AdminAuthenticationSuccessListener.php
  src/Sylius/Bundle/ApiBundle/EventListener/AuthenticationSuccessListener.php
  src/Sylius/Bundle/ApiBundle/Exception/NoRouteMatchesException.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Serializer/Denormalizer/ChannelPriceHistoryConfigDenormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Denormalizer/ProductAttributeValueDenormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ImageNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductNormalizer.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductVariantNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/Routing/IriConverterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Creator/ProductImageCreatorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/Filter/TaxonFilterSpec.php
  src/Sylius/Bundle/ApiBundle/spec/EventListener/AdminAuthenticationSuccessListenerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/EventListener/AuthenticationSuccessListenerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/ChannelCodeAwareContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/ChannelContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/LocaleCodeAwareContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/LocaleContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/LoggedInCustomerEmailAwareContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/LoggedInShopUserIdAwareContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ContextBuilder/UriVariablesAwareContextBuilderSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Denormalizer/ChannelPriceHistoryConfigDenormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Denormalizer/ProductAttributeValueDenormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ImageNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductVariantNormalizerSpec.php
Labels: Maintenance, API, Dependencies

#17308 Minor fixes
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Admin/Promotion/PromotionCoupon/PostResultExtension.php
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductVariantNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/GeneratedPromotionCouponsNormalizerSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductNormalizerSpec.php
Labels: Enhancement, DX

#17306 [All] Unification of services names
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/processors.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/installer.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/eligibility_checkers.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
Labels: Maintenance

#17279 [UI] Unify product thumbnail sizes
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/_thumbnails.scss
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/AdminBundle/templates/admin_user/form/sections/personal_information/avatar.html.twig
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/items/body/item.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product/grid/field/product_image.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product/show/content/page_body/general/shared/tab/product.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product/show/content/page_body/media.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product_review/form/sections/info/product/body.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/components/navbar/user.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/helper/product_image.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shipment/show/content/page_body/items/body/product.html.twig
Labels: UX

#17307 [All] Unification of services names
  UPGRADE-2.0.md
  src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/processors.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/installer.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/InventoryBundle/Resources/config/doctrine/model/InventoryUnit.orm.xml
  src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/integrations/sylius_shop/order_pay/providers.xml
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/CompositePromotionCouponEligibilityCheckerPass.php
  src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/CompositePromotionEligibilityCheckerPass.php
  src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/eligibility_checkers.xml
  src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/CompositePromotionCouponEligibilityCheckerPassTest.php
  src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/CompositePromotionEligibilityCheckerPassTest.php
  src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/CompositeShippingMethodEligibilityCheckerPass.php
  src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/email.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/controllers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/handlers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/offline/providers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/providers.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/resolvers.xml
  src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
Labels: Maintenance

#17309 [Maintenance] Remove deprecated APIP service
  UPGRADE-2.0.md
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/LegacyErrorHandlingCompilerPass.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/HydraErrorNormalizer.php
  src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/LegacyErrorHandlingCompilerPassTest.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/HydraErrorNormalizerSpec.php
Labels: Maintenance, API, Dependencies

#17311 [Composer] Bump symfonycasts/dynamic-forms dependency and put it in appropriate bundles
  composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
Labels: Maintenance, Dependencies

#16601 [ApiBundle][Image] Prevent resolving non-serialized image paths
  src/Sylius/Bundle/ApiBundle/Serializer/ImageNormalizer.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ImageNormalizerSpec.php
Labels: API

#17312 [Maintenance] Add info about private services to UPGRADE.md
  UPGRADE-2.0.md
  adr/2022_02_11_declaring_services_in_container.md
Labels: Maintenance

#17314 [ApiBundle] Apply default public setting for filters
  UPGRADE-2.0.md
  adr/2024_10_22_filters_structure_refactor.md
  src/Sylius/Bundle/ApiBundle/Resources/config/services/admin/filters.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/shop/filters.xml
Labels: Enhancement, API

#17315 [ApiBundle] NonArchivedExtension - remove the parameter and use the ArchivableInterface as reference to check resources
  UPGRADE-API-2.0.md
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Common/NonArchivedExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/SyliusApiExtensionTest.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Common/NonArchivedExtensionSpec.php
  src/Sylius/Bundle/ApiBundle/spec/Doctrine/ORM/QueryExtension/Shop/Common/EnabledExtensionSpec.php
Labels: Enhancement, API

#17321 [API][PHPSpec] Remove unused arguments from ImageNormalizerSpec
  src/Sylius/Bundle/ApiBundle/spec/Serializer/ImageNormalizerSpec.php
Labels: DX, API

#17318 [API] Deprecate legacy_error_handling and serialization_groups configuration parameters
  UPGRADE-API-1.14.md
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
Labels: Maintenance, API

#17317 [API] Remove legacy serialization_groups configuration parameters
  UPGRADE-API-2.0.md
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
  src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/SyliusApiExtensionTest.php
Labels: Maintenance, API

#17320 Deprecate exceptions from ApiBundle
  UPGRADE-1.14.md
  src/Sylius/Bundle/ApiBundle/Exception/CannotRemoveCurrentlyLoggedInUser.php
  src/Sylius/Bundle/ApiBundle/Exception/ChannelCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PaymentMethodCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductAttributeCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductVariantCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PromotionCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PromotionCouponCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProvinceCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ShippingMethodCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/TaxonCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ZoneCannotBeRemoved.php
Labels: API

#17324 Services IDs Unification
  src/Sylius/Abstraction/StateMachine/config/services.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/calculators.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/catalog_promotion/checkers.xml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterUriBasedSectionResolverPassTest.php
Labels: Maintenance

#17319 Extract common State processor for resource removal
  src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingPaymentMethodsContext.php
  src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteExceptionListener.php
  src/Sylius/Bundle/AdminBundle/spec/EventListener/ResourceDeleteExceptionListenerSpec.php
  src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductDeletionEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/EventSubscriber/TaxonDeletionEventSubscriber.php
  src/Sylius/Bundle/ApiBundle/Exception/CannotRemoveCurrentlyLoggedInUser.php
  src/Sylius/Bundle/ApiBundle/Exception/ChannelCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PaymentMethodCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductAttributeCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductOptionValueCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProductVariantCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PromotionCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/PromotionCouponCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ProvinceCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ShippingMethodCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/TaxonCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Exception/ZoneCannotBeRemoved.php
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/PaymentMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ProductAttribute.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ProductOption.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ProductVariant.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/Promotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/PromotionCoupon.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/ShippingMethod.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/state_processors.xml
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/AdminUser/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Channel/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Common/ResourceRemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Country/PersistProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/PaymentMethod/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Product/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ProductAttribute/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ProductOption/PersistProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ProductVariant/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Promotion/PromotionCoupon/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Promotion/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/ShippingMethod/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/StateProcessor/Admin/Zone/RemoveProcessor.php
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/ProductDeletionEventSubscriberSpec.php
  src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/TaxonDeletionEventSubscriberSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/AdminUser/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Channel/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Common/ResourceRemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Country/PersistProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/PaymentMethod/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Product/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ProductAttribute/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ProductOption/PersistProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ProductVariant/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Promotion/PromotionCoupon/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Promotion/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/ShippingMethod/RemoveProcessorSpec.php
  src/Sylius/Bundle/ApiBundle/spec/StateProcessor/Admin/Zone/RemoveProcessorSpec.php
  src/Sylius/Component/Core/Exception/ResourceDeleteException.php
Labels: Enhancement, DX

#17329 Fix missing icons
  src/Sylius/Bundle/ShopBundle/Menu/AccountMenuBuilder.php
  src/Sylius/Bundle/ShopBundle/templates/account/menu/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/grid/filters.html.twig
Labels: UX, Shop

#17264 [Admin][Shop] Set http_method_override to true by default
  src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
Labels: Admin, Shop

#17327 Add info about thumbnails to the upgrade file
  UPGRADE-2.0.md
Labels: Maintenance

#17332 Fix gateway factory not exist
  composer-require-checker.json
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/payment_method/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/payment_method/update.yaml
  src/Sylius/Bundle/AdminBundle/templates/payment_method/form/sections/gateway_configuration/type.html.twig
  src/Sylius/Bundle/AdminBundle/templates/payment_method/form/sections/gateway_configuration/use_payum.html.twig
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241024174728.php
  src/Sylius/Bundle/CoreBundle/Migrations/Version20241024174729.php
  src/Sylius/Bundle/PaymentBundle/Form/Type/GatewayConfigType.php
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/PayumBundle/Form/Extension/PayumGatewayConfigTypeExtension.php
  src/Sylius/Bundle/PayumBundle/Model/GatewayConfig.php
  src/Sylius/Bundle/PayumBundle/Model/GatewayConfigInterface.php
  src/Sylius/Bundle/PayumBundle/Resources/config/doctrine/model/GatewayConfig.orm.xml
  src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/PayumBundle/Storage/DoctrineStorage.php
Labels: Bug

#17335 [Maintenance] Fix invalid install command argument
  src/Sylius/Behat/Context/Cli/InstallerContext.php
  src/Sylius/Bundle/CoreBundle/Console/Command/InstallSampleDataCommand.php
Labels: Maintenance, Bug

#17283 [PaymentRequest] Encryption of payment related data
  .env
  .env.test
  .env.test_cached
  .env.test_cached_payum
  composer-require-checker.json
  composer.json
  config/encryption/.gitkeep
  config/encryption/test.key
  src/Sylius/Bundle/CoreBundle/Console/Command/InstallCommand.php
  src/Sylius/Bundle/PaymentBundle/Console/Command/GenerateEncryptionKeyCommand.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
  src/Sylius/Bundle/PaymentBundle/Listener/EntityEncryptionListener.php
  src/Sylius/Bundle/PaymentBundle/Listener/GatewayConfigEncryptionListener.php
  src/Sylius/Bundle/PaymentBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/console_command.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/encryption/encryption.xml
  src/Sylius/Bundle/PaymentBundle/Tests/Console/Command/GenerateEncryptionKeyCommandTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/SyliusPaymentExtensionTest.php
  src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
  src/Sylius/Component/Payment/Encryption/Encrypter.php
  src/Sylius/Component/Payment/Encryption/EncrypterInterface.php
  src/Sylius/Component/Payment/Encryption/EncryptionAwareInterface.php
  src/Sylius/Component/Payment/Encryption/EntityEncrypterInterface.php
  src/Sylius/Component/Payment/Encryption/Exception/EncryptionException.php
  src/Sylius/Component/Payment/Encryption/GatewayConfigEncrypter.php
  src/Sylius/Component/Payment/Encryption/PaymentRequestEncrypter.php
  src/Sylius/Component/Payment/Model/GatewayConfigInterface.php
  src/Sylius/Component/Payment/Model/PaymentRequestInterface.php
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Payment/spec/Encryption/EncrypterSpec.php
  src/Sylius/Component/Payment/spec/Encryption/GatewayConfigEncrypterSpec.php
  src/Sylius/Component/Payment/spec/Encryption/PaymentRequestEncrypterSpec.php
  src/Sylius/Component/Payment/spec/Encryption/fixtures/encryption_key
  tests/Functional/Encryption/GatewayConfigEncryptionTest.php
  tests/Functional/Encryption/PaymentRequestEncryptionTest.php
Labels: Feature, Enhancement

#17342 [Admin] Deprecate NotificationController
  UPGRADE-1.14.md
  src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
Labels: Maintenance

#17341 [Admin] Remove NotificationController
  UPGRADE-2.0.md
  src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
  src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php
Labels: Admin

#17339 [OrderPay] Avoid instantiating all available Payum gateways
  src/Sylius/Bundle/CoreBundle/OrderPay/Provider/PaymentRequestPayResponseProvider.php
  src/Sylius/Bundle/PayumBundle/OrderPay/Provider/PayumPayResponseProvider.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/offline/providers.xml
Labels: Enhancement

#17343 [AdminBundle] Customer index - add info that customer doesn't have a ShopUser
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
  src/Sylius/Bundle/AdminBundle/templates/customer/grid/field/enabled.html.twig
Labels: UX, Admin

#17349 Fix CI matrix APIP versions
  .github/workflows/ci_static-checks.yaml
  .github/workflows/matrix.json
  tests/Model/OrderAdjustmentsRecalculationTest.php
Labels: Maintenance, CI

#17345 [Shop] Reorganize Twig hooks on login page
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/login.yaml
  src/Sylius/Bundle/ShopBundle/templates/account/login.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/forgot_password.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/csrf_token.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/errors.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/form_fields.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/form_fields/password.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/form_fields/remember_me.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/form_fields/username.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/form/submit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/login_container/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/content/register_container.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/login/form.html.twig
Labels: Shop

#17337 [AdminBundle] Add base form type for ShopUserType and PromotionCouponGeneratorInstructionType
  src/Sylius/Bundle/AdminBundle/Form/Type/PromotionCouponGeneratorInstructionType.php
  src/Sylius/Bundle/AdminBundle/Form/Type/ShopUserType.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
Labels: Admin

#17336 [AdminBundle] Add LiveComponents for all simple Resources
  src/Sylius/Bundle/AdminBundle/Form/Type/CustomerType.php
  src/Sylius/Bundle/AdminBundle/Form/Type/PromotionCouponGeneratorInstructionType.php
  src/Sylius/Bundle/AdminBundle/Form/Type/ShopUserType.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/admin_user/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/admin_user/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/currency/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/customer/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/customer/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/exchange_rate/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/exchange_rate/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/locale/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_association_type/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_association_type/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_review/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_variant/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/product_variant/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/promotion_coupon/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/promotion_coupon/generate.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/promotion_coupon/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/shipping_category/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/shipping_category/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/tax_category/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/tax_category/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/tax_rate/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/tax_rate/update.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/currency.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/dashboard.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/order.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_attribute.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_option.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/product_variant.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/promotion_coupon.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/shipment.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/taxon.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/zone.xml
  src/Sylius/Bundle/AdminBundle/Twig/Component/ProductVariant/FormComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/PromotionCoupon/GeneratorInstructionFormComponent.php
  src/Sylius/Bundle/AdminBundle/templates/customer/form/sections/account_credentials.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product_variant/form.html.twig
  src/Sylius/Bundle/AdminBundle/templates/promotion_coupon/generate/form.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/content/form.html.twig
  src/Sylius/Bundle/PromotionBundle/Controller/PromotionCouponController.php
  src/Sylius/Component/Product/Factory/ProductVariantFactoryInterface.php
Labels: Feature, Admin
