Repository Sylius/Sylius, pull requests merged in 2024-11, with the labels that each got.

#17289 Add breadcrumbs to product reviews
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/create.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/twig/component.xml
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/BySlugComponent.php
  src/Sylius/Bundle/ShopBundle/templates/product/common/macro/breadcrumbs.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/page/header/breadcrumbs.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/create/content/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/create/content/header/breadcrumbs.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/header/breadcrumbs.html.twig
Labels: UX, Shop

#17405 [PaymentRequest] Mark Sensitive Fields And Ignore Encryption Key From Version Control
  .gitignore
  src/Sylius/Component/Payment/Model/PaymentRequest.php
  src/Sylius/Component/Payment/Model/PaymentRequestInterface.php
Labels: Enhancement

#17394 [Shop] Reorganize Twig hooks on product show page
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product/show.yaml
  src/Sylius/Bundle/ShopBundle/templates/product/show.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/header/breadcrumbs.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/attributes.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/attributes/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/attributes/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/details/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/details/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/reviews.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/reviews/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/reviews/content/add_review.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/reviews/content/view_more.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/reviews/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/images.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/images/main_image.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/images/thumbnails.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/images/thumbnails/image_variants.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/images/thumbnails/thumbnail.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/options/list.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/quantity.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/submit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/body.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/body/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/body/price.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/body/selection.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/head.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/head/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/head/price.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/add_to_cart/variants/table/head/selection.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/average_rating.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/average_rating/add_review.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/average_rating/number_of_reviews.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/average_rating/rating.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/catalog_promotions.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/prices.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/prices/lowest_price_before_discount.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/prices/price.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/summary/short_description.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/product_listing.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/product_listing/association.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/product_listing/associations.html.twig
Labels: DX, Shop

#17395 [Shop] Reorganize Twig hooks on product review index page
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/index.yaml
  src/Sylius/Bundle/ShopBundle/templates/cart/index/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/header/breadcrumbs.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header/buttons/add_review.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header/details/reviews_count.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/header/details/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/content/comment.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/footer.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/footer/author.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/footer/date.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/header/rating.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/main/list/review/header/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product_review/index/content/sidebar.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/product_review/list.html.twig
Labels: DX, Shop

#17391 [API] Mention resource configuration changes in upgrade file
  UPGRADE-API-2.0.md
Labels: Maintenance, API

#17408 [API] Use model class parameter instead of hardcoded class for ShippingMethodRule resource
  src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethodRule.xml
Labels: DX, API

#17409 [CI] Add 2.0-docs branch to upmerges
  .github/workflows/upmerge_pr.yaml
Labels: Documentation, Maintenance, CI

#17410 [CI] Add GH action to synchronize 2.0 branch with GitBook docs branch
  .github/workflows/merge_docs.yaml
Labels: Documentation, Maintenance, CI

#17406 Mention the major templates changes in upgrade file
  UPGRADE-2.0.md
Labels: Maintenance

#17400 Mention the dependencies changes in upgrade file
  UPGRADE-2.0.md
Labels: Maintenance

#17415 [Admin][HotFix] Fix form without live component
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/content/form.html.twig
Labels: Critical, Admin

#17419 [API] Remove deprecated and unused serialization groups
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AddressLogEntry.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AdminUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AvatarImage.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotion.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotionAction.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotionScope.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/ChangePasswordShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/RegisterShopUser.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/RequestResetPasswordToken.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/ResetPassword.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/SendContactRequest.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ExchangeRate.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Locale.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Payment.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PerChannelCustomerStatistics.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionAction.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionRule.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/serialization/Taxon.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/serialization/Command/Admin/Account/RequestResetPasswordEmail.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/serialization/Command/Admin/Account/ResetPassword.xml
Labels: API

#17413 SYL-4100: Checkout hooks reorganize
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/address.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/complete.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_payment.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_shipping.yaml
  src/Sylius/Bundle/ShopBundle/templates/checkout/address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses/address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses/address/address_book.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses/address/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses/address/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/addresses/different_address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/billing_address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/navigation.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/shipping_address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/address/content/form/user.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/form/extra_notes.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/form/navigation.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/form/summary.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/header/currency.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete/content/header/locale.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/navigation.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment/choice.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment/choice/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment/choice/details/description.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment/choice/details/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment/content/form/payments/payment/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/navigation.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/choice.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/choice/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/choice/details/description.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/choice/details/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/choice/fee.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping/content/form/shipments/shipment/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/shared/content.html.twig
Labels: DX, Shop

#17414 [Shop] Few improvement on cart index
  src/Sylius/Bundle/ShopBundle/templates/cart/index.html.twig
Labels: DX, Shop

#17417 [Docs] Add links to 2.x docs on the 1.x documentation
  docs/_themes/sylius_rtd_theme/layout.html
  docs/_themes/sylius_rtd_theme/versions.html
  docs/conf.py
  docs/requirements.txt
Labels: Documentation

#17423 [Admin] Add checkout.payment.allowed_states parameter
  src/Sylius/Bundle/AdminBundle/templates/shared/helper/dropdown.html.twig
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ChangePaymentMethodType.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php
Labels: Enhancement, DX

#17418 [Admin] Chore: Remove useless route vars
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/admin_user.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/channel.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/country.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer_group.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/locale.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/payment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/payment_method.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_association_type.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_attribute.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_option.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_review.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipping_category.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/tax_category.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/routing/zone.yml
Labels: DX, Admin

#17420 [PaymentRequest] Adjust ids of the services to link them to Payment Requests
  src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
  src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_pay/controllers.xml
  src/Sylius/Bundle/CoreBundle/Resources/config/services/order_pay/providers.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/command_provider.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/controllers.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/processors.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/provider.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/offline/providers.xml
Labels: DX

#17428 [Admin] Add twig.payment_method.excluded_gateways parameter
  src/Sylius/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/AdminBundle/DependencyInjection/SyliusAdminExtension.php
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig.xml
  src/Sylius/Bundle/AdminBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Sylius/Bundle/AdminBundle/Tests/DependencyInjection/SyliusAdminExtensionTest.php
  src/Sylius/Bundle/AdminBundle/Tests/Twig/PaymentMethodExtensionTest.php
  src/Sylius/Bundle/AdminBundle/Twig/PaymentMethodExtension.php
Labels: DX, Admin

#17427 SYL-4101: Hook rename
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/dashboard.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/account/order/index.yaml
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/buttons/change_password.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/buttons/edit.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/buttons/verify.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/user_info.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/user_info/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/user_info/details/email.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/user_info/details/full_name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/dashboard/index/content/main/section/user_info/status.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/order/index/content/main/main_section.html.twig
Labels: DX, Shop

#17430 [API] Update info about resource configuration changes in upgrade file
  UPGRADE-API-2.0.md
Labels: Maintenance, API

#17429 Implement common hooks structure as in AdminBundle
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/address.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/complete.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_payment.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/select_shipping.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/checkout/shared.yaml
  src/Sylius/Bundle/ShopBundle/templates/checkout/address.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/header/account.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/header/logo.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/layout.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/header.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/items.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/items/item.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/items/item/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/items/item/quantity.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/items/item/subtotal.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/items_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/order_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/promotion_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/shipping_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/taxes_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/steps.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/complete.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_payment.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/select_shipping.html.twig
Labels: DX, Shop

#17421 [Shop] Enable customization of body classes
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/base.yaml
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/body_classes/defaults.html.twig
Labels: DX, Shop

#17431 Admin security hooks refactor
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/security/login.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/security/request_password_reset.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/security/reset_password.yaml
  src/Sylius/Bundle/AdminBundle/templates/security/common/page.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/error.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/forgot_password.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/password.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/remember_me.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/submit.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/form/username.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/login/page/content/header.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/request_password_reset.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/request_password_reset/page/content.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/request_password_reset/page/content/form.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/request_password_reset/page/content/form/email.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/request_password_reset/page/content/form/submit.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/reset_password.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/reset_password/page/content/form.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/reset_password/page/content/form/password.html.twig
  src/Sylius/Bundle/AdminBundle/templates/security/reset_password/page/content/form/submit.html.twig
Labels: DX, Admin

#17422 Mention the serialization changes in API
  UPGRADE-API-2.0.md
Labels: Maintenance, API

#17434 [Bug] Turn off stimulus debug mode in production
  src/Sylius/Bundle/AdminBundle/Resources/assets/app.js
  src/Sylius/Bundle/ShopBundle/Resources/assets/app.js
Labels: Bug

#17435 Fix create button in admin panel
  src/Sylius/Bundle/AdminBundle/templates/shared/helper/button.html.twig
Labels: UX, Admin

#17437 Remove Obsolete Catalog Promotions Validation ADR
  adr/2022_02_09_catalog_promotions_validation.md
Labels: DX, Maintenance

#17442 SYL-4118: Mobile UI fixes in admin panel
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/header/title_block/title.html.twig
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/payments/items.html.twig
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/shipments/item/actions.html.twig
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/shipments/item/general.html.twig
  src/Sylius/Bundle/AdminBundle/templates/order/show/content/sections/shipments/items.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/content/header/title_block.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/navbar.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/navbar/items.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/navbar/menu.html.twig
Labels: UX, Admin

#17444 [UI] Add top margin to flash messages
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/_messages.scss
Labels: UX, Shop

#17445 [Admin] Fix deleting customer account
  features/admin/user/managing_users/deleting_account.feature
  src/Sylius/Behat/Context/Ui/UserContext.php
  src/Sylius/Bundle/AdminBundle/templates/customer/show/content/header/title_block/actions/delete.html.twig
Labels: Admin, Bug

#17451 Fix mobile product attributes form
  src/Sylius/Bundle/AdminBundle/templates/product_attribute/form/general/code.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product_attribute/form/general/position.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product_attribute/form/general/translatable.html.twig
  src/Sylius/Bundle/AdminBundle/templates/product_attribute/form/general/type.html.twig
Labels: DX, Admin

#17452 [UI] Add missing asterix
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/_form.scss
Labels: UX, Shop

#17454 [UI] Reduce the margin on the product show page
  src/Sylius/Bundle/ShopBundle/templates/product/show.html.twig
Labels: UX, Shop

#17446 [PaymentRequest] Fix Payum payment request
  .github/workflows/matrix.json
  config/bundles.php
  config/packages/test_cached_payum/_sylius.yaml
  config/packages/test_cached_payum/doctrine.yaml
  config/packages/test_cached_payum/fidry_alice_data_fixtures.yaml
  config/packages/test_cached_payum/framework.yaml
  config/packages/test_cached_payum/mailer.yaml
  config/packages/test_cached_payum/monolog.yaml
  config/packages/test_cached_payum/nelmio_alice.yaml
  config/packages/test_cached_payum/security.yaml
  config/packages/test_cached_payum/sylius_channel.yaml
  config/packages/test_cached_payum/sylius_theme.yaml
  config/packages/test_cached_payum/sylius_uploader.yaml
  config/packages/test_cached_payum/twig.yaml
  config/packages/test_cached_payum/web_profiler.yaml
  config/packages/test_cached_payum/webpack_encore.yaml
  config/services_test_cached_payum.yaml
  features/hybrid/checkout/changing_payment_method/cancelling_payment_request_when_payment_method_is_changed.feature
  features/shop/account/customer_account/viewing_orders_history/changing_payment_method.feature
  features/shop/checkout/paying_for_order/cancelling_payment_request_when_payment_method_is_changed.feature
  features/shop/checkout/paying_for_order/paying_offline_during_checkout.feature
  features/shop/checkout/paying_for_order/paying_offline_during_checkout_as_guest.feature
  features/shop/checkout/paying_for_order/preventing_changing_the_payment_method_of_a_cancelled_order.feature
  features/shop/checkout/paying_for_order/seeing_payment_method_instructions_after_checkout.feature
  features/shop/checkout/paying_for_order/selecting_order_payment_method.feature
  features/shop/payment_request/calling_notify_for_a_payment_method.feature
  features/shop/payment_request/calling_notify_for_a_payment_request.feature
  src/Sylius/Behat/Context/Api/Shop/OrderContext.php
  src/Sylius/Behat/Context/Api/Shop/PaymentRequestContext.php
  src/Sylius/Behat/Context/Setup/PaymentContext.php
  src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
  src/Sylius/Behat/Context/Ui/Shop/PaymentRequestContext.php
  src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
  src/Sylius/Behat/Resources/config/suites/api/account/customer.yml
  src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
  src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
  src/Sylius/Bundle/PaymentBundle/Command/Offline/StatusPaymentRequest.php
  src/Sylius/Bundle/PaymentBundle/CommandHandler/Offline/StatusPaymentRequestHandler.php
  src/Sylius/Bundle/PaymentBundle/CommandProvider/Offline/StatusPaymentRequestCommandProvider.php
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/command_handler.xml
  src/Sylius/Bundle/PaymentBundle/Resources/config/services/command_provider.xml
  src/Sylius/Bundle/PayumBundle/PaymentRequest/CommandProvider/PayumActionsCommandProvider.php
  src/Sylius/Bundle/PayumBundle/Resources/config/services/payment_request/command_provider.xml
  src/Sylius/Bundle/ShopBundle/Resources/config/services/order_pay/controllers.xml
  src/Sylius/Bundle/UserBundle/Resources/config/app/config.yml
  tests/Api/DataFixtures/ORM/gateway_config_payment_request.yaml
  tests/Api/Shop/CustomersTest.php
  tests/Api/Shop/PaymentRequestsTest.php
Labels: Enhancement

#17448 Refactor Upgrade file for 2.0
  UPGRADE-2.0.md
Labels: Maintenance

#17438 [Upgrade] Refine Sylius 1.14 Upgrade Guide
  UPGRADE-1.14.md
  UPGRADE-2.0.md
  src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
  src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/CommandDataTransformerPass.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
Labels: Maintenance

#17464 [Composer] Add conflict to phpstan/phpdoc-parser >= 2.0
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
Labels: Maintenance, Dependencies, Bug

#17469 SYL-4130: UI fixes
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/_buttons.scss
  src/Sylius/Bundle/ShopBundle/Resources/assets/styles/_utils.scss
  src/Sylius/Bundle/ShopBundle/templates/account/address_book/common/main/address/actions.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/address_book/set_as_default.html.twig
  src/Sylius/Bundle/ShopBundle/templates/account/common/content/menu.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/buttons.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/visitor/mobile.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/macro/navigation_buttons.html.twig
Labels: UX, Shop

#17461 Fix mobile pagination
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/index/content/grid/data_table.html.twig
Labels: UX, Admin

#17472 [Docs] Disallow indexing old-docs in search engines
  docs/_themes/sylius_rtd_theme/layout.html
Labels: Documentation

#17471 Fix channel collector's name to match the tag's id
  src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php
Labels: DX, Bug

#17484 Add missing info about removed parameter in 2.0
  UPGRADE-2.0.md
Labels: Maintenance

#17480 Add missing constructor changes info to upgrade 2.0 file
  UPGRADE-2.0.md
Labels: DX, Maintenance

#17487 [BUG] Fix sass loader compilation on path containing dot character
  src/Sylius/Bundle/AdminBundle/index.js
  src/Sylius/Bundle/ShopBundle/index.js
Labels: Bug

#17493 [CI] Add PHP 8.4 and SF 7.2 to unstable build
  .github/workflows/ci_e2e-unstable.yaml
Labels: Dependencies, CI

#17486 [Twig][Component] Replace private with protected constructor parameters
  src/Sylius/Bundle/AdminBundle/Twig/Component/Customer/OrderStatisticsComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/ChannelSelectorComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/NewCustomersComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/NewOrdersComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/StatisticsComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Order/AddressHistoryComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Product/Form/ProductTaxonsComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Product/FormComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Product/ProductAttributeAutocompleteComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/ProductVariant/FormComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/PromotionCoupon/GeneratorInstructionFormComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/Navbar/NotificationsComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/Navbar/ShopPreviewComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/Navbar/UserDropdownComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/RenderEntityWithTemplateComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Taxon/DeleteComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Taxon/FormComponent.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Taxon/TreeComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Account/ChangePasswordFormComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Cart/FormComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Cart/WidgetComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Checkout/Address/AddressBookComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Checkout/Address/FormComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Common/CurrencySwitcherComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Common/LocaleSwitcherComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Common/TaxonMenuComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/AddToCartFormComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/AssociationComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/BreadcrumbComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/BySlugComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/CardComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/ListComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/PriceComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/SummaryComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/ProductReview/CountComponent.php
  src/Sylius/Bundle/ShopBundle/Twig/Component/ProductReview/ListComponent.php
Labels: DX

#17494 [Docs v1] Organization docs refactor
  docs/book/organization/index.rst
  docs/book/organization/map.rst.inc
  docs/book/organization/team.rst
Labels: Documentation

#17499 Refine Upgrade Files content
  UPGRADE-2.0.md
  UPGRADE-API-2.0.md
Labels: Maintenance

#17501 Update README.md
  docs/README.md
Labels: Documentation

#17500 Update README.md
  README.md
Labels: Documentation

#17482 [Shop][2.0] Added the ability to render the accordion component that’s expanded by default
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/details/content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/product/show/content/info/overview/accordion/details/title.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/accordion/accordion_item_content.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/accordion/accordion_item_title.html.twig
Labels: UX, Shop

#17502 Update breadcrumbs.html
  docs/_themes/sylius_rtd_theme/breadcrumbs.html
Labels: Documentation

#17496 performance, accessibility, best practices and seo improvements
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/ShopBundle/templates/homepage/banner.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/components/header/cart.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/components/main_image.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/footer/content/copy.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/footer/content/payment_methods.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/logo.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/header/content/security/visitor/mobile.html.twig
Labels: UX, Shop

#17516 removal of double ‘private’ from upgrade-2.0.md
  UPGRADE-2.0.md
Labels: Maintenance

#17515 removing the double "private" in UPGRADE-1.14.md
  UPGRADE-1.14.md
Labels: Maintenance

#17525 [Maintenance] Remove unnecessary definition of interface
  src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
Labels: Maintenance
