Repository Sylius/Sylius, pull requests merged in 2025-05, with the labels that each got.

#17925 [CI] Fix failing behat tests
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  .github/workflows/ci_frontend.yaml
  src/Sylius/Behat/Element/Admin/Product/MediaFormElement.php
  src/Sylius/Behat/Element/Admin/Taxon/ImageFormElement.php
  src/Sylius/Behat/Element/Product/ShowPage/MediaElement.php
Labels: Maintenance, CI

#17927 [CI] Fix failing behat tests
  .github/workflows/ci_e2e-mysql.yaml
  src/Sylius/Behat/Element/Product/ShowPage/MediaElement.php
  src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
  src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
  src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
  src/Sylius/Behat/Page/Shop/Product/ShowPage.php
Labels: Maintenance, CI

#17918 [Shop] Add twig hooks to product card template
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/product_review/index.yaml
  src/Sylius/Bundle/ShopBundle/Resources/config/app/twig_hooks/shared/product/card.yaml
  src/Sylius/Bundle/ShopBundle/templates/product/common/card.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/product/card/details.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/product/card/details/image.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/product/card/details/name.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/product/card/prices.html.twig
Labels: Shop

#17926 Fix action templates for url option
  src/Sylius/Bundle/AdminBundle/templates/shared/grid/action/delete.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/grid/action/show.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/grid/action/update.html.twig
Labels: Admin, Bug

#17919 Fix dev firewall order
  config/packages/security.yaml
Labels: DX, Maintenance, Bug

#17784 [PHPSpec to PHPUnit] Component Addressing
  composer.json
  rector-spec-unit.php
  src/Sylius/Component/Addressing/Tests/Checker/CountryProvincesDeletionCheckerTest.php
  src/Sylius/Component/Addressing/Tests/Checker/ZoneDeletionCheckerTest.php
  src/Sylius/Component/Addressing/Tests/Comparator/AddressComparatorTest.php
  src/Sylius/Component/Addressing/Tests/Converter/CountryNameConverterTest.php
  src/Sylius/Component/Addressing/Tests/Factory/ZoneFactoryTest.php
  src/Sylius/Component/Addressing/Tests/Matcher/ZoneMatcherTest.php
  src/Sylius/Component/Addressing/Tests/Model/AddressTest.php
  src/Sylius/Component/Addressing/Tests/Model/CountryTest.php
  src/Sylius/Component/Addressing/Tests/Model/ProvinceTest.php
  src/Sylius/Component/Addressing/Tests/Model/ZoneMemberTest.php
  src/Sylius/Component/Addressing/Tests/Model/ZoneTest.php
  src/Sylius/Component/Addressing/Tests/Provider/ProvinceNamingProviderTest.php
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Addressing/phpspec.yml.dist
  src/Sylius/Component/Addressing/phpunit.xml.dist
  src/Sylius/Component/Addressing/spec/Checker/CountryProvincesDeletionCheckerSpec.php
  src/Sylius/Component/Addressing/spec/Checker/ZoneDeletionCheckerSpec.php
  src/Sylius/Component/Addressing/spec/Comparator/AddressComparatorSpec.php
  src/Sylius/Component/Addressing/spec/Converter/CountryNameConverterSpec.php
  src/Sylius/Component/Addressing/spec/Factory/ZoneFactorySpec.php
  src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php
  src/Sylius/Component/Addressing/spec/Model/AddressSpec.php
  src/Sylius/Component/Addressing/spec/Model/CountrySpec.php
  src/Sylius/Component/Addressing/spec/Model/ProvinceSpec.php
  src/Sylius/Component/Addressing/spec/Model/ZoneMemberSpec.php
  src/Sylius/Component/Addressing/spec/Model/ZoneSpec.php
  src/Sylius/Component/Addressing/spec/Provider/ProvinceNamingProviderSpec.php
  symfony.lock
Labels: DX, Maintenance

#17829 [Admin] Plus features clickbaits
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
  src/Sylius/Bundle/AdminBundle/Resources/private/entry.js
  src/Sylius/Bundle/AdminBundle/Resources/private/img/sylius-plus-sidebar.svg
  src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/Form/_roles.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
Labels: Admin

#17827 [Admin] Plus features clickbaits
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/assets/entrypoint.js
  src/Sylius/Bundle/AdminBundle/Resources/assets/images/sylius-plus-sidebar.svg
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/_navbar.scss
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/_plus-features.scss
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/main.scss
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/admin_user/create.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/admin_user/update.yaml
  src/Sylius/Bundle/AdminBundle/templates/admin_user/form/sections/roles.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/sidebar/menu/menu.html.twig
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Labels: Admin

#17937 [Admin] Plus UTM link
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/Form/_roles.html.twig
Labels: Maintenance, Admin

#17938 [Admin] Plus UTM link
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
  src/Sylius/Bundle/AdminBundle/templates/admin_user/form/sections/roles.html.twig
Labels: Admin

#17868 [Admin] Add taxon buttons x-axis padding
  src/Sylius/Bundle/AdminBundle/Resources/assets/styles/ui/_icons.scss
Labels: Admin

#17728 [APIP] Formatting values (FILTER_SANITIZE_URL)
  src/Sylius/Bundle/ApiBundle/Converter/IriToIdentifierConverter.php
  src/Sylius/Bundle/ApiBundle/Tests/Converter/IriToIdentifierConverterTest.php
Labels: Maintenance, API, Docker

#17940 Change emitUp to emit
  src/Sylius/Bundle/ShopBundle/Twig/Component/Product/AddToCartFormComponent.php
Labels: DX, Shop

#17946 [Composer] Add conflict to behat/gherkin
  CONFLICTS.md
  composer.json
Labels: Behat, Maintenance, Dependencies, Bug

#17952 Add instruction doc for disabling Mollie on Sylius Standard
  docs/cookbook/configuration/how-to-remove-sylius-mollie-plugin.rst
  docs/cookbook/configuration/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#17960 [Admin] Missing role icon in menu
  src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
Labels: Admin

#17957 [PHPSpec to PHPUnit] Currency Component
  src/Sylius/Component/Currency/Tests/Context/CompositeCurrencyContextTest.php
  src/Sylius/Component/Currency/Tests/Converter/CurrencyConverterTest.php
  src/Sylius/Component/Currency/Tests/Converter/CurrencyNameConverterTest.php
  src/Sylius/Component/Currency/Tests/Model/CurrencyTest.php
  src/Sylius/Component/Currency/Tests/Model/ExchangeRateTest.php
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Currency/phpspec.yml.dist
  src/Sylius/Component/Currency/phpunit.xml.dist
  src/Sylius/Component/Currency/spec/Context/CompositeCurrencyContextSpec.php
  src/Sylius/Component/Currency/spec/Converter/CurrencyConverterSpec.php
  src/Sylius/Component/Currency/spec/Converter/CurrencyNameConverterSpec.php
  src/Sylius/Component/Currency/spec/Model/CurrencySpec.php
  src/Sylius/Component/Currency/spec/Model/ExchangeRateSpec.php
Labels: DX, Maintenance

#17959 [PHPSpec to PHPUnit] User Component
  src/Sylius/Component/User/Tests/Canonicalizer/CanonicalizerTest.php
  src/Sylius/Component/User/Tests/Model/UserOAuthTest.php
  src/Sylius/Component/User/Tests/Model/UserTest.php
  src/Sylius/Component/User/Tests/Security/Checker/EnabledUserCheckerTest.php
  src/Sylius/Component/User/Tests/Security/Checker/TokenUniquenessCheckerTest.php
  src/Sylius/Component/User/Tests/Security/Generator/UniqueTokenGeneratorTest.php
  src/Sylius/Component/User/Tests/Security/PasswordUpdaterTest.php
  src/Sylius/Component/User/composer.json
  src/Sylius/Component/User/phpspec.yml.dist
  src/Sylius/Component/User/phpunit.xml.dist
  src/Sylius/Component/User/spec/Canonicalizer/CanonicalizerSpec.php
  src/Sylius/Component/User/spec/Model/UserOAuthSpec.php
  src/Sylius/Component/User/spec/Model/UserSpec.php
  src/Sylius/Component/User/spec/Security/Checker/TokenUniquenessCheckerSpec.php
  src/Sylius/Component/User/spec/Security/Generator/UniqueTokenGeneratorSpec.php
  src/Sylius/Component/User/spec/Security/PasswordUpdaterSpec.php
  src/Sylius/Component/User/tests/Security/Checker/EnabledUserCheckerTest.php
Labels: DX, Maintenance

#17969 [CI] Fix downloading robo.phar for packages build
  .github/workflows/ci_packages.yaml
Labels: Maintenance, CI

#17962 [PHPSpec to PHPUnit] Taxonomy Component
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/Taxonomy/phpspec.yml.dist
  src/Sylius/Component/Taxonomy/phpunit.xml.dist
  src/Sylius/Component/Taxonomy/spec/Factory/TaxonFactorySpec.php
  src/Sylius/Component/Taxonomy/spec/Generator/TaxonSlugGeneratorSpec.php
  src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
  src/Sylius/Component/Taxonomy/spec/Model/TaxonTranslationSpec.php
  src/Sylius/Component/Taxonomy/tests/Factory/TaxonFactoryTest.php
  src/Sylius/Component/Taxonomy/tests/Generator/TaxonSlugGeneratorTest.php
  src/Sylius/Component/Taxonomy/tests/Model/TaxonTest.php
  src/Sylius/Component/Taxonomy/tests/Model/TaxonTranslationTest.php
Labels: DX, Maintenance

#17978 [PHPSpec to PHPUnit] Taxation Component
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxation/phpspec.yml.dist
  src/Sylius/Component/Taxation/phpunit.xml.dist
  src/Sylius/Component/Taxation/spec/Calculator/DefaultCalculatorSpec.php
  src/Sylius/Component/Taxation/spec/Calculator/DelegatingCalculatorSpec.php
  src/Sylius/Component/Taxation/spec/Checker/TaxRateDateEligibilityCheckerSpec.php
  src/Sylius/Component/Taxation/spec/Model/TaxCategorySpec.php
  src/Sylius/Component/Taxation/spec/Model/TaxRateSpec.php
  src/Sylius/Component/Taxation/spec/Resolver/TaxRateResolverSpec.php
  src/Sylius/Component/Taxation/tests/Calculator/DefaultCalculatorTest.php
  src/Sylius/Component/Taxation/tests/Calculator/DelegatingCalculatorTest.php
  src/Sylius/Component/Taxation/tests/Checker/TaxRateDateEligibilityCheckerTest.php
  src/Sylius/Component/Taxation/tests/Model/TaxCategoryTest.php
  src/Sylius/Component/Taxation/tests/Model/TaxRateTest.php
  src/Sylius/Component/Taxation/tests/Resolver/TaxRateResolverTest.php
Labels: DX, Maintenance

#17963 Upgrade RECTOR and PHPStan version to `v2`
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Sylius/Bundle/CoreBundle/EventListener/CircularDependencyBreakingErrorListener.php
  src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
  src/Sylius/Component/Addressing/Model/Country.php
  src/Sylius/Component/Addressing/Model/Zone.php
  src/Sylius/Component/Core/Checker/ProductVariantLowestPriceDisplayChecker.php
  src/Sylius/Component/Core/Factory/ChannelFactory.php
  src/Sylius/Component/Core/Model/Channel.php
  src/Sylius/Component/Core/Model/Customer.php
  src/Sylius/Component/Core/Model/Order.php
  src/Sylius/Component/Core/Model/OrderInterface.php
  src/Sylius/Component/Core/Model/PaymentMethod.php
  src/Sylius/Component/Core/Model/Product.php
  src/Sylius/Component/Core/Model/ProductImage.php
  src/Sylius/Component/Core/Model/ProductVariant.php
  src/Sylius/Component/Core/Model/Promotion.php
  src/Sylius/Component/Core/Model/Shipment.php
  src/Sylius/Component/Core/Model/ShippingMethod.php
  src/Sylius/Component/Core/Model/Taxon.php
  src/Sylius/Component/Core/Statistics/ValueObject/BusinessActivitySummary.php
  src/Sylius/Component/Currency/Model/ExchangeRate.php
  src/Sylius/Component/Product/Model/Product.php
  src/Sylius/Component/Product/Model/ProductAssociation.php
  src/Sylius/Component/Product/Model/ProductOption.php
  src/Sylius/Component/Product/Model/ProductVariant.php
  src/Sylius/Component/Promotion/Model/Promotion.php
  src/Sylius/Component/Shipping/Model/Shipment.php
  src/Sylius/Component/Taxation/Model/TaxCategory.php
  src/Sylius/Component/Taxonomy/Model/Taxon.php
  src/Sylius/Component/User/Model/User.php
  src/Sylius/Component/User/Tests/Security/Generator/UniqueTokenGeneratorTest.php
Labels: DX, Maintenance, Dependencies

#17971 Allow ORM 3 on Addressing bundle
  .github/workflows/ci_packages.yaml
  .github/workflows/ci_static-checks.yaml
  .github/workflows/matrix.json
  RoboFile.php
  composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AddressingBundle/test/var/db.sql
Labels: Maintenance

#17975 Allow ORM 3 on Attribute bundle
  src/Sylius/Bundle/AttributeBundle/composer.json
Labels: Maintenance

#17979 Allow ORM 3 on Currency bundle
  src/Sylius/Bundle/CurrencyBundle/composer.json
Labels: Maintenance

#17988 Allow ORM 3 on Inventory bundle
  src/Sylius/Bundle/InventoryBundle/composer.json
Labels: Maintenance

#17985 [Taxonomy] Fix static analysis in component tests
  src/Sylius/Component/Taxonomy/tests/Model/TaxonTest.php
Labels: Bug

#17958 [DOC] use correct twig extension
  docs/sylius-official-plugins-documentation/cms-plugin/developer-reference/media.md
Labels: Documentation, Maintenance

#18004 [PHPSpec to PHPUnit] Shipping Component
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Shipping/phpspec.yml.dist
  src/Sylius/Component/Shipping/phpunit.xml.dist
  src/Sylius/Component/Shipping/spec/Calculator/DelegatingCalculatorSpec.php
  src/Sylius/Component/Shipping/spec/Calculator/FlatRateCalculatorSpec.php
  src/Sylius/Component/Shipping/spec/Calculator/PerUnitRateCalculatorSpec.php
  src/Sylius/Component/Shipping/spec/Calculator/UndefinedShippingMethodExceptionSpec.php
  src/Sylius/Component/Shipping/spec/Checker/Eligibility/CategoryRequirementEligibilityCheckerSpec.php
  src/Sylius/Component/Shipping/spec/Checker/Eligibility/CompositeShippingMethodEligibilityCheckerSpec.php
  src/Sylius/Component/Shipping/spec/Checker/Eligibility/ShippingMethodRulesEligibilityCheckerSpec.php
  src/Sylius/Component/Shipping/spec/Checker/Rule/TotalWeightGreaterThanOrEqualRuleCheckerSpec.php
  src/Sylius/Component/Shipping/spec/Checker/Rule/TotalWeightLessThanOrEqualRuleCheckerSpec.php
  src/Sylius/Component/Shipping/spec/Exception/UnresolvedDefaultShippingMethodExceptionSpec.php
  src/Sylius/Component/Shipping/spec/Model/ShipmentSpec.php
  src/Sylius/Component/Shipping/spec/Model/ShipmentUnitSpec.php
  src/Sylius/Component/Shipping/spec/Model/ShippingCategorySpec.php
  src/Sylius/Component/Shipping/spec/Model/ShippingMethodSpec.php
  src/Sylius/Component/Shipping/spec/Model/ShippingMethodTranslationSpec.php
  src/Sylius/Component/Shipping/spec/Resolver/CompositeMethodsResolverSpec.php
  src/Sylius/Component/Shipping/spec/Resolver/DefaultShippingMethodResolverSpec.php
  src/Sylius/Component/Shipping/spec/Resolver/ShippingMethodsResolverSpec.php
  src/Sylius/Component/Shipping/tests/Calculator/DelegatingCalculatorTest.php
  src/Sylius/Component/Shipping/tests/Calculator/FlatRateCalculatorTest.php
  src/Sylius/Component/Shipping/tests/Calculator/PerUnitRateCalculatorTest.php
  src/Sylius/Component/Shipping/tests/Calculator/UndefinedShippingMethodExceptionTest.php
  src/Sylius/Component/Shipping/tests/Checker/Eligibility/CategoryRequirementEligibilityCheckerTest.php
  src/Sylius/Component/Shipping/tests/Checker/Eligibility/CompositeShippingMethodEligibilityCheckerTest.php
  src/Sylius/Component/Shipping/tests/Checker/Eligibility/ShippingMethodRulesEligibilityCheckerTest.php
  src/Sylius/Component/Shipping/tests/Checker/Rule/TotalWeightGreaterThanOrEqualRuleCheckerTest.php
  src/Sylius/Component/Shipping/tests/Checker/Rule/TotalWeightLessThanOrEqualRuleCheckerTest.php
  src/Sylius/Component/Shipping/tests/Exception/UnresolvedDefaultShippingMethodExceptionTest.php
  src/Sylius/Component/Shipping/tests/Model/ShipmentTest.php
  src/Sylius/Component/Shipping/tests/Model/ShipmentUnitTest.php
  src/Sylius/Component/Shipping/tests/Model/ShippingCategoryTest.php
  src/Sylius/Component/Shipping/tests/Model/ShippingMethodTest.php
  src/Sylius/Component/Shipping/tests/Model/ShippingMethodTranslationTest.php
  src/Sylius/Component/Shipping/tests/Resolver/CompositeMethodsResolverTest.php
  src/Sylius/Component/Shipping/tests/Resolver/DefaultShippingMethodResolverTest.php
  src/Sylius/Component/Shipping/tests/Resolver/ShippingMethodsResolverTest.php
Labels: DX, Maintenance

#17984 [PHPSpec to PHPUnit] Attribute Component
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Attribute/phpspec.yml.dist
  src/Sylius/Component/Attribute/phpunit.xml.dist
  src/Sylius/Component/Attribute/spec/AttributeType/CheckboxAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/DateAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/DatetimeAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/FloatAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/IntegerAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/PercentAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/SelectAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/TextAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/AttributeType/TextareaAttributeTypeSpec.php
  src/Sylius/Component/Attribute/spec/Factory/AttributeFactorySpec.php
  src/Sylius/Component/Attribute/spec/Model/AttributeSpec.php
  src/Sylius/Component/Attribute/spec/Model/AttributeTranslationSpec.php
  src/Sylius/Component/Attribute/spec/Model/AttributeValueSpec.php
  src/Sylius/Component/Attribute/tests/AttributeType/CheckboxAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/DateAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/DatetimeAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/FloatAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/IntegerAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/PercentAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/SelectAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/TextAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/TextareaAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/Factory/AttributeFactoryTest.php
  src/Sylius/Component/Attribute/tests/Model/AttributeTest.php
  src/Sylius/Component/Attribute/tests/Model/AttributeTranslationTest.php
  src/Sylius/Component/Attribute/tests/Model/AttributeValueTest.php
  src/Sylius/Component/Channel/README.md
Labels: Maintenance

#18003 [PHPSpec to PHPUnit] Customer Component
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Customer/phpspec.yml.dist
  src/Sylius/Component/Customer/phpunit.xml.dist
  src/Sylius/Component/Customer/spec/Model/CustomerGroupSpec.php
  src/Sylius/Component/Customer/spec/Model/CustomerSpec.php
  src/Sylius/Component/Customer/tests/Model/CustomerGroupTest.php
  src/Sylius/Component/Customer/tests/Model/CustomerTest.php
Labels: DX, Maintenance

#18027 [Shop] Add twig hook per factory name in select payment
  src/Sylius/Bundle/ShopBundle/templates/shared/form/select_payment/payment/choice.html.twig
Labels: Enhancement, Shop

#18002 [TaxationBundle] Replace PHPSpec with PHPUnit tests
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/phpspec.yml.dist
  src/Sylius/Bundle/TaxationBundle/phpunit.xml.dist
  src/Sylius/Bundle/TaxationBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
  src/Sylius/Bundle/TaxationBundle/tests/DependencyInjection/Compiler/RegisterCalculatorsPassTest.php
  src/Sylius/Bundle/TaxationBundle/tests/DependencyInjection/SyliusTaxationExtensionTest.php
  src/Sylius/Bundle/TaxationBundle/tests/Functional/app/config/parameters.yml
  src/Sylius/Bundle/TaxationBundle/tests/Stub/TaxCalculatorStub.php
Labels: DX, Maintenance

#17983 [InventoryBundle] Replace PHPSpec with PHPUnit tests
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/phpspec.yml.dist
  src/Sylius/Bundle/InventoryBundle/phpunit.xml.dist
  src/Sylius/Bundle/InventoryBundle/spec/Validator/Constraints/InStockSpec.php
  src/Sylius/Bundle/InventoryBundle/spec/Validator/Constraints/InStockValidatorSpec.php
  src/Sylius/Bundle/InventoryBundle/tests/Validator/Constraints/InStockTest.php
  src/Sylius/Bundle/InventoryBundle/tests/Validator/Constraints/InStockValidatorTest.php
Labels: DX, Maintenance

#17981 [Currency][Customer][Taxonomy] Remove PHPSpec dependency and configuration from bundles where it was not used
  phpstan.neon.dist
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/phpspec.yml.dist
  src/Sylius/Bundle/CurrencyBundle/phpunit.xml.dist
  src/Sylius/Bundle/CurrencyBundle/tests/DependencyInjection/SyliusCurrencyExtensionTest.php
  src/Sylius/Bundle/CurrencyBundle/tests/Stub/CurrencyContextStub.php
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/phpspec.yml.dist
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/phpspec.yml.dist
Labels: DX, Maintenance

#18012 [PHPSpec to PHPUnit] Customer Component Fix
  src/Sylius/Component/Customer/tests/Model/CustomerGroupTest.php
  src/Sylius/Component/Customer/tests/Model/CustomerTest.php
Labels: Maintenance

#18013 [PHPSpec to PHPUnit] Attribute Component Fix
  src/Sylius/Component/Attribute/tests/AttributeType/FloatAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/IntegerAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/PercentAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/SelectAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/TextAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/AttributeType/TextareaAttributeTypeTest.php
  src/Sylius/Component/Attribute/tests/Factory/AttributeFactoryTest.php
  src/Sylius/Component/Attribute/tests/Model/AttributeValueTest.php
Labels: DX, Maintenance

#17951 [PHPSpec to PHPUnit] Component Product
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Product/phpspec.yml.dist
  src/Sylius/Component/Product/phpunit.xml.dist
  src/Sylius/Component/Product/spec/Factory/ProductFactorySpec.php
  src/Sylius/Component/Product/spec/Factory/ProductVariantFactorySpec.php
  src/Sylius/Component/Product/spec/Generator/CartesianSetBuilderSpec.php
  src/Sylius/Component/Product/spec/Generator/ProductVariantGeneratorSpec.php
  src/Sylius/Component/Product/spec/Generator/SlugGeneratorSpec.php
  src/Sylius/Component/Product/spec/Model/ProductAssociationSpec.php
  src/Sylius/Component/Product/spec/Model/ProductAssociationTypeSpec.php
  src/Sylius/Component/Product/spec/Model/ProductAssociationTypeTranslationSpec.php
  src/Sylius/Component/Product/spec/Model/ProductOptionSpec.php
  src/Sylius/Component/Product/spec/Model/ProductSpec.php
  src/Sylius/Component/Product/spec/Model/ProductTranslationSpec.php
  src/Sylius/Component/Product/spec/Model/ProductVariantSpec.php
  src/Sylius/Component/Product/spec/Model/ProductVariantTranslationSpec.php
  src/Sylius/Component/Product/spec/Resolver/AvailableProductOptionValuesResolverSpec.php
  src/Sylius/Component/Product/spec/Resolver/CompositeProductVariantResolverSpec.php
  src/Sylius/Component/Product/spec/Resolver/DefaultProductVariantResolverSpec.php
  src/Sylius/Component/Product/tests/Factory/ProductFactoryTest.php
  src/Sylius/Component/Product/tests/Factory/ProductVariantFactoryTest.php
  src/Sylius/Component/Product/tests/Generator/CartesianSetBuilderTest.php
  src/Sylius/Component/Product/tests/Generator/ProductVariantGeneratorTest.php
  src/Sylius/Component/Product/tests/Generator/SlugGeneratorTest.php
  src/Sylius/Component/Product/tests/Model/ProductAssociationTest.php
  src/Sylius/Component/Product/tests/Model/ProductAssociationTypeTest.php
  src/Sylius/Component/Product/tests/Model/ProductAssociationTypeTranslationTest.php
  src/Sylius/Component/Product/tests/Model/ProductOptionTest.php
  src/Sylius/Component/Product/tests/Model/ProductTest.php
  src/Sylius/Component/Product/tests/Model/ProductTranslationTest.php
  src/Sylius/Component/Product/tests/Model/ProductVariantTest.php
  src/Sylius/Component/Product/tests/Model/ProductVariantTranslationTest.php
  src/Sylius/Component/Product/tests/Resolver/AvailableProductOptionValuesResolverTest.php
  src/Sylius/Component/Product/tests/Resolver/CompositeProductVariantResolverTest.php
  src/Sylius/Component/Product/tests/Resolver/DefaultProductVariantResolverTest.php
Labels: DX, Maintenance

#18021 [PHPSpec to PHPUnit] Inventory Component
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Inventory/phpspec.yml.dist
  src/Sylius/Component/Inventory/phpunit.xml.dist
  src/Sylius/Component/Inventory/spec/Checker/AvailabilityCheckerSpec.php
  src/Sylius/Component/Inventory/spec/Model/InventoryUnitSpec.php
  src/Sylius/Component/Inventory/tests/Checker/AvailabilityCheckerTest.php
  src/Sylius/Component/Inventory/tests/Model/InventoryUnitTest.php
Labels: DX, Maintenance

#18028 [PHPSpec to PHPUnit] Locale Component
  rector-spec-unit.php
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Locale/phpspec.yml.dist
  src/Sylius/Component/Locale/phpunit.xml.dist
  src/Sylius/Component/Locale/spec/Context/CompositeLocaleContextSpec.php
  src/Sylius/Component/Locale/spec/Context/ImmutableLocaleContextSpec.php
  src/Sylius/Component/Locale/spec/Context/ProviderBasedLocaleContextSpec.php
  src/Sylius/Component/Locale/spec/Converter/LocaleConverterSpec.php
  src/Sylius/Component/Locale/spec/Model/LocaleSpec.php
  src/Sylius/Component/Locale/spec/Provider/CachedLocaleCollectionProviderSpec.php
  src/Sylius/Component/Locale/spec/Provider/LocaleCollectionProviderSpec.php
  src/Sylius/Component/Locale/spec/Provider/LocaleProviderSpec.php
  src/Sylius/Component/Locale/tests/Context/CompositeLocaleContextTest.php
  src/Sylius/Component/Locale/tests/Context/ImmutableLocaleContextTest.php
  src/Sylius/Component/Locale/tests/Context/ProviderBasedLocaleContextTest.php
  src/Sylius/Component/Locale/tests/Converter/LocaleConverterTest.php
  src/Sylius/Component/Locale/tests/Model/LocaleTest.php
  src/Sylius/Component/Locale/tests/Provider/CachedLocaleCollectionProviderTest.php
  src/Sylius/Component/Locale/tests/Provider/LocaleCollectionProviderTest.php
  src/Sylius/Component/Locale/tests/Provider/LocaleProviderTest.php
Labels: DX, Maintenance

#18023 [PHPSpec to PHPUnit] Promotion Component
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Promotion/phpspec.yml.dist
  src/Sylius/Component/Promotion/phpunit.xml.dist
  src/Sylius/Component/Promotion/spec/Action/PromotionApplicatorSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/CompositePromotionCouponEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/CompositePromotionEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionArchivalEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionCouponDurationEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionCouponUsageLimitEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionDurationEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionRulesEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionSubjectCouponEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionUsageLimitEligibilityCheckerSpec.php
  src/Sylius/Component/Promotion/spec/Exception/FailedGenerationExceptionSpec.php
  src/Sylius/Component/Promotion/spec/Factory/PromotionCouponFactorySpec.php
  src/Sylius/Component/Promotion/spec/Factory/PromotionCouponGeneratorInstructionFactorySpec.php
  src/Sylius/Component/Promotion/spec/Generator/PercentageGenerationPolicySpec.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorInstructionSpec.php
  src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorSpec.php
  src/Sylius/Component/Promotion/spec/Model/CatalogPromotionActionSpec.php
  src/Sylius/Component/Promotion/spec/Model/CatalogPromotionScopeSpec.php
  src/Sylius/Component/Promotion/spec/Model/CatalogPromotionSpec.php
  src/Sylius/Component/Promotion/spec/Model/CatalogPromotionTranslationSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionActionSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionCouponSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionRuleSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionSpec.php
  src/Sylius/Component/Promotion/spec/Model/PromotionTranslationSpec.php
  src/Sylius/Component/Promotion/spec/Processor/PromotionProcessorSpec.php
  src/Sylius/Component/Promotion/spec/Provider/ActivePromotionsProviderSpec.php
  src/Sylius/Component/Promotion/tests/Action/PromotionApplicatorTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/CompositePromotionCouponEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/CompositePromotionEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionArchivalEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionCouponDurationEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionCouponUsageLimitEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionDurationEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionRulesEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionSubjectCouponEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Checker/Eligibility/PromotionUsageLimitEligibilityCheckerTest.php
  src/Sylius/Component/Promotion/tests/Exception/FailedGenerationExceptionTest.php
  src/Sylius/Component/Promotion/tests/Factory/PromotionCouponFactoryTest.php
  src/Sylius/Component/Promotion/tests/Factory/PromotionCouponGeneratorInstructionFactoryTest.php
  src/Sylius/Component/Promotion/tests/Generator/PercentageGenerationPolicyTest.php
  src/Sylius/Component/Promotion/tests/Generator/PromotionCouponGeneratorInstructionTest.php
  src/Sylius/Component/Promotion/tests/Generator/PromotionCouponGeneratorTest.php
  src/Sylius/Component/Promotion/tests/Model/CatalogPromotionActionTest.php
  src/Sylius/Component/Promotion/tests/Model/CatalogPromotionScopeTest.php
  src/Sylius/Component/Promotion/tests/Model/CatalogPromotionTest.php
  src/Sylius/Component/Promotion/tests/Model/CatalogPromotionTranslationTest.php
  src/Sylius/Component/Promotion/tests/Model/PromotionActionTest.php
  src/Sylius/Component/Promotion/tests/Model/PromotionCouponTest.php
  src/Sylius/Component/Promotion/tests/Model/PromotionRuleTest.php
  src/Sylius/Component/Promotion/tests/Model/PromotionTest.php
  src/Sylius/Component/Promotion/tests/Model/PromotionTranslationTest.php
  src/Sylius/Component/Promotion/tests/Processor/PromotionProcessorTest.php
  src/Sylius/Component/Promotion/tests/Provider/ActivePromotionsProviderTest.php
Labels: DX, Maintenance

#18031 [Shop][Checkout] Add id to the summary elements
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/items_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/order_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/promotion_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/shipping_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/sidebar/summary/total/taxes_total.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/flashes.html.twig
Labels: Enhancement, Shop

#18036 [Core] Minor improvements in SalesStatisticsProvider
  src/Sylius/Component/Core/Statistics/Provider/SalesStatisticsProvider.php
Labels: DX

#18032 [PHPSpec to PHPUnit] Attribute Bundle
  src/Sylius/Bundle/AttributeBundle/Tests/Doctrine/ORM/Subscriber/LoadMetadataSubscriberTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/AttributeTypeValidatorTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidAttributeValueTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidAttributeValueValidatorTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidSelectAttributeConfigurationTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidSelectAttributeConfigurationValidatorTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidTextAttributeConfigurationTest.php
  src/Sylius/Bundle/AttributeBundle/Tests/Validator/Constraints/ValidTextAttributeConfigurationValidatorTest.php
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/phpspec.yml.dist
  src/Sylius/Bundle/AttributeBundle/phpunit.xml.dist
  src/Sylius/Bundle/AttributeBundle/spec/Doctrine/ORM/Subscriber/LoadMetadataSubscriberSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/AttributeTypeValidatorSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidAttributeValueSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidAttributeValueValidatorSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidSelectAttributeConfigurationSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidSelectAttributeConfigurationValidatorSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidTextAttributeConfigurationSpec.php
  src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidTextAttributeConfigurationValidatorSpec.php
Labels: DX, Maintenance

#18044 [Admin][Taxon] Pass the tree data to stimulus controller without HTML escaping
  src/Sylius/Bundle/AdminBundle/templates/taxon/sections/tree.html.twig
Labels: Admin, Bug

#18046 [PHPSpec to PHPUnit] Money Bundle
  src/Sylius/Bundle/MoneyBundle/Tests/Form/DataTransformer/SyliusMoneyTransformerTest.php
  src/Sylius/Bundle/MoneyBundle/Tests/Formatter/MoneyFormatterTest.php
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/phpspec.yml.dist
  src/Sylius/Bundle/MoneyBundle/phpunit.xml.dist
  src/Sylius/Bundle/MoneyBundle/spec/Form/DataTransformer/SyliusMoneyTransformerSpec.php
  src/Sylius/Bundle/MoneyBundle/spec/Formatter/MoneyFormatterSpec.php
Labels: DX, Maintenance

#18038 [PHPSpec to PHPUnit] Locale Bundle
  src/Sylius/Bundle/LocaleBundle/Tests/Checker/LocaleUsageCheckerTest.php
  src/Sylius/Bundle/LocaleBundle/Tests/Context/RequestBasedLocaleContextTest.php
  src/Sylius/Bundle/LocaleBundle/Tests/Context/RequestHeaderBasedLocaleContextTest.php
  src/Sylius/Bundle/LocaleBundle/Tests/Doctrine/EventListener/LocaleModificationListenerTest.php
  src/Sylius/Bundle/LocaleBundle/Tests/Listener/RequestLocaleSetterTest.php
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/phpspec.yml.dist
  src/Sylius/Bundle/LocaleBundle/phpunit.xml.dist
  src/Sylius/Bundle/LocaleBundle/spec/Checker/LocaleUsageCheckerSpec.php
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestBasedLocaleContextSpec.php
  src/Sylius/Bundle/LocaleBundle/spec/Context/RequestHeaderBasedLocaleContextSpec.php
  src/Sylius/Bundle/LocaleBundle/spec/Doctrine/EventListener/LocaleModificationListenerSpec.php
  src/Sylius/Bundle/LocaleBundle/spec/Listener/RequestLocaleSetterSpec.php
Labels: DX, Maintenance

#17986 [Admin] Add pending actions list on dashboard
  UPGRADE-2.1.md
  features/admin/pending_actions_per_channel.feature
  src/Sylius/Behat/Context/Ui/Admin/DashboardContext.php
  src/Sylius/Behat/Page/Admin/DashboardPage.php
  src/Sylius/Behat/Page/Admin/DashboardPageInterface.php
  src/Sylius/Behat/Resources/config/suites/ui/admin/dashboard.yaml
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/CountOrdersToProcessProvider.php
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/CountPendingPaymentsProvider.php
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/CountProductReviewsToApproveProvider.php
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/CountProductVariantsOutOfStockProvider.php
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/CountShipmentsToShipProvider.php
  src/Sylius/Bundle/AdminBundle/PendingAction/Provider/PendingActionCountProviderInterface.php
  src/Sylius/Bundle/AdminBundle/Resources/config/app/twig_hooks/dashboard/index.yaml
  src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/pending_action.xml
  src/Sylius/Bundle/AdminBundle/Resources/config/services/twig/component/dashboard/pending_action.xml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
  src/Sylius/Bundle/AdminBundle/Tests/PendingAction/Provider/CountOrdersToProcessProviderTest.php
  src/Sylius/Bundle/AdminBundle/Tests/PendingAction/Provider/CountPendingPaymentsProviderTest.php
  src/Sylius/Bundle/AdminBundle/Tests/PendingAction/Provider/CountProductReviewsToApproveProviderTest.php
  src/Sylius/Bundle/AdminBundle/Tests/PendingAction/Provider/CountProductVariantsOutOfStockProviderTest.php
  src/Sylius/Bundle/AdminBundle/Tests/PendingAction/Provider/CountShipmentsToShipProviderTest.php
  src/Sylius/Bundle/AdminBundle/Tests/Twig/Component/Dashboard/PendingActionCountComponentTest.php
  src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/PendingActionCountComponent.php
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body/orders_to_process.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body/pending_payments.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body/product_reviews_to_approve.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body/product_variants_out_of_stock.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/body/shipments_to_ship.html.twig
  src/Sylius/Bundle/AdminBundle/templates/dashboard/index/component/pending_actions/header.html.twig
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductReviewRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
  src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShipmentRepository.php
  src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
  src/Sylius/Component/Core/Repository/PaymentRepositoryInterface.php
  src/Sylius/Component/Core/Repository/ProductReviewRepositoryInterface.php
  src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php
  src/Sylius/Component/Core/Repository/ShipmentRepositoryInterface.php
Labels: Feature, Maintenance, Admin

#18051 [CI] Test Symfony 7.3 beta
  .github/workflows/ci_e2e-unstable.yaml
  .github/workflows/ci_packages-unstable.yaml
Labels: Maintenance, Dependencies, CI

#18047 [PHPSpec to PHPUnit] Review Bundle
  src/Sylius/Bundle/ReviewBundle/Tests/Doctrine/ORM/Subscriber/LoadMetadataSubscriberTest.php
  src/Sylius/Bundle/ReviewBundle/Tests/EventListener/ReviewChangeListenerTest.php
  src/Sylius/Bundle/ReviewBundle/Tests/Updater/AverageRatingUpdaterTest.php
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/phpspec.yml
  src/Sylius/Bundle/ReviewBundle/phpunit.xml.dist
  src/Sylius/Bundle/ReviewBundle/spec/Doctrine/ORM/Subscriber/LoadMetadataSubscriberSpec.php
  src/Sylius/Bundle/ReviewBundle/spec/EventListener/ReviewChangeListenerSpec.php
  src/Sylius/Bundle/ReviewBundle/spec/Updater/AverageRatingUpdaterSpec.php
Labels: DX, Maintenance

#18050 Make fixture factory constructor arguments protected
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionScopeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CustomerGroupExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductOptionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
Labels: DX

#17965 [2.0] Polish translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.pl.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.pl.yaml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.pl.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.pl.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.pl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.pl.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.pl.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.pl.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.pl.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.pl.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.pl.yml
Labels: Admin, Shop, API

#17974 [2.0] German translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.de.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.de.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.de.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.de.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.de.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.de.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.de.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.de.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.de.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.de.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.de.yml
Labels: Admin, Shop, API

#17966 [2.0] Dutch translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.nl.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.nl.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.nl.yml
Labels: Admin, Shop, API, Translations

#18040 [2.0] French belgian translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.fr_BE.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.fr_BE.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.fr_BE.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.fr_BE.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.fr_BE.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/flashes.fr_BE.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.fr_BE.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.fr_BE.yml
Labels: Admin, API, Translations

#18041 [2.0] British english translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en_GB.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.en_GB.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.en_GB.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.en_GB.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/flashes.en_GB.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.en_GB.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.en_GB.yml
Labels: Admin, API, Translations

#17964 [2.0] French translations
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.fr.yaml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.fr.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.fr.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.fr.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.fr.yml
Labels: Admin, Shop, API, Translations

#18042 [2.0] German austrian translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.de_AT.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.de_AT.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.de_AT.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.de_AT.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.de_AT.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/flashes.de_AT.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.de_AT.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.de_AT.yml
Labels: Admin, API

#18057 Reload image in README.md
  README.md
Labels: Maintenance

#18058 [2.0] French Canadian translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.fr_CA.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.fr_CA.yaml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.fr_CA.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.fr_CA.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.fr_CA.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/flashes.fr_CA.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.fr_CA.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.fr_CA.yml
Labels: Admin, API, Translations

#18053 Test Symfony 7.3 beta
  .github/workflows/ci_e2e-unstable.yaml
  RoboFile.php
  src/Sylius/Bundle/CoreBundle/OrderPay/Provider/PaymentRequestAfterPayResponseProvider.php
  src/Sylius/Bundle/CoreBundle/Resources/config/validation/ChannelPriceHistoryConfig.xml
  src/Sylius/Component/Customer/composer.json
Labels: Maintenance, Dependencies

#18063 [Composer] Bump APIP to 4.1 and remove conflict to api-platform/json-ld
  CONFLICTS.md
  composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
Labels: Maintenance, API, Dependencies

#18064 [Admin] Fix tests directory
  phpstan.neon.dist
  src/Sylius/Bundle/AdminBundle/phpunit.xml.dist
  src/Sylius/Bundle/AdminBundle/tests/PendingAction/Provider/CountOrdersToProcessProviderTest.php
  src/Sylius/Bundle/AdminBundle/tests/PendingAction/Provider/CountPendingPaymentsProviderTest.php
  src/Sylius/Bundle/AdminBundle/tests/PendingAction/Provider/CountProductReviewsToApproveProviderTest.php
  src/Sylius/Bundle/AdminBundle/tests/PendingAction/Provider/CountProductVariantsOutOfStockProviderTest.php
  src/Sylius/Bundle/AdminBundle/tests/PendingAction/Provider/CountShipmentsToShipProviderTest.php
  src/Sylius/Bundle/AdminBundle/tests/Twig/Component/Dashboard/PendingActionCountComponentTest.php
  src/Sylius/Component/Core/tests/Customer/Statistics/CustomerStatisticsTest.php
Labels: Maintenance, Admin

#18068 Make PHPUnit configs and tests directories consistent in all Components
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Addressing/phpunit.xml.dist
  src/Sylius/Component/Addressing/tests/Checker/CountryProvincesDeletionCheckerTest.php
  src/Sylius/Component/Addressing/tests/Checker/ZoneDeletionCheckerTest.php
  src/Sylius/Component/Addressing/tests/Comparator/AddressComparatorTest.php
  src/Sylius/Component/Addressing/tests/Converter/CountryNameConverterTest.php
  src/Sylius/Component/Addressing/tests/Factory/ZoneFactoryTest.php
  src/Sylius/Component/Addressing/tests/Matcher/ZoneMatcherTest.php
  src/Sylius/Component/Addressing/tests/Model/AddressTest.php
  src/Sylius/Component/Addressing/tests/Model/CountryTest.php
  src/Sylius/Component/Addressing/tests/Model/ProvinceTest.php
  src/Sylius/Component/Addressing/tests/Model/ZoneMemberTest.php
  src/Sylius/Component/Addressing/tests/Model/ZoneTest.php
  src/Sylius/Component/Addressing/tests/Provider/ProvinceNamingProviderTest.php
  src/Sylius/Component/Attribute/phpunit.xml.dist
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Channel/phpunit.xml.dist
  src/Sylius/Component/Channel/tests/Checker/ChannelDeletionCheckerTest.php
  src/Sylius/Component/Channel/tests/Context/CachedPerRequestChannelContextTest.php
  src/Sylius/Component/Channel/tests/Context/CompositeChannelContextTest.php
  src/Sylius/Component/Channel/tests/Context/RequestBased/ChannelContextTest.php
  src/Sylius/Component/Channel/tests/Context/RequestBased/CompositeRequestResolverTest.php
  src/Sylius/Component/Channel/tests/Context/RequestBased/HostnameBasedRequestResolverTest.php
  src/Sylius/Component/Channel/tests/Context/SingleChannelContextTest.php
  src/Sylius/Component/Channel/tests/Factory/ChannelFactoryTest.php
  src/Sylius/Component/Channel/tests/Model/ChannelTest.php
  src/Sylius/Component/Core/phpunit.xml.dist
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Currency/phpunit.xml.dist
  src/Sylius/Component/Currency/tests/Context/CompositeCurrencyContextTest.php
  src/Sylius/Component/Currency/tests/Converter/CurrencyConverterTest.php
  src/Sylius/Component/Currency/tests/Converter/CurrencyNameConverterTest.php
  src/Sylius/Component/Currency/tests/Model/CurrencyTest.php
  src/Sylius/Component/Currency/tests/Model/ExchangeRateTest.php
  src/Sylius/Component/Customer/phpunit.xml.dist
  src/Sylius/Component/Inventory/phpunit.xml.dist
  src/Sylius/Component/Locale/phpunit.xml.dist
  src/Sylius/Component/Order/phpunit.xml.dist
  src/Sylius/Component/Payment/phpunit.xml.dist
  src/Sylius/Component/Product/phpunit.xml.dist
  src/Sylius/Component/Promotion/phpunit.xml.dist
  src/Sylius/Component/Review/phpunit.xml.dist
  src/Sylius/Component/Shipping/phpunit.xml.dist
  src/Sylius/Component/Taxation/phpunit.xml.dist
  src/Sylius/Component/Taxonomy/phpunit.xml.dist
  src/Sylius/Component/User/composer.json
  src/Sylius/Component/User/phpunit.xml.dist
  src/Sylius/Component/User/tests/Canonicalizer/CanonicalizerTest.php
  src/Sylius/Component/User/tests/Model/UserOAuthTest.php
  src/Sylius/Component/User/tests/Model/UserTest.php
  src/Sylius/Component/User/tests/Security/Checker/EnabledUserCheckerTest.php
  src/Sylius/Component/User/tests/Security/Checker/TokenUniquenessCheckerTest.php
  src/Sylius/Component/User/tests/Security/Generator/UniqueTokenGeneratorTest.php
  src/Sylius/Component/User/tests/Security/PasswordUpdaterTest.php
Labels: DX, Maintenance

#18070 [Behat] Migrate phpspec to PHPUnit tests
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_e2e-unstable.yaml
  composer.json
  phpspec.yml.dist
  phpunit.xml.dist
  rector-spec-unit.php
  src/Sylius/Behat/spec/NotificationTypeSpec.php
  src/Sylius/Behat/spec/Service/Converter/IriConverterSpec.php
  src/Sylius/Behat/spec/Service/Generator/UploadedImagePathGeneratorSpec.php
  src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php
  src/Sylius/Behat/spec/Service/Provider/EmailMessagesProviderSpec.php
  src/Sylius/Behat/spec/Service/Resolver/CurrentPageResolverSpec.php
  src/Sylius/Behat/spec/Service/SecurityServiceSpec.php
  src/Sylius/Behat/spec/Service/SessionManagerSpec.php
  src/Sylius/Behat/spec/Service/Setter/ChannelContextSetterSpec.php
  src/Sylius/Behat/spec/Service/SharedSecurityServiceSpec.php
  src/Sylius/Behat/spec/Service/SharedStorageSpec.php
  src/Sylius/Behat/tests/NotificationTypeTest.php
  src/Sylius/Behat/tests/Service/Converter/IriConverterTest.php
  src/Sylius/Behat/tests/Service/Generator/UploadedImagePathGeneratorTest.php
  src/Sylius/Behat/tests/Service/Generator/ford.jpg
  src/Sylius/Behat/tests/Service/NotificationCheckerTest.php
  src/Sylius/Behat/tests/Service/Provider/EmailMessagesProviderTest.php
  src/Sylius/Behat/tests/Service/Resolver/CurrentPageResolverTest.php
  src/Sylius/Behat/tests/Service/SecurityServiceTest.php
  src/Sylius/Behat/tests/Service/SessionManagerTest.php
  src/Sylius/Behat/tests/Service/Setter/ChannelContextSetterTest.php
  src/Sylius/Behat/tests/Service/SharedSecurityServiceTest.php
  src/Sylius/Behat/tests/Service/SharedStorageTest.php
Labels: DX, Behat, Maintenance

#18075 [PHPSpec to PHPUnit] Order Bundle - Fix
  src/Sylius/Bundle/OrderBundle/Tests/Context/SessionBasedCartContextTest.php
  src/Sylius/Bundle/OrderBundle/Tests/Remover/ExpiredCartsRemoverTest.php
  src/Sylius/Bundle/OrderBundle/Tests/Resetter/CartChangesResetterTest.php
  src/Sylius/Bundle/OrderBundle/phpunit.xml.dist
Labels: DX, Maintenance

#18073 [PHPSpec to PHPUnit] Payment Bundle
  src/Sylius/Bundle/PaymentBundle/Tests/Canceller/PaymentRequestCancellerTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/CommandHandler/Offline/CapturePaymentRequestHandlerTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/Generator/GatewayNameGeneratorTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/Validator/Constraints/GatewayFactoryExistsValidatorTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/Validator/GroupsGenerator/GatewayConfigGroupsGeneratorTest.php
  src/Sylius/Bundle/PaymentBundle/Tests/Validator/GroupsGenerator/PaymentMethodGroupsGeneratorTest.php
  src/Sylius/Bundle/PaymentBundle/Validator/GroupsGenerator/GatewayConfigGroupsGenerator.php
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/phpspec.yml.dist
  src/Sylius/Bundle/PaymentBundle/phpunit.xml.dist
  src/Sylius/Bundle/PaymentBundle/spec/Canceller/PaymentRequestCancellerSpec.php
  src/Sylius/Bundle/PaymentBundle/spec/CommandHandler/Offline/CapturePaymentRequestHandlerSpec.php
  src/Sylius/Bundle/PaymentBundle/spec/Generator/GatewayNameGeneratorSpec.php
  src/Sylius/Bundle/PaymentBundle/spec/Validator/Constraints/GatewayFactoryExistsValidatorSpec.php
  src/Sylius/Bundle/PaymentBundle/spec/Validator/GroupsGenerator/GatewayConfigGroupsGeneratorSpec.php
  src/Sylius/Bundle/PaymentBundle/spec/Validator/GroupsGenerator/PaymentMethodGroupsGeneratorSpec.php
Labels: DX, Maintenance

#18077 [PayumBundle] Migrate phpspec to PHPUnit tests
  src/Sylius/Bundle/PayumBundle/Tests/Action/AuthorizePaymentActionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Action/CapturePaymentActionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Action/Offline/ConvertPaymentActionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Action/Offline/ResolveNextRouteActionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Action/ResolveNextRouteActionTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Factory/GetStatusFactoryTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Factory/ResolveNextRouteFactoryTest.php
  src/Sylius/Bundle/PayumBundle/Tests/HttpClient/HttpClientTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Model/GatewayConfigTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Provider/PaymentDescriptionProviderTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Request/GetStatusTest.php
  src/Sylius/Bundle/PayumBundle/Tests/Request/ResolveNextRouteTest.php
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/PayumBundle/phpspec.yml.dist
  src/Sylius/Bundle/PayumBundle/phpunit.xml.dist
  src/Sylius/Bundle/PayumBundle/spec/Action/AuthorizePaymentActionSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Action/CapturePaymentActionSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Action/Offline/ConvertPaymentActionSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Action/Offline/ResolveNextRouteActionSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Action/ResolveNextRouteActionSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Factory/GetStatusFactorySpec.php
  src/Sylius/Bundle/PayumBundle/spec/Factory/ResolveNextRouteFactorySpec.php
  src/Sylius/Bundle/PayumBundle/spec/HttpClient/HttpClientSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Model/GatewayConfigSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Provider/PaymentDescriptionProviderSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Request/GetStatusSpec.php
  src/Sylius/Bundle/PayumBundle/spec/Request/ResolveNextRouteSpec.php
Labels: DX, Maintenance

#18072 [ProductBundle] Migrate phpspec to PHPUnit tests
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/ProductBundle/phpspec.yml.dist
  src/Sylius/Bundle/ProductBundle/phpunit.xml.dist
  src/Sylius/Bundle/ProductBundle/spec/EventListener/SelectProductAttributeChoiceRemoveListenerSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Form/DataTransformer/ProductVariantToProductOptionsTransformerSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Form/DataTransformer/ProductsToProductAssociationsTransformerSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildAttributesFormSubscriberSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/GenerateProductVariantsSubscriberSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Validator/Constraint/ProductVariantCombinationSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Validator/Constraint/UniqueSimpleProductCodeSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Validator/ProductVariantCombinationValidatorSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Validator/ProductVariantOptionValuesConfigurationValidatorSpec.php
  src/Sylius/Bundle/ProductBundle/spec/Validator/UniqueSimpleProductCodeValidatorSpec.php
  src/Sylius/Bundle/ProductBundle/tests/DependencyInjection/SyliusProductExtensionsTest.php
  src/Sylius/Bundle/ProductBundle/tests/EventListener/SelectProductAttributeChoiceRemoveListenerTest.php
  src/Sylius/Bundle/ProductBundle/tests/Form/DataTransformer/ProductVariantToProductOptionsTransformerTest.php
  src/Sylius/Bundle/ProductBundle/tests/Form/DataTransformer/ProductsToProductAssociationsTransformerTest.php
  src/Sylius/Bundle/ProductBundle/tests/Form/EventSubscriber/BuildAttributesFormSubscriberTest.php
  src/Sylius/Bundle/ProductBundle/tests/Form/EventSubscriber/BuildProductVariantFormSubscriberTest.php
  src/Sylius/Bundle/ProductBundle/tests/Form/EventSubscriber/GenerateProductVariantsSubscriberTest.php
  src/Sylius/Bundle/ProductBundle/tests/Stub/ProductVariantResolverStub.php
  src/Sylius/Bundle/ProductBundle/tests/Validator/Constraint/ProductVariantCombinationTest.php
  src/Sylius/Bundle/ProductBundle/tests/Validator/Constraint/UniqueSimpleProductCodeTest.php
  src/Sylius/Bundle/ProductBundle/tests/Validator/ProductVariantCombinationValidatorTest.php
  src/Sylius/Bundle/ProductBundle/tests/Validator/ProductVariantOptionValuesConfigurationValidatorTest.php
  src/Sylius/Bundle/ProductBundle/tests/Validator/UniqueSimpleProductCodeValidatorTest.php
Labels: DX, Maintenance

#18066 [2.0] Swedish translations
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.sv.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.sv.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.sv.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.sv.yaml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.sv.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.sv.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.sv.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.sv.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.sv.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.sv.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.sv.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.sv.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.sv.yml
Labels: Admin, API, Translations

#18065 [2.0] Portuguese translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.pt.yml
  src/Sylius/Bundle/ApiBundle/Resources/translations/validators.pt.yaml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.pt.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.pt.yaml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.pt.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.pt.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/validators.pt.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/flashes.pt.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.pt.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.pt.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.pt.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.pt.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.pt.yml
Labels: Admin, Shop, API, Translations

#18086 [Shop][Checkout] Add hooks with active step name to header and sidebar hooks
  src/Sylius/Bundle/ShopBundle/templates/checkout/common/layout.html.twig
Labels: Shop

#18085 Update upgrade file
  UPGRADE-2.1.md
Labels: Maintenance

#18080 [API][Shop] Fix hardcoded variants squashing on product
  src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/EnabledVariantsExtension.php
  src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
  src/Sylius/Bundle/ApiBundle/Serializer/Normalizer/ProductNormalizer.php
  src/Sylius/Bundle/ApiBundle/Tests/Doctrine/ORM/QueryExtension/Shop/Product/EnabledVariantsExtensionTest.php
  src/Sylius/Bundle/ApiBundle/spec/Serializer/Normalizer/ProductNormalizerSpec.php
Labels: API, Bug

#18089 [CI] Update matrix for 2.0 branch
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/matrix.json
  composer.json
  src/Sylius/Abstraction/StateMachine/composer.json
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/ShopBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UiBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Addressing/composer.json
  src/Sylius/Component/Attribute/composer.json
  src/Sylius/Component/Channel/composer.json
  src/Sylius/Component/Core/composer.json
  src/Sylius/Component/Currency/composer.json
  src/Sylius/Component/Customer/composer.json
  src/Sylius/Component/Inventory/composer.json
  src/Sylius/Component/Locale/composer.json
  src/Sylius/Component/Order/composer.json
  src/Sylius/Component/Payment/composer.json
  src/Sylius/Component/Product/composer.json
  src/Sylius/Component/Promotion/composer.json
  src/Sylius/Component/Review/composer.json
  src/Sylius/Component/Shipping/composer.json
  src/Sylius/Component/Taxation/composer.json
  src/Sylius/Component/Taxonomy/composer.json
  src/Sylius/Component/User/composer.json
Labels: Maintenance, Admin, Shop, API, CI

#18091 Remove phpspec entirely
  .editorconfig
  .gitattributes
  .github/workflows/ci_static-checks.yaml
  .gitignore
  Makefile
  README.md
  RoboFile.php
  composer-require-checker.json
  composer.json
  monorepo-builder.php
  phparkitect.php
  phpspec.yml.dist
  rector-spec-unit.php
  src/Sylius/Bundle/ApiBundle/.gitattributes
  src/Sylius/Bundle/ApiBundle/composer.json
  src/Sylius/Bundle/ApiBundle/phpspec.yml.dist
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/UiBundle/.gitattributes
  src/Sylius/Bundle/UiBundle/composer.json
  symfony.lock
Labels: Maintenance, API, Dependencies

#18049 Orm 3 support
  .github/workflows/ci_packages.yaml
  .github/workflows/matrix.json
  RoboFile.php
  composer.json
  config/packages/framework.yaml
  src/Sylius/Bundle/AddressingBundle/composer.json
  src/Sylius/Bundle/AddressingBundle/test/var/db.sql
  src/Sylius/Bundle/AdminBundle/composer.json
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/config.yaml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/Bar.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/Foo.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/FooSyliusResource.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/config/doctrine/Taxon.orm.xml
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/Bar.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/Foo.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/FooSyliusResource.php
  src/Sylius/Bundle/ApiBundle/Tests/Application/src/Entity/Taxon.php
  src/Sylius/Bundle/AttributeBundle/composer.json
  src/Sylius/Bundle/ChannelBundle/composer.json
  src/Sylius/Bundle/CoreBundle/composer.json
  src/Sylius/Bundle/CurrencyBundle/composer.json
  src/Sylius/Bundle/CustomerBundle/composer.json
  src/Sylius/Bundle/InventoryBundle/composer.json
  src/Sylius/Bundle/LocaleBundle/composer.json
  src/Sylius/Bundle/MoneyBundle/composer.json
  src/Sylius/Bundle/OrderBundle/composer.json
  src/Sylius/Bundle/PaymentBundle/composer.json
  src/Sylius/Bundle/PayumBundle/composer.json
  src/Sylius/Bundle/ProductBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/composer.json
  src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php
  src/Sylius/Bundle/PromotionBundle/test/app/config/config.yml
  src/Sylius/Bundle/PromotionBundle/test/src/AppBundle/AppBundle.php
  src/Sylius/Bundle/PromotionBundle/test/src/AppBundle/Resources/config/doctrine/PromotionSubject.orm.yml
  src/Sylius/Bundle/PromotionBundle/test/src/Entity/PromotionSubject.php
  src/Sylius/Bundle/ReviewBundle/composer.json
  src/Sylius/Bundle/ShippingBundle/composer.json
  src/Sylius/Bundle/TaxationBundle/composer.json
  src/Sylius/Bundle/TaxonomyBundle/composer.json
  src/Sylius/Bundle/UserBundle/composer.json
  src/Sylius/Component/Core/composer.json
  tests/Functional/AbstractOrmTestCase.php
  tests/Functional/Doctrine/Dump/CompositeKeysModel.php
  tests/Functional/Doctrine/Dump/Model.php
  tests/Functional/Doctrine/Mock/DriverConnectionMock.php
  tests/Functional/OrderByIdentifierSqlWalkerTest.php
Labels: Maintenance, Admin, API
