Repository Sylius/Sylius, pull requests merged in 2025-08, with the labels that each got.

#18293 Revert "[Fixtures] Make factory example constructor arguments protected"
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionScopeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CustomerGroupExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductOptionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
Labels: Maintenance

#18182 [2.0] Dutch translations
  src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/AdminBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/ChannelBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/CoreBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/LocaleBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/OrderBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/PayumBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/ProductBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/ReviewBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/ShopBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.nl.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.nl.yml
  src/Sylius/Bundle/UiBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/flashes.nl.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/messages.nl.yml
  src/Sylius/Bundle/UserBundle/Resources/translations/validators.nl.yml
Labels: Admin, Translations

#17864 [Promotion] Corrects order of amounts to apply correct promotion amount
  src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicator.php
Labels: Bug
