Repository Sylius/Sylius, pull requests merged in 2025-07, with the labels that each got.

#18198 [CI] Load Node version conditionally + bring back phpspecs for 2.0 full builds
  .github/workflows/ci_e2e-mariadb.yaml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_e2e-pgsql.yaml
  .github/workflows/ci_static-checks.yaml
Labels: Maintenance, CI

#18186 Update storage based locale switcher to redirect to homepage if the d…
  UPGRADE-2.1.md
  src/Sylius/Bundle/ShopBundle/Locale/StorageBasedLocaleSwitcher.php
  src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/storage.xml
Labels: Maintenance, Shop, API, Docker

#18205 Adjust CONFLICTS files after upmerge from 1.14
  CONFLICTS.md
  src/Sylius/Bundle/ApiBundle/CONFLICTS.md
Labels: Maintenance, API, Dependencies

#18185 Fix typo in documentation
  docs/getting-started-with-sylius/customizing-business-logic.md
Labels: Documentation, Maintenance, Admin

#18209 Update AWS S3 documentation for image storage configuration
  docs/the-cookbook-2.0/how-to-automatically-store-images-on-aws-s3.md
Labels: Documentation, Maintenance

#18216 [ShopBundle] Fix missing void return
  src/Sylius/Bundle/ShopBundle/SyliusShopBundle.php
Labels: Shop

#18218 [Admin] Adjust UI directions of actions/rules/scopes
  src/Sylius/Bundle/AdminBundle/templates/catalog_promotion/form_theme.html.twig
  src/Sylius/Bundle/AdminBundle/templates/promotion/form_theme.html.twig
  src/Sylius/Bundle/AdminBundle/templates/shipping_method/form_theme.html.twig
Labels: Admin, Frontend

#17675 Configurable grid provider
  UPGRADE-2.1.md
  src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
  src/Sylius/Bundle/CoreBundle/Grid/Provider/OverrideGridProvider.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/providers.xml
  src/Sylius/Bundle/CoreBundle/tests/Grid/Provider/OverrideGridProviderTest.php
Labels: DX, Maintenance

#18257 Update README image
  README.md
Labels: Maintenance

#18266 [Fixtures] Make factory example constructor arguments protected
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionScopeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/CustomerGroupExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductOptionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxCategoryExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php
  src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
Labels: DX, Maintenance

#18279 [Composer] Limit conflict with symfony/ux
  CONFLICTS.md
  composer.json
Labels: Maintenance, Dependencies, Bug
