Repository Sylius/Sylius, pull requests merged in 2025-09, with the labels that each got.

#18339 Fixed placing order with not possible zone
  features/checkout/shipping_order/preventing_placing_order_with_address_not_in_shipping_method_zone.feature
  src/Sylius/Behat/Context/Setup/ShippingContext.php
  src/Sylius/Bundle/CoreBundle/Resources/config/services/shipping.xml
  src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php
  tests/Checker/Eligibility/ZoneEligibilityCheckerTest.php
Labels: Bug

#18342 FEAT: [AdminBundle] Open shop preview and nessecary user dropdown links in new tab
  src/Sylius/Bundle/AdminBundle/Twig/Component/Shared/Navbar/UserDropdownComponent.php
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/navbar/menu/shop_preview.html.twig
Labels: Admin

#18316 sort main and bulk actions by position
  src/Sylius/Bundle/AdminBundle/templates/shared/crud/common/content/header/title_block/actions.html.twig
  src/Sylius/Bundle/ShopBundle/templates/shared/grid/data_table.html.twig
Labels: Admin, Bug

#18331 [CONFLICT][UX] Fix composer conflict for symfony/ux-live-component and mark flaky test as failing
  composer.json
  features/shop/checkout/addressing_order/sign_in_during_addressing_step.feature
Labels: Maintenance, Dependencies

#18352 [API] Add variantName serialization groups to OrderItem configuration
  src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
  tests/Api/Responses/admin/order/get_order.json
  tests/Api/Responses/admin/order/get_orders_before_date.json
  tests/Api/Responses/admin/order_item/get_order_item_response.json
  tests/Api/Responses/shop/checkout/cart/add_item.json
  tests/Api/Responses/shop/checkout/cart/get_cart.json
  tests/Api/Responses/shop/checkout/cart/get_existing_cart_if_customer_has_cart.json
  tests/Api/Responses/shop/checkout/cart/update_cart_as_guest.json
  tests/Api/Responses/shop/checkout/cart/update_cart_as_shop_user.json
  tests/Api/Responses/shop/checkout/cart/update_item_quantity.json
  tests/Api/Responses/shop/checkout/completion/order_with_free_non_shippable_items.json
  tests/Api/Responses/shop/checkout/completion/order_with_non_shippable_items.json
  tests/Api/Responses/shop/checkout/completion/order_with_shippable_and_non_shippable_items.json
  tests/Api/Responses/shop/checkout/payment_method/select_payment_method_by_guest.json
  tests/Api/Responses/shop/checkout/payment_method/select_payment_method_by_user.json
  tests/Api/Responses/shop/checkout/shipping_method/select_shipping_method.json
  tests/Api/Responses/shop/order/change_payment_method_as_guest.json
  tests/Api/Responses/shop/order/change_payment_method_as_user.json
  tests/Api/Responses/shop/order/get_order_by_guest.json
  tests/Api/Responses/shop/order/get_order_by_user.json
  tests/Api/Responses/shop/order/update_payment_method.json
  tests/Api/Responses/shop/order_item/get_order_item_by_guest.json
  tests/Api/Responses/shop/order_item/get_order_item_by_user.json
  tests/Api/Responses/shop/order_item/get_order_items_by_guest.json
  tests/Api/Responses/shop/order_item/get_order_items_by_user.json
Labels: API

#17705 Fix deleting a value from an existing select product attribute while it's in use (Postgresql issue only)
  features/product/managing_product_attributes/editing_select_product_attribute.feature
  src/Sylius/Bundle/CoreBundle/Doctrine/DQL/Cast.php
  src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
  src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php
Labels: Bug

#18395 TASK: fix broken links in readme file
  README.md
Labels: Maintenance
